### ISSUE TITLE
Track disk usage of regions.

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1003]
### What problem does the new feature solve?

Track total disk space usage of some table.

### What does the feature do?

When writing rows to SST file:
https://github.com/GreptimeTeam/greptimedb/blob/c04f2d4c498eaea2d2b9e6bff21a59d751681180/src/storage/src/sst.rs#L249-L256

The access layer returns an `SstInfo` that currently includes only time range of file, we can also add a file size field to it and persist the value in manifest.
The file size can be easily obtained from `ParquetWriter`, both by reading the length of buffer or the metadata of object.

https://github.com/GreptimeTeam/greptimedb/blob/bb529c963b0a44bcf0fd3ff34558642a6ef8bfe8/src/storage/src/sst/parquet.rs#L130

### Implementation challenges
- [X] Collect the disk usages of regions #1125 
- [x] Report disk usage stats to metasrv thru heartbeat.

**Comment by fengjiachun** [comment]
This also needs to be sent to `metasrv` via heartbeat

**Comment by lizhemingi** [comment]
Let me take this one if you don't mind.

**Comment by lizhemingi** [comment]
I have finished the part of `we can also add a file size field to it and persist the value in manifest` in this issue.
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/9639449/221405065-95f50a60-1b87-4add-b6b9-a50419d1c2c3.png">

But I have some questions about the `This also needs to be sent to metasrv via heartbeat` part. 

- What kind of information should be sent via heartbeat? Like a total file size usage for all files in one region is enough ? Or list all the files and its file size ?
    I found there is a `approximate_bytes` in `RegionStat`, is it designed for this feature? If so, means a total file size usage is enough I believe.
- I did not find anywhere to delete sst files right now, so after compaction the compacted files still exist on disk(correct me if I am wrong here), will these files also be counted in heartbeat ?
- Any work is expected after file size information is added in heartbeat in `metasrv` side ?

@fengjiachun @v0y4g3r Looking forward to your response, thank you.

**Comment by v0y4g3r** [comment]
> What kind of information should be sent via heartbeat?

Region level disk usages is enough I think.

> I did not find anywhere to delete sst files right now

Since #1030 is merged, we can reclaim disk space after compaction now.

> Any work is expected after file size information is added in heartbeat in metasrv side ?

- Load balancing: we can use that info to select datanode when creating new regions.
- Metering and billing: for commercial users that can be used to track cost of services.

**Comment by lizhemingi** [comment]
> Since https://github.com/GreptimeTeam/greptimedb/pull/1030 is merged, we can reclaim disk space after compaction now.

Whoops, seems like my local branch is far away behind remote.

> Load balancing: we can use that info to select datanode when creating new regions.
Metering and billing: for commercial users that can be used to track cost of services.

What I actually want to know is the work that need to be done in this issue, this two topics are a little bit big for this issue I think.

**Comment by v0y4g3r** [comment]
> What I actually want to know is the work that need to be done in this issue, this two topics are a little bit big for this issue I think.

You can focus on collecting the disk usage first. We will create a new issue for  reporting these stats.

**Comment by evenyag** [comment]
@v0y4g3r Since #1125 is merged, could we close this issue now?

**Comment by v0y4g3r** [comment]
> @v0y4g3r Since #1125 is merged, could we close this issue now?

This issue also involves collecting disk usages and report the stats to metasrv thru heartbeat. Maybe leave it open and list the unfinished tasks.

**Comment by lizhemingi** [comment]
I can finish the rest part too.

Will using `approximate_bytes` in `RegionStat` to report the disk usage a correct way ?

And any modification is expected in `metasrv` side right now?

**Comment by fengjiachun** [comment]
> Will using approximate_bytes in RegionStat to report the disk usage a correct way ?

Yes, we welcome you to submit a pull request for this.
