### ISSUE TITLE
Unify retrieving schema in http api

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#1012]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Currently http api consists of several handler functions, some listed below: 
 - [`sql`](https://github.com/GreptimeTeam/greptimedb/blob/e17d564bf0acbe15f3b1033cf143c0065b91c39c/src/servers/src/http/handler.rs#L37)
 - [`promql`](https://github.com/GreptimeTeam/greptimedb/blob/e17d564bf0acbe15f3b1033cf143c0065b91c39c/src/servers/src/http/handler.rs#L77)
 - [`influxdb_write`](https://github.com/GreptimeTeam/greptimedb/blob/e17d564bf0acbe15f3b1033cf143c0065b91c39c/src/servers/src/http/influxdb.rs#L29)
 - etc.

Each handler uses its own query param struct, possibly giving schema a different name(`database`, `schema`, `db`, etc.)

During [`authorize`](https://github.com/GreptimeTeam/greptimedb/blob/e17d564bf0acbe15f3b1033cf143c0065b91c39c/src/servers/src/http/authorize.rs#L96), it's necessary to get schema name in order to check whether a user's is allowed to connect to this schema. Due to different query param struct of each http api defined, it seems impossible to get schema name here. Now the implementation just tries to get `db` in query string, but it cloud be broken anytime

It's better to find a way to unify all http api with at least some common param names, so that this kind of situation won't happen again

**Comment by killme2008** [comment]
@shuiyisong This issue need a review, looks like it is solved?

**Comment by shuiyisong** [comment]
> @shuiyisong This issue need a review, looks like it is solved?

Yes it's resolved. Closing it now.
