### ISSUE TITLE
Scripts can't work in a distributed cluster

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1014]
### What problem does the new feature solve?

The script function only works in standalone mode (only can be executed on datanode), it can't work in a distributed cluster. 

### What does the feature do?

Make script function work in a distributed cluster.

### Implementation challenges

* The `scripts` table should be distributed.
* Make the script engine run on the frontend.

**Comment by v0y4g3r** [comment]
That's a duplicated with #411
