### ISSUE TITLE
Prometheus HTTP API support more endpoints

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#1016]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

In addition to `query` and `query_range` endpoints, as [Prometheus HTTP API](https://prometheus.io/docs/prometheus/latest/querying/api/) describes, there are some other useful endpoints which will help Prometheus users to explore the metadata or details of the datasets. And these endpoints will help greptimedb to be integrated into other systems more smoothly as a Prometheus service.

One example:

```http
curl 'localhost:9090/api/v1/labels'
{
    "status": "success",
    "data": [
        "__name__",
        "call",
        "code",
        "config",
        "dialer_name",
        "endpoint",
        "event",
        "goversion",
        "handler",
        "instance",
        "interval",
        "job",
        "le",
        "listener_name",
        "name",
        "quantile",
        "reason",
        "role",
        "scrape_job",
        "slice",
        "version"
    ]
}
```

### Implementation challenges

There are so many challenges to implement these endpoints as Prometheus describes, such as:

- metadata. greptimedb store no metadata at all.
- targets. greptimedb has no target concept.

**Comment by yuanbohan** [comment]
#596 needs to consider this issue carefully.

**Comment by yuanbohan** [comment]
# SHOULD

- [ ] GET & POST /api/v1/query
- [ ] GET & POST /api/v1/query_range
- [ ] GET & POST /api/v1/format_query
- [ ] GET & POST /api/v1/series
- [ ] GET & POST /api/v1/labels
- [ ] GET /api/v1/label/<label_name>/values

# NO NEED

- GET /api/v1/targets
- GET /api/v1/rules
- GET /api/v1/alerts
- GET /api/v1/targets/metadata
- GET /api/v1/metadata
- GET /api/v1/alertmanagers
- GET & POST /api/v1/query_exemplars

### status

- GET /api/v1/status/config
- GET /api/v1/status/flags
- GET /api/v1/status/runtimeinfo
- GET /api/v1/status/buildinfo
- GET /api/v1/status/tsdb
- GET /api/v1/status/walreplay

### admin

- POST & PUT /api/v1/admin/tsdb/snapshot
- POST & PUT /api/v1/admin/tsdb/delete_series
- POST & PUT /api/v1/admin/tsdb/clean_tombstones

**Comment by waynexia** [comment]
Close as completed
