### ISSUE TITLE
Copy table from file

### ISSUE THREAD

**Issue by fengjiachun** [GreptimeTeam/greptimedb#1038]
### What problem does the new feature solve?

Now that we support exporting a table's data to a parquet file #1000 , accordingly, we also need to import the data file into the database.

### What does the feature do?

Referring to the [duckdb](https://duckdb.org/docs/sql/statements/copy.html) documentation, we can implement a statement similar to the following:

```sql
COPY tbl FROM '/xxx/data.parquet' WITH (FORMAT='parquet');
```

The first stage can support parquet file format, and in the future can support more formats, such as CSV...

**Comment by WenyXu** [comment]
As I read code #1000, I realized we could leverage OpenDAL to implement that import data from or export data to different user-defined storages.

// Copy data from S3
```sql
COPY tbl FROM 's3://hz-cold-0/xxx/data.parquet' WITH (FORMAT='parquet');
```
In the future, we can build a built-in access credentials table for accessing user's cloud storage, i.e.

|  StorageType  | AccessID / Host | Key |  Format | Actions |
|  ----  | ----  |  ----  |  ---- | ---- |
| S3  | hz-cold-0 |  encrypted('powerkey')  |  Default | R/W |
| OSS  | hz-cold-1 |  encrypted('powerkey')  |  Default |  R/W |
| HTTPS | https://public-repo.com | empty | Default |  R |

 We can leave this feature to a new tracking issue.

**Comment by killme2008** [comment]
> Can I take this? By the way, should we distinguish the existing `Copy` using `Copy Into` and `Copy From`

Feel free to try it. I think it's just the different sub-commands of `COPY.`

> As I read code https://github.com/GreptimeTeam/greptimedb/pull/1000, I realized we could leverage OpenDAL to 
> implement that import data from or export data to different user-defined storages.

Good catch! It's the feature we want. And we are using OpenDAL to access all different storage.

**Comment by evenyag** [comment]
> `Copy Into` and `Copy From`

What about `COPY TO` and `COPY FROM`?

> COPY TO copies the contents of a table to a file, while COPY FROM copies data from a file to a table 

Refer to [https://www.postgresql.org/docs/current/sql-copy.html](https://www.postgresql.org/docs/current/sql-copy.html)
