### ISSUE TITLE
Improve the testing ability of sqlness

### ISSUE THREAD

**Issue by jun0315** [GreptimeTeam/greptimedb#1039]
### What type of enhancement is this?

Performance, Refactor

### What does the enhancement do?

At present, sqlness supports standalone and distributed integration testing of rust sdk interface, We have the following areas for improvement:

- User can choose different distributed startup modes, including the current simple distributed mode (one matasrv `using memory`, one frontend and one datanode), and the complex mode (one matasrv `using etcd`, one frontend and three datanodes), and reconstruct the stand-alone and distributed code to reduce redundancy.

- More protocols (HTTP/PG/Script) are supported in sqlness, and existing interface test cases are reused as much as possible. If it is python script, it may need to be rewritten.

### Implementation challenges
*No response*

### Related links

https://github.com/GreptimeTeam/greptimedb/tree/develop/tests
https://docs.greptime.com/user-guide/clients

**Comment by tisonkun** [comment]
Closed as stale.

This should be filed in the Sqlness repo: https://github.com/CeresDB/sqlness?
