### ISSUE TITLE
Fails to connect gretimedb in docker with mysql client

### ISSUE THREAD

**Issue by vinland-avalon** [GreptimeTeam/greptimedb#1050]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

When I try to connect a gretimedb (standalone mode) with mysql client. It fails.

### What operating system did you use?

macOS Ventura 13.0 

### Relevant log output and stack trace

```bash
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

### How can we reproduce the bug?

```bash
docker run -p 4002:4002 greptime/greptimedb standalone start

mysql -h 127.0.0.1 -P 4002
```

**Comment by waynexia** [comment]
>mysql -h 127.0.0.1 -P 400

Do you mean "-P4002"?

**Comment by vinland-avalon** [comment]
> > mysql -h 127.0.0.1 -P 400
> 
> Do you mean "-P4002"?

Yes it is. I'll revise it.

**Comment by DiamondMofeng** [comment]
Mysql server defaultly only listen to `127.0.0.1` instead of `0.0.0.0`, that is the reason.

**Comment by vinland-avalon** [comment]
Thank you! It works with --mysql-addr!

**Comment by waynexia** [comment]
Appreciate it @DiamondMofeng ❤️ 

Close this as resolved.
