### ISSUE TITLE
Refactor region SST struct to hold an UUID as SST key to reduce overhead

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1053]
### What type of enhancement is this?

Performance

### What does the enhancement do?

SST file struct `FileMeta` uses a `String` as the file name:
https://github.com/GreptimeTeam/greptimedb/blob/373d4f9b9c55cef46bbac599bab1da45c1e20819/src/storage/src/sst.rs#L294

In fact, SST file names are always UUID v4:

On flush:
https://github.com/GreptimeTeam/greptimedb/blob/e17d5a1c41147fd8033cf87017c5099a53158d34/src/storage/src/flush.rs#L252

On compaciton:
https://github.com/GreptimeTeam/greptimedb/blob/ff48d2706923993b49f150f00d482d9c0586b07f/src/storage/src/compaction/task.rs#L177

So we can simply store an 128 bit `UUID` struct in `FileMeta` to alleviate heap allocation.

**Comment by vinland-avalon** [comment]
May I take this one?

**Comment by killme2008** [comment]
@vinland-avalon Please go ahead

**Comment by josseffy** [comment]
The names of files that flushed to external storage must still have an extension of `.parquet`. The improvement is about how struct `FileMeta` get stored in memory.  Am I right?

**Comment by vinland-avalon** [comment]
The names of files that flushed to external storage must still have an extension of `.parquet`. The refactoring is about how struct `FileMeta` get stored in memory -- we can ingnore the extension and just store uuid here. Am I right?

**Comment by evenyag** [comment]
We could add a typedef or a new type `FileId` to avoid exposing Uuid directly. I'd prefer to use new type pattern as we can add some method to `FileId`, similar to the `ProcedureId`

https://github.com/GreptimeTeam/greptimedb/blob/df751c38b4014641da0cf59a9e13ab5d4d44355b/src/common/procedure/src/procedure.rs#L166-L168

**Comment by vinland-avalon** [comment]
Make sense. Thx!

**Comment by vinland-avalon** [comment]
Hi, I've finished my coding. I'm ready for your reviews :) @v0y4g3r @evenyag
