### ISSUE TITLE
Implement VectorOp::take

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1054]
### What problem does the new feature solve?

`VectorOp` defines a set of basic compute operations.
https://github.com/GreptimeTeam/greptimedb/blob/a9c8584c987318a41edd7fe4e2ebc382538db7af/src/datatypes/src/vectors/operations.rs#L30-L31

This ticket requests to add the `take` method, like [this one in arrow](https://docs.rs/arrow/latest/arrow/compute/kernels/take/fn.take.html). It can construct a new vector out of an existing one, with given indices, which is useful in scenarios like sorting and repeating.

### What does the feature do?

Add a new method `take` to `VectorOp`

**Comment by e1ijah1** [comment]
Hi, I'd like to work on this issue :)
