### ISSUE TITLE
Persist compaction time window to table manifest

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1055]
### What problem does the new feature solve?

Everytime when compacting a table, we scan all SST files in level 0 and calculate a suitable time window for compaction.

https://github.com/GreptimeTeam/greptimedb/blob/af1f8d6101eaee9829f4947cb4f2d958e7d4c479/src/storage/src/compaction/strategy.rs#L51

With the presumption that the workload of a given table remains consistent, we can persist the inferred time window to table manifest to avoid calculating it everytime. 

Another benefit of this proposal is that it enforces all SSTs in level 1 to have the same aligned time window, which makes it easier to find compactable SSTs in level 1.

### What does the feature do?

Persist inferred time window to table manifest on first compaction and use that window for following compactions.

### Implementation challenges

We can add a field `compaction_time_window` on `TableOptions `:

https://github.com/GreptimeTeam/greptimedb/blob/e17d5a1c41147fd8033cf87017c5099a53158d34/src/table/src/requests.rs#L62-L70

We can also allow users to manually specify this option when creating table using `WITH` clause like:

```sql
CREATE TABLE monitor (host STRING,
    ts BIGINT,
    cpu DOUBLE DEFAULT 0,
    memory DOUBLE,
    TIME INDEX (ts),
    PRIMARY KEY(host)
) ENGINE=mito WITH(regions=1, ttl='7days', compaction_time_window='2hours');
```

**Comment by etolbakov** [comment]
Hi @v0y4g3r, 
I would like to give a go if you don't mind.

**Comment by killme2008** [comment]
ping @v0y4g3r
