### ISSUE TITLE
Enable dictionary encoding for primary key columns

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1056]
### What problem does the new feature solve?

To eliminate duplicate values in highly repetitive columns, and provide the ability to retrieve occurrence set efficiently, we can make use of parquet's per column [dictionary page](https://parquet.apache.org/docs/file-format/data-pages/encodings/#dictionary-encoding-plain_dictionary--2-and-rle_dictionary--8). Ideally, this can reduce on-disk data size and accelerate query execution.

### What does the feature do?

This can be roughly divided into several steps
- enable parquet dictionary encoding for some columns
- expose interfaces to
  - retrieve the key set
  - push down filter calculation down to the dictionary
- expose configurable parameters to adjust (on both user side and engine side) its behavior

**Comment by killme2008** [comment]
@v0y4g3r do we still need it?

**Comment by v0y4g3r** [comment]
> @v0y4g3r do we still need it?

No, since TimeSeriesMemtable is merged.
