### ISSUE TITLE
Time Window CompactionStrategy

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1068]
## What type of enhancement is this?
Performance

## What does the enhancement do?
Now we've built a table compaction framework, and we should proceed with more compaction strategies, like [time window compaction strategy](https://cassandra.apache.org/doc/latest/cassandra/operating/compaction/twcs.html) in cassandra/scylladb.

## Implementation challenges
TBD

**Comment by vinland-avalon** [comment]
@v0y4g3r I'd like to give it a try if you don't mind~

**Comment by v0y4g3r** [comment]
> @v0y4g3r I'd like to give it a try if you don't mind~

Go ahead please. But you may have to write an RFC for that before coding.

**Comment by vinland-avalon** [comment]
It seems that the `TWCS` has been implemented at #930 . So, what's the difference between this one and that one?
