### ISSUE TITLE
Check the write permission before export the table

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1069]
### What type of enhancement is this?

User experience

### What does the enhancement do?

To reduce redundant IO, The `Copy To` should check the write permission of the target file or dir before scanning the table.

https://github.com/GreptimeTeam/greptimedb/blob/fdd17c6eeb9ff0afc33a0212f76518634e37ffea/src/datanode/src/sql/copy_table.rs#L35-L64

**Comment by v0y4g3r** [comment]
I think we can split the `CopyTableRequest::file_name` into path and file name. When building object store we use path as root and check if current process has write permission before actually read data from table.

**Comment by WenyXu** [comment]
> I think we can split the `CopyTableRequest::file_name` into path and file name. When building object store we use path as root and check if current process has write permission before actually read data from table.

I will check the OpenDAL docs later. There may be no permissions check method. But we still can write bytes into a temp( or a manifest) file to check to create and write permission.
