### ISSUE TITLE
Manually trigger flush/compaction through HTTP API

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1087]
### What problem does the new feature solve?

Just like [HBase](https://hbase.apache.org/book.html#_manually_compacting_mob_files), we need to provide a method for users to manually trigger flush/compaction.

### What does the feature do?

Allow user to manually trigger compaction through HTTP API (or through command line tool using gRPC).

### Implementation challenges

Now the flush entry is on prewrite:
https://github.com/GreptimeTeam/greptimedb/blob/373d4f9b9c55cef46bbac599bab1da45c1e20819/src/storage/src/region/writer.rs#L556

and the compaction entry is after flush (as a callback):
https://github.com/GreptimeTeam/greptimedb/blob/373d4f9b9c55cef46bbac599bab1da45c1e20819/src/storage/src/region/writer.rs#L610

To implement this feature we need to add a new HTTP route, maybe "/manually-flush", and trigger flush task in that handler.

**Comment by evenyag** [comment]
Could we trigger flush via the SQL interface? ClickHouse has a similar statement to trigger a merge operation.

**Comment by WenyXu** [comment]
> Could we trigger flush via the SQL interface? Something similar to [`OPTIMIZE TABLE`](https://clickhouse.com/docs/en/sql-reference/statements/optimize). But this might be dangerous.
> 
> We might also need to expose `flush()`/`compact()` to the `table` trait first. So this issue might require several steps to implement.

Hi, I'm trying to work on this issue. I submitted a PR(#1094) to expose the `flush()` to the `table` trait and another PR(https://github.com/GreptimeTeam/greptime-proto/pull/11) to introduce the `FlashTableExpr` to implement the `flush()` for the frontend node.
