### ISSUE TITLE
Auto schema for gRPC ingestion

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1088]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

As we have decided to use gRPC as our primary data ingestion protocol, we need to enable auto schema inference for gRPC write APIs, so that it will work for metric collection scenarios.

This feature has already been implemented on influxdb and prometheu protocol. We might have to update gRPC protocol to distinguish tags and fields in order to inference primary key.

**Comment by killme2008** [comment]
@MichaelScofield Please verity this feature, looks like we already support it.

**Comment by MichaelScofield** [comment]
Verified, already supported.
