### ISSUE TITLE
gRPC write timestamp with different column name

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#1096]
### What type of bug is this?

Incorrect result, Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

insert data into greptimedb via gRPC, using different timestamp column name in different request, will add a new timestamp column with NULL value

![image](https://user-images.githubusercontent.com/4557527/221784972-adccddc3-9a0c-4381-b7db-5258c3e777e0.png)

![image](https://user-images.githubusercontent.com/4557527/221785066-9f4d7aa9-a8bd-442d-a2bc-26fe6dbe72d5.png)

### What operating system did you use?

Archlinux  x86_64 AMD Ryzen 5 5600H with Radeon Graphics

### How can we reproduce the bug?

```bash
1. insert and create table automatically

git clone git@github.com:GreptimeTeam/greptimedb-client-go.git
go run examples/insert/insert.go

2. Set different ts name
series.SetTimeWithKey("timestamp", time.Now()) 

3. insert again
go run examples/insert/insert.go
```

**Comment by v0y4g3r** [comment]
I'm afraid it's a by-design behavior. We do infer schema change during gRPC inserts. But I think we should add a schema-change validation before actually alter the schema, since renaming timestamp column is not allowed.
