### ISSUE TITLE
implement `to_unixtime()` function

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1103]
### What problem does the new feature solve?

Currently, we display all timestamp type in RFC3339 format, which is human-readable and widely used. However, sometimes we may need to convert them to the unix timestamp format, which is a number of seconds since January 1st 1970. This can be useful for debugging purposes, such as comparing timestamps across different sources or systems.

### What does the feature do?

The feature will add a new UDF called `to_unixtime()`, which takes a timestamp in RFC3339 format as an input and returns its equivalent unix timestamp as an output. For example, `to_unixtime("2023-03-01T06:35:02Z")` will return `1678269302`. The UDF will also handle different time zones and leap seconds correctly.

And when applied to a column with TIMESTAMP as type, `to_unixtime` will change how it's displayed.

We have implemented `from_unixtime()` which can be referenced. It does the opposite conversion.

**Comment by etolbakov** [comment]
Hi @waynexia 
I wonder if this is still relevant? 
I found this [TODO](https://github.com/GreptimeTeam/greptimedb/blob/610a895b6619c93f986e76c10aa1417388e6c0ee/src/common/function/src/scalars/timestamp/from_unixtime.rs#L16) at the top of `from_unixtime()`, have a feeling that it would be true for `to_unixtime` as well.

**Comment by etolbakov** [comment]
@waynexia yeah, I can give it go if it's not super urgent.
As for the `to_unixtime()` can we use `to_timestamp_seconds` for our purposes or am I missing something?

**Comment by waynexia** [comment]
>As for the to_unixtime() can we use to_timestamp_seconds for our purposes or am I missing something?

`to_timestamp_seconds` is something more like `from_unixtime()`, it convert a integer to timestamp format. An [example](https://github.com/apache/arrow-datafusion/blob/8a262c3ec0a100607ae97641d7a374c847a71f20/datafusion/core/tests/sql/timestamp.rs#L153-L159):

```
    "SELECT to_timestamp_seconds(ts) FROM ts_data LIMIT 3"

        "+--------------------------------+",
        "| totimestampseconds(ts_data.ts) |",
        "+--------------------------------+",
        "| 2020-09-08T13:42:29            |",
        "| 2020-09-08T12:42:29            |",
        "| 2020-09-08T11:42:29            |",
        "+--------------------------------+",
```

**Comment by Jacen-cpu** [comment]
Is this true?
https://github.com/GreptimeTeam/greptimedb/issues/1103#issue-1604345194
` to_unixtime("2023-03-01T06:35:02Z") return 1678269302`
```
mysql> select from_unixtime(1678269302); 
+---------------------------------+
| fromunixtime(Int64(1678269302)) |
+---------------------------------+
| 2023-03-08 09:55:02             |
+---------------------------------+
1 row in set (0.00 sec)
```

**Comment by Jacen-cpu** [comment]
@waynexia I want to know how to add a UDF in sql.

**Comment by waynexia** [comment]
>to_unixtime("2023-03-01T06:35:02Z") return 1678269302

That's it 👍 

>I want to know how to add a UDF in SQL.

You can take [`from_unixtime()`](https://github.com/GreptimeTeam/greptimedb/blob/610a895b6619c93f986e76c10aa1417388e6c0ee/src/common/function/src/scalars/timestamp/from_unixtime.rs#L16) as reference.

**Comment by etolbakov** [comment]
@evenyag @waynexia 
this issue could be closed as the PRs have been merged, wdyt?

**Comment by killme2008** [comment]
Looks like the `to_unxtime` only supports `string` type right now, but we store the timestamps in `timestamp` type, we can't use this function to cast them into unix times:

```sql
create table test(a int, b timestamp time index);

insert into test values(1, 2);
```

And try to use `to_unixtime`:

```
select to_unixtime(b) from test;
```

Report error:
```
Internal error occurred during query exec, server actively close the channel to let client try next time: Failed to collect recordbatch, source: Failed to poll stream, source: External error: Failed to poll stream, source: Arrow error: Invalid argument error: column types must match schema types, expected Timestamp(Second, None) but found Int64 at column index 0.
```

I think this function should accepts `timestamp` type as arguments too, we can change the signature into:

```
    fn signature(&self) -> Signature {
        Signature::uniform(1, 
            vec![ConcreteDataType::String(StringType), ConcreteDataType::Timestamp(TimestampType)],
            Volatility::Immutable,
        )
    }

```

**Comment by etolbakov** [comment]
@killme2008 I'm happy to add a fix here if it's not super urgent

**Comment by killme2008** [comment]
> @killme2008 I'm happy to add a fix here if it's not super urgent

Cool, it's not urgent. Appreciate it if you can fix it. Thank you.
