### ISSUE TITLE
Replace tempdir with tempfile

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1108]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

[tempdir](https://github.com/rust-lang-deprecated/tempdir) is archived, we should use [tempfile](https://github.com/Stebalien/tempfile) instead

### Implementation challenges

We need to replace all usages of [tempdir](https://github.com/rust-lang-deprecated/tempdir) with [tempfile](https://github.com/Stebalien/tempfile) and finally remove tempdir from our dependencies.

**Comment by etolbakov** [comment]
@evenyag 
Seems that this issue could be closed.

**Comment by evenyag** [comment]
Fixed in #1123
