### ISSUE TITLE
Creating table via procedure does not respect TTL option

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1112]
### What type of bug is this?

Configuration

### What subsystems are affected?

Datanode

### What happened?

When creating table using Procedure framework, seems that table options are not passed to "create region" subprocedure

https://github.com/GreptimeTeam/greptimedb/blob/0b3f955ca7c7eb145a786a36fa764a6ed60a8464/src/mito/src/engine/procedure/create.rs#L162

So TTL option may not take effect.

### What operating system did you use?

macOS

### How can we reproduce the bug?

Create a new table with explicit TTL options and checks if manifest contains that value.

**Comment by etolbakov** [comment]
Hello @v0y4g3r,
is it something that you have in mind?

```rust
 let open_opts = OpenOptions {
            parent_dir: table_dir.clone(),
            write_buffer_size: None,
            ttl: self.data.request.table_options.ttl,
        };
        let create_opts = CreateOptions {
            parent_dir: table_dir,
            write_buffer_size: None,
            ttl: self.data.request.table_options.ttl,
        };
```

**Comment by etolbakov** [comment]
@v0y4g3r , @killme2008 
I believe, this issue could be closed.

**Comment by killme2008** [comment]
@etolbakov Yep, thanks for your contribution.
