### ISSUE TITLE
[Docs] Add a How-to-run-tests section into Contributing Guide

### ISSUE THREAD

**Issue by xtang** [GreptimeTeam/greptimedb#1119]
### What type of enhancement is this?

Other

### What does the enhancement do?

From our contributor @masonyc, 
> I think it's beneficial to put the how-to-run-tests guides into the github contribute page...

That's a great idea!

**Comment by morigs** [comment]
I wanted to submit a PR fixing this, but the I noticed that some tests are failing when running using `cargo test`:

```sh
$ cargo test --workspace
...
test result: FAILED. 25 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 8.48s
```

However, everything nice and clean when using nextest:

```sh
$ cargo nextest run
...
Summary [  37.646s] 1142 tests run: 1142 passed, 3 skipped
```

**Comment by waynexia** [comment]
>I wanted to submit a PR fixing this,

👍 

>but the I noticed that some tests are failing when running using cargo test:

Can you reproduce this? And if so, please give a list of what failed, I'll take a look at it

nextest is faster than the built-in test harness. I'm using it on my daily dev. We could provide both way in the doc (both `cargo test --workspace` and `cargo nextest run`)

**Comment by morigs** [comment]
Here's my output. Not sure if this is helpful, because it's almost unreadable to me)
[greptime-test.log](https://github.com/GreptimeTeam/greptimedb/files/10894978/greptime-test.log)

**Comment by waynexia** [comment]
Thanks! 

Two failed cases:
```
test instance::prometheus::tests::test_distributed_prometheus_remote_rw ... FAILED
test instance::tests::test_distributed_exec_sql ... FAILED
```

Others are backtrace (those unreadable texts) 🤣

**Comment by killme2008** [comment]
Perhaps because of the max file descriptors limitation.  Can you run the test after executing `ulimit -n 10000`?

**Comment by morigs** [comment]
@killme2008 wow, good catch. Increasing file descriptors limit really helps!
