### ISSUE TITLE
Add column supports at first or after the existing columns

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1120]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Add column supports before/after the existing columns.

For example:

```sql
ALTER TABLE monitor ADD COLUMN new_column1 double FIRST;
ALTER TABLE monitor ADD COLUMN new_column2 double AFTER memory;
```

**Comment by lizhemingi** [comment]
Let me have a try if you don't mind.

**Comment by killme2008** [comment]
@lizhemingi Go head! Thanks.
