### ISSUE TITLE
Rename `promql` and `prometheus` server

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1127]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Context: https://github.com/GreptimeTeam/greptimedb/pull/924#issuecomment-1413560052

The current `prometheus` server is for prometheus remote storage. And `promql` server is for prometheus HTTP server. We should rename them to avoid confusion.

Proposal: rename `prometheus` to `prom-store` and `promql` to `prometheus`

**Comment by v0y4g3r** [comment]
Is this issue resolved?

**Comment by etolbakov** [comment]
@waynexia I'd like to give it a try if you don't mind

**Comment by waynexia** [comment]
Appreciate it!
