### ISSUE TITLE
Listen to 0.0.0.0 by default

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1128]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

As in https://github.com/GreptimeTeam/docs/pull/222, we realized that when listening to 127.0.0.1, users cannot connect to greptimedb via 127.0.0.1/localhost on docker host. 

## Proposal

To fix this issue we can listen to 0.0.0.0 by default. 

## Cons

Is there any security issue to expose the service to all network by default?

Alternative proposals are welcomed.

**Comment by dragon-zhang** [comment]
May I ask if this issue has been fixed? If not, can I try it?

**Comment by sunng87** [comment]
@dragon-zhang Thanks for reaching out. The solution mentioned in my issue was not perfect so we still want to seek for a better one to avoid expose the service to all network by default. 

If you want to get started with development of greptimedb you can find other issues labeled "good first issue". Thank you

**Comment by tisonkun** [comment]
@sunng87 could you provide a reproduce where we cannot connect to the Docker instance now?

We exchangeably use `127.0.0.1` and `0.0.0.0` and without a repro it's hard to figure out which line is relevant.

**Comment by sunng87** [comment]
@tisonkun check the example here https://docs.greptime.com/getting-started/installation/greptimedb-standalone#docker

If you remove those options `--http-addr`/`--mysql-addr` etc. The server will listen to `127.0.0.1` by default and the service won't be available outside docker network

**Comment by sunng87** [comment]
But using `0.0.0.0` by default is actually not a good idea. Currently we fix this by adding those startup options for our example. I think it's OK to mark this as finished.
