### ISSUE TITLE
Exposing cluster topology and status via frontend http api

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1131]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

As mentioned in https://github.com/GreptimeTeam/dashboard/issues/159 , it would be nice to have an overview of cluster status, including:

- how many datanodes, frontends and metas in current cluster
- their address, load and other usage information
- how many clients are connected to current cluster

These information will be reporting to meta via heartbeats, and exposed via frontend HTTP API, say `/v1/self/status`

**Comment by SSebo** [comment]
Is this issue open for community contributor? @sunng87

**Comment by sunng87** [comment]
I think we are approaching an alternative solution for this in #2921 and #2931 . You might be interested in one of those tasks.

**Comment by sunng87** [comment]
I'm closing this because we are going to implement this with sql and table data from information schema.
