### ISSUE TITLE
Adopt `human-panic`

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1165]
### What type of enhancement is this?

User experience

### What does the enhancement do?

By adopting "[human-panic](https://crates.io/crates/human-panic)", we can provide a more verbose and friendly panic message to user. At least we can print out our repo's "issues" link, and guide users how and what to submit them.

**Comment by ArslanYM** [comment]
How can we add this feature?

**Comment by MichaelScofield** [comment]
@ArslanYM I think we can start from taking `human_panic`'s [tests](https://github.com/rust-cli/human-panic/tree/master/tests) as examples.

**Comment by tisonkun** [comment]
@MichaelScofield Here is an attempt, while I have two concerns or suggestions to discuss.

### Code

```rust
    let metadata = human_panic::Metadata {
        version: env!("CARGO_PKG_VERSION").into(),
        name: "GreptimeDB".into(),
        authors: Default::default(),
        homepage: "https://github.com/GreptimeTeam/greptimedb/issues".into(),
    };
    human_panic::setup_panic!(metadata);
    panic!("error");
```

### Output

```
$ cargo build --release
$ ./target/release/greptime standalone start
Well, this is embarrassing.

GreptimeDB had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/ts/160w4k_j5mv5bjk9rnjkzjpm0000gn/T/report-879ad8f0-f282-4f16-9c9e-c85b1d388b36.toml". Submit an issue or email with the subject of "GreptimeDB Crash Report" and include the report as an attachment.

- Homepage: https://github.com/GreptimeTeam/greptimedb/issues

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!
```

### Concerns or suggestions

First, the `setup_panic` macro is expanded to:

```rust
        match $crate::PanicStyle::default() {
            $crate::PanicStyle::Debug => {}
            $crate::PanicStyle::Human => {
                let meta = $meta;

                panic::set_hook(Box::new(move |info: &PanicInfo| {
                    let file_path = handle_dump(&meta, info);
                    print_msg(file_path, &meta)
                        .expect("human-panic: printing error message to console failed");
                }));
            }
        }
```

where `PanicStyle::default()` is:

```rust
        if cfg!(debug_assertions) {
            PanicStyle::Debug
        } else {
            match ::std::env::var("RUST_BACKTRACE") {
                Ok(_) => PanicStyle::Debug,
                Err(_) => PanicStyle::Human,
            }
        }
```

So we can only debug this manner with `--release`. I don't know if it's desired but it's hardcode (generally the human-panic is programed once but why do we just cannot access it when in DEBUG mode?).

Second, the configurable fields do not contain something like `Open an issue to ...` which is referred above.

I'd like to confirm the expected output to see how much we should hack into the crate or do something in the upstream to meet our requirement.

Briefly, is the [output](#output) above you expect?

**Comment by tisonkun** [comment]
What I propose above is to customize the panic manner by:

1. Change the `match $crate::PanicStyle::default()` block with our own conditions;
2. Hack into `print_msg` for printing what we exactly want.

**Comment by MichaelScofield** [comment]
@tisonkun thx, here are my thoughts:
1. I think it's fine that `human-panic` only works in release mode. I find an issue in its repo about this behavior consideration, and I agree with that: https://github.com/rust-cli/human-panic/issues/48
2. From what I see, the output contains all the necessary info for user to fire a crash report issue to us. It's only the text polish improvement problem. So personally I prefer the upstream change. Should the `human-panic` come out with a better output message template or whatever, we can simply upgrade it. WDYT?

**Comment by tisonkun** [comment]
OK. Let me prepare a simple integration now.
