### ISSUE TITLE
Proposal: Adds semantic type to column schema

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1183]
### What type of enhancement is this?

API improvement, Tech debt reduction

### What does the enhancement do?

The gRPC protocol contains three semantic types:

* Tag:  just like labels in Prometheus or tags in OpenTSDB.
* Field: the value field.
* Timestamp: the time index column.

All these types can be configured by users. But it's not implemented in SQL.
The time index column already exists in the table(region) schema, but the tag and field aren't.
We are implementing smart indexing for tag columns. It requires knowing whether a column is a tag column. If not, we should not create an index for fields, because they will not be used in the query criterion.

I proposals adding a new column option `LABEL` for `CREATE TABLE`:

```sql
CREATE TABLE monitor (
  host STRING LABEL,
  ts TIMESTAMP,
  cpu DOUBLE DEFAULT 0,
  memory DOUBLE,
  TIME INDEX (ts),
  PRIMARY KEY(host)) ENGINE=mito WITH(regions=1);
```

We set the `host` column to be a label by the `LABEL` column option, then the smart indexer will choose to create an index for it to speed up the query which contains this label. 
Recommend renaming the `Tag` in gRPC to `Label` too.

**Comment by vinland-avalon** [comment]
Sounds good to improve SQL. But when it comes to name, why choose `Label` rather than `Tag`? I find something related at #551. `Tag` seems good enough.

**Comment by killme2008** [comment]
In fact, the primary key in greptimedb is used to represent the tag or label semantics in TSDB protocols. We can add all tags(or labels) to the primary key constraint.
