### ISSUE TITLE
Establish a heartbeat mechanism between meta and frontend

### ISSUE THREAD

**Issue by Fengys123** [GreptimeTeam/greptimedb#1189]
### What problem does the new feature solve?

In #816, I encountered a [problem](https://github.com/GreptimeTeam/greptimedb/issues/816#issuecomment-1469658825). So we need a mechanism to notify the frontend catalog cache invalidation.

And, [region failover](https://github.com/GreptimeTeam/greptimedb/pull/1139#discussion_r1133831429) also needs  a heartbeat mechanism between meta and frontend.

### What does the feature do?

It is similar to the heartbeat between datanode and meta.

**Comment by WenyXu** [comment]
completed in #1555
