### ISSUE TITLE
Only single quote string is allowed in where clause

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1210]
### What type of bug is this?

Other

### What subsystems are affected?

Frontend

### What happened?

It seems our `WHERE` clause follows PostgreSQL dialect that only allow string wraps in singe quote `'`. While in MySQL, it allows both single quote and double quotes. 

The behaviour is inconsistent for `INSERT` statement, when providing values, double-quote strings are accepted.

We should change `WHERE` clause to accept double-quote string as well.

### What operating system did you use?

any

### How can we reproduce the bug?

```bash
Run SQL:


SELECT * FROM system_metrics WHERE host = "abc";
```

**Comment by NiwakaDev** [comment]
I'd like to work on this issue.

**Comment by killme2008** [comment]
> I'd like to work on this issue.

Assigned it to you, Thank you.

**Comment by NiwakaDev** [comment]
Thank you for your quick reply!

>If we want different behavior, maybe we could switch to [MySqlDialect](https://docs.rs/sqlparser/latest/sqlparser/dialect/struct.MySqlDialect.html).

I initially considered using MySqlDialect, and then I replaced `GenericDialect` with `MySqlDialect`:

https://github.com/GreptimeTeam/greptimedb/blob/6b6617f9cb24439b29b79bbc2bb7dee99a656d40/src/frontend/src/instance.rs#L435-L437

but several tests fail, like so:
```
    ... skip(26) ...,
~   Error: 3000(PlanQuery), No field named "a". -> +-----------+,
+   | Utf8("a") |,
+   +-----------+,
+   | a         |,
+   +-----------+,
    ... skip(3) ...,
~   Error: 3000(PlanQuery), No field named "A". -> +-----------+,
+   | Utf8("A") |,
+   +-----------+,
+   | A         |,
+   +-----------+,

//..

[
    ... skip(358) ...,
~   Affected Rows: 0 -> Error: 2000(InvalidSyntax), sql parser error: Expected column name or constraint definition, found: "Sort",
    ... skip(12) ...,
~   Affected Rows: 9 -> Error: 4001(TableNotFound), Table not found: greptime.public.DirectReports,
    ... skip(5) ...,
~   +------------+-------------------+------------------------------+---------------+ -> Error: 4001(TableNotFound), Table `greptime.public.DirectReports` not exist,
-   | EmployeeID | Name              | Title                        | EmployeeLevel |,
-   +------------+-------------------+------------------------------+---------------+,
-   | 1          | Ken Sánchez       | Chief Executive Officer      | 1             |,
-   | 273        | >Brian Welcker    | Vice President of Sales      | 2             |,
-   | 16         | >>David Bradley   | Marketing Manager            | 3             |,
-   | 23         | >>>Mary Gibson    | Marketing Specialist         | 4             |,
-   | 274        | >>Stephen Jiang   | North American Sales Manager | 3             |,
-   | 276        | >>>Linda Mitchell | Sales Representative         | 4             |,
-   | 275        | >>>Michael Blythe | Sales Representative         | 4             |,
-   | 285        | >>Syed Abbas      | Pacific Sales Manager        | 3             |,
-   | 286        | >>>Lynn Tsoflias  | Sales Representative         | 4             |,
-   +------------+-------------------+------------------------------+---------------+,
    ... skip(35) ...,
~   Affected Rows: 1 -> Error: 4001(TableNotFound), Table `greptime.public.DirectReports` not exist,
   
Environment standalone run finished, cost:2709ms
Failed cases:
[
    "/Users/username/Desktop/greptimedb/tests/cases/standalone/common/create/create",
    "/Users/username/Desktop/greptimedb/tests/cases/standalone/common/select/dummy",
    "/Users/username/Desktop/greptimedb/tests/cases/standalone/order/order_variable_size_payload",
]
```

**Comment by NiwakaDev** [comment]
This issue seems to be more difficult than I thought because we need to make the `MySqlDialect` operate only within the `WHERE` clause. Does anyone have any ideas for a implementation?

**Comment by evenyag** [comment]
@sunng87 Do we still consider this a bug?

**Comment by sunng87** [comment]
Because we are going to act as a drop-in MySQL replacement, I still believe we need to be compatible with its dialect. Maybe we can switch to `MySqlDialect` globally to see what impact is it. We already have strong sqlness test suite and it should be relatively easy to judge.

**Comment by NiwakaDev** [comment]
Thank you for your quick reply, @sunng87.

>Maybe we can switch to MySqlDialect globally to see what impact is it. 

I guess that we could switch to the MySqlDialect globally by making changes here:

https://github.com/GreptimeTeam/greptimedb/blob/6b6617f9cb24439b29b79bbc2bb7dee99a656d40/src/frontend/src/instance.rs#L435-L437

What is your opinion on this?

**Comment by sunng87** [comment]
Thank you @NiwakaDev, if you want a quick verification, you will need to update this as well:

https://github.com/GreptimeTeam/greptimedb/blob/develop/src/query/src/parser.rs#L54

I agree this is heavier than a "good first issue". We can take over this if you are ok.

**Comment by NiwakaDev** [comment]
@sunng87 

>I agree this is heavier than a "good first issue". We can take over this if you are ok.
Sure. I'll look for other issues.

**Comment by killme2008** [comment]
We are using different dialects in different protocols, so i think it's not an issue right now.
