### ISSUE TITLE
PGO applicability

### ISSUE THREAD

**Issue by zamazan4ik** [GreptimeTeam/greptimedb#1218]
### What type of enhancement is this?

User experience

### What does the enhancement do?

I have tested building greptimedb with PGO and want to share some results.

I was using https://github.com/GreptimeTeam/greptimedb/tree/develop/benchmarks as a training and benchmarking scenario. The build was performed with `cargo-pgo`. Test env is my Mac M1 on macOS 13.2.1.

The results are the following:
* Usual release build without PGO: https://pastebin.com/NKFvRAGf 
* PGO build: https://pastebin.com/CrLnBBNi

Results are quite promising so I guess it's worth documenting somewhere that PGO could be used to achieve an additional performance boost.

**Comment by waynexia** [comment]
Thanks for investigating this, the result you have presented are impressive 🚀 

>I guess it's worth documenting somewhere that PGO could be used to achieve an additional performance boost.

Definitely. I just create an [issue](https://github.com/GreptimeTeam/docs/issues/267) in our docs repo requests document about benchmark tools. It would be a suitable location to include details related to pgo. Would you be interested in helping with the documentation?

**Comment by zamazan4ik** [comment]
> Would you be interested in helping with the documentation?

Not sure that I could write the whole text since I am not a technical writer... But definitely I can share a lot of good materials regarding PGO. And can describe, how PGO could be performed.

**Comment by tisonkun** [comment]
Superseded by https://github.com/GreptimeTeam/docs/issues/544.
