### ISSUE TITLE
Implement `deriv` fn in PromQL

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1227]
### What problem does the new feature solve?

Implement the deriv function resets from PromQL. Refer to [promql's document](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv) and [the go implementation](https://github.com/prometheus/prometheus/blob/90b2f7a540b8a70d8d81372e6692dcbb67ccbaaa/promql/functions.go#L839-L856) for more details.

### What does the feature do?

- implement the function, refer to https://github.com/GreptimeTeam/greptimedb/blob/develop/src/promql/src/functions/aggr_over_time.rs for examples
- add unit tests for your implementations
- add the necessary document

**Comment by haohuaijin** [comment]
Hi, @waynexia 
can you have a look at this?

**Comment by waynexia** [comment]
Closed by #1324, thanks @haohuaijin ❤️
