### ISSUE TITLE
Incremental region stats collector

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1231]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Current region stats collector implementation iterates all regions to sum the disk usage:
https://github.com/GreptimeTeam/greptimedb/pull/1167/files#diff-33a752df95b8b95391e84139c7ec6d57e85d52cc319bc985aca49783be9f9d36R258-R277

When most of the regions are idle, the stats collector will report a lot of unchanged stats like:
```json
[ {
      "id": 25744033972224,
      "catalog": "<...>",
      "schema": "testsaa",
      "table": "monitor2",
      "rcus": 0,
      "wcus": 0,
      "approximate_bytes": 0,
      "approximate_rows": 0
    },
    {
      "id": 25701084299265,
      "catalog": "<...>",
      "schema": "testsaa",
      "table": "aa",
      "rcus": 0,
      "wcus": 0,
      "approximate_bytes": 0,
      "approximate_rows": 0
    },
...
]
```

We need to improve the stats collector to an incremental collector that only reports changed region stats to reduce orverhead.

### Implementation challenges

We can add a "usage_updated" flag to regions, once regions flushes a new memtable to disk the flag is set to true which indicates stats collector should sum the disk usages of this regions, otherwise it can just skip this region.

**Comment by qstommyshu** [comment]
Hi,
I'm wondering how can I check the stats in the stats collector(or how can I run the stats collector).

**Comment by v0y4g3r** [comment]
> Hi, I'm wondering how can I check the stats in the stats collector(or how can I run the stats collector).

HI Tommy, here's some background information of this task.

First of all, regions stat collector is actually a background task scheduled everytime heartbeat is triggered:
https://github.com/GreptimeTeam/greptimedb/blob/1a21a6ea417810d0cc6ef0992ba61dc20856e68a/src/datanode/src/heartbeat.rs#L107-L110

Datanode reports it's region stats along with heartbeat to metasrv. By this region stats metasrv can then determine the load of all datanodes and distribute regions to datanodes accordingly.

But for some datanode, most regions remain inactive, then it's region stats may not change since last reported. We need to avoid reporting these unchanged stats to reduce overhead. That's all this task is about.

As for your question, you can simply print the `region_stats` to stdout here: https://github.com/GreptimeTeam/greptimedb/blob/1a21a6ea417810d0cc6ef0992ba61dc20856e68a/src/datanode/src/heartbeat.rs#L109

Or you can also report these stats to metrics registry so that you can use HTTP API to retrive region stats.

https://github.com/GreptimeTeam/greptimedb/blob/0c88bb09e32e1e21990f9f454f8c024287aef06e/src/common/telemetry/src/metric.rs#L35

**Comment by JohnsonLee-debug** [comment]
Hi. Maybe i could give it a try.

**Comment by tisonkun** [comment]
Unassigned due to long time inactive. Release to any contributor.

**Comment by leaf-potato** [comment]
Does this issue still need to be resolved? I want to have a try for it.

**Comment by killme2008** [comment]
> Does this issue still need to be resolved? I want to have a try for it.

Of course, thank you.

**Comment by leaf-potato** [comment]
After PR https://github.com/GreptimeTeam/greptimedb/pull/1167, the code has changed a lot. In order to modify the code correctly, I first sorted out the current function call process.

1. The heartbeat background call the `load_region_stats` function to get region usage:
https://github.com/GreptimeTeam/greptimedb/blob/803780030d4d3ef5524f88580f2750d98fdeabcf/src/datanode/src/heartbeat.rs#L245-L247

2. Call `region_server.region_disk_usage` function in function `load_region_stats` to get disk usage: https://github.com/GreptimeTeam/greptimedb/blob/803780030d4d3ef5524f88580f2750d98fdeabcf/src/datanode/src/heartbeat.rs#L319-L326

3. After `RegionServer`, `MitoEngine`, etc. struct, call `region_usage` of `MitoRegion` to construct the `RegionUsage` struct.
https://github.com/GreptimeTeam/greptimedb/blob/803780030d4d3ef5524f88580f2750d98fdeabcf/src/mito2/src/region.rs#L238-L241

4. In `RegionUsage`, call `disk_usage` method to get the value that we want to repot:
https://github.com/GreptimeTeam/greptimedb/blob/803780030d4d3ef5524f88580f2750d98fdeabcf/src/mito2/src/region.rs#L56-L58

I don't know if it is correct, please correct me if there is any mistake.

**Comment by leaf-potato** [comment]
I have a question. If we change to incremental reporting of region usage, how does the meta service know the usage of unchanged regions? Will the meta service maintain the usage of all regions?

**Comment by evenyag** [comment]
> If we change to incremental reporting of region usage, how does the meta service know the usage of unchanged regions?

@leaf-potato  You are right, this is the problem. I wonder if the incremental collector is necessary currently. This issue is quite complicated to implement.

Maybe we can close this issue first. We can still reopen it if collecting region status becomes a bottleneck.

**Comment by leaf-potato** [comment]
> Maybe we can close this issue first. We can still reopen it if collecting region status becomes a bottleneck.

@evenyag Agree with you. Previously, only the disk space of the sst file was calculated. Therefore, when the data is still in the memory and has not been written to the disk, the following data with the `approximate_bytes` field being 0 may be transmitted in the heartbeat. 
```json
[ 
  {
      "id": 25744033972224,
      "catalog": "<...>",
      "schema": "testsaa",
      "table": "monitor2",
      "rcus": 0,
      "wcus": 0,
      "approximate_bytes": 0,
      "approximate_rows": 0
    }
]
```
This situation may be optimized, but the current disk calculation estimates the memory data as disk space, so this problem does not exist. Cc @v0y4g3r.

**Comment by evenyag** [comment]
> the following data with the approximate_bytes field being 0 may be transmitted in the heartbeat.

This is tolerable.

**Comment by leaf-potato** [comment]
> > the following data with the approximate_bytes field being 0 may be transmitted in the heartbeat.
> 
> This is tolerable.

Got it, thanks!
