### ISSUE TITLE
Support batch range delete on meta's `Store` api

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#1237]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Addition to `DeleteRange` on meta's `Store` api, add `BatchDeleteRange` so that different ranges of key-prefix can be deleted at once, ensuring atomicity.

**Comment by fengjiachun** [comment]
Do we really need `BatchDeleteRange`? Isn't `BatchDelete` sufficient?
I think we need to consider carefully since `BatchDeleteRange` is a powerful and error-prone API.  😄

**Comment by shuiyisong** [comment]
In certain scenarios like `drop databases`, when we need to delete a variety of prefixed keys, `BatchDeleteRange` might come handy due to its guarantee of atomicity. There are two other alternatives: 
1. Invoking multiple `DeleteRange`, but this may require coordinating with a retry framework in order to ensure consistency. 
3. Using `Range` to obtain all the keys that need to be deleted and then invoke `BatchDelete` to remove them all at once.

I am confident that using `Range` and `BatchDelete` will suffice for our needs here. Let's give it a try! 😆
