### ISSUE TITLE
information_schema.TABLES support for mysql protocol

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1251]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

A few visualization or BI tools, grafana for example, has query builders to help user to construct a query. These query builders retrieve table information from a table called `information_schema.TABLES` in mysql: https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.0/en/information-schema-tables-table.html

At the moment if we configure greptimedb as a grafana mysql data source, it error at this query:
```
Failed to execute query 'SELECT DISTINCT TABLE_SCHEMA from information_schema.TABLES where TABLE_TYPE != 'SYSTEM VIEW' ORDER BY TABLE_SCHEMA' err.msg=Failed to execute query: SELECT DISTINCT TABLE_SCHEMA from information_schema.TABLES where TABLE_TYPE != 'SYSTEM VIEW' ORDER BY TABLE_SCHEMA,
```

We don't need to implement this schema or table actually but should be able to respond queries like this, in order to provide better usability with tools depend on it.

### Implementation challenges

Since mysql is not designed with multi-tenancy in mind, we should carefully deal with the query under it's context of greptimedb's catalog and schema.

**Comment by sunng87** [comment]
Currently we have `system.information_schema.tables` that stores the information. There are two approaches to enhance this:

- create information_schema for each catalog
- transform the query on `select * from mycatalog.information_schema.tables` to `select * from system.information_schema.tables where catalog = mycatalog`

**Comment by sunng87** [comment]
[metabase](https://metabase.com) relies on `information_schema.tables` as well, plus it's query is a little complex than grafana:

```sql
SELECT TABLE_SCHEMA TABLE_CAT, NULL TABLE_SCHEM, TABLE_NAME, IF(TABLE_TYPE='BASE TABLE' or TABLE_TYPE='SYSTEM VERSIONED', 'TABLE', TABLE_TYPE) as TABLE_TYPE, TABLE_COMMENT REMARKS, NULL TYPE_CAT, NULL TYPE_SCHEM, NULL TYPE_NAME, NULL SELF_REFERENCING_COL_NAME, NULL REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = database() AND  TABLE_TYPE IN ('BASE TABLE','SYSTEM VERSIONED','PARTITIONED TABLE','VIEW','FOREIGN TABLE','MATERIALIZED VIEW','EXTERNAL TABLE') ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME
```

There is an interesting function call `database()` that will return current selected database.

**Comment by sunng87** [comment]
The query grafana uses to load table names:

```sql
SELECT table_name FROM information_schema.tables WHERE table_schema = 'test' ORDER BY table_name
```

**Comment by MichaelScofield** [comment]
Well, that metabase's query is quite difficult to support. Currently we can only execute this:

```sql
SELECT
  TABLE_SCHEMA TABLE_CAT,
  NULL TABLE_SCHEM,
  TABLE_NAME,
  NULL TYPE_CAT,
  NULL TYPE_SCHEM,
  NULL TYPE_NAME,
  NULL SELF_REFERENCING_COL_NAME,
  NULL REF_GENERATION
FROM
  INFORMATION_SCHEMA.TABLES
WHERE
  TABLE_SCHEMA = 'hello'
  AND TABLE_TYPE IN (
    'BASE TABLE',
    'SYSTEM VERSIONED',
    'PARTITIONED TABLE',
    'VIEW',
    'FOREIGN TABLE',
    'MATERIALIZED VIEW',
    'EXTERNAL TABLE'
  )
ORDER BY
  TABLE_TYPE,
  TABLE_SCHEMA,
  TABLE_NAME
```

the result is:

```text
+-----------+-------------+------------+----------+------------+-----------+---------------------------+----------------+
| table_cat | table_schem | table_name | type_cat | type_schem | type_name | self_referencing_col_name | ref_generation |
+-----------+-------------+------------+----------+------------+-----------+---------------------------+----------------+
| hello     |        NULL | world      |     NULL |       NULL |      NULL |                      NULL |           NULL |
+-----------+-------------+------------+----------+------------+-----------+---------------------------+----------------+
```

Three things are missing:

1. Cannot execute `database()` in the middle. Only `select database()` is supported.
2. No `IF(...)` in select (this one seems the hardest).
3. No `TABLE_COMMENT` column.

**Comment by sunng87** [comment]
No problem. When it's too difficult to be fully compatible with metabase's mysql data source, we can create a simplified data source by forking it and add "greptimedb" source. It's not always preferred but it's acceptable.
