### ISSUE TITLE
New syntax for creating distributed table

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1281]
### What problem does the new feature solve?

Creating a distributed table requires manually specify partition rules. For example:

```sql
CREATE TABLE dist_table(
    ts TIMESTAMP DEFAULT current_timestamp(),
    n INT,
    row_id INT,
    TIME INDEX (ts)
)
PARTITION BY RANGE COLUMNS (n) (
    PARTITION r0 VALUES LESS THAN (5),
    PARTITION r1 VALUES LESS THAN (9),
    PARTITION r2 VALUES LESS THAN (MAXVALUE),
)
engine=mito;
```

The "partition by ..." part is a little complex and not easy to write.

### What does the feature do?

1. If user does not need that fixed partition rule (I think under most scenarios, not), we could ease the burden of writing the SQL by implementing the existed "with(regions = n)" syntax, and skip defining the region's ranges (the `PARTITION ... VALUES ...` part). 
2. Originally the whole "PARTITION BY" syntax are borrowed from MySQL, for compatibility. But I don't think we should stick to that anymore. Besides, the "partition" in our create table statement is actually refers to "region", and the word "partition" has its own meaning in our domain knowledge. Let's not overuse the word.

**Breaking change alert!** I propose the following new syntax for creating distributed table:

```sql
CREATE TABLE dist_table(
    ts TIMESTAMP DEFAULT current_timestamp(),
    n INT,
    row_id INT,
    TIME INDEX (ts),
)

# both syntax 1:
DISTRIBUTE BY RANGE COLUMNS(n) ( # "PARTITION BY" => "DISTRIBUTE BY"
    REGION r0 VALUES LESS THAN (5), # "PARTITION" => "REGION"
    REGION r1 VALUES LESS THAN (9),
    REGION r2 VALUES LESS THAN (MAXVALUE),
)

# and syntax 2 are ok:
DISTRIBUTE BY RANGE COLUMNS(n) # "PARTITION BY" => "DISTRIBUTE BY"
with(regions = 3) # omit defining the range for each region

engine=mito;
```

The Frontend (or the Metasrv) should automatically calculate the ranges for each region, then create the distributed table as always.

**Comment by NiwakaDev** [comment]
According to the below comment, `partition` and `region` will be handled as different thing in the near future.
https://github.com/GreptimeTeam/greptimedb/blob/5b7b2cf77d9a9d1262acfc55f1783895ec70d4e9/src/partition/src/range.rs#L54-L57

So, I guess that the new syntax is as follows:
```sql
CREATE TABLE dist_table(
    ts TIMESTAMP DEFAULT current_timestamp(),
    n INT,
    row_id INT,
    TIME INDEX (ts),
)

DISTRIBUTE BY RANGE COLUMNS(n) # "PARTITION BY" => "DISTRIBUTE BY"
with(partitions = 3) # not regions

engine=mito;
```

**Comment by MichaelScofield** [comment]
Currently we are refactoring the datanode, making it not aware of tables (datanode then becomes "region server", see https://github.com/GreptimeTeam/greptimedb/blob/develop/docs/rfcs/2023-07-06-table-engine-refactor.md). We hope that the "partition" here in the create table SQL would be removed in the future. It's simpler to unify these two concept to "region" only.
