### ISSUE TITLE
Adapt to OpenTelemery protocol

### ISSUE THREAD

**Issue by JasonChen86899** [GreptimeTeam/greptimedb#1288]
### What problem does the new feature solve?

Make greptimedb adapt to OpenTelemery protocol(OTLP) for storing **log, tracing , metric** time series data

Related discussions: 
https://github.com/GreptimeTeam/greptimedb/discussions/1176

### What does the feature do?

Can receive and store OLTP time series data

### Implementation challenges

Three ideas about this

1.  Adapt OLTP protocol in client library

2. Add OLTP exporter in greptimedb Frontend

3. Add another alone backend build on greptimedb just like [promscale](https://docs.timescale.com/promscale/latest/) which is another tsdb component.

**Comment by morigs** [comment]
It seems logic to implement OTLP in the frontend among other protocols. However, I'm not sure if it's a good idea to support logs and traces. They are known to have a high volume (terabytes to petabytes), so ofter specialized storages like Grafana Tempo are used

**Comment by JasonChen86899** [comment]
yeah, Grafana Tempo is very good. But in my sense, log trace are all timeseries data like metrics and metrics store are also need a high volume. 
Querying log and tracing will be two steps:  1. within a time duration range 2. get detail for each data in range

Maybe there is something different in mertics store with log and trace store, but I donot know and you can tell me😄

**Comment by morigs** [comment]
Querying everything from one store sounds awesome, however, in practice, store has to be optimized to specific type of workload. Traces/logs meta (id, tags, time) are low-volume and timeseries indeed. Metrics are low volume too, usually, tens of gigabytes. However, traces and logs data (message, events etc) are high volume and can occupy terabytes to petabytes. Thus, they're stored in specialized storages, like elastic, clickhouse or some index + S3.

I'm trying to say that logs/traces support is possible, but may require a lot of effort, this can be a big task IMO.
So I'd initially support metrics only and discuss traces/logs separately.

**Comment by JasonChen86899** [comment]
Thx a lot  for explaining difference between metric and log/tracing. You are right and we can only support metrics first. 

Maybe we can start another discussion about log\tracing data. 
just from my knowledge
1. logki use blotdb and object store((like s3),
2. tempo use parquet and object store that is the same as greptimedb
so we can do something with log/tracing meta and data design. 
Maybe we can start an new issue or discussion to design this together with greptimedb member

**Comment by evenyag** [comment]
We could implement specialized engines for log/trace data if necessary. Currently, I'd like to focus on metrics-like data first so we might not optimize for log/trace data.

> we can only support metrics first.

We could support metrics first. After that, if users don't care about performance, we could store log/trace data like how we store metrics.

> Maybe we can start another discussion about log\tracing data.

A new discussion thread is welcome.

**Comment by killme2008** [comment]
We already supported it in https://github.com/GreptimeTeam/greptimedb/pull/1974
