### ISSUE TITLE
Avoid annoying log: _last_checkpoint range=0- -> errored: NotFound

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1292]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Now the server continuously print the following warning, which is annoying
```
2023-03-31T06:58:28.229448Z  WARN opendal::services: service=fs operation=read path=system/information_schema/0/0_0000000000/manifest/_last_checkpoint range=0- -> errored: NotFound (persistent) at read => entity not found

Context:
    service: fs
    path: system/information_schema/0/0_0000000000/manifest/_last_checkpoint
    range: 0-

Source: No such file or directory (os error 2)
```

### Implementation challenges

Better to supressing this log

**Comment by killme2008** [comment]
It's printed by OpenDAL. Already submit an issue https://github.com/apache/incubator-opendal/issues/1820
