### ISSUE TITLE
Insert distributed table if partition column has default value

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1293]
### What type of enhancement is this?

User experience

### What does the enhancement do?

To insert into distributed table, partition column's value must be present. For example, create distributed table like this:

```sql
create table hello (
    host string,
    ts timestamp DEFAULT CURRENT_TIMESTAMP,
    cpu double default 0,
    TIME INDEX (ts),
    PRIMARY KEY(host)
) engine=mito with(regions=1);
```

Partition column is "ts". We can insert data like this:

```sql
insert into hello(host, cpu, ts) values ('host1', 1.1, 1000)
```

but not like this:

```sql
insert into hello (host, cpu) values ('host2', 2.2)
```

If partition column's value is missing but defined with default value, we should use it.

**Comment by NiwakaDev** [comment]
I'd like to work on this issue!!

**Comment by MichaelScofield** [comment]
@NiwakaDev welcome!
