### ISSUE TITLE
execute promql in distributed mode

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1296]
### What type of enhancement is this?

User experience

### What does the enhancement do?

as title

Now promql is executed through query engine, as logical plans. After #1013 is done, promql should be fairly easy to be executed in distributed mode.

**Comment by waynexia** [comment]
https://github.com/GreptimeTeam/greptimedb/pull/1437 add two basic sqlness cases to run TQL under the distributed mode. The next step is to enable plan/expr pushdown for PromQL planner

**Comment by waynexia** [comment]
Finished in #1684
