### ISSUE TITLE
Failed to execute query, invalid function "user"

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1299]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

can't plan sql

### What operating system did you use?

macos

### Relevant log output and stack trace

error throwed at in planner.rs line 72:

```rust
let result = sql_to_rel.statement_to_plan(df_stmt).with_context(|_| {
```

### How can we reproduce the bug?

create table like this:

```sql
CREATE TABLE hello (
id bigint,
user STRING,
created_ts TIMESTAMP,
PRIMARY KEY(user),
TIME INDEX(created_ts)
)
```

then execute sql:

```sql
 select * from hello where user = 'foo';
```

not expected error:

ERROR 1815 (HY000): Failed to execute query: select * from hello where user = 'foo', source: Failed to plan statement, source: Cannot plan SQL: SELECT * FROM hello WHERE user = 'foo', source: Error during planning: Invalid function 'user'

**Comment by killme2008** [comment]
Looks like we should quote the `user` with double quote:

```sql
mysql> select * from hello where "user"='a';
+------+------+---------------------+
| id   | user | created_ts          |
+------+------+---------------------+
|    1 | a    | 1970-01-01 00:00:00 |
+------+------+---------------------+
1 row in set (0.02 sec)

```

**Comment by killme2008** [comment]
`user` is a keyword in PostgreSQL and MySQL

https://www.postgresql.org/docs/current/sql-keywords-appendix.html

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by MichaelScofield** [comment]
Well, I think we can improve the user experience. Better to interpret "user" as column if it doesn't end with "()". Like this:

```sql
select * from hello where user = 'foo'; # "user" is column

select * from hello where user() = 'foo'; # "user" is function
```

 I'll further investigate it.
