### ISSUE TITLE
Implement `holt_winters` function in PromQL

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1307]
### What problem does the new feature solve?

`holt_winters` is a "Triple exponential smoothing" method used to smooth and predicate on time series data (from [wikipedia](https://en.wikipedia.org/wiki/Exponential_smoothing#Triple_exponential_smoothing_(Holt_Winters))). I'm not very familiar with its use cases and semantic, but prometheus provides [this function](https://prometheus.io/docs/prometheus/latest/querying/functions/#holt_winters) ([implementation](https://github.com/prometheus/prometheus/blob/main/promql/functions.go#L299))

### What does the feature do?

Implement the `holt_winters` function: `holt_winters(v range-vector, sf scalar, tf scalar)`

Document quote from prometheus' code base:
>Holt-Winters is similar to a weighted moving average, where historical data has exponentially less influence on the current data. Holt-Winter also accounts for trends in data. The smoothing factor (0 < sf < 1) affects how historical data will affect the current data. A lower smoothing factor increases the influence of historical data. The trend factor (0 < tf < 1) affects how trends in historical data will affect the current data. A higher trend factor increases the influence. of trends. Algorithm taken from https://en.wikipedia.org/wiki/Exponential_smoothing  titled: "Double exponential smoothing".

### Implementation challenges

unlike other range functions, `holt_winters` accepts two extra parameters `sf` and `tf`. `#[range_fn]` util macro doesn't support this format thus we need to implement the entire structure manually. A similar case is the `idelta` under `promql/functions/idelta.rs`.

**Comment by etolbakov** [comment]
Hi @waynexia 
let me give it a go?

**Comment by waynexia** [comment]
Closed by #1342, thanks again @etolbakov 😀
