### ISSUE TITLE
Distributed query tracing

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1312]
### What problem does the new feature solve?

Can't see the status of distributed query, hard to debug.

### What does the feature do?

Add distributed query tracing, and visualize it.

**Comment by waynexia** [comment]
can https://github.com/GreptimeTeam/greptimedb/issues/1023 + jaeger solve this?

**Comment by MichaelScofield** [comment]
Part of it, #1023 is too broad, we need more domain specific tracing.
