### ISSUE TITLE
an open source project needs GreptimeDB to support  CTE, is there any plan to support WITH syntax which is useful in complex query?

### ISSUE THREAD

**Issue by apdong2022** [GreptimeTeam/greptimedb#1315]

**Comment by SSebo** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/5784607/229471494-526fa514-dd20-47b7-aaf0-3fc802a6052b.png">

execute CTE query from new stand alone environment.

**Comment by waynexia** [comment]
>execute CTE query from new stand alone environment.

Thanks for the feedback and this example ❤️ will take a look into this

**Comment by SSebo** [comment]
I also found `time` can not be a column name because of `TIME INDEX` already be used as keyword. `time` may be a popular column name to store `DATE`, `TIME` or `DATETIME`.

**Comment by waynexia** [comment]
You can quote (`"`) the column name to make it usable:
```sql
CREATE TABLE IF NOT EXISTS system_metrics (
    disk_util DOUBLE PRIMARY KEY,
    "time" TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIME INDEX,
);
```
![image](https://user-images.githubusercontent.com/15380403/229474769-0943d328-910e-4660-89bd-1fb8f1096635.png)
