### ISSUE TITLE
Slow datanote startup due to replay

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#1317]
### What type of enhancement is this?

Performance

### What does the enhancement do?

When datanote is starting up, it tries to replay WAL from last existing checkpoint. For some reason if checkpoint is not available for certain tables, it would take a lot of time to replay every single time.

Checkpoint feature is introduced quite lately. Checkpoint would only be created until some data has been written into the database and flushed. If a table was created and filled with data before checkpoint feature, and no longer used anymore, it would add up to the datanode startup time describe above, and could not be skipped. 

One possible solution would be after replaying WAL during datanode startup, check if the WAL size is large enough to create a checkpoint; if so, create a checkpoint immediately, so that next time when datanode restart, it could startup quickly.

**Comment by killme2008** [comment]
> One possible solution would be after replaying WAL while datanode startup, check if the WAL size is large enough to create a checkpoint; if so, create a checkpoint immediately, so that next time when datanode restart, it could startup quickly.

The checkpoint itself will slow the startup too. Maybe need an option to control it.
