### ISSUE TITLE
Supporting time zone

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1319]
### What problem does the new feature solve?

Currently GreptimeDB supports parsing timestamps with time zone, but does not support time zone in data types, nor interpreting UTC timestamp values into user's local time.

arrow-schema's [`DataType::Timestamp`](https://docs.rs/arrow-schema/36.0.0/arrow_schema/enum.DataType.html#variant.Timestamp) has an additional time zone field

### What does the feature do?

- [ ] Allow ingesting data with explicit time zones
    - [X] `INSERT INTO`: Parsing timestamp without tz info according to local time zone
    - [x] `COPY FROM` #1341
- [ ] Interpret UTC timestamps to local time zone on query 
    - [X] Display time zone info in query result: #1332

### Implementation challenges

The underlying representation of GreptimeDB's vectors are arrow's arrays. Unfortunately in arrow-array, `Timestamp[...]Array`'s data type does not contain any time zone info, instead their time zones are [hard coded to `None`](https://github.com/apache/arrow-rs/blob/5f27509d98cd401b31edc87fab686531b6ee34e3/arrow-array/src/types.rs#L152), although timestamp types with different time zones are considered as different types, which will leads to "mismatch schema error" as in [this thread](https://github.com/GreptimeTeam/greptimedb/discussions/1303#discussioncomment-5502771).

**Comment by waynexia** [comment]
>Another issue would be how we treat the timestamps in parquet which contain a int64 value along with a timezone, should we adjust the int64 value into UTC time zone?

I think we can adjust all timestamp-related types to UTC, and stores the time zone as extra infos in metadata in the very beginning. Then all our storage and computing operations only need to care about one standard time zone. User provided time zone only works on the outermost user-facing level, like displaying the result.

**Comment by ArslanYM** [comment]
Is this issue fixed?

**Comment by v0y4g3r** [comment]
> Is this issue fixed?

When #1341 is merged, we will be able to insert/import timestamps with time zones. The only caveat will be displaying timestamps in local time zone and parsing timestamps without time zone info in the local (system) time zone.
