### ISSUE TITLE
Dashbord service should not startup in metasrv and datanode

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb#1334]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode, Meta

### What happened?

The #1239 embeds the dashboard service and listens on the `:4000` port during the HTTP server start-up [process](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/servers/src/http.rs#L505). 

It functions properly in standalone mode. However, in distributed mode, the frontend/metasrv/datanode services also start the dashboard service due to the common [implementation](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/servers/src/http.rs#L429) of the HTTP server. If I run the distributed mode on the same host, the service fails to start due to the `4000` port being used by other components. 

The dashboard service should be exported by the frontend and it's not necessary to be started by the metasrv and datanode services, which are not direct components used by the user.

### What operating system did you use?

macOS 

### How can we reproduce the bug?

Follow the [instruction](https://docs.greptime.com/getting-started/distributed) to deploy the cluster on the host by using the latest binary(`v0.2.0-nightly-20230403`), it will fail by the 4000 port is already used when starting datanode.

**Comment by MichaelScofield** [comment]
https://github.com/GreptimeTeam/greptimedb/pull/1256 adds http server to datanode, looks like we have to update the docs, to start datanode by `--http-addr=xxx`

**Comment by zyy17** [comment]
@MichaelScofield The `--http-addr` can resolve the port confliction, but it seems the `/dashboard` endpoint is still working:

```
$ ./greptime metasrv start --store-addr 127.0.0.1:2379 --server-addr 0.0.0.0:3002 --http-addr 0.0.0.0:14000

$ curl -XGET http://localhost:14000/dashboard/
```

IMO, we should:

1. Add the user configuration to determine whether the component should start with `/dashboard`;
2. When in distributed mode, the metasrv and datanode should disable `/dashboard`;

**Comment by MichaelScofield** [comment]
make sense, I will look into it
