### ISSUE TITLE
Reduce the impact of block methods on tokio runtime

### ISSUE THREAD

**Issue by Fengys123** [GreptimeTeam/greptimedb#1335]
### What type of enhancement is this?

Performance

### What does the enhancement do?

We have some scenarios where we need to call an asynchronous method in a synchronous method in tokio runtime.

example: https://github.com/GreptimeTeam/greptimedb/blob/develop/src/catalog/src/remote/manager.rs#L532

At present, our solution is to create a new thread every time a synchronous method is called, and then call block_on on this thread to execute the asynchronous method.

There are two problems:

1. Every time a synchronous method is called, a thread will be created. It is too expensive.
2. The execution time of the synchronous method is too long, which may cause the tokio runtime blocking.

There are two ideas:

1. use[ tokio::task::block_in_place](https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html), But it doesn't work with the current_thread runtime.
2. use a thread pool, but only problem one is solved, problem 2 is not resolved.

**Comment by MichaelScofield** [comment]
I think we can completely resolve this issue by not using DataFusion's catalog list

**Comment by killme2008** [comment]
Looks like there is already an async version of catalog in datafusion 

https://github.com/apache/arrow-datafusion/issues/3777

https://github.com/apache/arrow-datafusion/pull/4607

Maybe we need to upgrade datafusion.

**Comment by waynexia** [comment]
>Maybe we need to upgrade datafusion.

They are already available in our deps

**Comment by MichaelScofield** [comment]
@killme2008 now datafusion only has async version of getting table. we need other methods to be async too, like iterating tables names.

**Comment by killme2008** [comment]
> @killme2008 now datafusion only has async version of getting table. we need other methods to be async too, like iterating tables names.

Got it, i think we can submit an issue to datafusion for it.

**Comment by MichaelScofield** [comment]
Well, seeing the discussions in https://github.com/apache/arrow-datafusion/issues/3777 , I don’t think the async version of catalog list could be easily done, too many breaking changes to APIs including the major one, SessionContext.

I think the best strategy is to get rid of the table management of datafusion. We can just use datafusion as a pure query engine.

Btw, datafusion itself also realize this issue, see https://github.com/apache/arrow-datafusion/issues/5291

**Comment by evenyag** [comment]
We could cache the catalog data and refresh them in the async context. I remember that @v0y4g3r has some ideas on it.

**Comment by MichaelScofield** [comment]
Ballista shares the same idea, it has a “refresh” method that update all catalogs cached in local. However, the “refresh” is an all-to-all comparison, not efficient. If we were to implement the same refreshment, I think we have to do the same: fetching all catalogs from remote and then compare(or replace) with local cache. Not good.

**Comment by evenyag** [comment]
Anyway, a cache is necessary if we don't want to issue a remote call to the meta each time we access the remote catalog. But I think we don't need to do an `all-to-all comparison`, we only need to replace the local cache with the remote data.

We can use different cache policies for catalogs, schemas, tables, and tables' metadata. e.g.
- For catalogs, schemas, and tables, we update them periodically
- For metadata of tables, we can use a fixed capacity cache (with TTL?) and update the individual table entry on a cache miss

**Comment by fengjiachun** [comment]
`metasrv` has push capability, which can achieve incremental updates of cache based on push.
