### ISSUE TITLE
Disable dashboard in the http servers of datanode and metasrv

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1337]
@MichaelScofield The `--http-addr` can resolve the port confliction, but it seems the `/dashboard` endpoint is still working:

```
$ ./greptime metasrv start --store-addr 127.0.0.1:2379 --server-addr 0.0.0.0:3002 --http-addr 0.0.0.0:14000

$ curl -XGET http://localhost:14000/dashboard/
```

IMO, we should:

1. Add the user configuration to determine whether the component should start with `/dashboard`;
2. When in distributed mode, the metasrv and datanode should disable `/dashboard`;

_Originally posted by @zyy17 in https://github.com/GreptimeTeam/greptimedb/issues/1334#issuecomment-1498434380_

**Comment by MichaelScofield** [comment]
I think it can be easily done by adding a boolean flag to http server's builder

**Comment by zyy17** [comment]
@MichaelScofield Please assign it to me. I will try to resolve it.

**Comment by MichaelScofield** [comment]
nice @zyy17
