### ISSUE TITLE
Implement `predict_linear` function in PromQL

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1349]
### What problem does the new feature solve?

[`predict_linear`](https://prometheus.io/docs/prometheus/latest/querying/functions/#predict_linear) is a function that predicts the future value. It's based on [simple linear regression](https://en.wikipedia.org/wiki/Simple_linear_regression) just like [`deriv()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv)

### What does the feature do?

Implement the `predict_linear` function: `predict_linear(v range-vector, t scalar)`

### Implementation challenges

unlike other range functions, `predict_linear` accepts one extra parameter `t` to specify the time. #[range_fn] util macro doesn't support this format thus we need to implement the entire structure manually. A similar case is the `idelta` under `promql/functions/idelta.rs`.

**Comment by waynexia** [comment]
cc @haohuaijin for who implemented the `deriv()` function. This is a bit more challenging than `deriv()`. Would you like to take this?

**Comment by haohuaijin** [comment]
Sure, I'm happy to take it. @waynexia

**Comment by waynexia** [comment]
Closed by #1362
