### ISSUE TITLE
Breaking changes recording

### ISSUE THREAD

**Issue by fengjiachun** [GreptimeTeam/greptimedb#1350]
GreptimeDB is still in the early stages of heavy development. It is easy to encounter some incompatible upgrades, and if there are any breaking changes, we need to record them here for users or ourselves to refer to at any time.

| Version |	Date  |	Description |	Impact	|  Issues/PRs  |
| -- | -- | -- | -- | -- |
| v0.1.0 |  2023-04-10 | xxx  |  xxx | xxx |

**Comment by waynexia** [comment]
Link to get all breaking changes: https://github.com/GreptimeTeam/greptimedb/pulls?q=label%3A%22breaking+change%22

**Comment by evenyag** [comment]
Some breaking changes I see before the next release:
- #1352 

Conventional commits and the breaking change label should be more convenient. It's easy to forget to maintain this issue.
