### ISSUE TITLE
Add table id and engine to information_schema.tables

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1355]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

#1327 introduces the `tables` table to the information schema. Currently, this table contains the following columns
- table_catalog
- table_schema
- table_name
- table_type

It's helpful to provide more information about the table, including
- the table id (TABLE_ID or GREPTIME_TABLE_ID)
- the engine name (ENGINE)

MySQL has an `ENGINE` column in its [`tables`](https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html) table. TiDB adds a `TIDB_TABLE_ID` [to show the table's id](https://docs.pingcap.com/tidb/dev/information-schema-tables).

### Implementation challenges

We need to add more columns to the `tables` table
https://github.com/GreptimeTeam/greptimedb/blob/09f003d01d8e1c7cf54b3a458675dc5cda41780a/src/catalog/src/information_schema/tables.rs#L41-L47

Then refactor the `add_table()` method to put more information to the output record batch.
https://github.com/GreptimeTeam/greptimedb/blob/09f003d01d8e1c7cf54b3a458675dc5cda41780a/src/catalog/src/information_schema/tables.rs#L101-L104

Table id and the engine are available in the `TableInfo`.

**Comment by haohuaijin** [comment]
Can I have a try? And could you provide `table_id` and `table_engine` about information_schema.tables itself.
https://github.com/GreptimeTeam/greptimedb/blob/09f003d01d8e1c7cf54b3a458675dc5cda41780a/src/catalog/src/information_schema/tables.rs#L107-L113

**Comment by evenyag** [comment]
Sure. I'm not sure which table id is proper. @MichaelScofield Could we use `NULL` for the table id and engine of this table?
