### ISSUE TITLE
u64 gets casted to float64 unexpectedly

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1385]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

```
query: SELECT uint64s FROM all_datatypes WHERE uint64s = 18446744073709551615
cast_scalar_value: UInt64 Float64(18446744073709552000)
thread 'mysql-io-handlers' panicked at 'called `Result::unwrap()` on an `Err` value: QueryExecution { source: Fail to create physical plan: Error during planning: column:Column { relation: Some(Bare { table: "all_datatypes" }), name: "uint64s" } value:Float64(18446744073709552000) is invalid. Caused by: Plan("column:Column { relation: Some(Bare { table: \"all_datatypes\" }), name: \"uint64s\" } value:Float64(18446744073709552000) is invalid") }', src/servers/tests/mod.rs:79:71
```

### What operating system did you use?

Arch Linux with Kernel: 6.2.10-arch1-1

### How can we reproduce the bug?

```bash
TBD
```

**Comment by tisonkun** [comment]
How can we reproduce this issue? I run `test_query_prepared` locally and it doesn't report an error now.

**Comment by waynexia** [comment]
> How can we reproduce this issue? I run `test_query_prepared` locally and it doesn't report an error now.

Thanks for your attention 👍 I've verified this bug is fixed in https://github.com/GreptimeTeam/greptimedb/pull/1677 and files #2892 to re-enable corresponding case
