### ISSUE TITLE
bug: wrongly next_column_id in manifest file after new columns added.

### ISSUE THREAD

**Issue by lizhemingi** [GreptimeTeam/greptimedb#1389]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Meta

### What happened?

Add column failed after server restarted.  Reproduce steps can be found below.

The root cause of this bug is the wrongly next_column_id stored in manifest file after new columns added. 
We store manifest in https://github.com/GreptimeTeam/greptimedb/blob/cc7c313937bd57171badcfd7cc1ff7a9ec4f3e41/src/mito/src/table.rs#L253-L264
Which is before bump `next_column_id` of `TableMeta` in
https://github.com/GreptimeTeam/greptimedb/blob/cc7c313937bd57171badcfd7cc1ff7a9ec4f3e41/src/mito/src/table.rs#L266-L267

I think we should simply call `create_alter_operation` before update manifest and store the result, then use it to update region after manifest is updated. I can send a pr to fix if the proposal s acceptable.

### What operating system did you use?

Ubuntu 21.04 x64

### How can we reproduce the bug?

```bash
In standalone mode:

1. `CREATE TABLE integers8(i BIGINT, j BIGINT, k VARCHAR(255), TIME INDEX(i));`
2. `ALTER TABLE integers8 add column m int;` The `next_column_id` after this step in manifest file is wrong, but correct in memory, so the server can still work if not restart.
3. shutdown standalone server and restart
4. `ALTER TABLE integers8 add column n int;`

```
![image](https://user-images.githubusercontent.com/9639449/232291409-12f8f0bc-0217-4dd0-9041-f94b7cf93c3f.png)

**Comment by killme2008** [comment]
Good catch!  I think your proposal will work, and maybe you can add a sqlness test case for this bug too.

FYI. You can restart the database node in sqlness by the following command:

```
-- SQLNESS ARG restart=true
```

**Comment by lizhemingi** [comment]
@killme2008 Will do. Assign this to me please.

**Comment by killme2008** [comment]
@lizhemingi Are u working on this issue? Let's fix it.

**Comment by lizhemingi** [comment]
@killme2008 Yeah I am working on it. And I already fix the bug but run sqlness failed for the already exist cases in my environment and I am looking into it. Will submit a pr this afternoon for this bug first.

**Comment by lizhemingi** [comment]
Sorry for the slow progress.
