### ISSUE TITLE
Distributed query planner

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1393]
### What problem does the new feature solve?

In distributed mode, queries are planned on frontend. Currently frontend pushes only `TableScan` to datanode and executes all the other plans in place, which may cause frontend OOM when the aggregation plan retrieves a large volume of data from datanodes. 

### What does the feature do?

We need to add a distributed planner to frontend so that real distributed plans can be generated to alleviate the workload of frontend.

### Implementation challenges

There is a long road towards a fairly good distributed planner, but we can start from [ballista](https://github.com/apache/arrow-ballista)'s [implementation](https://github.com/apache/arrow-ballista/blob/a9ecd3a065077bec6c5d271e890d091c594746fa/ballista/scheduler/src/planner.rs#L40) and more time-series related optimization rules can be added to that.

**Comment by waynexia** [comment]
Available after #1660
