### ISSUE TITLE
Compress manifest and checkpoint

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1394]
### What problem does the new feature solve?

Current manifest logs and checkpoints are in JSON format, they are really large.

I think we can compress them to reduce IO and memory consumption.

### What does the feature do?

Compress manifest and checkpoints by ZSTD/Snappy etc.

**Comment by Taylor-lagrange** [comment]
Hi, can i work on this issue?

**Comment by killme2008** [comment]
@Taylor-lagrange Of course, welcome to try it.

I like to design a `layer` or `middleware` mechanism for `ManifestObjectStore`.

https://github.com/GreptimeTeam/greptimedb/blob/f2cc912c87a6199e42fd6b11c3cab88562105924/src/storage/src/manifest/storage.rs#L95

And implements the `CompressLayer` for it.

**Comment by Taylor-lagrange** [comment]
Yeah, an implementation like that is more general. I'm new to this project, so it may take me one or two day to hack on this project.  What do you mainly use to communicate?（is slack?） I mainly want to know if there are some code-related questions or some design documents about this issue (if any), where to communicate with you. It seems that there are not many chats in the issue area.

**Comment by killme2008** [comment]
@Taylor-lagrange We are using slack, you can find me there. My nickname is `dennis zhuang`.
Sorry for that, we don't have any design docs related to this issue, I think maybe you can submit an RFC just like #1274 before coding. It's not a hurry, feel free to try it.

**Comment by killme2008** [comment]
The greptime community slack channel https://greptime.com/slack
