### ISSUE TITLE
POST method of SQL HTTP doesn't work when with authorization.

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#1414]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

The POST method of `sql` doesn't work after setting username and password when starting GreptimeDB.

When I start a server without authorization, the following code works well:

```
./greptime standalone start
```

```
curl http://localhost:4000/v1/sql -d "sql=INSERT INTO system_metrics(host, cpu) VALUES('hello', 1), ('world', 2)"

{"code":0,"output":[{"affectedrows":2}],"execution_time_ms":0}
```

But it doesn't work after setting username and password, and there is no response.

```
./greptime standalone start --user-provider=static_user_provider:file:db_user
```

```
curl http://localhost:4000/v1/sql -H 'authorization: Basic eWlyYW46eWlyYW4=' -d "sql=INSERT INTO system_metrics(host, cpu) VALUES('hello', 1), ('world', 2)"
```

The server logs:

```
2023-04-18T09:30:54.272533Z ERROR servers::http::authorize: authorize failed: Illegal param: db not provided or corrupted
```

### What operating system did you use?

Mac OS X 

### How can we reproduce the bug?

1. Start server

```
./greptime standalone start
```

2. Create table with MySQL

```
CREATE TABLE system_metrics (
  host STRING,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  cpu DOUBLE DEFAULT 0,
  memory DOUBLE,
  TIME INDEX (ts),
  PRIMARY KEY(host)) ENGINE=mito WITH(regions=1);
```

3. Insert data via SQL HTTP, woks well so far.

```
curl http://localhost:4000/v1/sql -d "sql=INSERT INTO system_metrics(host, cpu) VALUES('hello', 1), ('world', 2)"

{"code":0,"output":[{"affectedrows":2}],"execution_time_ms":0}
```

4. Restart the server with username and password.

```
./greptime standalone start --user-provider=static_user_provider:file:db_user
```

5. Insert data via the same SQL HTTP

```
curl http://localhost:4000/v1/sql -H 'authorization: Basic Z3JlcHRpbWVfdXNlcjpncmVwdGltZV9wYXNzd29yZA==' -d "sql=INSERT INTO system_metrics(host, cpu) VALUES('hello', 1), ('world', 2)"
```

That doesn't work now and no http response.

The server logs:

```
2023-04-18T09:39:45.292226Z ERROR servers::http::authorize: authorize failed: Illegal param: db not provided or corrupted
```

**Comment by shuiyisong** [comment]
As server log suggests

**Comment by nicecui** [comment]
I think the problem maybe caused by [here](https://github.com/GreptimeTeam/greptimedb/blob/6b6617f9cb24439b29b79bbc2bb7dee99a656d40/src/servers/src/http/authorize.rs#L123) that it only extract `db` from `query` in Get method.

**Comment by shuiyisong** [comment]
```
2023-04-18T09:30:54.272533Z ERROR servers::http::authorize: authorize failed: Illegal param: db not provided or corrupted
```
As server log suggests, you may need to add db parameter to connection info once you use `user_provider`. The logic of checking database name while `user_provider` is presented is also aligned with MySQL and PG protocol.

```
curl http://localhost:4000/v1/sql?db=public -H 'authorization: Basic Z3JlcHRpbWVfdXNlcjpncmVwdGltZV9wYXNzd29yZA==' -d "sql=INSERT INTO system_metrics(host, cpu) VALUES('hello', 1), ('world', 2)"
```
Adding `?db=public` should do.

> I think the problem maybe caused by [here](https://github.com/GreptimeTeam/greptimedb/blob/6b6617f9cb24439b29b79bbc2bb7dee99a656d40/src/servers/src/http/authorize.rs#L123) that it only extract db from query in Get method.

**Comment by nicecui** [comment]
that means `?db=public` must be added to the end of the url when starting GreptimeDB with username and password?
