### ISSUE TITLE
Constrain type of TIME INDEX column

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1415]
### What type of enhancement is this?

Tech debt reduction, User experience

### What does the enhancement do?

The current version allows users to create tables with `TIME INDEX` constraint on both timestamp types and bigint type. Like
```sql
CREATE TABLE monitor (
  host STRING PRIMARY KEY,
  ts BIGINT TIME INDEX,
  cpu DOUBLE,
);
```
And those columns will be implicitly interpreted as millisecond timestamps, which is a bit strange and may cause ambiguity.

This ticket proposes to narrow the constraint, and reject non-timestamp column as `TIME INDEX`. Force the user to give a specific resolution to their time index.

---------------------

Another constraint is to reject queries that compare non-timestamp types with timestamp types. E.g.:
```sql
select * from monitor where ts > 1;
```
In this case the literal `1` doesn't contains resolution info. And we should require users to add this by a cast operation to make it clear:
```sql
select * from monitor where ts > 1::timestamp;
```

**Comment by evenyag** [comment]
When I use bigint as time index, compaction will throw the following error message
