### ISSUE TITLE
feat: catalog level `scripts` table

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#1432]
### What problem does the new feature solve?

According to #868 , `scripts` table should be created at catalog level. However, as [here](https://github.com/GreptimeTeam/greptimedb/blob/830367b8f426e8b4b0acb1f909d39b7111375d5a/src/script/src/manager.rs#L30) shows, `ScriptManager` only holds one `ScriptTable` using default catalog and default schema.

We should place something like a map in `ScriptManager` so it could route to different catalog's script table.

ref: #665 

### What does the feature do?

1. replace `table: ScriptsTable` with something like `tables: Arc<DashMap<String, ScriptTableRef>` in `ScriptManager` 
2. change initialization and other process accordingly

### Implementation challenges

1. Currently scripts table is created as system table at frontend(distributed mode). Since system table have to be created before catalog manager starts, If we were to make scripts table at catalog level, it would have to be normal table rather than system table. Thus we will have to create it at datanode using create table grpc and so on. 
2. The original idea to make scripts table at catalog level requires a "default" schema for each catalog, however creating a catalog won't automatically create a default schema for that catalog. That's something we will have to figure out too.

**Comment by killme2008** [comment]
I'll look into this issue.

**Comment by killme2008** [comment]
> Currently scripts table is created as system table at frontend(distributed mode). Since system table have to be created before catalog manager starts, If we were to make scripts table at catalog level, it would have to be normal table rather than system table. Thus we will have to create it at datanode using create table grpc and so on.

First of all, this system table will not be created until the catalog manager starts, they are only registered with hooks. So this concern does not exist.

> The original idea to make scripts table at catalog level requires a "default" schema for each catalog, however creating a catalog won't automatically create a default schema for that catalog. That's something we will have to figure out too.

Yep, catalog level scripts only exist in cloud, I think we should move this issue to the cloud project.
