### ISSUE TITLE
Table options can't be found in distributed mode

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1433]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

When implementing `SHOW CREATE` statement #1336 , I found that the table options can't be retrieved from table info, it's stored in the region on datanode.

After discussing with @v0y4g3r , @waynexia , maybe we can provide an RPC to get the table info from the table's first region.

### What operating system did you use?

Mac OS

### How can we reproduce the bug?

`show create table [table]` in distributed mode doesn't display the table options info.

**Comment by MichaelScofield** [comment]
Why not store them in Metasrv?

**Comment by NiwakaDev** [comment]
I'd like to work on this issue.

**Comment by MichaelScofield** [comment]
@NiwakaDev thx!

**Comment by NiwakaDev** [comment]
Though I addressed this issue in #2209, we can't yet close this issue because #2209 doesn't address adding test for the other options except `regions`:

https://github.com/GreptimeTeam/greptimedb/pull/2209#discussion_r1299605948:
>The other table options to test are: "ttl" and "write_buffer_size". See https://docs.greptime.com/reference/sql/create#table-options. Also for create external table, there are more table options: https://docs.greptime.com/reference/sql/create#create-external-table.
