### ISSUE TITLE
Enable grpc compression

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1445]
### What problem does the new feature solve?

Reduce bandwidth while dealing with grpc requests and responses.

### What does the feature do?

There are two places we can enable compression:

- tonic's grpc [compression](https://github.com/hyperium/tonic/tree/master/examples/src/compression) 
- ArrowFlight's Arrow [compression](https://github.com/hyperium/tonic/tree/master/examples/src/compression)

We can enable both.

**Comment by e1ijah1** [comment]
I'm quite interested in this feature and would like to contribute if possible. Could you please confirm if the compression for Arrow Flight is implemented within the FlightEncoder struct? I would greatly appreciate any further details regarding the implementation.

**Comment by MichaelScofield** [comment]
@e1ijah1 welcome! Yes, compression for Arrow data is set in IpcWriteOptions, which is owned by the FlightEncoder. You may find this usefull: https://stackoverflow.com/questions/71802355/possible-ways-to-compress-apache-arrow-recordbatch

**Comment by tisonkun** [comment]
How can it be relevant to "Frontend"?
