### ISSUE TITLE
Improve and distinguish different errors for IllegalInsertData

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1451]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

When implementing Erlang client for GreptimeDB, I found that the error message returned by server was confusing, especially the `Illegal insert data`.

It happens in several cases but doesn't contain a useful message.

https://github.com/GreptimeTeam/greptimedb/blob/2cf828da3c946f09c02a1779c18899970f0a6158/src/common/grpc-expr/src/insert.rs#L297

https://github.com/GreptimeTeam/greptimedb/blob/2cf828da3c946f09c02a1779c18899970f0a6158/src/common/grpc-expr/src/insert.rs#L331

Distinguishing different errors for `IllegalInsertData` will help users and SDK developers.

**Comment by NiwakaDev** [comment]
@killme2008 

I'd like to work on this. By the way, do we need to add unit tests for this?

**Comment by killme2008** [comment]
@NiwakaDev Cool assigned it to you.
It would be great if you could add some unit tests for it, you can find some tests in https://github.com/GreptimeTeam/greptimedb/blob/develop/tests-integration/tests/grpc.rs
