### ISSUE TITLE
Renaming table in distributed table does not change table routes

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1464]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend, Meta

### What happened?

Table routes is maintain by metasrv to keep track of all living datanodes for some table. The key of table route consists of table name and table id, like: `__meta_table_route-greptime-public-some_table-1025`.

When we rename a table from `some_table` to `new_table`, we should also rename the table routes key from `__meta_table_route-greptime-public-some_table-1025` to `__meta_table_route-greptime-public-new_table-1025`, otherwise frontend will not be able to find the datanodes of that table.

### What operating system did you use?

N/A

### How can we reproduce the bug?

- Start all components in distributed mode
- Create a table t
- Rename table t to new_table

**Comment by Fengys123** [comment]
Solved in #1654, so closed.

**Comment by Fengys123** [comment]
Solved in https://github.com/GreptimeTeam/greptimedb/pull/1654, so closed.
