### ISSUE TITLE
prevent sensitive information (key, password, secrets etc.) from being printed in plain 

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1487]
### What type of enhancement is this?

Configuration, User experience

### What does the enhancement do?

Sensitive information might get leaked by being printed out for debugging purposes. It should be avoided in (any?) condition.

This can be archived by using a new type wrapper to override `Display` or `Debug` for sensitive fields

**Comment by DevilExileSu** [comment]
Sounds interesting, could you assign it to me?

**Comment by WenyXu** [comment]
> Sounds interesting, could you assign it to me?

Enjoy coding 🥳
