### ISSUE TITLE
Database level TTL

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1496]
### What problem does the new feature solve?

Currently, to enable TTL for a table, we need to explicitly set the TTL for each table at creation. By default, each table has no TTL. However, we should enable TTL for tables ingested by TSDB protocols.

We could set the TTL option for each table, but it's inconvenient if we want to adjust the TTL for all tables.

A better way is introducing a database (global) level TTL option so each table can inherit this default TTL.

### What does the feature do?

One possible solution is
- Add a global TTL option
- Add an `enable_ttl` option to each table, which is false by default
- When we ingest a table via TSDB protocols, enable TTL
- If `enable_ttl` is true and `ttl` of a table is `Some` then the `ttl` override the global option.

### Implementation challenges

We need a way to pass the global TTL option to the storage engine. We might also need to consider compatibility issues while adding the `enable_ttl` option.

**Comment by evenyag** [comment]
I plan to implement a global TTL option first. Users can configure a global TTL for all tables on the current machine.

If a table already has a TTL specified in table options, the storage engine uses that TTL. Otherwise, the global_ttl takes effect.

**Comment by sunng87** [comment]
Just released we need database/schema level TTL I'm going to reopen this.

Our current TTL is implemented at installation scope then on cloud or multi-tenant environment we will need finer control for each database

**Comment by v0y4g3r** [comment]
Let's move all further discusions to #3708
