### ISSUE TITLE
Incomplete message raised while accessing S3 objects

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1505]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

A sentinel routine checks if GreptimeDB is alive every 10 minutes, but after database instance idle for a while and the sentinel initiates a table query, datanode raised an error complaining "connection closed before message completed".

After some research we found that it would be related to [the mismatch between S3 connection idle timeout and hyper default connection pool idle time](https://github.com/hyperium/hyper/issues/2136).

### What operating system did you use?

NA

### Relevant log output and stack trace

![image](https://user-images.githubusercontent.com/6406592/236108787-e399b9eb-0ea2-4404-b103-4fd2a1012691.png)

### How can we reproduce the bug?

NA

**Comment by v0y4g3r** [comment]
Quote from [seanmonstar](https://github.com/hyperium/hyper/issues/2136#issuecomment-589345238):

> This is just due to the racy nature of networking.
> 
> hyper has a connection pool of idle connections, and it selected one to send your request. Most of the time, hyper will receive the server's FIN and drop the dead connection from its pool. But occasionally, a connection will be selected from the pool and written to at the same time the server is deciding to close the connection. Since hyper already wrote some of the request, it can't really retry it automatically on a new connection, since the server may have acted already.

**Comment by Xuanwo** [comment]
Please try use https://docs.rs/opendal/latest/opendal/services/struct.S3.html#method.http_client to configure the underlying http client which can be built via https://docs.rs/opendal/latest/opendal/raw/struct.HttpClient.html#method.build
