### ISSUE TITLE
Print error logs in datanode

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1506]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Currently a query in GreptimeDB will be processed by two components, `datanode` and `frontend`. This suits both standalone and distributed modes. The procedure looks like `user` -> `frontend` -> `datanode` -> `frontend` -> `user`. In the `datanode` -> `frontend` step, `frontend` will log out errors it receives from `datanode` like the following text, but we don't log the actual detailed error in the `datanode`. 

```
2023-05-04 11:25:58	
2023-05-04T03:25:58.824689Z  INFO servers::mysql::server: MySQL connection coming from: 10.0.0.224:63043

2023-05-04 11:25:57	
2023-05-04T03:25:57.293436Z  WARN servers::mysql::server: Internal error occurred during query exec, server actively close the channel to let client try next time: Internal IO error, source: peer terminated connection.
```

**Comment by NiwakaDev** [comment]
>but we don't log the actual detailed error in the datanode.

I'd like to work on this issue, but I'm not very familiar with `greptime`. 

So, I have two questions:

1. What is the actual detailed error? 
2. Where is the actual detailed error in datanode directory?

**Comment by waynexia** [comment]
> > but we don't log the actual detailed error in the datanode.
> 
> I'd like to work on this issue, but I'm not very familiar with `greptime`.
> 
> So, I have two questions:
> 
>     1. What is the actual detailed error?
> 
>     2. Where is the actual detailed error in datanode directory?

The "actual error" refers to the second type of `Result<T, E>` -- the actual error, literally. We need to log it by `error!()` before the datanode drops it so that we can know what's going on from the log. One noticeable entrypoint is the [`GrpcQueryHandler`](https://github.com/GreptimeTeam/greptimedb/blob/fb9978e95d0d1f1f6b6136a1973376cdf138cdfb/src/datanode/src/instance/grpc.rs#L189-L207).

**Comment by evenyag** [comment]
I have opened PR #1507 to add some logs in the GreptimeRequestHandler. This might resolve this issue.

**Comment by MichaelScofield** [comment]
Datanode only expose grpc service when running in cluster mode. So adding logs in GrpcQueryHandler is sufficient.

**Comment by NiwakaDev** [comment]
@evenyag 

>@NiwakaDev I'm sorry that I didn't mention this issue 😢

Don't worry!

**Comment by waynexia** [comment]
Close as completed in #1507, apologize for the inconvenient @NiwakaDev 😢

**Comment by NiwakaDev** [comment]
@MichaelScofield, @waynexia, @evenyag 

>Datanode only expose grpc service when running in cluster mode. So adding logs in GrpcQueryHandler is sufficient.

It seems to also expose http service when running in cluster mode. Why does datanode only expose grpc service?

https://github.com/GreptimeTeam/greptimedb/blob/fb9978e95d0d1f1f6b6136a1973376cdf138cdfb/src/datanode/src/server.rs#L43-L62

**Comment by MichaelScofield** [comment]
I remembered that datanode expose http service only for metric. It doesn't handle actual read/write requests.
