### ISSUE TITLE
Timestamp output format is not compatible with MySQL clients: Timezone is not allowed

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1508]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

I'm getting error while configuring greptimedb and grafana:

```
convert frame from rows error: invalid time bytes: 2023-05-04 16:00:19.653+0800
```

It turns out that MySQL does not output timezone for time types including `TIMESTAMP`, `DATETIME`: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

The doc also indicates how mysql handles timezone:

> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time. The time zone can be set on a per-connection basis. As long as the time zone setting remains constant, you get back the same value you store.

### What operating system did you use?

any

### How can we reproduce the bug?

```
MySQL [public]> select * from host_load1 limit 10;
+------------------------------+-----------+----------+---------------+
| ts                           | collector | host     | value         |
+------------------------------+-----------+----------+---------------+
| 2023-05-04 15:38:04.655+0800 | load      | thinkneo |   0.517578125 |
| 2023-05-04 15:38:19.653+0800 | load      | thinkneo |    0.40234375 |
| 2023-05-04 15:38:34.653+0800 | load      | thinkneo |        0.8125 |
| 2023-05-04 15:38:49.653+0800 | load      | thinkneo |  0.8544921875 |
| 2023-05-04 15:39:04.653+0800 | load      | thinkneo |  0.7451171875 |
| 2023-05-04 15:39:19.653+0800 | load      | thinkneo | 0.73974609375 |
| 2023-05-04 15:39:34.653+0800 | load      | thinkneo |  0.7177734375 |
| 2023-05-04 15:39:49.654+0800 | load      | thinkneo | 0.55810546875 |
| 2023-05-04 15:40:04.653+0800 | load      | thinkneo | 0.56982421875 |
| 2023-05-04 15:40:19.654+0800 | load      | thinkneo | 0.51708984375 |
+------------------------------+-----------+----------+---------------+
10 rows in set (0.056 sec)
```

**Comment by v0y4g3r** [comment]
Sorry I thought it would be a feature to [display time offset in MySQL output](https://github.com/GreptimeTeam/greptimedb/pull/1332), but it turns out to be a bug 🤣
