### ISSUE TITLE
Wrong max_table_id log in remote catalog manager

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1513]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Meta, Other

### What happened?

The log in the remote `CatalogManager` is always `Max table id allocated: 1023`:

https://github.com/GreptimeTeam/greptimedb/blob/c8301feed7310937900d03d6f9bd7649f625cc9e/src/catalog/src/remote/manager.rs#L418

Because the `max_file_id` doesn't change at all in `initiate_catalogs` function:

```rust
    /// Fetch catalogs/schemas/tables from remote catalog manager along with max table id allocated.
    async fn initiate_catalogs(&self) -> Result<(HashMap<String, CatalogProviderRef>, TableId)> {
        let mut res = HashMap::new();
        let max_table_id = MIN_USER_TABLE_ID - 1;

        let mut catalogs = self.iter_remote_catalogs().await;
        while let Some(r) = catalogs.next().await {
            let CatalogKey { catalog_name, .. } = r?;
            info!("Fetch catalog from metasrv: {}", catalog_name);
            let catalog = res
                .entry(catalog_name.clone())
                .or_insert_with(|| self.new_catalog_provider(&catalog_name))
                .clone();

            self.initiate_schemas(catalog_name, catalog, max_table_id)
                .await?;
        }

        Ok((res, max_table_id))
    }

```

I think it might be that we want to pass a mutable reference of `max_table_id` into `initiate_schemas`, and change its value in the function. But it looks like we don't implement it correctly.

And I think we should print the log for every catalog in `initiate_catalogs` instead of the current place.It doesn't make sense to print such log for the catalog manager.

### What operating system did you use?

All os sytem

### How can we reproduce the bug?

Described as above.

**Comment by haohuaijin** [comment]
Hi, can i work on this issue?
