### ISSUE TITLE
Build release for windows and centos7

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1515]
### What type of enhancement is this?

Other

### What does the enhancement do?

We can build release for windows platform and centos7 etc.

**Comment by v0y4g3r** [comment]
After some research, build binaries on Windows will be a little tricky since some dependency like [raft-engine](https://github.com/tikv/raft-engine/issues/95) and [tikv-jemalloc-ctl](https://github.com/tikv/jemallocator/issues/22) do not compile on Windows.

**Comment by waynexia** [comment]
> After some research, building binaries on Windows will be a little tricky since some dependencies like [raft-engine](https://github.com/tikv/raft-engine/issues/95) and [tikv-jemalloc-ctl](https://github.com/tikv/jemallocator/issues/22) do not compile on Windows.

Are these all the unsupported deps? `jemalloc` has some alternatives, `raft-engine` might not be that easy to be replaced. But I'm afraid there will be new unsupported when we resolve these two...
