### ISSUE TITLE
Open catalogs and schemas in parallel

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1517]
### What type of enhancement is this?

Performance

### What does the enhancement do?

In catalog manager(especially remote), it initialize the catalogs and schemas serially. 

Maybe we can initialize the catalogs and schemas in parallel too, just like tables.

https://github.com/GreptimeTeam/greptimedb/blob/c8301feed7310937900d03d6f9bd7649f625cc9e/src/catalog/src/remote/manager.rs#L233

**Comment by gitccl** [comment]
Hi, I'd like to do this task.

**Comment by killme2008** [comment]
> Hi, I'd like to do this task.

Great, thank u. I think maybe you can do it after #1516 is merged to avoid conflicts.

**Comment by gitccl** [comment]
> > Hi, I'd like to do this task.
> 
> Great, thank u. I think maybe you can do it after #1516 is merged to avoid conflicts.

Got it. Thanks.

**Comment by gitccl** [comment]
Hi, I met some problems. I want to use `common_runtime::spawn_bg(async move {})` to initialize the catalogs in parallel, but `&self` cannot be used in `async move` block. Should I change the method `initiate_schemas` to a function?

**Comment by killme2008** [comment]
> Hi, I met some problems. I want to use `common_runtime::spawn_bg(async move {})` to initialize the catalogs in parallel, but `&self` cannot be used in `async move` block. Should I change the method `initiate_schemas` to a function?

Feel free to modify. We can discuss it when doing the code review.

**Comment by gitccl** [comment]
> > Hi, I met some problems. I want to use `common_runtime::spawn_bg(async move {})` to initialize the catalogs in parallel, but `&self` cannot be used in `async move` block. Should I change the method `initiate_schemas` to a function?
> 
> Feel free to modify. We can discuss it when doing the code review.

Ok. Thanks.
