### ISSUE TITLE
Refactor: using "id" (instead of its "name") to find the table

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1525]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Now we are using table names to find the tables in catalog, which could cause potential bugs after the table got renamed.

On the other hand, the table id is globally unique for each table, we should use that as far as possible.

### Implementation challenges

There are too many places we are using table names to find them. Some places could be changed to table ids, some couldn't(and shouldn't). How to best recognize that and set a refactoring guideline is very challenging I think.

**Comment by killme2008** [comment]
The table name to table id transform must be done at catalog level, because the users only have the table name. After that, all the references to the tables should use table ids.

**Comment by MichaelScofield** [comment]
@DevilExileSu For `MemoryCatalogManager`, I think we can add the map to it. Also you need another map `Map<TableName, TableId>` to find table id from its name. Sometimes you just only have the table name at you hand at the first place, for example, parsing the SQL.

**Comment by evenyag** [comment]
> Also you need another map `Map<TableName, TableId>` to find table id from its name.

@MichaelScofield We could retrieve the table id from TableRef. If we find out the TableRef from the catalog via `catalog.schema.table`, then we have the table id. Maybe we don't need this map.

Once https://github.com/GreptimeTeam/greptimedb/issues/1869 is done, I think we don't need to send `catalog`, `schema`, and `table name` to datanodes.

**Comment by DevilExileSu** [comment]
> Also you need another map `Map<TableName, TableId>` to find table id from its name. Sometimes you just only have the table name at you hand at the first place, for example, parsing the SQL.

Yes, I think that `pub catalogs: RwLock<HashMap<String, SchemaEntries>>` already includes the functionality of looking up `TableRef` and `TableId` by `TableName`, so we may not need `Map<TableName, TableId>`.

**Comment by DevilExileSu** [comment]
@MichaelScofield @killme2008 If you don't mind, I would like to give it a try.

**Comment by MichaelScofield** [comment]
@killme2008 are you working on this?

**Comment by MichaelScofield** [comment]
Now we are fully turned to region server, no table name involved in read and write other than necessary table finding for user facing interface. I think this issue is no longer valid.
