### ISSUE TITLE
Export tokio runtime metrics from tokio-console

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1529]
> @waynexia didn't find any metrics related things in its docs, can you give a hint?

I'm looking at [this document](https://docs.rs/console-subscriber/latest/console_subscriber/#adding-the-console-subscriber), but I haven't tried it myself. The path is not that straightforward:
- collect data from tokio-console via `tracing` library (by adding a console layer)
- export data from tracing to metrics subscriber (we haven't do this yet)

And it looks that the metrics (or maybe traces) are not configurable. We probably want to do more experenments on it before put it into our codebase. Thus it's better to do this in another PR.

_Originally posted by @waynexia in https://github.com/GreptimeTeam/greptimedb/issues/1512#issuecomment-1537028757_

As the comment above suggests, we may export the metrics of tokio runtime by digging into tokio-console(tokio's `console-subscriber`), or using its [console-api](https://github.com/tokio-rs/console/tree/main/console-api).

**Comment by SSebo** [comment]
Is this issue only for new contributor? Or any one interested can involve in?

**Comment by MichaelScofield** [comment]
@SSebo you are very welcome to take this issue!

**Comment by SSebo** [comment]
https://github.com/GreptimeTeam/greptimedb/pull/2985
