### ISSUE TITLE
Support more file formats for COPY TO

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1550]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Currently, COPY TO feature supports Parquet, CSV, and NDJSON formats, we need to support more formats, like ORC
AVRO etc.

We can utilize the existing `BufferedWriter `.

https://github.com/GreptimeTeam/greptimedb/blob/2ab0e42d6f10f7c3be7c7049ac9136e5455c96d7/src/common/datasource/src/buffered_writer.rs#L26-L39

 And implement the `DfRecordBatchEncoder` trait for the corresponding writer(e.g., `json::Writer<SharedBuffer, LineDelimited>`).

https://github.com/GreptimeTeam/greptimedb/blob/2ab0e42d6f10f7c3be7c7049ac9136e5455c96d7/src/common/datasource/src/file_format/json.rs#L148-L165

Then add a new output format for `Copy To` at: 
https://github.com/GreptimeTeam/greptimedb/blob/2ab0e42d6f10f7c3be7c7049ac9136e5455c96d7/src/frontend/src/statement/copy_table_to.rs#L44-L73

**Comment by QuenKar** [comment]
hello, I'd like to try this task.

**Comment by etolbakov** [comment]
@WenyXu 
I would like to give it a go if you don't mind?

**Comment by WenyXu** [comment]
> @WenyXu
> I would like to give it a go if you don't mind?

😊 Thanks

**Comment by tisonkun** [comment]
Close as stale.

@WenyXu we can create new good first issues with concrete file formats supports, like AVRO and ORC, so that it's more clear to go forward.
