### ISSUE TITLE
Add "table id" to Datanode heartbeat

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1566]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Table id is just as Important as its name, we should carry it Datanode's heartbeat. It's relatively simple to do, table id is stored in table meta, which is already present when assembling heartbeat data.

**Comment by tarunsamanta2k20** [comment]
I would like to work on it. Please let me know to which file I have to add.

**Comment by MichaelScofield** [comment]
@tarunsamanta2k20 glad to know. You can add table id to `RegionStat` in the function `datanode_stat` in file `src/catalog/src/lib.rs`. `RegionStat` is defined [here](https://github.com/GreptimeTeam/greptime-proto/blob/main/proto/greptime/v1/meta/heartbeat.proto#L59), table id is needed to be added as a new field to it.

**Comment by MichaelScofield** [comment]
ping @tarunsamanta2k20 , any updates?

**Comment by tarunsamanta2k20** [comment]
@MichaelScofield let me check.

**Comment by tarunsamanta2k20** [comment]
@MichaelScofield i have to add table_id as a new filed here https://github.com/GreptimeTeam/greptime-proto/blob/main/proto/greptime/v1/meta/heartbeat.proto#L59.

Right?

**Comment by tarunsamanta2k20** [comment]
@MichaelScofield is it fine? TableName table_id =3;

**Comment by MichaelScofield** [comment]
@tarunsamanta2k20 you can add it as field `uint64 table_id = 7` in message `RegionStat`.

**Comment by tarunsamanta2k20** [comment]
@MichaelScofield let's review this one.

**Comment by tarunsamanta2k20** [comment]
@MichaelScofield do you want me to solve this issue?
