### ISSUE TITLE
Add "table engine" to Datanode heartbeat

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1583]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Now we have multiple table engines, and "engine" is a serious attribute of table. We should carry it Datanode's heartbeat. It's relatively simple to do, table engine is stored in table meta, which is already present when assembling heartbeat data.

**Comment by QuenKar** [comment]
hi，I want to try this task.

**Comment by QuenKar** [comment]
@MichaelScofield hi, I have been reading some code and documentation recently, and there is something that has confused me. 
I find `table engine` is stored in `tableMeta`.A datanode has many tables, for example, if TableA may use "mito engine" and TableB may use "another engine", should we transfer all `table engine` information to metasrv by using a hashmap ? and in HeartbeatRequest proto,I found all attrs are about datanode itself, but table engine in my view is bind with a table. Is it appropriate to add the table engine info here？
https://github.com/GreptimeTeam/greptime-proto/blob/f43972af48f8be1cbb1d27640a8aba8b30955028/proto/greptime/v1/meta/heartbeat.proto#LL35C1-L51C2

**Comment by MichaelScofield** [comment]
@QuenKar I think the table engine should be placed inside message `RegionStat`, just like the table's name. What's Important to Metasrv is actually "region", you can view region as concrete entity while table as some regions group in logical.
