### ISSUE TITLE
Test: write reproducible tests for metrics

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1584]
I think we should add back this test, not for the catalog metrics but to ensure the `/metrics` API is working.

We can change the assertions.

_Originally posted by @killme2008 in https://github.com/GreptimeTeam/greptimedb/pull/1574#discussion_r1193481753_

**Comment by killme2008** [comment]
Already have one 

https://github.com/GreptimeTeam/greptimedb/blob/5f65e3ff442e1efb31e15945cb7cafc00f30580c/tests-integration/tests/http.rs#L429
