### ISSUE TITLE
Add "maintenance mode" for region failover in Metasrv.

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1586]
### What problem does the new feature solve?

Eliminate the unnecessary region failover when the datanodes are planned to be unavailable for a short period of time. For example, rolling upgrade for datanodes.

### What does the feature do?

Add a flag to indicate the cluster is in "maintenance mode" for Metasrv. So that Metasrv could suspend region failover.

### Implementation challenges

How to set the "maintenance mode" to the Metasrv? Currently we are lacking of the control panel to the cluster. We have to design it first.

**Comment by MichaelScofield** [comment]
Now we have admin http interface in Metasrv (see function `fn make_admin_service(meta_srv: MetaSrv) -> Admin`), I think we could just create a new http handler just like the others, and set/remove a key for "maintenance mode" in `in_memory: ResettableKvStoreRef` in struct MetaSrv. When the `RegionFailoverManager` trys to do region failover, it simply checks whether the key is set or not.

**Comment by xifyang** [comment]
I want to have a try

**Comment by MichaelScofield** [comment]
@xifyang welcome!
