### ISSUE TITLE
Obsolete WAL entries when dropping table

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1589]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### What happened?

Currently GreptimeDB does not support `DROP TABLE` clause #497 . Before this issue is resolved, we need to find a way to clean the data in WAL so that WAL can push the obsolete offset forward so that disk space can be  reclaimed.

### What operating system did you use?

NA

### Relevant log output and stack trace

```bash
NA
```

### How can we reproduce the bug?

NA

**Comment by evenyag** [comment]
#1577 should fix this.
