### ISSUE TITLE
`CAST` data type is needed when using `COPY FROM`

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#1594]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

Cannot import csv file via `COPY FROM`

### What operating system did you use?

Mac

### How can we reproduce the bug?

The data example:

```
hostname,environment,usage_user,usage_system,usage_idle,usage_nice,usage_iowait,usage_irq,usage_softirq,usage_steal,usage_guest,usage_guest_nice,ts
host_0,test,32,58,36,72,61,21,53,12,59,72,2023-04-01T00:00:00+00:00
host_1,staging,12,32,50,84,19,73,38,37,72,2,2023-04-01T00:00:00+00:00
host_2,test,98,5,40,95,64,39,21,63,53,94,2023-04-01T00:00:00+00:00
host_3,test,98,95,7,48,99,67,14,86,36,23,2023-04-01T00:00:00+00:00
host_4,test,32,44,11,53,64,9,17,39,20,7,2023-04-01T00:00:00+00:00
```

Then create table:
```
create table tsbs_cpu(hostname STRING, environment STRING, usage_user DOUBLE, usage_system DOUBLE, usage_idle DOUBLE, usage_nice DOUBLE, usage_iowait DOUBLE, usage_irq DOUBLE, usage_softirq DOUBLE, usage_steal DOUBLE, usage_guest DOUBLE, usage_guest_nice DOUBLE, ts TIMESTAMP TIME INDEX, PRIMARY KEY(hostname));
```

Import data:

```
copy tsbs_cpu from '/tmp/greptimedb/tom.csv' WITH(FORMAT='csv');
```

get the error:

> ERROR 1815 (HY000): Failed to execute query: copy tsbs_cpu from '/tmp/greptimedb/tom.csv' WITH(FORMAT='csv'), source: Schema datatypes not match at index 2, expected table schema: Field { name: "hostname", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "environment", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "usage_user", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name

I guess the reason is the schema doesn't match, since the type of `usage_user` is double, but my data value is `32`.

**Comment by killme2008** [comment]
Use the datatype in table schema to cast data type in files.
