### ISSUE TITLE
Optimize heartbeat payload size

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1606]
> If a datanode contains over 10,000 regions, i wonder that if the heartbeat request is too large.

_Originally posted by @killme2008 in https://github.com/GreptimeTeam/greptimedb/pull/1558#discussion_r1196490874_

As the comment above suspects, it's needed to see how the heartbeat payload size is when it contains very many region stats. Optimization should be taken in place to reduced the bandwidth usage (and the cpu time and memory to process them of course).

**Comment by fengjiachun** [comment]
It is not necessary to carry `region stats` with every heartbeat. Only one out of N can carry `region status`.

**Comment by Fengys123** [comment]
> Only one out of N can carry region status.

RegionFailureHandler may need to carry region stats every heartbeat,

If only one out of N can carry region status, region failover may work incorrectly. cc @MichaelScofield

**Comment by MichaelScofield** [comment]
@Fengys123 It's indeed we need to carry all the status of currently contained regions in datanode in the heartbeat. If we can proof that the heartbeat's payload size is not big even if it carries very large regions stats, we can close this issue.

**Comment by fengjiachun** [comment]
Seems the "large data" refer only to strings like [catalog_name, schema_name, table_name]?

**Comment by MichaelScofield** [comment]
@fengjiachun it might be, but we'd better do some tests to see what the size is

**Comment by fengjiachun** [comment]
> @fengjiachun it might be, but we'd better do some tests to see what the size is

cc @Fengys123

**Comment by Fengys123** [comment]
Did some tests and generated some data, as shown below: 
```
The size of payload: 6.5429688 KB, Region number: 100, 
The size of payload: 65.42969 KB, Region number: 1000, 
The size of payload: 654.2969 KB, Region number: 10000, 
The size of payload: 6542.9688 KB, Region number: 100000, 
```
> Test Code [here](https://github.com/GreptimeTeam/greptime-proto/commit/df32364e77c0f177740787a5a146787b31247605)

**Comment by MichaelScofield** [comment]
So the heartbeat's payload is not small enough to be neglected considering we might open a lot of regions on a single datanode. Which part of the heartbeat contributes the most bytes in payload?

**Comment by Fengys123** [comment]
Ok let me continue to explore.

**Comment by Fengys123** [comment]
In  `RegionStat`, `table_name` field about 70%, other about 30%.

**Comment by Fengys123** [comment]
```
# Normal
The size of payload: 7.5195313 KB, Region number: 100, 
The size of payload: 75.19531 KB, Region number: 1000, 
The size of payload: 751.9531 KB, Region number: 10000, 
The size of payload: 7519.5313 KB, Region number: 100000, 

# Set `table_name` of `table_ident` to none
The size of payload: 3.0273438 KB, Region number: 100, 
The size of payload: 30.273438 KB, Region number: 1000, 
The size of payload: 302.73438 KB, Region number: 10000, 
The size of payload: 3027.3438 KB, Region number: 100000, 

# Set 'table_ident' to none
The size of payload: 1.953125 KB, Region number: 100, 
The size of payload: 19.53125 KB, Region number: 1000, 
The size of payload: 195.3125 KB, Region number: 10000, 
The size of payload: 1953.125 KB, Region number: 100000, 

Summarize
1. `table_ident` accounts for 75%, of which `table_name` in table_ident accounts for 60%
2. Others accounted for 25%,
```

**Comment by MichaelScofield** [comment]
I think we could simply use table id.

**Comment by fengjiachun** [comment]
proto does not need to be modified, catalog_name, schema_name, and table_name in table_ident can be left empty.

**Comment by evenyag** [comment]
If we finish refactoring the datanode, I guess we only need to pass a region id.

**Comment by fengjiachun** [comment]
> If we finish refactoring the datanode, I guess we only need to pass a region id.

Yes.

**Comment by fengjiachun** [comment]
> If we finish refactoring the datanode, I guess we only need to pass a region id.

Close this issue as there is now only a region Id (u64).
