### ISSUE TITLE
Supports google cloud storage

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1611]
### What type of enhancement is this?

API improvement, Configuration

### What does the enhancement do?

Supports google cloud storage service by opendal:

* https://opendal.apache.org/docs/rust/opendal/services/struct.Gcs.html

**Comment by NiwakaDev** [comment]
I'd like to work on this!! 

#656 and #911 are helpful as references?

**Comment by WenyXu** [comment]
Thanks @NiwakaDev , This PR #1081 may also be helpful
