### ISSUE TITLE
/status endpoint to retrieve runtime and build info

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1650]
### What type of enhancement is this?

API improvement, User experience, Other

### What does the enhancement do?

For example, Prometheus has a `/status` endpoint that returns some info about runtime and build etc.

<img width="1286" alt="Screenshot 2023-05-26 at 09 52 49" src="https://github.com/GreptimeTeam/greptimedb/assets/14142/4712e133-2e25-4725-9577-ea1a4a0f07ae">

GreptimeDB needs such an endpoint or page in the dashboard too.
Maybe we can add a RESTFul API to retrieve the information and render it by the dashboard.

**Comment by killme2008** [comment]
> @killme2008 @waynexia I'm happy to give it a go if you don't mind

Cool, please go ahead, thanks,

**Comment by etolbakov** [comment]
yeah, I have the same understanding. [Dashboard](https://github.com/GreptimeTeam/dashboard) could be a graphical representation of the payload returned from the `/status` endpoint.

**Comment by killme2008** [comment]
Yes, it will be rendered in dashbaord.

**Comment by alili** [comment]
> Yes, it will be rendered in dashboard.

It sounds very reasonable that we should see the running data of our database on our own dashboard

**Comment by killme2008** [comment]
@alili  Can you create an issue in dashboard  repo to add the status page?

The `/status` endpoint is ready. Thanks to @etolbakov .

**Comment by etolbakov** [comment]
@alili @killme2008 
I was curious to try, could you please take a look?
https://github.com/GreptimeTeam/dashboard/pull/283 
Definitely design improvements are required so if you could help me with that I'll be grateful
