### ISSUE TITLE
Providing option to disable auto deduplication

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1666]
### What problem does the new feature solve?

For some analytic scenario auto data deduplication on the primary key is not expected. We can provide some options to disable this behavior

### What does the feature do?

E.g., via table option or add a new table engine. This option can affect both compaction and table scan stages

**Comment by tisonkun** [comment]
@waynexia @MichaelScofield is this resolved by implementing the append-only mode?

**Comment by waynexia** [comment]
Yes

**Comment by tisonkun** [comment]
This is superseded by https://github.com/GreptimeTeam/greptimedb/issues/3480.

Close.
