### ISSUE TITLE
Stream table scan results to frontend

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1676]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Currently we always return record batches to frontend when executing table scan and mark `Output::Stream` as unreacheable:

https://github.com/GreptimeTeam/greptimedb/blob/f64527da2213d81c530b284d6d86aa32ac1cd82f/src/frontend/src/table/scan.rs#L58-L72

This will force both datanode and frontend to collect all rows yielded by table scan and datanode sends these rows to frontend all at once, which may cause frontend/datanode OOM.

We need to refactor the table scan API into a stream manner so that rows are passed to frontend record batch by record batch.

**Comment by MichaelScofield** [comment]
duplicated in #1718
