### ISSUE TITLE
Filter out outdated heartbeats at Metasrv.

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1707]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

After the region failover is done, the distribution of region is changed. However, there might be heartbeats carrying outdated data, typically caused by network lagging, process awaking from dormant, or the heartbeats are just on the flight.

These heartbeats are not necessary and harmful, should be filtered out at Metasrv. We can compare the heartbeats info with the most recent global region placement metadata.

Also we need to remove the incorrect region ident keys in failure detect runner, too (by sending a control message).

**Comment by killme2008** [comment]
@MichaelScofield @fengjiachun Please take a look this issue

**Comment by MichaelScofield** [comment]
@fengjiachun Are you working on this?

**Comment by fengjiachun** [comment]
Yes, I will fix this issue ASAP.

My plan is to synchronize with the region lease. If metasrv decides not to renew a lease for a specific region, then the corresponding heartbeat will be removed.
