### ISSUE TITLE
Optimize distributed deletions from gRPC

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1708]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

GRPC delete requests are just like insert requests, carrying the column data for deletions. They both had very similar implementations: splitting the to be inserted/deleted data by partition rules, not parallel or batched, and done in a per table fashion etc.

Now the distributed insertions are optimized in a batch in https://github.com/GreptimeTeam/greptimedb/pull/1687 , it's time we do that for distributed deletions as well.

**Comment by NiwakaDev** [comment]
I'd like to work on this issue. Should I first start by implementing `DeleteRequests` like `InsertRequests`?:
https://github.com/GreptimeTeam/greptime-proto/pull/47

**Comment by MichaelScofield** [comment]
@NiwakaDev Yes, I think we should first implement it.
