### ISSUE TITLE
Make `version()` function of our mysql server returns GreptimeDB info

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1711]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Now `select version()` in our mysql server always returns static info:

```txt
+-----------+
| version() |
+-----------+
| 8.0.26    |
+-----------+
```

It's fun to see the GreptimeDB's version, git commit, tags etc. instead. Just like our `greptimedb --version`.

**Comment by QuenKar** [comment]
Hi! I try this task yesterday.
<img width="565" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/47681251/bcb8c7d8-2398-4a43-b99d-b9901b832950">
Now, my impl just like this. if change the `git branch`, the information will change as well.
<img width="496" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/47681251/42f56edf-d96b-4862-9422-1e2a217cd243">

<img width="872" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/47681251/52ff9d7b-39e7-4b7d-aeda-d5f53f41263d">
Is this what you want？
