### ISSUE TITLE
Update table metadata values in a batch atomically

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1715]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

When doing region failover, the updating of metadata values is guarded by a distributed lock. It does not robust enough. For example, the lock lease could be expired in the middle of one's updating, letting others to start updating concurrently. For now, we set the lease of the distributed lock to 10 seconds, which is long enough here to get the job done. Maybe we should introduce "version" companion values to these two metadata values, and use ETCD transaction request to update them?

**Comment by MichaelScofield** [comment]
Since region failover is only running in leader metasrv, we can use memlock instead of etcdlock.

**Comment by MichaelScofield** [comment]
Then we should make this whole table metadata update as a single txn implemented inside `TableMetadataManager` (don't expose the "txn" object)

**Comment by Fengys123** [comment]
> Since region failover is only running in leader metasrv, we can use memlock instead of etcdlock.

It seems that there is no need to add mem-lock, Since when the procedure is executed, the lock-key will be obtained first.
