### ISSUE TITLE
More properly guard against concurrent schemaless table creations and alterations

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1716]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Now the schemaless table creations and alterations are run concurrently (introduced by #1687 ). This could cause some issues when running concurrently. For example, unique table ids are wasted, or unnecessary calls to Metasrv. We should properly guard against it in Frontend.

**Comment by MichaelScofield** [comment]
Although the schemaless table creations and alterations are reverted back to serialized execution now, we can still benifit from adding a lock to control the concurrency, avoiding doing some unnecessary work.

**Comment by sunray-ley** [comment]
I want to have a try.

**Comment by MichaelScofield** [comment]
thx @sunray-ley , assigned

**Comment by killme2008** [comment]
@MichaelScofield Looks like we don't have this problem currently after we used procedures for all DDL statements. Could you check it?

**Comment by MichaelScofield** [comment]
@killme2008 This problem is gone not because we are using procedure but the schemaless table creations are changed back to serial mode.
