### ISSUE TITLE
Make the gRPC channel between Frontend and Datanode configurable

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1717]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Currently the values for `ChannelConfig` are hard coded in `DatanodeClients`, better made them configurable in Frontend's config file.

**Comment by MichaelScofield** [comment]
The one `DatanodeClients` that's used in Metasrv is already configurable, see #1965 . We can do the same for Frontend.

**Comment by sunray-ley** [comment]
Hello, I have tried this task, and now the gRPC channel between Frontend and Datanode is configurable.
I have also opened a PR. Could you please check if I did it correctly?

**Comment by MichaelScofield** [comment]
@sunray-ley thx, I'll review your PR today.
