### ISSUE TITLE
Streaming get flight data

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1718]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Currently we are accumulating the recordbatches in the datanode client, and returning query result as a whole to the caller. This is not the most optimal. We should instead fully utilize the server stream of `get` in Arrow Flight, and returns a stream of recordbatches to the caller.

**Comment by waynexia** [comment]
> We would also refactor `PartitionExec` so that datanode can return a real stream instead of a `PartitionExec` holding a full recordbatch.

context: https://github.com/GreptimeTeam/greptimedb/issues/1676
