### ISSUE TITLE
Tests failed: `test_region_manifest_checkpoint*`

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1720]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

The following tests failed:

```txt
     Summary [   6.870s] 1163/1431 tests run: 1161 passed, 2 failed, 5 skipped
        FAIL [   0.209s] storage manifest::region::tests::test_region_manifest_checkpoint_compress
        FAIL [   0.177s] storage manifest::region::tests::test_region_manifest_checkpoint_uncompress
```

When trying to release db. See full logs here: https://github.com/GreptimeTeam/greptimedb/actions/runs/5172675489/jobs/9317233410

### What operating system did you use?

ubuntu

### How can we reproduce the bug?

Run tests in release action.

**Comment by killme2008** [comment]
Looks like it's a race condition, the test sleeps for a while to wait GC task running, but it may not run as expected in time. It happens rarely, I think we can close this issue until it happens frequently.
