### ISSUE TITLE
Support "where" in "show" statement

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1722]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The `show tables` statement has `where expr` part to filter the result, see https://dev.mysql.com/doc/refman/8.0/en/show-tables.html . It's better we support it. Also to `show databases`

**Comment by NiwakaDev** [comment]
I'd like to work on this, but it might take long time to implement.

**Comment by MichaelScofield** [comment]
@NiwakaDev Welcome! Take your time to do it ~
