### ISSUE TITLE
Integrations tests for upgrading database

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#1730]
### What type of enhancement is this?

Other

### What does the enhancement do?

As we are approaching more users and installations we start to pay more attention to correctness and ux on upgrading database. To ensure that, we will need CI to perform tests for that. 

A basic setup can be:

- Container images that contain all state from our supported releases. For instance, the state can be:
  - local write-ahead logs
  - local data files
  - data files that hosted on a minio installation
  - an etcd instance that hosts previous cluster data
- Build binary from PR head and put `greptime` binary into container
- Run `greptime` binary in both standalone and cluster mode
- Run tests
- Label PR `breaking change` if test fails
- Request an optional upgrade/migration script

**Comment by MichaelScofield** [comment]
With compatibility test being added to our CI, I think this issue can be closed.
