### ISSUE TITLE
Make `PhiAccrualFailureDetector` configurable

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1738]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Currently the `PhiAccrualFailureDetector` is using default configurations. Better make them configurable in Metasrv's config file.

**Comment by Criterionist** [comment]
i want to have a try

**Comment by WenyXu** [comment]
> i want to have a try

Thks

**Comment by killme2008** [comment]
@Criterionist Are u still working on this feature?
