### ISSUE TITLE
refactor: Remove MySQL related options from Datanode

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1739]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Options `mysql_addr` and `mysql_runtime_size` is unused as we don't start a MySQL server on datanode now.
https://github.com/GreptimeTeam/greptimedb/blob/8cda1635cc6c9878a7bf46219f0009a155a1be75/src/datanode/src/datanode.rs#L343-L344

We can also remove the command line argument now
https://github.com/GreptimeTeam/greptimedb/blob/8cda1635cc6c9878a7bf46219f0009a155a1be75/src/cmd/src/datanode.rs#L88

### Implementation challenges

NA

**Comment by WangTingZheng** [comment]
I can take this task.

**Comment by WenyXu** [comment]
> I can take this task.

Thks
