### ISSUE TITLE
Track metrics in TableScan plan

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1778]
### What problem does the new feature solve?

We are using DataFusion's metrics to track runtime consumption like CPU time or rows computed. But the root execution plan `TableScan` doesn't maintains such information. Makes the overall metrics inaccurate.

### What does the feature do?

Support metrics in `TableScan`'s execution plan

**Comment by waynexia** [comment]
Going to implement this next week

**Comment by shuiyisong** [comment]
It would be nice if we could record `table_scan_bytes` too 😋
