### ISSUE TITLE
Make heartbeat intervals configurable in Frontend and Datanode

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1792]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Currently the heartbeat intervals are hardcoded to 5 seconds in both Frontend and Datanode. It's better to set them in config files.

**Comment by ccjeff** [comment]
Hi I'm new to the project and I'd like to have a try with the issue. Is this issue still open to be worked on? Thanks!

**Comment by WenyXu** [comment]
> Hi I'm new to the project and I'd like to have a try with the issue. Is this issue still open to be worked on? Thanks!

😙

**Comment by ccjeff** [comment]
Hi, I just want to clarify some questions before opening the PR for this issue. For the Datanode I have updated the `MetaClientOptions` structure to include the `heartbeat_interval_millis` which was hard-coded in the instance before. However, I've noticed that in Frontend the `HeartbeatTask` is using `report_interval`. Is this field what I should be changing to make it configurable? I found they were using different time units (milliseconds in the data node and seconds in Frontend) so I wasn't sure if they were intended to be designed differently. Thank you :)

**Comment by MichaelScofield** [comment]
@ccjeff thx!

- there are two heartbeat interval configs: `heartbeat_interval_millis` for datanode and `report_interval` for frontend. I think it's better to unify them to one name: `heartbeat_interval_millis`
  - use milliseconds of course
- for datanode, `heartbeat_interval_millis` is better placed in `DatanodeOptions`
- for frontend, `heartbeat_interval_millis` is better placed in `FrontendOptions`
