### ISSUE TITLE
/config HTTP API to render the config file.

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1793]
### What type of enhancement is this?

API improvement, Configuration

### What does the enhancement do?

Let's add a new endpoint to HTTP API: `/config` to render the current config in tom format.

Then the users can check the current runtime configuration by HTTP request or save it to a file for backup etc.

**Comment by sunng87** [comment]
Remember to put these administration APIs under a different path from data APIs. We don't expose these APIs in some deployment.

**Comment by etolbakov** [comment]
@killme2008 
I'm happy to give it a go if you don't mind

**Comment by killme2008** [comment]
> @killme2008 I'm happy to give it a go if you don't mind

Cool, please go ahead. Thank you.

**Comment by MichaelScofield** [comment]
done in #1896
