### ISSUE TITLE
Some SQL statements cannot be run in the cloud

### ISSUE THREAD

**Issue by alili** [GreptimeTeam/greptimedb#1804]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Other

### What happened?

`Query engine output error: Failed to execute query: select key_name,COUNT(*) as times from keymaster WHERE key_name like '%+%' Group by key_name order by times DESC limit 10, source: Failed to execute logical plan, source: Failure during query execution, source: Fail to create physical plan: External error: Failed to encode Substrait logical plan, source: Failed to encode DataFusion plan, source: This feature is not implemented: Unsupported expression: keymaster.key_name LIKE Utf8("%+%")`

I could run this code in standalone, but there was an error in the cloud version

### What operating system did you use?

cloud

### Relevant log output and stack trace

```bash
Query engine output error: Failed to execute query: select key_name,COUNT(*) as times from keymaster WHERE key_name like '%+%' Group by key_name order by times DESC limit 10, source: Failed to execute logical plan, source: Failure during query execution, source: Fail to create physical plan: External error: Failed to encode Substrait logical plan, source: Failed to encode DataFusion plan, source: This feature is not implemented: Unsupported expression: keymaster.key_name LIKE Utf8("%+%")
```

### How can we reproduce the bug?

In QA environment

**Comment by killme2008** [comment]
Fixed by #1806
