### ISSUE TITLE
improve influx v2 api compability

### ISSUE THREAD

**Issue by ttys3** [GreptimeTeam/greptimedb#1815]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

currently the doc said greptime support influxdb v2 api

https://docs.influxdata.com/influxdb/v1.8/tools/api/?t=Auth+Enabled#apiv2write-http-endpoint

https://github.com/influxdata/influxdb-client-go#influxdb-18-api-compatibility

but instead,  greptimedb uses `/v1/influxdb/write`

it should support `/api/v2/write` endpoint so exits influx sdk (https://docs.influxdata.com/influxdb/v2.0/api-guide/client-libraries/) client could just use the same code to write.

since this use a standalone port, I do not think its a problem.

besides this, you need also ignore `org`  param.  and change `db` param to use `bucket`, since v2 does not have `db`

### Implementation challenges

just mount a  `/api/v2/write` endpoint to the exists v2 impl code

related code:

https://github.com/GreptimeTeam/greptimedb/blob/5ab074709206c539657d91ac8766065addd3b084/src/servers/src/http.rs#L492-L498

**Comment by MichaelScofield** [comment]
@ttys3 Thanks! Will fix it ASAP!
