### ISSUE TITLE
Support to query on ORC format files

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1820]
### What problem does the new feature solve?

The PR [#1814](https://github.com/GreptimeTeam/greptimedb/pull/1814) supports importing ORC format data. We can easily utilize the `orc-rust` crate and support queries on ORC format files by converting files to `SendableRecordBatchStream`.

https://github.com/GreptimeTeam/greptimedb/blob/a4226a0e823e16461872e1767acaed340357b72d/src/file-table-engine/src/table/format.rs#L376-L400

### What does the feature do?

Support to query on ORC format files.

**Comment by gobraves** [comment]
I would like to give it a go if you don't mind? @WenyXu

**Comment by WenyXu** [comment]
> I would like to give it a go if you don't mind? @WenyXu

Thks

**Comment by gobraves** [comment]
@WenyXu 
Hello, I would like to confirm two points regarding this issue:
1. It seems we may not need to implement `new_orc_plan`. Based on your description and the code, it appears there isn't an `ExecutionPlan` for orc. If we were to implement `new_orc_plan`, wouldn't we need to implement an `ExecutionPlan` for orc?
2. Regarding the construction of `new_orc_stream`, should it support projection? orc-rust provides `Cursor::new` to set projection, but it only accepts a `&[&str&[&str]` type. Also, it seems that `src/common/datasource/src/file_format/orc.rs` does not support this. Should it be supported?

**Comment by WenyXu** [comment]
> 

Hi, @gobraves, Nice to hear from you.
For question 1, Yes, we don't implement something like `new_orc_plan` anymore. We removed the `scan` method recently. For the second question, I guess there is something that allows you to take projection on the `RecordBatchStream`. Take a look `arrow` crate.

**Comment by gobraves** [comment]
@WenyXu  I understand now. With the schema, projection can be performed while reading the RecordBatchStream, and there is no need to read all the data before applying the projection.
Thanks!

**Comment by WenyXu** [comment]
> 
If you wish, you can implement a built-in columns projector for [orc-rust](https://github.com/wenyxu/orc-rs) like `ParquetReader` did in `arrow`.

**Comment by gobraves** [comment]
@WenyXu 
Are you referring to [ParquetRecordBatchReader](https://github.com/apache/arrow-rs/blob/414235e7630d05cccf0b9f5032ebfc0858b8ae5b/parquet/src/arrow/arrow_reader/mod.rs#L318)? 
I think I'll complete this issue first, and if possible, I'll try to implement that feature later.

**Comment by WenyXu** [comment]
> @WenyXu Are you referring to [ParquetRecordBatchReader](https://github.com/apache/arrow-rs/blob/414235e7630d05cccf0b9f5032ebfc0858b8ae5b/parquet/src/arrow/arrow_reader/mod.rs#L318)? I think I'll complete this issue first, and if possible, I'll try to implement that feature later.

Yep

**Comment by WenyXu** [comment]
Hi @gobraves, I fix a bug in #1922 . It may help with your implementation.

**Comment by gobraves** [comment]
@WenyXu hi，Where should I write unit tests? Or how can I integrate them into the existing test module?

**Comment by WenyXu** [comment]
> @WenyXu hi，Where should I write unit tests? Or how can I integrate them into the existing test module?

Hi @gobraves, please check here: https://github.com/GreptimeTeam/greptimedb/tree/develop/src/common/datasource/tests

**Comment by gobraves** [comment]
> Hi @gobraves, please check here: https://github.com/GreptimeTeam/greptimedb/tree/develop/src/common/datasource/tests

Ok, I got it.  Thank you.

**Comment by gobraves** [comment]
hi @WenyXu，I have committed a PR where I described my implementation for creating a new Orc stream.

**Comment by WenyXu** [comment]
> hi @WenyXu，I have committed a PR where I described my implementation for creating a new Orc stream.

Hi @gobraves, Thank you for your contribution. I added some comments to your PR.  And feel free to reach me via Slack if you have any questions.
