### ISSUE TITLE
Check manifest file when createing table

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1833]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Create table may fail and will be retried by procedure. To make sure manifest files are correct we should check its content if there are any.

**Comment by NiwakaDev** [comment]
I'd like to work on this issue if you don't mind. If so, Do you have any guidelines for addressing this issue?

**Comment by waynexia** [comment]
@evenyag maybe you have some thoughts?

**Comment by evenyag** [comment]
I haven't figured out a clear solution for this. What's more, I plan to refactor manifests and table engine in #1869 which might fix this issue. Let's postpone this.

**Comment by killme2008** [comment]
Looks like we don't need to fix this in 0.4, because we removed the table manifest and replaced it with metasrv management.
