### ISSUE TITLE
Redesign the "Instance"s

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1836]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Currently the "Instance"s are a bit messy. We have Datanode Instance and Frontend Instance, and we have two starting mode: standalone and distributed. Which mode starts what instance, is totally chaos. That's because Instance takes too many responsibility, or fields. Notably, the heartbeat task, the catalog manager and query handlers. Ideally, in standalone mode, we should start Frontend Instance and Datanode query handlers; in distributed mode, we should start Datanode Instance and its heartbeat, Frontend Instance and its heartbeat, separately. Clearly a redesign should be taken seriously.

**Comment by NiwakaDev** [comment]
I think we can get Datanode Instance to have `StatementExecutor` as a field, not Frontend Instance.

**Comment by MichaelScofield** [comment]
@NiwakaDev Thx for your suggestion! The `StatementExecutor` is better kept resided in Frontend Instance, since the Frontend Instance is expected to handle all query protocols. But rather the `SqlStatementExecutor` should not impl for Datanode Instance. We should create a new struct to execute sql stmt within Datanode.
