### ISSUE TITLE
Http request body limits setting

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1842]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

The axum do not accept bodies larger than 2MB, https://docs.rs/axum/latest/axum/extract/index.html#request-body-limits

But we can change it by `DefaultBodyLimit`

https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html

We can add a config param to HTTP options.

**Comment by ItIsOHM** [comment]
Hey there @killme2008 , I'd love to contribute as a beginner. Can you please assign this to me and also help me as to where I can start to tackle this issue from?

From what I can  understand, we need to implement this sort of a solution?
![image](https://github.com/GreptimeTeam/greptimedb/assets/62976081/91a7ecc8-4aca-4800-9cfa-65a8d7cc4c7f)

**Comment by etolbakov** [comment]
@ItIsOHM I was just passing by :) probably you would like to extract `10 * 1000 * 1000` to `const` with a meaningful name so it will be easier to put that value to the settings information.

**Comment by ItIsOHM** [comment]
> @ItIsOHM I was just passing by :) probably you would like to extract `10 * 1000 * 1000` to `const` with a meaningful name so it will be easier to put that value to the settings information.

Oh yes absolutely! Just wanted to know if I was going in the correct direction with this :D

**Comment by killme2008** [comment]
> Hey there @killme2008 , I'd love to contribute as a beginner. Can you please assign this to me and also help me as to where I can start to tackle this issue from?
> 
> From what I can understand, we need to implement this sort of a solution? ![image](https://user-images.githubusercontent.com/62976081/249566448-91a7ecc8-4aca-4800-9cfa-65a8d7cc4c7f.png)

Glad you are interested.

First, you have to add a param such as `http_body_maximum_size_size` to `HttpOptions` in server crate:

https://github.com/GreptimeTeam/greptimedb/blob/7e23dd77142506ec3238a2a8dae1e18c07cbee10/src/servers/src/http.rs#L128

Recommend setting its type as `common_base::readable_size::ReadableSize` so that user can set it as `6G` etc.

Second, add the  `DefaultBodyLimit` to the HTTP server layer

https://github.com/GreptimeTeam/greptimedb/blob/7e23dd77142506ec3238a2a8dae1e18c07cbee10/src/servers/src/http.rs#L534

Feel free to try it! Thank you.

**Comment by ItIsOHM** [comment]
Hey there @killme2008, recently opened a PR that looks to fix this issue :D
