### ISSUE TITLE
Add pagination to KvStore's `range` method

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#1846]
### What type of bug is this?

Crash, Incorrect result, Unexpected error

### What subsystems are affected?

Datanode

### What happened?

Datanode needs to initialize tables while starting up. In distributed mode, it [calls `range`](https://github.com/GreptimeTeam/greptimedb/blob/559d1f73a2819b775b9c8757cff08522ec216f14/src/catalog/src/remote/manager.rs#L452) on kv backend to retrieve table global key using prefix `__tg-{catalog}-{schema}`, which essentially goes through meta-srv and hits etcd with range request. However, etcd has a limit on single request size. If too many tables are created within the schema, it would hit etcd's size limit and fail to perform the request.

attached: value on etcd
```
xxx@etcd-0:/opt/bitnami/etcd$ etcdctl get "__tg-q6dj4up5mmri-qadbmetrics" --prefix | wc -c
4419593
```

### What operating system did you use?

Ubuntu 21.04 x64

### Relevant log output and stack trace

```bash
Error: StartDatanode { ** irrelevant location **, source: Catalog { location: Location { file: "/home/runner/work/greptimedb/src/datanode/src/instance.rs", line: 268, column: 39 }, source: MetaSrv { location: Location { file: "greptimedb/src/catalog/src/remote/client.rs", line: 178, column: 18 }, source: TonicStatus { source: Status { code: Internal, message: "Failed to execute via Etcd, source: grpc request error: status: OutOfRange, message: \"Error, message length too large: found 4448105 bytes, the limit is: 4194304 bytes\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\"} }", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 28 Jun 2023 11:55:09 GMT", "content-length": "0"} }, source: None }, location: Location { file: "/home/runner/work/greptimedb/src/meta-client/src/client/store.rs", line: 144, column: 43 } } } } }
```

### How can we reproduce the bug?

1. deploy a distributed cluster of greptimedb
2. create thousands of table within one scheme
    - at this point, connect to greptimedb frontent using mysql/pg client and try to execute `show tables;`, it should return the same error msg
3. try to restart datanode and fail

**Comment by MichaelScofield** [comment]
I'm working on a refactor of table's metadata values. Will resolve this issues, too.
