### ISSUE TITLE
add/move prometheus routes to default http port

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1848]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The simulated prometheus http endpoint occupies a dedicated port (default to 4004). To reduce exported ports we can consider add a route rule for 4004 on our default http port (default to 4000) or just merge these two ports.

**Comment by shawnh2** [comment]
hi, i would like to help with it, plz assign

**Comment by WenyXu** [comment]
> hi, i would like to help with it, plz assign

Thx
