### ISSUE TITLE
Implement new error proc macro to display logs

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1854]
### What type of enhancement is this?

User experience

### What does the enhancement do?

All errors are using `#[snafu(display)]` to define their text error message. But those text for logging and to users should be different.

## proposed

Implement a proc-macro to generate methods like the following:

```rust
impl Error {
    pub fn for_debug() -> String {
        // like backtrace
        // contains `location` and `message` but without `source`
        todo!()
    }

    pub fn to_user() -> String {
        // one paragraph
        // without location and source
        // composed of three parts:
        // - `status code`
        // - `status code's doc`
        // - `message` from the inner-most error
        todo!()
    }
}
```
Then we can get two kinds of error. One for logging (example omitted) and one for user (`Unsupported 1001(Unsupported operation): Unable to convert value NULL to sql value`)

## implementation details

Pre-requirement:
- We should adjust our `#[snafu(display)]` to remove all source and location. Let's call this displayed text "message"
- Change all external error source (e.g., std io error or datafusion error)'s name from `source` to `error`. This is for distinguishing our error type and other errors.

`for_debug()`:
- match the error enum and concat `message` + `location` for each variant
- if contains field named `source`, call its `for_debug()` and concat the result in new line

`to_user()`
- display status code and its documentation
- use [`Error::source`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source) to retrieve the inner-most error and display it

**Comment by Gump9** [comment]
which file can i have a look on this issue,i want to know things we have done

**Comment by waynexia** [comment]
For our current error system you can check any of `error.rs` files.
