### ISSUE TITLE
[enhancement] updating of the user accounts via SQL statement

### ISSUE THREAD

**Issue by thinkORo** [GreptimeTeam/greptimedb#1862]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

With a specific SQL statement, like `select update_user_accounts()`, the user has the ability to refresh an updated static_user_provider-file.

This would have the advantage of not having to restart the service to get a new list of users or passwords.

### Implementation challenges

I would assume that there is not special implementation challenge. But I have not done this in Rust before.
But I would like to support in any way.

**Comment by killme2008** [comment]
Good idea! 

> I would assume that there is not special implementation challenge. But I have not done this in Rust before.
But I would like to support in any way.

It's great if you want to try.

**Comment by thinkORo** [comment]
Contrary to my own suggestion with `select update_user_accounts()`, after looking at the code, I would perhaps suggest more of an `alter system refresh_user_accounts`.

For this I would extend `statements/alter.rs` by `AlterSystem` (in addition to AlterTable) at the beginning to be able to offer further functions later if necessary.

I am looking forward to your feedback.

**Comment by evenyag** [comment]
What about adding the keyword `reload` or `refresh`? e.g. `alter system reload user_accounts`.

We could reuse this keyword to reload other things. I find out clickhouse has some `system reload` commands.
https://clickhouse.com/docs/en/sql-reference/statements/system#reload-dictionaries

**Comment by tisonkun** [comment]
Try impl in https://github.com/GreptimeTeam/greptimedb/pull/3564#issuecomment-2014728699.

Succeed but I tend to reject this one. See the comment linked above.

**Comment by tisonkun** [comment]
In short: Briefly we can try to provide a way for custom user provider impl.

Or a generic dynamic user provider impl.
