### ISSUE TITLE
Potential memory leak in histograms from `metrics` crate

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1906]
### What type of bug is this?

Other

### What subsystems are affected?

Standalone mode, Frontend, Datanode, Meta

### What happened?

As mentioned in https://github.com/metrics-rs/metrics/issues/245 and https://github.com/metrics-rs/metrics/issues/339

> we buffer all individual histogram measurements until something drains them. This indeed represents an unbounded queue, effectively. We used to have a rolling windowed histogram setup where users had to explicitly specify how long a histogram should record for, but that introduced a lot of overhead to recording each point since we had to make every record call check if things needed to be dropped, etc.

If we never call `/metrics` to retrieve metrics from the server, our histograms might never release its allocated memory.

### What operating system did you use?

All

### How can we reproduce the bug?

Put or query some data frequently but never curl `/metrics`.

**Comment by v0y4g3r** [comment]
Maybe switch to [prometheus-rust](https://docs.rs/prometheus/latest/prometheus/)

**Comment by SSebo** [comment]
recommend this lib https://github.com/sunng87/metriki

**Comment by Taylor-lagrange** [comment]
please assign this to me

**Comment by evenyag** [comment]
Closed by #2655
