### ISSUE TITLE
refactor: Separating statement parse func in `sql/parser.rs` into separate `*_parser.rs`

### ISSUE THREAD

**Issue by DevilExileSu** [GreptimeTeam/greptimedb#1914]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

The implementations of `show`, `describe`, `explain`, and `drop` statement parsing are all in `sql/parser.rs`. Perhaps it would be better to split them into separate `*_parser.rs` files and place them in the `sql/parsers` directory, just like other statements.

**Comment by Gump9** [comment]
can i have a try?

**Comment by waynexia** [comment]
Thanks
