### ISSUE TITLE
refactor: Remove `common_error::prelude`

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1927]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Remove `prelude` mod from `common-error` crate. Most re-exports in the `prelude` mod is seldom been used.
https://github.com/GreptimeTeam/greptimedb/blob/ed756288b3d30bd487961c26b72c54633ecfb0b3/src/common/error/src/lib.rs#L20-L30

### Implementation challenges

Remove the prelude mod and replace usages of `prelude` by using items explicitly.

Before:
```rust
use common_error::prelude::*;

#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum Error {}

impl ErrorExt for Error {}
```

After:
```rust
use snafu::Snafu;
use common_error::ext::ErrorExt;

#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum Error {}

impl ErrorExt for Error {}
```

**Comment by WenyXu** [comment]
> i want to have a try🤓️

Thx
