### ISSUE TITLE
Tidy up all timeout config places, make them set from some static sources

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1935]
### What type of enhancement is this?

Configuration, Tech debt reduction

### What does the enhancement do?

In #1861,  #1901, and #1878, We introduce a lot of hard code timeout configurations.

e.g.,
```rust
 timeout(
      // TODO(weny): makes timeout configurable.
          Duration::from_secs(10),
          self.meta_client.submit_ddl_task(request),
      )
      .await
      .context(error::TimeoutSnafu)?
      .context(error::RequestMetaSnafu)
```

It's better to make it configurable for each request.

i.g.,
``` rust
let mut alter_request = AlterRequest{ .. };
alter_request.timeout = Some(Duration::from_secs(10));

client.alter(alter_request).await;
```

**Comment by waynexia** [comment]
maybe a good first issue?

**Comment by MichaelScofield** [comment]
Actually we need to tidy up all the places that use all sorts of timeouts, and set them from some static config sources.

**Comment by fengjiachun** [comment]
https://github.com/hyperium/tonic/blob/master/tonic/src/transport/service/grpc_timeout.rs#L49

**Comment by fengjiachun** [comment]
We seem unable to set a longer timeout for one of the requests individually, as the internal implementation will let the smaller value win.


https://github.com/hyperium/tonic/blob/master/tonic/src/transport/service/grpc_timeout.rs#L49

**Comment by fengjiachun** [comment]
Looks like this issue has been solved, can we close it? @MichaelScofield @WenyXu

**Comment by MichaelScofield** [comment]
No, we have to go through our codes to see all the timeouts are or could be properly set from some config files.
