### ISSUE TITLE
ERROR 1815 (HY000): Failed to execute query: desc system_metrics

### ISSUE THREAD

**Issue by daheige** [GreptimeTeam/greptimedb#1941]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

% mysql -h 127.0.0.1 -P 4002
mysql> use public
Database changed
mysql> CREATE TABLE IF NOT EXISTS system_metrics (
    ->     host STRING,
    ->     idc STRING,
    ->     cpu_util DOUBLE,
    ->     memory_util DOUBLE,
    ->     disk_util DOUBLE,
    ->     ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ->     PRIMARY KEY(host, idc),
    ->     TIME INDEX(ts)
    -> );
Query OK, 0 rows affected (0.32 sec)
mysql> desc system_metrics;
ERROR 1815 (HY000): Failed to execute query: desc system_metrics, source: Failed to parse SQL, source: SQL statement is not supported: desc system_metrics, keyword: system_metrics
mysql> show create table system_metrics;

### What operating system did you use?

Darwin 21.6.0 Darwin Kernel Version 21.6.0

### Relevant log output and stack trace

```bash
2023-07-11T14:27:55.898833Z  WARN servers::mysql::writer: Failed to execute query 'desc system_metrics' err.msg=Failed to execute query: desc system_metrics, source: Failed to parse SQL, source: SQL statement is not supported: desc system_metrics, keyword: system_metrics err.code=Unsupported err.source=Failed to parse SQL, source: SQL statement is not supported: desc system_metrics, keyword: system_metrics err.source.sources=[SQL statement is not supported: desc system_metrics, keyword: system_metrics]
```

### How can we reproduce the bug?

cargo run -- standalone start

**Comment by killme2008** [comment]
https://docs.greptime.com/reference/sql/describe_table

It should be `DESCRIBE TABLE system_metrics`.

Looks like we don't support 'desc [table]` yet.

**Comment by killme2008** [comment]
`DESC TABLE system_metrics` works too.

**Comment by daheige** [comment]
This command is supported by the MySQL protocol. Since greptimedb supports the SQL protocol, it is recommended to support this command as much as possible to facilitate developers and maintenance personnel to view table information.


------------------ Original ------------------
From: dennis zhuang ***@***.***&gt;
Date: Tue,Jul 11,2023 10:37 PM
To: GreptimeTeam/greptimedb ***@***.***&gt;
Cc: heige ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GreptimeTeam/greptimedb] ERROR 1815 (HY000): Failed to executequery: desc system_metrics (Issue #1941)





 
https://docs.greptime.com/reference/sql/describe_table
 
It should be DESCRIBE TABLE system_metrics.
 
Looks like we don't support 'desc [table]` yet.

**Comment by waynexia** [comment]
Thanks for reporting this. I've submitted a patch to support it https://github.com/GreptimeTeam/greptimedb/pull/1944. Please check it out :heart:

**Comment by daheige** [comment]
ok


------------------ Original ------------------
From: Jim ***@***.***&gt;
Date: Wed,Jul 12,2023 11:36 AM
To: GreptimeTeam/greptimedb ***@***.***&gt;
Cc: heige ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [GreptimeTeam/greptimedb] ERROR 1815 (HY000): Failed to executequery: desc system_metrics (Issue #1941)





 
Thanks for reporting this. I've submitted a patch to support it #1944. Please check it out ❤️
