### ISSUE TITLE
[Build error] hostname not found

### ISSUE THREAD

**Issue by xtang** [GreptimeTeam/greptimedb#1963]
### What type of bug is this?

Other

### What subsystems are affected?

Frontend, Other

### What happened?

When initially trying to compile GreptimeDB from source on my new Arch Linux operating system, the process encountered a failure due to the inability to find the `hostname` command. Upon examining the source code at `servers/src/http/handler.rs:184`, it seems that the HTTP server would include the build machine's hostname in the status response via the `BUILD_HOSTNAME` variable, which would evaluate `hostname`. So after installing the inetutils package, the compilation was successful.

But I just wonder why the status response requires the build machine's hostname. Is this intentional or part of the design? or I miss something?

### What operating system did you use?

Arch Linux 6.3.9-arch1-1

### Relevant log output and stack trace

```bash
error: failed to run custom build command for `servers v0.3.2 (/home/khaos/Workspace/greptimedb/src/servers)`

Caused by:
  process didn't exit successfully: `/home/khaos/Workspace/greptimedb/target/release/build/servers-856be51d3a25adf5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=RUSTC_VERSION=rustc 1.71.0-nightly (a368898de 2023-05-02)

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "error executing 'hostname ': No such file or directory (os error 2)"', /home/khaos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/build-data-0.1.4/src/lib.rs:615:66
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```


### How can we reproduce the bug?

To build the source code when the hostname program is not installed before,

**Comment by MichaelScofield** [comment]
It's introcuded in #1789, showing host's name in `/status` endpoint. I think we can remove it.

**Comment by waynexia** [comment]
I also run into this error. It looks like `hostname` is not in the default bundle in Arch. This library doesn't provide a way to get around this (it just `.unwrap()` https://docs.rs/build-data/latest/src/build_data/lib.rs.html#614-616). +1 with removing it

**Comment by killme2008** [comment]
I think we can fork the `build-data` and fix this `unwrap`.

**Comment by sunray-ley** [comment]
I also think we can fork `build-data` to address this issue. My proposed solution is to optimize the `get_hostname()` function by using the cross-platform `hostname` crate to retrieve the hostname.
Furthermore, I am a newcomer to this project, and I would like to give this problem a try. :)

**Comment by etolbakov** [comment]
sorry, just found this issue, sure, I'll take a look shortly
