### ISSUE TITLE
Allocate id  for a new column in metasrv or procedure

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1969]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Now the alter request doesn't have a column id and each datanode needs to allocate an id for a new column individually. We should allocate column id in metasrv or procedure to ensure we could get a consistent column id.

**Comment by killme2008** [comment]
Looks like we don't need column id anymore after #2982.
I closed this issue currently. Please feel free to open it if you think it's necessary.
