### ISSUE TITLE
Make `TableRouteValue` manager a member of table metadata management family

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1986]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

In #1728 we refactor some table metadata values, made them read and write at their corresponding managers instead of operating the raw kv interfaces from `KvBackend`. However, there's one table metadata value left behind: the `TableRouteValue`. It's still using the old ways. Better create an "TableRouteManager" just like the others.

**Comment by WenyXu** [comment]
Currently, the `TableRouteValue`'s operations in the procedure aren't idempotent. We need to ensure the `TableRouteValue`'s operations in the procedure are idempotent.

https://github.com/GreptimeTeam/greptimedb/blob/1f371f5e6ef4537232777ee0ac6773e697445971/src/meta-srv/src/procedure/alter_table.rs#L179-L202

https://github.com/GreptimeTeam/greptimedb/blob/1f371f5e6ef4537232777ee0ac6773e697445971/src/meta-srv/src/procedure/drop_table.rs#L123-L132
