### ISSUE TITLE
aggregate_diff value sub

### ISSUE THREAD

**Issue by clickme-zxy** [GreptimeTeam/greptimedb#199]
when write aggregate diff, (https://numpy.org/doc/stable/reference/generated/numpy.diff.html)
the aggregate diff will sub  the two value and panic "attmpt to panic sub overflow"

the value we has is :i8、i6、i32 、i64
when come to i64， the aggregate will panic of overflow(since the largest value type is i64)

so implement the value sub so to avoid the panic

**Comment by tisonkun** [comment]
@MichaelScofield @clickme-zxy, could you provide a reproduction so that we can understand the issue more intuitively?

Said a SQL that encounters error while it should not be.

**Comment by MichaelScofield** [comment]
@tisonkun create another issue https://github.com/GreptimeTeam/greptimedb/issues/3385 for this.

**Comment by MichaelScofield** [comment]
Close as superceded by #3385
