### ISSUE TITLE
Memory usage control for various protocol handlers in Frontend

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#1995]
### What problem does the new feature solve?

Maybe OOM by large number of client requests; and responses from Datanode. It can be another type of flow control.

### What does the feature do?

1. investigate how client requests bytes are read in in each protocol handler server and design a memory usage metrics and management.
    - useful in datanode, too 
2. make flight get to datanode streaming (already tracked in #1718). memory metrics and control are needed here as well
3. revisit all potential memory leaks sites, including but not confine to: uncontrolled runtime spawns, unbounded channels and metrics (related: #1906).

**Comment by fengjiachun** [comment]
Can we close this now? @MichaelScofield

**Comment by MichaelScofield** [comment]
Close this issue because it seems vague now. We still need some kind of client control, but that can be raised again in another issue.
