### ISSUE TITLE
Procedure testing with failpoint

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#1996]
### What problem does the new feature solve?

Improve the robustness for DDL procedures

### What does the feature do?

Injects the failpoint and checks the behavior of procedure

**Comment by NiwakaDev** [comment]
You mean that something like:

```rust
CreateTableProcedure::new([step1, fail_step2, step3]) // we can inject failpoint via new method
```

?

**Comment by WenyXu** [comment]
> You mean that something like:
> 
> ```rust
> CreateTableProcedure::new([step1, fail_step2, step3]) // we can inject failpoint via new method
> ```
> 
> ?
Yep, we can utilize the fail-rs
https://github.com/tikv/fail-rs

**Comment by killme2008** [comment]
@WenyXu Please take a look at this issue.

**Comment by WenyXu** [comment]
> @WenyXu Please take a look at this issue.

I have yet to make a plan to inject the fail point. Specifically, for the region migration procedure, almost all errors can be covered with unit tests.

**Comment by tisonkun** [comment]
Then let's close this issue as won't do or invalid for now.

Once we find a concrete necessary or plan to introduce failpoints-based test, we can open a new issue for that.
