### ISSUE TITLE
Accept `influxdb` write request when corresponding table doesn't exist even if request doesn't have timestamp

### ISSUE THREAD

**Issue by NiwakaDev** [GreptimeTeam/greptimedb#1997]
### What problem does the new feature solve?

Right now we can execute the following command when a corresponding table exists.

However,  right now we couldn't execute it when a corresponding one doesn't exist:

```bash
curl -i -XPOST "http://localhost:4000/v1/influxdb/write?db=public&precision=ms" \
--data-binary \
'monitor,host=127.0.0.1 cpu=0.1,memory=0.4'
```

Accoording to [influxdb timestamp](https://docs.influxdata.com/influxdb/v2.7/reference/syntax/line-protocol/#timestamp), timestamp is just optional.

So, I think we need to support this feature. 

### What does the feature do?

No response

### Implementation challenges

No response

**Comment by NiwakaDev** [comment]
If we need to support this feature, I'd like to work on this issue.

**Comment by MichaelScofield** [comment]
Thx @NiwakaDev ! We can automatically create table from insertion data. Is it failed because we require timestamp column for the created table, and we can't deduce it from the influxdb line you mentioned above? If that's the case, I think we can automatically create it just for influxdb protocol

**Comment by NiwakaDev** [comment]
@killme2008  @MichaelScofield 

I guess that we don't have mockable time functions. So I'd like to add them for testing, like so:

```rust
trait TimeProvider {
  fn current_time() -> i64;
  //..
}

struct MockTimeProvider;

impl TimeProvider for MockTimeProvider {
  //..
}

let instance = FeInstance(..);
instance.set_time_provider(Arc::new(MockTimeProvider()))
```

inspired:
https://github.com/influxdata/influxdb_iox/blob/732ae81f0b5496bb0e70e4463f57c350adfbe52a/iox_time/src/lib.rs#L190-L219

**Comment by MichaelScofield** [comment]
@NiwakaDev can we use the `ColumnDefaultConstraint::Fuction(CURRENT_TIMESTAMP)`?

**Comment by killme2008** [comment]
Sorry, i don't get the point. I think we don't need a mock function at all.We can just polulate the missing timestamp columns with 

https://github.com/GreptimeTeam/greptimedb/blob/662879ff4b90687c79136bea1ce520e19b53ceff/src/common/time/src/timestamp.rs#L41

And cast it to the precision in the protocols.
