### ISSUE TITLE
Return an error in arrow array convert function

### ISSUE THREAD

**Issue by QuenKar** [GreptimeTeam/greptimedb#2010]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

`try_from_arrow_timestamp_array` and `try_from_arrow_time_array` have similar questions.
if datatype not match, we now just use `unreachable!()` to indicates the unreachable code. 

https://github.com/GreptimeTeam/greptimedb/blob/develop/src/datatypes/src/vectors/primitive.rs#L145-L147

We can use `CastTypeSnafu` to return a richer error message.

**Comment by killme2008** [comment]
Good catch! can you create a PR to fix it?

**Comment by QuenKar** [comment]
> Good catch! can you create a PR to fix it?

Ok, I will solve it.
