### ISSUE TITLE
tokio-postgres not support query parameter

### ISSUE THREAD

**Issue by xxaier** [GreptimeTeam/greptimedb#2017]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

Error: Error { kind: Parameters(2, 0), cause: None }
```
use async_lazy::Lazy;
use tokio_postgres::{types::ToSql, Client, Error, NoTls, Row, ToStatement};
static GT: Lazy<Client> = Lazy::const_new(|| {
  let pg_uri = std::env::var("GREP_URI").unwrap();
  Box::pin(async move {
    let (client, connection) = tokio_postgres::connect(&format!("postgres://{}", pg_uri), NoTls)
      .await
      .unwrap();
    tokio::spawn(async move {
      if let Err(e) = connection.await {
        eprintln!("postgres connection error: {e}");
      }
    });
    client
  })
});
// #[ctor]
// fn init() {
//   TRT.block_on(async move {
//     use std::future::IntoFuture;
//     PG.into_future().await;
//   });
// }
macro_rules! q {
  ($name:ident,$func:ident,$rt:ty) => {
    #[allow(non_snake_case)]
    pub async fn $name<T>(statement: &T, params: &[&(dyn ToSql + Sync)]) -> Result<$rt, Error>
    where
      T: ?Sized + ToStatement,
    {
      match GT.get().unwrap().$func(statement, params).await {
        Ok(r) => Ok(r),
        Err(err) => {
          if err.is_closed() {
            tracing::error!("{}", err);
            std::process::exit(1);
          }
          Err(err)
        }
      }
    }
  };
}
q!(G, query, Vec<Row>);
// q!(Q1, query_one, Row);
// q!(Q01, query_opt, Option<Row>);
#[tokio::main]
async fn main() -> Result<(), Error> {
  use std::future::IntoFuture;
  GT.into_future().await;
  let rows = G(
    "select uid,cid,rid,CAST(ts AS BIGINT) t FROM seen WHERE uid=$1 AND ts>$2 ORDER BY ts",
    &[&1i64, &2i64],
  )
  .await?;
  dbg!(&rows);
  let uid: i64 = rows[0].get(0);
  let cid: i8 = rows[0].get(1);
  let rid: i64 = rows[0].get(2);
  let ts: i64 = rows[0].get(3);
  dbg!(uid, cid, rid, ts);
  Ok(())
}
```

### What operating system did you use?

mac

### How can we reproduce the bug?

test code is here https://github.com/wacdev/testgrep

**Comment by xxaier** [comment]
table 定义如下
![image](https://github.com/GreptimeTeam/greptimedb/assets/130831741/aa5cd67d-8ae1-488d-8d00-84582ede90bd)

**Comment by killme2008** [comment]
@xxaier Thank u for your report, I'll look into it ASAP.

**Comment by waynexia** [comment]
The error is reported when the placeholder doesn't contains data type:

![image](https://github.com/GreptimeTeam/greptimedb/assets/15380403/89a30780-6036-4931-ba0d-c6e410fc9c76)

**Comment by sunng87** [comment]
This client expects server to inference parameter types, which is a postgres feature of its extended subprotocol. At the moment, greptimedb doesn't have parameter type inference. Let me revisit [my TODO here](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/servers/src/postgres/handler.rs#L261) to see if it's possible with recent logical plan refactoring.

As a workaround, you can use `query_simple` (the simple subprotocol) for now.

**Comment by sunng87** [comment]
I've created #2032 to address compatibility with tokio-postgres, as well as some other language driver like nodejs.
