### ISSUE TITLE
Refactor CatalogKey and SchemaKey

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2024]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

After https://github.com/GreptimeTeam/greptimedb/pull/1985, we refactored the table metadata. However, there are still some incompatible codes.

In the latest version, we replaced the separator `-` with `/`.
https://github.com/GreptimeTeam/greptimedb/blob/1f371f5e6ef4537232777ee0ac6773e697445971/src/common/meta/src/key.rs#L78-L83

However, there are still some old designs, and they will break the system.

https://github.com/GreptimeTeam/greptimedb/blob/1f371f5e6ef4537232777ee0ac6773e697445971/src/common/meta/src/helper.rs#L33-L44

https://github.com/GreptimeTeam/greptimedb/blob/5f65e3ff442e1efb31e15945cb7cafc00f30580c/src/common/meta/src/helper.rs#L113-L125

**Comment by WenyXu** [comment]
BTW, the `TableRouteKey` seems safe for now. However, I highly recommend refactoring it too. 

https://github.com/GreptimeTeam/greptimedb/blob/1f371f5e6ef4537232777ee0ac6773e697445971/src/common/meta/src/key/table_route.rs#L42-L59

**Comment by evenyag** [comment]
I also recommend validating catalog/schema/table names before creating them.
