### ISSUE TITLE
function: to_timezone(timestamp, timezone)

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2029]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

We need a function to cast a timestamp into other timezones such as:

```sql
SELECT to_timezone(1623167145000000, 'Europe/Berlin')
```

**Comment by parkma99** [comment]
Could it assign to me?

**Comment by waynexia** [comment]
Sure

**Comment by killme2008** [comment]
> Could you give more infomation about this issue?

Of course.

We want to write a UDF that converts a timestamp with a special timezone.
An example of a timestamp function can be found:

https://github.com/GreptimeTeam/greptimedb/blob/develop/src/common/function/src/scalars/timestamp/to_unixtime.rs

After you implement the function, remember to register it to the function registry:

https://github.com/GreptimeTeam/greptimedb/blob/662879ff4b90687c79136bea1ce520e19b53ceff/src/common/function/src/scalars/timestamp.rs#L25

And test it in sqlness too:
https://github.com/GreptimeTeam/greptimedb/tree/develop/tests/cases/standalone/common/function

**Comment by waynexia** [comment]
`to_timezone` in questdb: https://questdb.io/docs/reference/function/date-time/#to_timezone:

>Arguments:
>
>    - timestamp is any timestamp as Unix timestamp or string equivalent
>    - timezone may be Country/City tz database name, time zone abbreviation such as PST or in UTC offset in string format.
>
>Return value:
>
>Return value type is timestamp

**Comment by evenyag** [comment]
As mentioned in https://github.com/GreptimeTeam/greptimedb/pull/2039#discussion_r1508491202, we can restrict the input type to a timestamp (users can cast a string to a timestamp before using this function).

Then we can choose the time unit of the return type according to the input.
