### ISSUE TITLE
`PrimitiveVector` should as a logical data type

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#203]
`PrimitiveVector` contains a primitive array, but the logical data type of vector may differ from it's internal array, for example, `DateVector` is represented by a `Int32Vector`, but the logical type is `Date`.

In fact, arrow's [`PrimitveArray::new`](https://docs.rs/arrow2/0.10.1/arrow2/array/struct.PrimitiveArray.html#method.new) accepts a parameter to specify it's logical data type, so `PrimitiveVector` should also have a logical data type.

**Comment by waynexia** [comment]
I suggest changing the parameter `Primitive` of `PrimitiveVector` to `LogicalType` (or another naming). With a type parameter `PhysicalType`. Just like [this in arrow](https://docs.rs/arrow/latest/arrow/datatypes/trait.ArrowPrimitiveType.html) - `ArrowPrimitiveType` and type parameter `Native`.

**Comment by tisonkun** [comment]
```rust
pub struct PrimitiveVector<T: LogicalPrimitiveType> {
    array: PrimitiveArray<T::ArrowPrimitive>,
}
```

This is  implemented now? @v0y4g3r @waynexia

**Comment by evenyag** [comment]
This is related to the arrow2 crate, I guess we can close this issue now.

**Comment by tisonkun** [comment]
No longer relevant.
