### ISSUE TITLE
DEFAULT CURRENT TIMESTAMP should cast timestamp to target resolution

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2030]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

We can create a timestampmillisecond vector and cast it

https://github.com/GreptimeTeam/greptimedb/blob/9c1f0234de54d976ddaf5de426218293c6f687b8/src/datatypes/src/schema/constraint.rs#L161-L170

We could use `VectorOp::cast()` to do this.
https://github.com/GreptimeTeam/greptimedb/blob/9c1f0234de54d976ddaf5de426218293c6f687b8/src/datatypes/src/vectors/operations.rs#L63-L66

We might use `is_timestamp_compatible()` to check whether the type could be cast to a timestamp instead of using match.
https://github.com/GreptimeTeam/greptimedb/blob/9c1f0234de54d976ddaf5de426218293c6f687b8/src/datatypes/src/data_type.rs#L363-L365

### Implementation challenges

We should add some sqlness tests to cover this case.

**Comment by parkma99** [comment]
I would like to take it.
