### ISSUE TITLE
Supports TIMESTAMP_MS, TIMESTAMP_S and TIMESTAMP_NS types

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2072]
### What problem does the new feature solve?

They are just the alias for the timestamp types with different units.

Hope to run the following SQL:

```sql
SELECT DATE '1992-01-01'::TIMESTAMP_MS;
```

### What does the feature do?

Timestamp types alias with different units.

**Comment by waynexia** [comment]
what does `MS` mean? Millisecond or Microsecond

**Comment by killme2008** [comment]
> what does `MS` mean? Millisecond or Microsecond

Millisecond

**Comment by killme2008** [comment]
> Then how to express MicroSecond? Or we can define it as `TimestampMilli`, `TimestampMicro`, `TimestampSecond`, `TimestampMillisecond` (duplicate some for convenient)

These names look too long. Maybe we can use `timstamp_micros` for MicroSecond.

**Comment by Gump9** [comment]
I want to have a try,any example?which file should i change?

**Comment by waynexia** [comment]
Also support this grammar:
```sql
SELECT TIMESTAMP ‘2020-01-01 01:23:45.12345678’::TIMESTAMP(9);
Error: 3000(PlanQuery), This feature is not implemented: Unsupported SQL type Timestamp(Some(9), None)
```

**Comment by Gump9** [comment]
> Also support this grammar:
> 
> ```sql
> SELECT TIMESTAMP ‘2020-01-01 01:23:45.12345678’::TIMESTAMP(9);
> Error: 3000(PlanQuery), This feature is not implemented: Unsupported SQL type Timestamp(Some(9), None)
> ``` 
OK,give me some time please,a little busy lately😰

**Comment by killme2008** [comment]
@Gump9 hi, are you still working on this issue? We want to support these types in v0.4

**Comment by Gump9** [comment]
> @Gump9 hi, are you still working on this issue? We want to support these types in v0.4

Sorry, I must finished the school project in the past month, and I haven't had enough time to focus on this issue.🤕️I will try other issue soon,my bad
