### ISSUE TITLE
Can't parse timestamp with before christ date.

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2076]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Other

### What happened?

For example:

```sql
select '290309-12-22 (BC) 00:00:00'::timestamp;
```

### What operating system did you use?

Any OS

### How can we reproduce the bug?

Described as above.

**Comment by v0y4g3r** [comment]
We support `-100-01:01 00:00:00` to represent BC timestamps, but the overflow issue should be addressed first #2082

**Comment by killme2008** [comment]
Can we support this format `290309-12-22 (BC) 00:00:00`? Looks like PostgreSQL supporting it too.

**Comment by v0y4g3r** [comment]
> Can we support this format `290309-12-22 (BC) 00:00:00`? Looks like PostgreSQL supporting it too.

Tried in PostgreSQL, `yyyy-mm-dd (BC) HH:MM:SS` does work, but the [doc](https://www.postgresql.org/docs/15/datatype-datetime.html#DATATYPE-DATETIME-INPUT) does not guarantee this behavior:

> Valid input for the time stamp types consists of the concatenation of a date and a time, followed by an optional time zone, **followed** by an optional AD or BC. (Alternatively, AD/BC can appear before the time zone, but this is not the preferred ordering.) 

Also, the timestamp range in PostgreSQL is "4713 BC" to "294276 AD", thus `select '290309-12-22 (BC) 00:00:00'::timestamp` will actually fail:

<img width="639" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/6406592/f9a0aaa5-c222-493d-92d1-b3ff1f2517f7">
