### ISSUE TITLE
Retry in procedure should use the latest route table

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2101]
### What type of enhancement is this?

Other

### What does the enhancement do?

Currently the procedure will take a "snapshot" of the route table for the entire lifecycle. Once region failover occurs during a procedure, it will keep retrying on the outdated node. This can be improved by refreshing the `region id -> node id` part on each retry

**Comment by killme2008** [comment]
@MichaelScofield Please take a look at this issue.
