### ISSUE TITLE
gRPC inserting with incorrect affected row

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#2109]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### What happened?

using greptimedb-client-go to construct 10,000 rows records, but most of the tag, field and timestamp columns are the same, which means most of the rows won't be inserted into greptimedb, but the result tells that there are 10,000 rows affected.

## outputs
```
AffectedRows: 10000
```

## actual result in MySQL client
![image](https://github.com/GreptimeTeam/greptimedb/assets/4557527/d706db01-0b9e-42dc-bb8d-546ecf7dbed7)

### What operating system did you use?

Linux beelink 6.4.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 31 Jul 2023 11:41:04 +0000 x86_64 GNU/Linux

### How can we reproduce the bug?

```go
package main

import (
	"context"
	"fmt"
	"time"

	greptime "github.com/GreptimeTeam/greptimedb-client-go"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	options := []grpc.DialOption{
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	}
	cfg := greptime.NewCfg("127.0.0.1").
		WithPort(4001).
		WithDatabase("public").
		WithAuth("", "").
		WithDialOptions(options...).
		WithCallOptions()
	client, err := greptime.NewClient(cfg)
	if err != nil {
		panic("failed to init client")
	}

	series := greptime.Series{}
	series.AddTag("region", "az")
	series.AddTag("region1", "ap")
	series.AddTag("region2", "eu")
	series.AddStringTag("host", "localhost")
	series.AddStringTag("host1", "localhost1")
	series.AddStringTag("host2", "localhost2")
	series.AddFloatField("cpu", 0.90)
	series.AddFloatField("cpu1", 0.91)
	series.AddFloatField("cpu2", 0.92)
	series.AddField("memory", 10240)
	series.AddField("memory1", 10241)
	series.AddField("memory2", 10242)

	metric := greptime.Metric{}
	for i := 0; i < 10000; i++ {
		series.SetTimestamp(time.Now())
		metric.AddSeries(series)
	}

	req := greptime.InsertRequest{}
	req.WithTable("monitor").WithMetric(metric)

	reqs := greptime.InsertsRequest{}
	reqs.Append(req)

	resp, err := client.Insert(context.Background(), reqs)
	if err != nil {
		fmt.Printf("fail to insert, err: %+v\n", err)
		return
	}
	fmt.Printf("AffectedRows: %d\n", resp.GetAffectedRows().GetValue())
}
```

**Comment by waynexia** [comment]
One possible reason is duplicated rows. Our DB will automatically remove duplication (iff time index + primary key are the same) on read.

**Comment by yuanbohan** [comment]
> One possible reason is duplicated rows. Our DB will automatically remove duplication (iff time index + primary key are the same) on read.

And yes, but the affected rows in response SHOULD NOT be 10,000, it SHOULD BE the actual affected number of rows

**Comment by waynexia** [comment]
This is a good point... But I can explain why it's 10000 in two aspects
- The 10000 inserted rows are treated as 10000 independent data, and those duplicates can be seen as "update" to the previous one
- The dedup process is done on reading. Those 10000 rows are persisted to file in actual.

**Comment by evenyag** [comment]
It's not recommended to rely on the value of affected rows. Sometimes it's hard to get the correct affected rows (e.g. DELETE). We return it because some SQL protocols need this.

In your case, rows with the same key are actually inserted twice and the row being overwritten is also "affected". Since our `INSERT` operation is actually a `PUT` operation in some NoSQL dbs.

To see whether an insert request is executed successfully, checking the response code is enough.

**Comment by yuanbohan** [comment]
This is not a bug, but a workaround solution, and DO NOT rely on the affected row.
