### ISSUE TITLE
Frontend should check table exists before creating a table

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2128]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend, Meta

### What happened?

Runs a 3-node datanode cluster.

Firstly, Creates a 3-region table, it should be ok.
```sql
 CREATE TABLE if not exists my_table6 (
        i INT PRIMARY KEY,
        ts TIMESTAMP(9) TIME INDEX,
    ) PARTITION BY RANGE COLUMNS (i) (PARTITION r0 VALUES LESS THAN (715827882), PARTITION r1 VALUES LESS THAN (1431655764), PARTITION r2 VALUES LESS THAN (MAXVALUE),);
```

And rerun the above, then you will get an error:
```
"Error: 1003(Internal), status: Internal, message: \"Failed to request Datanode, expected: 3, but only 0 available\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Wed, 09 Aug 2023 02:52:49 GMT\", \"content-length\": \"0\"} }"`
```

This is because the creating table will run into the `selector` method before checking whether the table exists. Currently, the datanode can't have multiple regions of one table.

### What operating system did you use?

ubuntu 23.04

### How can we reproduce the bug?

Runs a 3-node datanode cluster.

Firstly, Creates a 3-region table, it should be ok.
```sql
 CREATE TABLE if not exists my_table6 (
        i INT PRIMARY KEY,
        ts TIMESTAMP(9) TIME INDEX,
    ) PARTITION BY RANGE COLUMNS (i) (PARTITION r0 VALUES LESS THAN (715827882), PARTITION r1 VALUES LESS THAN (1431655764), PARTITION r2 VALUES LESS THAN (MAXVALUE),);
```

And rerun the above, then you will get an error:
```
"Error: 1003(Internal), status: Internal, message: \"Failed to request Datanode, expected: 3, but only 0 available\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Wed, 09 Aug 2023 02:52:49 GMT\", \"content-length\": \"0\"} }"`
```

**Comment by NiwakaDev** [comment]
I'd like to address this issue, but I don't know how to reproduce a test for this issue.

I tried to reproduce this issue, like so:

```rust
    #[tokio::test(flavor = "multi_thread")]
    async fn test_distributed_insert_delete_and_query() {
        common_telemetry::init_default_ut_logging();

        let instance =
            tests::create_distributed_instance("test_distributed_insert_delete_and_query").await;
        let frontend = instance.frontend();
        let frontend = frontend.as_ref();

        let table_name = "my_dist_table";
        let sql = format!(
            r"
CREATE TABLE {table_name} (
    a INT,
    b STRING PRIMARY KEY,
    ts TIMESTAMP,
    TIME INDEX (ts)
) PARTITION BY RANGE COLUMNS(a) (
    PARTITION r0 VALUES LESS THAN (10),
    PARTITION r1 VALUES LESS THAN (20),
    PARTITION r2 VALUES LESS THAN (50),
    PARTITION r3 VALUES LESS THAN (MAXVALUE),
)"
        );
        create_table(frontend, sql).await;
        let sql = format!(
            r"
CREATE TABLE if not exists {table_name} (
    a INT,
    b STRING PRIMARY KEY,
    ts TIMESTAMP,
    TIME INDEX (ts)
) PARTITION BY RANGE COLUMNS(a) (
    PARTITION r0 VALUES LESS THAN (10),
    PARTITION r1 VALUES LESS THAN (20),
    PARTITION r2 VALUES LESS THAN (50),
    PARTITION r3 VALUES LESS THAN (MAXVALUE),
)"
        );
        create_table(frontend, sql).await;

    //
```

And then I executed `cargo nextest run test_distributed_insert_delete_and_query`
But, the above test seems to pass.

**Comment by WenyXu** [comment]
How about having a try with [gtctl](https://github.com/greptimeTeam/gtctl)

**Comment by NiwakaDev** [comment]
> How about having a try with [gtctl](https://github.com/greptimeTeam/gtctl)

I tried it and playground in greptimecloud, but create table was successfully created. (playground in greptimecloud has 3 regions.) Am I missing something?

## Reproduction

```sql
CREATE TABLE test_table (
    a INT PRIMARY KEY,
    ts TIMESTAMP TIME INDEX
) PARTITION BY RANGE COLUMNS(a) (
    PARTITION r0 VALUES LESS THAN (10),
    PARTITION r1 VALUES LESS THAN (20),
    PARTITION r2 VALUES LESS THAN (MAXVALUE),
);
```
Then

```sql
CREATE TABLE if not exists test_table (
    a INT PRIMARY KEY,
    ts TIMESTAMP TIME INDEX
) PARTITION BY RANGE COLUMNS(a) (
    PARTITION r0 VALUES LESS THAN (10),
    PARTITION r1 VALUES LESS THAN (20),
    PARTITION r2 VALUES LESS THAN (MAXVALUE),
);
```

## Link 
https://greptime.com/product/cloud

**Comment by WenyXu** [comment]
> 



> > How about having a try with [gtctl](https://github.com/greptimeTeam/gtctl)
> 
> I tried it and playground in greptimecloud, but create table was successfully created. (playground in greptimecloud has 3 regions.) Am I missing something?
> 
> ## Reproduction
> ```sql
> CREATE TABLE test_table (
>     a INT PRIMARY KEY,
>     ts TIMESTAMP TIME INDEX
> ) PARTITION BY RANGE COLUMNS(a) (
>     PARTITION r0 VALUES LESS THAN (10),
>     PARTITION r1 VALUES LESS THAN (20),
>     PARTITION r2 VALUES LESS THAN (MAXVALUE),
> );
> ```
> 
> Then
> 
> ```sql
> CREATE TABLE if not exists test_table (
>     a INT PRIMARY KEY,
>     ts TIMESTAMP TIME INDEX
> ) PARTITION BY RANGE COLUMNS(a) (
>     PARTITION r0 VALUES LESS THAN (10),
>     PARTITION r1 VALUES LESS THAN (20),
>     PARTITION r2 VALUES LESS THAN (MAXVALUE),
> );
> ```
> 
> ## Link
> https://greptime.com/product/cloud

Hi @NiwakaDev , Thank you for your report. The cloud service may not use the latest version. I'll double-check it later.

**Comment by MichaelScofield** [comment]
Verified, it's gone in v0.4
