### ISSUE TITLE
Using SecretString to store senstive values in `copy` stmt

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2144]
### What problem does the new feature solve?

`copy` stmt can carry senstive data like S3 API key or secret. This makes leaking easily.

### What does the feature do?

Right now the senstive values are all stored in plain strings, and we have to write special redacting codes for printing them. It's better we use [`SecretString`](https://docs.rs/secrecy/latest/secrecy/type.SecretString.html) for them.

A follow up of https://github.com/GreptimeTeam/greptimedb/pull/3744. 

### Implementation challenges

**Comment by tisonkun** [comment]
Current code -

* https://github.com/GreptimeTeam/greptimedb/pull/2141
* https://github.com/GreptimeTeam/greptimedb/pull/3080

A thoroughly solution should be, supporting reconstruct query from statements, and redact options of copy stmt on demand.

See:

```rust
match self.query_statement(stmt, query_ctx.clone()).await {
    Ok(output) => {
        let output_result =
            query_interceptor.post_execute(output, query_ctx.clone());
        results.push(output_result);
    }
    Err(e) => {
        let redacted = sql::util::redact_sql_secrets(query.as_ref());
        error!(e; "Failed to execute query: {redacted}");

        results.push(Err(e));
        break;
    }
}
```

We currently print all the query if any of the statement failed to execute.

**Comment by MichaelScofield** [comment]
We can make the sensetive data stored in their own fields, rather then the `OptionMap`.

**Comment by tisonkun** [comment]
Then the code to access an option value is somehow awkward. If we insist in trying `SecretString`, I may suggest:

```rust
pub struct OptionMap {
    map: HashMap<String, String>,
    secrets: HashMap<String, String>,
}
```

And do the merge read within the encapsulation of `OptionMap`.

**Comment by MichaelScofield** [comment]
I'm ok with moving all the senstive data to a "secrets" map like that.
