### ISSUE TITLE
Why is querying millions of inserted data slower than MySQL?

### ISSUE THREAD

**Issue by tx991020** [GreptimeTeam/greptimedb#2151]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Why is querying millions of inserted data slower than MySQL?

**Comment by MichaelScofield** [comment]
@tx991020 can you provide more detailed infomation about your benchmark testing setup?

**Comment by tx991020** [comment]
translates to The format is as follows
"1","1208026841","477458502","FKlJh","2023-08-05 08:56:00","pSvqg","gQWxL","JikNj","972076018","348948709","1","GMZHG","XzNXZ","QHfSD","0","ejliy"

6 million records
Comparison between standalone MySQL and standalone GrepTime: In terms of a count query with a non-indexed field, GrepTime is several seconds slower than MySQL in execution.

**Comment by tx991020** [comment]
MySQL takes 6 seconds, while GrepTime seems to take 11 seconds

**Comment by MichaelScofield** [comment]
Thx! Can you share the create table sql as well? If there are senstive data, it's ok to change the columns names. We'd like to do the same benchmark to investigate more

**Comment by tx991020** [comment]
CREATE TABLE IF NOT EXISTS xxxx (
  a BIGINT NULL,
  b BIGINT NULL,
  c TIMESTAMP(3) NOT NULL DEFAULT current_timestamp(),
  d TIMESTAMP(3) NULL DEFAULT current_timestamp(),
  e STRING NULL DEFAULT '',
  f INT NULL,
  g INT NULL,
  h INT NULL,
  i STRING NULL,
  j STRING NULL,
  k STRING NULL,
  l STRING NULL,
  m STRING NULL,
  n STRING NULL,
  o INT NULL,
  p INT NULL,
  q INT NULL,
  r STRING NULL,
  s STRING NULL,
  t STRING NULL,
  u STRING NULL,
  v STRING NULL,
  w STRING NULL,
  x TINYINT NULL DEFAULT 0,
  y INT NULL,
  z STRING NULL,
  aa STRING NULL,
  ab TINYINT NULL DEFAULT 0,
  ac TINYINT NULL DEFAULT 0,
  TIME INDEX (c),
  PRIMARY KEY (a)
)
ENGINE=mito
WITH(
  regions = 1
);

**Comment by MichaelScofield** [comment]
@tx991020 can you share the queries for benchmarking, too?

**Comment by tx991020** [comment]
slect count(*) from xxx;   slelect e from xxx  where xx

**Comment by MichaelScofield** [comment]
thx, we'll investigate the query performance asap

**Comment by MichaelScofield** [comment]
@tx991020 we are currently have some issues related to scan, dragging down our overall query performance. It's planned to be optimized soon, stay tuned!
