### ISSUE TITLE
PromQL error

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#2154]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend, Datanode

### What happened?

I tried some PromQL expressions of [node-exporter dashboard](https://grafana.com/grafana/dashboards/1860-node-exporter-full), but failed to query expected results for some expressions.

- [ ] `avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu))`

```
Error: No field named cpu. Valid fields are node_load5.greptime_timestamp, "AVG(node_load5.greptime_value)".
```

- [ ] `node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes`

```
No field named node_memory_swapfree_bytes.instance. Valid fields are "node_memory_SwapTotal_bytes".instance, "node_memory_SwapTotal_bytes".job, "node_memory_SwapTotal_bytes".greptime_timestamp, "node_memory_SwapTotal_bytes".greptime_value, "node_memory_SwapFree_bytes".instance, "node_memory_SwapFree_bytes".job, "node_memory_SwapFree_bytes".greptime_timestamp, "node_memory_SwapFree_bytes".greptime_value.
```

### What operating system did you use?

Linux beelink 6.4.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 31 Jul 2023 11:41:04 +0000 x86_64 GNU/Linux

### How can we reproduce the bug?

- use GreptimeCloud preview, and exec `docker run --rm -e GREPTIME_URL='' -e GREPTIME_USERNAME='' -e GREPTIME_PASSWORD='' --name greptime-node-exporter greptime/node-exporter` from quick start without prometheus
- directly exec the expressions above

**Comment by waynexia** [comment]
I've verified this is fixed on the current latest HEAD, the corresponding PR should be https://github.com/GreptimeTeam/greptimedb/pull/2297
