### ISSUE TITLE
Create columns with tag semantic type

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2183]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

If the users write data by influxdb, opentsdb or Prometheus remote write, GreptimeDB will auto-create the table with the correct semantic types:

* `SemanticType::Tag` for tags(or labels in Prometheus)
* `SematicType::Field` for fields(or values)
* `SematicType::Timestamp` for time index column

But when using SQL to create table, it doesn't provide a way to create columns with `tag` semantic type,all the columns not in the primary key except time index are `field` semantic type.

I think we can provide a SQL extension to create tables with tag columns, for example:

```
CREATE TABLE IF NOT EXISTS system_metrics (
    host STRING TAG,
    idc STRING TAG,
    cpu_util DOUBLE,
    memory_util DOUBLE,
    disk_util DOUBLE,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIME INDEX(ts)
);
```

It's the same as:

```sql
CREATE TABLE IF NOT EXISTS system_metrics (
    host STRING,
    idc STRING,
    cpu_util DOUBLE,
    memory_util DOUBLE,
    disk_util DOUBLE,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key(host, idc),
    TIME INDEX(ts)
);
```

Then the `host` and `idc` will be created with `tag` semantics. The columns except time index without `TAG` option will be created with `field` semantics.

### Implementation challenges

* Make the column option parser to support `tag` option.
* Pass the `tag` semantic type to create table request.

**Comment by NiwakaDev** [comment]
I'd like to work on this issue, but do I need to wait until `migrate-region-server` is merged?

**Comment by MichaelScofield** [comment]
@NiwakaDev You can checkout a branch from `migrate-region-server` and implement the feature on top of it. We will finally make the `migrate-region-server` branch the new "develop" branch.

**Comment by killme2008** [comment]
Thank you. But we don't want this feature yet. It needs more discussion. 
The `primary key` constraint looks good enough to represent the columns in tag semantics and it contains the columns ordering info. 
Not sure if we need a new syntax for it. As you know, less is more.

**Comment by NiwakaDev** [comment]
Until this discussion land, I think that we can add a section about relationship between primary keys and tags in the document so that user can easily understand:
https://github.com/GreptimeTeam/docs/issues/452

**Comment by killme2008** [comment]
> Until this discussion land, I think that we can add a section about relationship between primary keys and tags in the document so that user can easily understand: [GreptimeTeam/docs#452](https://github.com/GreptimeTeam/docs/issues/452)

Can't agree more with it, thank u.
