### ISSUE TITLE
Implement `KvBackend` for `RaftEngineLogStore`

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#2215]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

To unify all catalogs including `LocalCatalogManager`/`FrontendCatalogManager`.

**Comment by tisonkun** [comment]
Should be resolved by https://github.com/GreptimeTeam/greptimedb/pull/2280.
