### ISSUE TITLE
Faile to find partition column: n

### ISSUE THREAD

**Issue by DevilExileSu** [GreptimeTeam/greptimedb#2216]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

`commit: c5f507c20e69b28dd2291c2e5649d05fe4fe67cb`

Distributed mode.

In the case where the table doesn't have a primary key set, I successfully created a partitioned table. However, after I inserted data, when I tried to delete the existing data from the table based on the partition key, I encountered an error: Failed to find partition column: n. Similarly, if I set a primary key but the partition key is not the primary key, I get the same error. 

![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/a0a31399-6077-4472-bed9-9d8ce9fb9b42)
![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/cd5f5a17-f5b6-43f4-aff3-cf89ec1ca9c2)
![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/01987b96-f093-48b7-bda3-07c176c9e659)

The issue arises from the fact that after performing a scan, only data from the `primary key` and `ts` column are returned, and the partition column is not returned. 

https://github.com/GreptimeTeam/greptimedb/blob/c5f507c20e69b28dd2291c2e5649d05fe4fe67cb/src/query/src/datafusion.rs#L153-L175

As a result, during the `split_delete()` process, the corresponding data cannot be found.
https://github.com/GreptimeTeam/greptimedb/blob/c5f507c20e69b28dd2291c2e5649d05fe4fe67cb/src/partition/src/splitter.rs#L96-L103

Maybe we need to return the partition column data in the scan.

### What operating system did you use?

6.1.41-1-MANJARO

### How can we reproduce the bug?

```sql
CREATE TABLE dist_table(
    ts TIMESTAMP DEFAULT current_timestamp(),
    n INT,
    row_id INT,
    TIME INDEX (ts)
)
PARTITION BY RANGE COLUMNS (n) (
    PARTITION r0 VALUES LESS THAN (5),
    PARTITION r1 VALUES LESS THAN (9),
    PARTITION r2 VALUES LESS THAN (MAXVALUE),
)
engine=mito;

INSERT INTO dist_table(n, row_id) VALUES (1, 1);
INSERT INTO dist_table(n, row_id) VALUES (2, 2);
INSERT INTO dist_table(n, row_id) VALUES (3, 3);
INSERT INTO dist_table(n, row_id) VALUES (4, 4);
INSERT INTO dist_table(n, row_id) VALUES (5, 5);

delete from dist_table where n in (1, 2);
```

**Comment by MichaelScofield** [comment]
Now partition columns have to be primary keys, this issue can be resolved. See my test:

![image](https://github.com/GreptimeTeam/greptimedb/assets/990479/61ebe3aa-c444-4e0e-ad28-dca1278c72d0)
