### ISSUE TITLE
Simultaneously inserting multiple records into a distributed table without a primary key.

### ISSUE THREAD

**Issue by DevilExileSu** [GreptimeTeam/greptimedb#2217]
### What type of bug is this?

Data corruption, Incorrect result

### What subsystems are affected?

Frontend

### What happened?

`commit: c5f507c20e69b28dd2291c2e5649d05fe4fe67cb`

Using `INSERT INTO dist_table(n, row_id) VALUES (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12);` to simultaneously insert multiple records into a partitioned table without a primary key, under the condition of not crossing partitions, only the last data will be retained. If it's across multiple partitions, each partition will retain only the last data. 

![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/f60b47df-de8a-4ec1-92d0-3ced7d199dec)

And the timestamps for each individual data record are not consistent.

When performing the same operation on a single table without a primary key, the results are inconsistent with the previous case.

![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/126951b5-9361-42fd-8631-3418f4d853e7)

I think the results for both the single table and the partitioned table should be consistent.

### What operating system did you use?

6.1.41-1-MANJARO

### How can we reproduce the bug?

```sql
CREATE TABLE dist_table(
    ts TIMESTAMP DEFAULT current_timestamp(),
    n INT,
    row_id INT,
    TIME INDEX (ts)
)
PARTITION BY RANGE COLUMNS (n) (
    PARTITION r0 VALUES LESS THAN (5),
    PARTITION r1 VALUES LESS THAN (9),
    PARTITION r2 VALUES LESS THAN (MAXVALUE),
)
engine=mito;

INSERT INTO dist_table(n, row_id) VALUES (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12);
```

**Comment by DevilExileSu** [comment]
If a partitioned table with a primary key is used, where the primary key and partition key do not intersect, inserting the same primary key data into different partitions will still encounter the aforementioned issue.
![image](https://github.com/GreptimeTeam/greptimedb/assets/39342795/989869df-94df-410e-a7dc-4455a1c9a622)

I think that during the [split_insert()](https://github.com/GreptimeTeam/greptimedb/blob/9352649f22b558bf7c44f25a41b301271ea045e5/src/partition/src/splitter.rs#L46) process, the data with the same primary key should be merged, retaining the last input data, rather than handling this in the `dn`. This approach could help resolve this issue

**Comment by killme2008** [comment]
In fact, the time index column will be added to the primary key implicitly.  So if you don't create the primary key, then the time index column is the actual primary key. And the data with the same timestamp will be overwritten. (The last one wins as you see).

But in distributed mode, if the partition key is not the same as the primary key, then the primary key will be regional, not global. If you want to keep the global primary key constraint, you must ensure the portion key is the same as the primary key(Both of the columns and column orders).

I think this behaviour is acceptable, and the distributed mode can't be consistent with the standalone mode.

We need some docs to describe the primary key and partition key in detail. @nicecui

**Comment by DevilExileSu** [comment]
> But in distributed mode, if the partition key is not the same as the primary key, then the primary key will be regional, not global. If you want to keep the global primary key constraint, you must ensure the portion key is the same as the primary key(Both of the columns and column orders).
> 
> I think this behaviour is acceptable, and the distributed mode can't be consistent with the standalone mode.

Thank you for your answers, I understand! 

There is still an issue regarding when to insert the default value of the time index. Should it be inserted in the `fe` or in the `dn`? Inserting it in the dn can lead to different timestamps when inserting multiple data records simultaneously.

> We need some docs to describe the primary key and partition key in detail. @nicecui

I also suggest modifying the [example](https://docs.greptime.com/user-guide/cluster) in the docs.
