### ISSUE TITLE
feat: enable the github action bot to read and execute commands from comments

### ISSUE THREAD

**Issue by niebayes** [GreptimeTeam/greptimedb#2221]
### What problem does the new feature solve?

Occasionally, the Continuous Integration (CI) process might become stuck, displaying a "waiting for status to be reported" message. In such scenarios, the only option is to trigger CI again by submitting a new commit which may be an empty commit though. Certain open-source projects, like Apache Doris, have implemented a GitHub Action bot specifically for this purpose. It allows users to manually initiate CI and benchmarking by issuing commands through GitHub comments.

### What does the feature do?

Enable the github action bot to read and execute commands from github comments.

**Comment by LYZJU2019** [comment]
May I give it a try?

**Comment by niebayes** [comment]
@LYZJU2019   Not sure if this is still a required feature. You can directly @ the project maintainers.

**Comment by evenyag** [comment]
> Occasionally, the Continuous Integration (CI) process might become stuck, displaying a "waiting for status to be reported" message.

@LYZJU2019 We already addressed this problem, so we don't need a bot to trigger CI now. I'll close this issue, and you can find other issues that you are interested in.
