### ISSUE TITLE
bug: save unused options

### ISSUE THREAD

**Issue by NiwakaDev** [GreptimeTeam/greptimedb#2240]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

Right now, It seems like `greptimedb` accept unused options when creating external tables.

### What operating system did you use?

Maybe Any OS

### How can we reproduce the bug?

First, create an external table:
```sql
CREATE EXTERNAL TABLE foo with (location='~.csv',format='csv', hello='world');
```

Then, execute the following command:
```sql
SHOW CREATE TABLE foo;
```

Will show:
```
~
ENGINE=file
WITH(
  format = 'csv',  
  hello = 'world',  // This is an unused option.
  location = '~.csv'
) |

~
```

**Comment by killme2008** [comment]
Good catch! Can you help us to fix it?

**Comment by NiwakaDev** [comment]
Yes!
