### ISSUE TITLE
can't use s3 in contabo.com https://contabo.com/en/object-storage/

### ISSUE THREAD

**Issue by xxaier** [GreptimeTeam/greptimedb#2288]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### What happened?

![image](https://github.com/GreptimeTeam/greptimedb/assets/130831741/31470651-efea-49e8-aa54-bcc509bc0c7e)

### What operating system did you use?

ubuntu

### How can we reproduce the bug?

see this in slack
![image](https://github.com/GreptimeTeam/greptimedb/assets/130831741/1218552d-157a-4060-85bf-3c413074a05b)

**Comment by killme2008** [comment]
@xxaier We will fix it in v0.4, it will be released next week.
Thanks for your report.

**Comment by killme2008** [comment]
Fixed in #2308  and will be released in v0.4
