### ISSUE TITLE
Type conversion bypassed when inserting rows with both literals and functions

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#2302]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend, Datanode

### What happened?

When inserting rows using SQL, if the SQL `values` part contains only literal values, these literal values, like strings, will be parsed to column data type using `parse_string_to_value` which contains some customized logic to accomodate more formats.

But if the SQL contains both literals and function, like:
```sql
insert into naluduo0 (d,dt,t0,t3,t6,t9) values (now(),'2023-01-01 00:00:00',now(),now(),now(),now());
```

In order to get the results of the functions, this SQL is first evaluated by datafusion query engine. datafusion then tries to cast string literals to column data types, which may fail because of some formats datafusion does not support, and `parse_string_to_value` is bypassed.

### What operating system did you use?

NA

### How can we reproduce the bug?

```sql
create table naluduo1 (ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIME INDEX, dt datetime);
insert into naluduo1 (dt) values ('2023-01-01 00:00:00');
-- ok

create table naluduo0
          (
              ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIME INDEX,
              d date,
              dt datetime,
              t0 timestamp(0),
              t3 timestamp(3),
              t6 timestamp(6),
              t9 timestamp(9),
          );
insert into naluduo0 (d,dt,t0,t3,t6,t9) values (now(),'2023-01-01 00:00:00',now(),now(),now(),now());
-- failed with "Cast error: Cannot cast string to Date64"
```

**Comment by killme2008** [comment]
We already support this feature.

```sql
mysql> create table naluduo0
    ->           (
    ->               ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP TIME INDEX,
    ->               d date,
    ->               dt datetime,
    ->               t0 timestamp(0),
    ->               t3 timestamp(3),
    ->               t6 timestamp(6),
    ->               t9 timestamp(9),
    ->           );
Query OK, 0 rows affected (0.02 sec)

mysql> insert into naluduo0 (d,dt,t0,t3,t6,t9) values (now(),'2023-01-01 00:00:00',now(),now(),now(),now());
Query OK, 1 row affected (0.03 sec)
```
