### ISSUE TITLE
Incorrect result after adding filter to SQL query

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#2321]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

Not sure if this is related to #2320 , but we experienced similar incorrect result on SQL API as well.

![image](https://github.com/GreptimeTeam/greptimedb/assets/221942/354418e6-83cd-448f-962f-914c8053296f)

![image](https://github.com/GreptimeTeam/greptimedb/assets/221942/57a970b0-16c1-4645-8da7-30e5ea6fd5ce)

The data returned from second query should include those from the first one and shares same time range and order. 

### What operating system did you use?

any

### How can we reproduce the bug?

1. Ingest data with vector
2. Execute the SQL query to see if it happens

**Comment by killme2008** [comment]
Looks like the second result was right. It included `system` and other mode.s

**Comment by waynexia** [comment]
Some data from 11:00 and 14:00 is missed in the first result. I'm investigating this

**Comment by killme2008** [comment]
> Some data from 11:00 and 14:00 is missed in the first result. I'm investigating this

It's a severe issue, we should take it as a high-priority task.
