### ISSUE TITLE
[Testing] Using Etcd KvStore in testing GreptimeDB cluster in github action

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2357]
### What type of enhancement is this?

Other

### What does the enhancement do?

Currently we are using `MemStore` in testing GreptimeDB cluster. It's best we can test against real Etcd.

However, setup a clean Etcd server in developer's environment is tedious everytime we do it when we run tests locally. Why not do it in github action?

### Implementation challenges

Install a real Etcd server in github action is easy. The hard part is how the testing codes aware that they should run against an Etcd KvStore. Luckily, this can be done by action yaml's env. An example can be found at `object_store_test.rs`. Like this:

1. Adds `ETCD_ADDR: "127.0.0.1:2379"` in the test steps in `develop.yml`;
2. In `GreptimeDbCluster`, 
  ```rust
    let kv_store = if let Ok(etcd_addr) = env::var(ETCD_ADDR) {
      EtcdStore::with_endpoints(etcd_addr).unwrap()
    } else {
      Arc::new(MemStore::default())
    }
  ```
3. Clean the data in Etcd, so we can get an clean start for next test case. It can be done when dropping `GreptimeDbCluster`.

**Comment by WenyXu** [comment]
The main challenge is that the tests are run in parallel. Consider wrapping the `EtcdStore` with a unique prefix for each test.

**Comment by tisonkun** [comment]
It seems that after https://github.com/GreptimeTeam/greptimedb/pull/2448 `test-integration` doesn't run anymore. Shall we bring it back first? Or I omit somewhere we do the test.

**Comment by MichaelScofield** [comment]
@tisonkun It seems the `tests-integration` does run, see a recent github ci screenshot:
![image](https://github.com/GreptimeTeam/greptimedb/assets/990479/4c4c729e-665a-4717-86c0-b0e12c574d69)
https://github.com/GreptimeTeam/greptimedb/actions/runs/6812357466/job/18524527569

**Comment by tisonkun** [comment]
@MichaelScofield Thank you! Perhaps we can improve the CI job/step name. I'll try to do it if I can work a solution for this issue alongside. Or if anyone would like to improve it alone.

**Comment by MichaelScofield** [comment]
@tisonkun feel free to improve the step name to a more appropriate one!
