### ISSUE TITLE
Rename columns

### ISSUE THREAD

**Issue by NiwakaDev** [GreptimeTeam/greptimedb#2362]
### What problem does the new feature solve?

Rename columns

### What does the feature do?

It seems like there isn't the following feature in the document.

```sql
alter table test_table rename column old_column to new_column
```

Maybe `greptimedb` already has something like the above? I'd like to use this feature.

## Link
https://docs.greptime.com/reference/sql/alter

**Comment by MichaelScofield** [comment]
Unfortunately, this feature is not implemented yet. Though it's been tracked in #996

**Comment by MichaelScofield** [comment]
close as duplicated
