### ISSUE TITLE
Invalidate keys cache using an atomic operation

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2369]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

Now, we invalidate keys in multiple operations. It's better to invalidate keys in an atomic operation.
```rust
        let key = TableInfoKey::new(table_id);
        self.backend_cache_invalidator
            .invalidate_key(&key.as_raw_key())
            .await;
        debug!(
            "invalidated cache key: {}",
            String::from_utf8_lossy(&key.as_raw_key())
        );

        let key = &TableRouteKey { table_id };
        self.backend_cache_invalidator
            .invalidate_key(&key.as_raw_key())
            .await;
        debug!(
            "invalidated cache key: {}",
            String::from_utf8_lossy(&key.as_raw_key())
        );

        Ok(())
```

There are many ways to do this, e.g., 
- `invalidate_keys(vec![key1,key2]);`
- `invalidate_with(|kv_guard| kv_guard.remove(key1); kv_guard.remove(key2));`
-  `let txn = invalidator::txn() txn...`

**Comment by WenyXu** [comment]
> hi @WenyXu I want to try this issue. I think I'd like to go with the 2nd suggestion. `invalidate_with(|kv_guard| kv_guard.remove(key1); kv_guard.remove(key2));` This syntax looks more natural and easier to understand.

Thanks😃

**Comment by killme2008** [comment]
@WenyXu I am not sure if this issue is fixed, could you check it?
