### ISSUE TITLE
Adds cast function to DataType/ConcreteDataType

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2376]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

We need a function to cast a `Value` into the specific data type just like:

```rust
let  n= Value::Int64(1694589525);

// cast int64 into TimestampSecondType
let ts = ConcreteDataType::Timestamp(TimestampType::TimestampSecondType).cast(n).unwrap();
```

The signature of `cast` may be:

```
fn cast(value: Value) -> Option<Value>;
```

If the value can't be cast into the datatype, return `None`.

**Comment by QuenKar** [comment]
I will add cast function.
