### ISSUE TITLE
[Testing] some test cases in test-integration are failed

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2386]
### What type of enhancement is this?

Other

### What does the enhancement do?

The failed tests are:

Summary [  12.542s] 1775 tests run: 1737 passed, 38 failed, 11 skipped

- [x] tests-integration grpc::test::test_distributed_insert_delete_and_query
- [x] tests-integration grpc::test::test_standalone_insert_and_query
- [ ] tests-integration tests::instance_test::test_execute_external_create::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_external_create::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_external_create_without_ts_type::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_external_create_without_ts_type::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_csv::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_csv::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_json::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_json::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_json_with_schame::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_json_with_schame::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_orc::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_orc::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_parquet::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_execute_query_external_table_parquet::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_execute_show_databases_tables::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_information_schema_dot_columns::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_information_schema_dot_columns::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_information_schema_dot_tables::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_information_schema_dot_tables::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_show_create_external_table::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_show_create_external_table::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_show_create_table::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_show_create_table::case_2_test_with_distributed
- [ ] tests-integration tests::instance_test::test_use_database::case_1_test_with_standalone
- [ ] tests-integration tests::instance_test::test_use_database::case_2_test_with_distributed
- [ ] tests-integration::main integration_grpc_file_test::test_insert_and_select
- [ ] tests-integration::main integration_http_file_test::test_config_api
- [ ] tests-integration::main integration_http_file_test::test_prom_http_api
- [ ] tests-integration::main integration_http_file_test::test_prometheus_promql_api
- [ ] tests-integration::main integration_http_file_test::test_scripts_api
- [ ] tests-integration::main integration_http_file_test::test_sql_api
- [ ] tests-integration::main integration_sql_file_test::test_mysql_crud
- [ ] tests-integration::main integration_sql_file_test::test_postgres_crud
- [ ] tests-integration::main integration_sql_file_test::test_postgres_parameter_inference

**Comment by killme2008** [comment]
upadte:

```
   grpc::test::test_distributed_insert_delete_and_query
    grpc::test::test_standalone_insert_and_query
    tests::instance_test::test_create_table_after_rename_table::case_1_test_with_standalone
    tests::instance_test::test_execute_external_create::case_1_test_with_standalone
    tests::instance_test::test_execute_external_create::case_2_test_with_distributed
    tests::instance_test::test_execute_external_create_without_ts_type::case_1_test_with_standalone
    tests::instance_test::test_execute_external_create_without_ts_type::case_2_test_with_distributed
    tests::instance_test::test_execute_query_external_table_csv::case_1_test_with_standalone
    tests::instance_test::test_execute_query_external_table_csv::case_2_test_with_distributed
    tests::instance_test::test_execute_query_external_table_json::case_1_test_with_standalone
    tests::instance_test::test_execute_query_external_table_json::case_2_test_with_distributed
    tests::instance_test::test_execute_query_external_table_json_with_schame::case_1_test_with_standalone
    tests::instance_test::test_execute_query_external_table_json_with_schame::case_2_test_with_distributed
    tests::instance_test::test_execute_query_external_table_orc::case_1_test_with_standalone
    tests::instance_test::test_execute_query_external_table_orc::case_2_test_with_distributed
    tests::instance_test::test_execute_query_external_table_parquet::case_1_test_with_standalone
    tests::instance_test::test_execute_query_external_table_parquet::case_2_test_with_distributed
    tests::instance_test::test_execute_show_databases_tables::case_1_test_with_standalone
    tests::instance_test::test_information_schema_dot_columns::case_1_test_with_standalone
    tests::instance_test::test_information_schema_dot_columns::case_2_test_with_distributed
    tests::instance_test::test_information_schema_dot_tables::case_1_test_with_standalone
    tests::instance_test::test_information_schema_dot_tables::case_2_test_with_distributed
    tests::instance_test::test_rename_table::case_1_test_with_standalone
    tests::instance_test::test_show_create_external_table::case_1_test_with_standalone
    tests::instance_test::test_show_create_external_table::case_2_test_with_distributed
    tests::instance_test::test_show_create_table::case_1_test_with_standalone
    tests::instance_test::test_show_create_table::case_2_test_with_distributed
```

**Comment by zhongzc** [comment]
update:

[ ] tests-integration grpc::test::test_distributed_insert_delete_and_query
[ ] tests-integration grpc::test::test_standalone_insert_and_query
[ ] tests-integration tests::instance_test::test_execute_insert_by_select::case_1_test_with_standalone
[ ] tests-integration tests::instance_test::test_execute_insert_by_select::case_2_test_with_distributed
[ ] tests-integration::main integration_http_file_test::test_config_api
[ ] tests-integration::main integration_http_file_test::test_scripts_api
[ ] tests-integration::main integration_sql_file_test::test_mysql_auth
[ ] tests-integration::main integration_sql_file_test::test_mysql_crud
[ ] tests-integration::main integration_sql_file_test::test_postgres_auth
[ ] tests-integration::main integration_sql_file_test::test_postgres_crud
[ ] tests-integration::main integration_sql_file_test::test_postgres_parameter_inference

**Comment by killme2008** [comment]
@zhongzc I will look into  `test_postgres_xxx` and `test_mysql_xxx`.

**Comment by waynexia** [comment]
There are all fixed
