### ISSUE TITLE
Validate the table name before creating or renaming a table

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2485]
We should validate the table name before creating or renaming a table.

_Originally posted by @evenyag in https://github.com/GreptimeTeam/greptimedb/issues/2483#issuecomment-1733000197_

**Comment by MichaelScofield** [comment]
As long as the table name satisfy the `NAME_PATTERN`, I think it can be considered legal.

Schema name and catalog name must satisfy that pattern, too. We should check them both when creating them.

**Comment by killme2008** [comment]
Looks like we already did it.

https://github.com/GreptimeTeam/greptimedb/blob/f735f739e5de7a028a7b860b4e507eb774c9523a/src/operator/src/statement/ddl.rs#L133

https://github.com/GreptimeTeam/greptimedb/blob/f735f739e5de7a028a7b860b4e507eb774c9523a/src/operator/src/statement/ddl.rs#L246
