### ISSUE TITLE
Revert the wal_dir back

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2492]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

It was removed in https://github.com/GreptimeTeam/greptimedb/commit/f71aa373c1fdf47b2160295ab34e8341f856f613

But it's helpful when you have different disks for wal and data, so let's add it back.

**Comment by Shoothzj** [comment]
I am interested in this change. Could you please assign this to me?

**Comment by killme2008** [comment]
> I am interested in this change. Could you please assign this to me?

Cool, it's yours.

**Comment by tisonkun** [comment]
@killme2008 I noticed that now we use these three consts for different dir:

```rust
/// WAL dir for local file storage
pub const WAL_DIR: &str = "wal/";

/// Data dir for table engines
pub const DATA_DIR: &str = "data/";

/// Cluster state dir
pub const CLUSTER_DIR: &str = "cluster/";
```

Does this issue mean to use a configurable or at least variable wal_dir to replace the const? What for the rest two?

Besides, this seems be closed by https://github.com/GreptimeTeam/greptimedb/commit/d9e7b898a303df232f89832cac828a841160a31c.

**Comment by tisonkun** [comment]
The three consts seem default value.
