### ISSUE TITLE
Rename the kv directory

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2493]
### What type of enhancement is this?

Configuration, User experience

### What does the enhancement do?

The v0.4 standalone process will create a directory named `kv`. I think it's really a bad name, it doesn't provide any useful info for the users.

Some choices such as `meta`, `state`, or `internal` would be better.

**Comment by Lilit0x** [comment]
@killme2008 , you mean [here](https://github.com/GreptimeTeam/greptimedb/blob/a4282415f7fa3f5909566778def6768ce695bc36/src/common/config/src/lib.rs#L48C1-L48C1)

**Comment by killme2008** [comment]
> @killme2008 , you mean here

Yes, prefer a better name to describe it's usage. cc @waynexia  What's your option?

**Comment by killme2008** [comment]
@Lilit0x We decided to use `metadata` as the new name of this internal state directory.  Are u interested in creating a PR for it?

**Comment by Lilit0x** [comment]
@killme2008 , yes, I am

**Comment by killme2008** [comment]
@Lilit0x Thank u👍🏻. Appreciate it if you could create a PR today or tomorrow, we want to release v0.4.0 tomorrow.
