### ISSUE TITLE
The background task drop table multiple times

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2501]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Datanode

### What happened?

The background task drop table multiple times

<img width="1256" alt="Screenshot 2023-09-26 at 19 07 38" src="https://github.com/GreptimeTeam/greptimedb/assets/32535939/cbb1c652-cbf6-458e-ab99-33ad807d7718">

### What operating system did you use?

Ubuntu 23.04

### How can we reproduce the bug?

1. Create a table
2. Insert data
3. Flush data
4. Drop the table

**Comment by evenyag** [comment]
Forgot to break the loop here.

https://github.com/GreptimeTeam/greptimedb/blob/a4282415f7fa3f5909566778def6768ce695bc36/src/mito2/src/worker/handle_drop.rs#L97-L100

We should add a test for this.

**Comment by WenyXu** [comment]
> Forgot to break the loop here.
> 
> https://github.com/GreptimeTeam/greptimedb/blob/a4282415f7fa3f5909566778def6768ce695bc36/src/mito2/src/worker/handle_drop.rs#L97-L100
> 
> We should add a test for this.

Let’s put our dear friend @waynexia  in bug jail🤧
