### ISSUE TITLE
Support `create table xxx like yyy`

### ISSUE THREAD

**Issue by Gump9** [GreptimeTeam/greptimedb#2509]
### What problem does the new feature solve?

When i migrate tests from DuckDB,I found that we don't support this statement`create table xxx like yyy`,now we must use `show create table yyy` statement first,and then copy the `create` statement of `yyy` to create `xxx`.Should we support this statement?
It seems that we can't copy constraint from `yyy` to  `xxx` when we use `create table xxx like yyy` directly :
<img width="506" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/67940783/39552cfb-0238-45a9-8e52-e2feb9b4f8d8">

### What does the feature do?

Support statement `create table xxx like yyy`

**Comment by killme2008** [comment]
It's a useful feature, let's move it to the following release plan.

**Comment by KKould** [comment]
I want to try to implement this

**Comment by tisonkun** [comment]
@KKould this feature is nontrivial. What's your plan in implementing it?

**Comment by waynexia** [comment]
Sounds good. Let me assign it to you
