### ISSUE TITLE
Improve error message when column doesn't have default

### ISSUE THREAD

**Issue by NiwakaDev** [GreptimeTeam/greptimedb#2512]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Improve an error message when a column doesn't have default.

Let's say that we have the following table:
```sql
create table test_table(a string not null, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
```

And then, The following sql:
```sql
insert into test_table values(default, default);
```

results in:
```
ERROR 1815 (HY000): Failed to execute query, query: insert into test_table values(default, default)
```

This error doesn't tell us that the `a` doesn't have default.

I think that we can improve the error message like this:
```
`a` doesn't have a default value
```

**Comment by evenyag** [comment]
I guess the server doesn't return the root cause due to https://github.com/GreptimeTeam/greptimedb/pull/2428
```
ERROR 1815 (HY000): Failed to execute query, query: insert into test_table values(default, default)
```

After https://github.com/GreptimeTeam/greptimedb/pull/2506 is merged, the latest commit should output the reason
```
mysql> insert into test_table values(default, default);
ERROR 1815 (HY000): No valid default value can be built automatically, column: a
```

**Comment by NiwakaDev** [comment]
I see. Thank you.
