### ISSUE TITLE
MySQL time zone settings is broken in 0.4

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#2529]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### What happened?

Cannot set timezone in mysql any more

```
MySQL [public]> SET time_zone = 'UTC';
Query OK, 0 rows affected (0.001 sec)

MySQL [public]> SELECT @@time_zone;
+-------------+
| @@time_zone |
+-------------+
|             |
+-------------+
1 row in set (0.000 sec)

MySQL [public]> SET time_zone = '+08:00';
Query OK, 0 rows affected (0.000 sec)

MySQL [public]> SELECT @@time_zone;
+-------------+
| @@time_zone |
+-------------+
|             |
+-------------+
1 row in set (0.000 sec)

MySQL [public]> SET time_zone = 'Europe/Berlin';
Query OK, 0 rows affected (0.000 sec)

MySQL [public]> SELECT @@time_zone;
+-------------+
| @@time_zone |
+-------------+
|             |
+-------------+
1 row in set (0.000 sec)
```

### What operating system did you use?

any

### How can we reproduce the bug?

Open a mysql client console and follow docs: https://docs.greptime.com/user-guide/clients/mysql#time-zone

Execute `SELECT @@time_zone` returns empty result

**Comment by killme2008** [comment]
Broken by https://github.com/GreptimeTeam/greptimedb/commit/e0aecc920925328cff6315efd5fc1921f46617d0

Always new a `QueryContext` for every request. Must use `session.context()` instead.
