### ISSUE TITLE
Encoding the byte array in JSON with base64

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2542]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Encoding byte arrays in JSON is inefficient. One acceptable solution is encoding the byte array with base64.

https://github.com/GreptimeTeam/greptimedb/blob/17b385a985e7b628ad8d86520671e3b99db1f25f/src/common/meta/src/rpc/ddl.rs#L276-L292

https://github.com/GreptimeTeam/greptimedb/blob/17b385a985e7b628ad8d86520671e3b99db1f25f/src/common/meta/src/rpc/ddl.rs#L347-L358

**Comment by killme2008** [comment]
I think the performance of ddl procedure is not a major concern right now, and this serialization can't be the major performance bottleneck of it. I prefer the json format personally,  it is more readable and friendly for debugging and management.

**Comment by WenyXu** [comment]
> I think the performance of ddl procedure is not a major concern right now, and this serialization can't be the major bottleneck of it. I prefer the JSON format personally, it is more readable and friendly for debugging and management.


In this case, we only encode protobuf-encoded byte array with base64. By default, JSON format will treat the u8 array as the u32 array, which results in an expansion ratio of up to 4:1.
```rust
let pb = PbAlterTableTask { 
             alter_table: Some(self.alter_table.clone()), 
         }; 
         let buf = pb.encode_to_vec(); 
         serializer.serialize_bytes(&buf) 
```

**Comment by fengjiachun** [comment]
By the way, it seems that we haven't gained any benefits from using the JSON format in our current code processing. Formatting JSON from protobuf bytes doesn't enhance readability or user-friendliness.

**Comment by killme2008** [comment]
Got the point. If you want to make this change, please do it ASAP before v0.4.0 is released.
