### ISSUE TITLE
Make data home can be configured by command-line args

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2570]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Supports `--data-home` argument for standalone and datanode sub command.

https://github.com/GreptimeTeam/greptimedb/blob/9284bb7a2b9e50159dc5a34540d57ee1539de94f/src/cmd/src/datanode.rs#L85

https://github.com/GreptimeTeam/greptimedb/blob/9284bb7a2b9e50159dc5a34540d57ee1539de94f/src/cmd/src/standalone.rs#L86

**Comment by waynexia** [comment]
My bad. It's available in 0.4 🥲
