### ISSUE TITLE
Frontend/Datanode use different command line to configure grpc addr

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2571]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Frontend uses `grpc-addr`
https://github.com/GreptimeTeam/greptimedb/blob/d7aeb369a6891e9e245018438bba41afc359b72d/src/cmd/src/frontend.rs#L91-L92

Datanode uses `rpc-addr`
https://github.com/GreptimeTeam/greptimedb/blob/d7aeb369a6891e9e245018438bba41afc359b72d/src/cmd/src/datanode.rs#L88-L89

Standalone uses `rpc-addr`
https://github.com/GreptimeTeam/greptimedb/blob/d7aeb369a6891e9e245018438bba41afc359b72d/src/cmd/src/standalone.rs#L194-L195

**Comment by masonyc** [comment]
Hi, I am interested in this change. Could you please assign this to me? 

To clarify, goal is to rename all of them to `grpc_addr`?
