### ISSUE TITLE
static user provider doesn't work for gRPC in v0.4.0

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2578]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Other

### What happened?

Start the standalone with static user provider:

```
cargo run -- standalone start --user-provider=static_user_provider:cmd:greptime_user=greptime_pwd
```

But the `user_provider` in gRPC handler is always `None`, looks like the bug is back again.

https://github.com/GreptimeTeam/greptimedb/blob/0a9972aa9a24c8a68d9d4fa93f5273924fe6c854/src/servers/src/grpc/greptime_handler.rs#L70

And our test doesn't cover this case at all.

### What operating system did you use?

Ubuntu 22

### How can we reproduce the bug?

As described above.

**Comment by shuiyisong** [comment]
In integration test we build server instance and set user provider directly, skipping the parsing command part.

**Comment by evenyag** [comment]
@shuiyisong Can we close this PR now?

**Comment by shuiyisong** [comment]
@evenyag Yes. We'll track adding tests in #2579
