### ISSUE TITLE
Use readable form for all size and duration options in config file

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2582]
### What type of enhancement is this?

Configuration, User experience

### What does the enhancement do?

There are still many options don't use ReadableSize and ReadableDuration.

grpc
https://github.com/GreptimeTeam/greptimedb/blob/0a9972aa9a24c8a68d9d4fa93f5273924fe6c854/src/frontend/src/service_config/grpc.rs#L24-L27

heartbeat
https://github.com/GreptimeTeam/greptimedb/blob/0a9972aa9a24c8a68d9d4fa93f5273924fe6c854/src/servers/src/heartbeat_options.rs#L20-L23

meta client
https://github.com/GreptimeTeam/greptimedb/blob/9e33ddceeaf14a87f12f3a502d22eda734608533/src/meta-client/src/lib.rs#L22-L31

**Comment by masonyc** [comment]
Hi, I would like to work on this one
