### ISSUE TITLE
Illegal SchemaNameKey format: '__schema_name/greptime/'illegal-database''

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2595]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### What happened?

`-` is not supported in catalog/schema name. Quote it in `CREATE DATABASE` can bypass this limit. But it will breaks other internal components

### What operating system did you use?

Arch Linux with Kernel: 6.3.5-arch1-1

### Relevant log output and stack trace

```bash
MySQL [(none)]> show databases;
ERROR 1815 (HY000): Invalid table metadata, err: Illegal SchemaNameKey format: '__schema_name/greptime/'illegal-database''
```

### Expected behavior

`SHOW DATABASES` works and can give the correct result.

### How can we reproduce the bug?

```sql
show databases;
create database illegal-database;
create database 'illegal-database';
show databases;
```

**Comment by tisonkun** [comment]
@waynexia so what is the expected manner?

* Disallow "illegal character" even if it's quoted; or,
* Support such characters internally.


BTW, perhaps we can add such a section in the bug report issue template (what is expected) >_<

**Comment by waynexia** [comment]
>@waynexia so what is the expected manner?

Updated to the issue description. Under `Expected behavior` section

**Comment by tisonkun** [comment]
The issue is not about `-`, but the extra `'`:

```
mysql> create database 'illegaldatabase';
Query OK, 1 row affected (0.01 sec)

mysql> show databases;
ERROR 1815 (HY000): Invalid table metadata, err: Illegal SchemaNameKey format: '__schema_name/greptime/'illegaldatabase''
mysql> 
```

I'll try to dig it a bit.
