### ISSUE TITLE
Execute `create database` in procedure

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2601]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Before implementing the `drop database` #825, we should move the `create database` execution into the procedure.  It needs to require a schema-level lock before execution.

**Comment by john8628** [comment]
can i have a try?  @WenyXu

**Comment by WenyXu** [comment]
> can i have a try? @WenyXu

Thanks ❤️

**Comment by WenyXu** [comment]
> @WenyXu I think I need some help for working on adding support for a new CreateDatabaseProcedure by:
> 
> 1. Adding a new variant CreateDatabase(CreateDatabaseTask) to the ddlTask enum
> 2. Implementing CreateDatabaseTask in [ddl.rs](http://ddl.rs/)
> 3. Implementing submit_create_database_task async function in ddl_taskmanager
>    However, when running the project I'm getting the following error:
>    error[E0432]: unresolved import `api::v1::meta::CreateDatabaseTask`
>    --> src/common/meta/src/rpc/ddl.rs:22:5
>    |
>    22 |     CreateDatabaseTask as PbCreateDatabaseTask
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    |     |
>    |     no `CreateDatabaseTask` in `v1::meta`
>    |     help: a similar name exists in the module: `CreateTableTask`

You need to define the it in this [repo](https://github.com/GreptimeTeam/greptime-proto/)

**Comment by john8628** [comment]
OK ,got it , thanks

**Comment by WenyXu** [comment]
Hi @john8628, How is it going? Do you have any updates?

**Comment by john8628** [comment]
> you have any updates

I am sorry, it seems difficult to me; I cannot do it alone.

**Comment by WenyXu** [comment]
> > you have any updates
> 
> I am sorry, it seems difficult to me; I cannot do it alone.

It's fine. Maybe take a look at other good first issues.

**Comment by john8628** [comment]
> > > you have any updates
> > 
> > 
> > I am sorry, it seems difficult to me; I cannot do it alone.
> 
> It's fine. Maybe take a look at other good first issues.

thanks

**Comment by fengjiachun** [comment]
Close this issue, the detail in this comment: https://github.com/GreptimeTeam/greptimedb/pull/2880#issuecomment-1842422784
