### ISSUE TITLE
create_or_open should always set writable flag

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2634]
- We should also add a test for it
- Now if the region already exists, it is returned in readonly mode. However, we expect the region to be writable.

https://github.com/GreptimeTeam/greptimedb/blob/0fbde48655f4732fa9ad512c57b6a0dcb05a8934/src/mito2/src/region/opener.rs#L111-L123

We should set the writable flag to true.

**Comment by WenyXu** [comment]
It's not a good way to handle the region's state. After the Datanode restarts, it also involves the `create_or_open`. However, in this situation, we must set the writable via heartbeat. 

In the future, we will introduce a Readonly flag to the `TableRouteValue`, to indicate the Leader Peer might be dead or unavailable. We should allow `create_or_open` to open a read-only region, and setting writable via heartbeat.

**Comment by evenyag** [comment]
> After the Datanode restarts, it also involves the `create_or_open`

In this case, the datanode invokes `open()`, not `create_or_open()`. `create_or_open()` is only called when we want to create a region.
