### ISSUE TITLE
Remove redundant `try_flush` invoking

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2657]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

Remove the redundant `try_flush` invoking,  it's already invoked in `write`. And remove the `pub` visitability for `try_flush`.

https://github.com/GreptimeTeam/greptimedb/blob/102e4c975dd511552fa3355440b67979817e1cd1/src/mito2/src/sst/stream_writer.rs#L86-L93

**Comment by Abhishek-Mallick** [comment]
Please assign this to me

**Comment by killme2008** [comment]
@Abhishek-Mallick Just a kind reminder, are u still working on this issue? Happy New Year!

**Comment by Abhishek-Mallick** [comment]
Hey @killme2008 Happy 2024!
Sorry was a bit late
Yes I'll work on this right away
