### ISSUE TITLE
Remove main branch

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#2717]
### What type of enhancement is this?

Other

### What does the enhancement do?

We use `develop` branch mainly, and the `main` branch is simply unused.

Perhaps we should remove it to avod confusion. I personally checkout to `main` wrongly multiple times in these days.

And although I can remove the branch locally and use an alias like `git symbolic-ref refs/heads/main refs/heads/develop`, an upstream `main` is still confusing.

### Implementation challenges

A maintaine should be able to remove it from GitHub Web UI.

cc @waynexia @fengjiachun @lfc

**Comment by waynexia** [comment]
>I personally checkout to main wrongly multiple times in these days.

Same with you.

We are considering to switch to `main` recently. But it might take some time. What do you think @fengjiachun @killme2008 ?

**Comment by fengjiachun** [comment]
In our next release, we'll switch to the main branch.  cc @waynexia @evenyag

**Comment by tisonkun** [comment]
Good to know. Then this issue is invalid.

Closing..

**Comment by tisonkun** [comment]
@fengjiachun do we have an estimate for this? I've heard that we may cut 0.5 in these days.
