### ISSUE TITLE
Uses full table name as a lock key during the failover procedure.

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2738]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

We should use the full table name as a lock key like we did in other procedures(e.g., [here](https://github.com/GreptimeTeam/greptimedb/blob/8f3b299a45a577b79d891f7f04457cb6f87686ff/src/common/meta/src/ddl/create_table.rs#L270-L278))
https://github.com/GreptimeTeam/greptimedb/blob/8f3b299a45a577b79d891f7f04457cb6f87686ff/src/meta-srv/src/procedure/region_failover.rs#L378-L385

The lock was removed accidentally in #2368

**Comment by Dysprosium0626** [comment]
It seems like an easy task and good start for beginner like me.
Can you assign this to me?

**Comment by WenyXu** [comment]
> It seems like an easy task and good start for beginner like me. Can you assign this to me?

Sorry, this issue might need some future discussion; how about looking at other good first issues? Thank you 😊
