### ISSUE TITLE
Speed up the starting of datanode

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2774]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Opening a region in mito2 still waits for network returns in a `&mut self`  function, which is super expensive.(If opening a region requires 50ms, this worker only has 20qps)

https://github.com/GreptimeTeam/greptimedb/blob/4fcda272fb127e4a0106a5923b27a621202ffac3/src/mito2/src/worker/handle_open.rs#L66-L76

**Comment by tisonkun** [comment]
Is this issue still relevant? It seems quite vague what we can improve.

**Comment by tisonkun** [comment]
Closed unless we have more concrete stuff to improve.
