### ISSUE TITLE
Change the return type of `RegionEngine::handle_request()`

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2784]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

This interface inherits `common_query::Output` from the previous table engine. 

```rust
pub enum Output {
    AffectedRows(usize),
    RecordBatches(RecordBatches),
    Stream(SendableRecordBatchStream),
}
```

It combines the result of query (`RecordBatches` and `Stream`) and non-query (`AffectedRows`) together. After refactoring to region engine and region server, those requests are handled separately in two APIs. `RegionEngine::handle_request()` only handles non-query requests, thus the return type can be simplified to only contains the `AffectedRows` branch.

**Comment by Dysprosium0626** [comment]
Can I have a try?
