### ISSUE TITLE
query data via gorm PostgresQL

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#2795]
### What type of bug is this?

Crash, Data corruption

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

1. start greptimedb `cargo run -- standalone start`
2. clone repo https://github.com/yuanbohan/gorm-greptimedb, and run `go run main.go`

### What did you expect to see?

behave the same as PostgresQL

### What did you see instead?

panic with no data fetched

### What operating system did you use?

Mac OS X, Ventuna 13.4.1 (c), Apple M1 Pro

### Relevant log output and stack trace

```bash
2023/11/23 09:22:15 /Users/yuanbohan/workspace/github.com/gorm-greptimedb/db/pg.go:40 ERROR: Failed to describe statement (SQLSTATE XX000)
[7.457ms] [rows:0] SELECT * FROM "monitors"
panic: ERROR: Failed to describe statement (SQLSTATE XX000)
```
```

**Comment by killme2008** [comment]
Any error logs in greptimedb?

**Comment by yuanbohan** [comment]
> Any error logs in greptimedb?

no

**Comment by yuanbohan** [comment]
This isn't a bug, and I will re-open this issue if I found another issue.
