### ISSUE TITLE
Failed to delete python script from scripts table

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb#2813]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend, Datanode

### Minimal reproduce step

1. Deploy greptimedb cluster: https://docs.greptime.com/getting-started/try-out-the-greptimedb-cluster
2. Add scripts: https://docs.greptime.com/user-guide/scripts-&-functions/getting-started;
3. Delete the scripts:

```
mysql> select name from scripts;
+---------------+
| name          |
+---------------+
| system_status |
+---------------+
1 row in set (0.01 sec)

mysql> delete from scripts where name = 'system_status';
ERROR 1815 (HY000): Invalid request to region 4402341478400(1025, 0), reason: missing column script
```

### What did you expect to see?

Delete script OK

### What did you see instead?

```
mysql> select name from scripts;
+---------------+
| name          |
+---------------+
| system_status |
+---------------+
1 row in set (0.01 sec)

mysql> delete from scripts where name = 'system_status';
ERROR 1815 (HY000): Invalid request to region 4402341478400(1025, 0), reason: missing column script
```

### What operating system did you use?

macOS

**Comment by evenyag** [comment]
Should be a bug in mito engine 😢

**Comment by evenyag** [comment]
Addressed in https://github.com/GreptimeTeam/greptimedb/pull/2815
