### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by jonyangx** [GreptimeTeam/greptimedb#2838]
### What type of bug is this?

Configuration

### What subsystems are affected?

Other

### Minimal reproduce step

develop branch
cargo build

### What did you expect to see?

build success

### What did you see instead?

error: failed to run custom build command for `proc-macro2 v1.0.70`

Caused by:
  process didn't exit successfully: `/root/opensource/greptimedb/target/debug/build/proc-macro2-8f058ae0d1db576a/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libc v0.2.150`

Caused by:
  process didn't exit successfully: `/root/opensource/greptimedb/target/debug/build/libc-fcb26f7a7908db9b/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

### What operating system did you use?

Alibaba Cloud Linux 3.2104 LTS 64bit

### Relevant log output and stack trace

```bash
error: failed to run custom build command for `proc-macro2 v1.0.70`

Caused by:
  process didn't exit successfully: `/root/opensource/greptimedb/target/debug/build/proc-macro2-8f058ae0d1db576a/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libc v0.2.150`

Caused by:
  process didn't exit successfully: `/root/opensource/greptimedb/target/debug/build/libc-fcb26f7a7908db9b/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by waynexia** [comment]
Thanks for reporting this issue :heart:

Is your environment fresh? Or will you still run into this error after `cargo clean`?

**Comment by jonyangx** [comment]
> Thanks for reporting this issue ❤️
> 
> Is your environment fresh? Or will you still run into this error after `cargo clean`?

I've done cargo clean .

**Comment by evenyag** [comment]
Maybe related to https://github.com/rust-lang/cargo/issues/10679

**Comment by jonyangx** [comment]
➜ rustc -Vv
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4

**Comment by jonyangx** [comment]
refer to https://github.com/rust-lang/cargo/issues/10679 , https://github.com/rust-lang/cargo/issues/10679 ,Use export RUSTFLAGS="-Ctarget-feature=-crt-static" fix it.

**Comment by waynexia** [comment]
TIL, thanks for your info!
