### ISSUE TITLE
Support TQL [ANALYZE|EXPLAIN] `VERBOSE`

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#2850]
### What problem does the new feature solve?

`TQL EXPLAIN` And `TQL ANALYZE` provide intuitive illustrations of how a PromQL query is (will be) executed and the per step cost. We can provide a better experience by supporting `TQL EXPLAIN VERBOSE` and `TQL ANALYZE VERBOSE`, which gives a more detailed plan and cost and should help when trying to optimize some complex queries. 

### What does the feature do?

Add support to
- `TQL ANALYZE VERBOSE`
- `TQL EXPLAIN VERBOSE`

**Comment by etolbakov** [comment]
@waynexia sorry for the delay, still working on it

**Comment by waynexia** [comment]
Don't worry! And feel free to reach out to me anytime 😉
