### ISSUE TITLE
Can't select data by timestamp equals a literal

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2856]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

First create table and insert data:

```text
mysql> create table test(ts timestamp time index, a int);
Query OK, 0 rows affected (30.06 sec)

mysql> insert into test values(1,1);
Query OK, 1 row affected (0.03 sec)

mysql> select * from test;
+----------------------------+------+
| ts                         | a    |
+----------------------------+------+
| 1970-01-01 00:00:00.001000 |    1 |
+----------------------------+------+
1 row in set (0.07 sec)
```

Then `select * from test where ts = '1970-01-01 00:00:00.001000';`.

The result is empty, which is incorrect.

Two walkaround:

- add time unit directly: `select * from test where ts = “1970-01-01 00:00:00.001000”::timestamp_ms;`
- add time zone to time literal: `select * from test where ts = "1970-01-01 08:00:00.001000"`

### What did you expect to see?

select non-empty data

### What did you see instead?

select empty data

### What operating system did you use?

all

**Comment by killme2008** [comment]
@waynexia What's the status of this issue?

**Comment by waynexia** [comment]
> @waynexia What's the status of this issue?

It's fixed in https://github.com/GreptimeTeam/greptimedb/pull/2905
