### ISSUE TITLE
Able to pretty print sql query result in http output

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#2877]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Currently the sql query result in http api is printed as json, which is not good for us human to view the table data directly. For example, https://docs.greptime.com/user-guide/query-data/sql#http-api . If we could provide an option to pretty print the sql query result in table format, like mysql clients do, it would be very helpful for maintainer in offline/restricted/limited environment to debug and test our db. So I suggest adding a parameter "`format=table`" in http api along with "`sql=xxx`" to this end.

**Comment by tisonkun** [comment]
Also ref to ClickHouse's Pretty format - https://clickhouse.com/docs/en/interfaces/formats#pretty
