### ISSUE TITLE
refactor: make HTTP API returns non-200 status code when execution fails

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2888]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The HTTP always returns 200 status code even when the execution fails currently. The failure status is attached in the response content as the `code` field. It does not comply with RESTful conventions and may confuse.

We'd like to refactor this behavior and return the non-200 status code when the execution fails. But we need to keep returning the `code` field in the response JSON content.

### Implementation challenges

Maybe some test cases should be fixed while doing this refactor.

**Comment by killme2008** [comment]
> @killme2008 I would love to work on this issue :)

Appreciated. Please take it.

There are some code that you may want to read

All the HTTP API implementation is under:
https://github.com/GreptimeTeam/greptimedb/tree/develop/src/servers/src/http

And the main handler is

https://github.com/GreptimeTeam/greptimedb/blob/develop/src/servers/src/http/handler.rs

The `JsonReponse` is at

https://github.com/GreptimeTeam/greptimedb/blob/ea80570cb1f13c0a87f31a4e412b67fc53c74532/src/servers/src/http.rs#L246

**Comment by killme2008** [comment]
@ananta Just a kind reminder, are u still working on this issue? Happy New Year!

**Comment by ananta** [comment]
Hey Happy New Year 🎊 @killme2008 !!,

I got caught up with school stuff and couldn't finish the task. I'm going to unassign myself for now, but I'll check back later and see if I can help out if it's still open. Thanks!

**Comment by killme2008** [comment]
> Hey Happy New Year 🎊 @killme2008 !!,
> 
> I got caught up with school stuff and couldn't finish the task. I'm going to unassign myself for now, but I'll check back later and see if I can help out if it's still open. Thanks!

All right! Welcome back if you are not busy in the future. Thank you.

**Comment by tisonkun** [comment]
Closed as resolved in #3473.
