### ISSUE TITLE
The `redact_sql_secrets` didn't work if a secret contains '/'

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2889]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Datanode

### Minimal reproduce step

1. Create a table
2. Execute a `Copy To/From` statement that the secret of `CONNECTION` contains '/'

### What did you expect to see?

...ACCESS_KEY_ID=‘******’,SECRET_ACCESS_KEY='***'..

### What did you see instead?

...ACCESS_KEY_ID=‘******’,SECRET_ACCESS_KEY='{XXX_SECRET}'..

### What operating system did you use?

Doesn't matter

**Comment by tisonkun** [comment]
I can work on this issue to fix the REGEXP. But we still have some cases that REGEXP cannot cover esp. for escaping:

```
access_key_id="xxx""yyy"
```

Even I can handle `\"` but if it's a syntax error like above, how can we redact it or we can just fail with syntax error without printing the SQL.

**Comment by tisonkun** [comment]
Seems we currently use this function in:

```rust
let redacted = sql::util::redact_sql_secrets(query.as_ref());
error!(e; "Failed to execute query: {redacted}");
```

only.

**Comment by tisonkun** [comment]
Improve a bit at https://github.com/GreptimeTeam/greptimedb/pull/3080
