### ISSUE TITLE
Does greptimedb support timezone?

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#2893]
### What problem does the new feature solve?

I use MySQL Client to run range queries, and want to aggregate data by +8:00 timezone, then I do the the following steps:

Set timezone:

```sql
SET time_zone = '+08:00';
```

Run the range query:

```sql
SELECT ts, host, min(val) RANGE (INTERVAL '1' day) FROM host ALIGN (INTERVAL '1' day) TO '1900-01-01T00:00:00+08:00';
```

The problem is I have already set the client timezone to `+08:00`, could I just use the following SQL statement without the `to` option timestamp `'1900-01-01T00:00:00+08:00'` in the query statement:

```sql
SELECT ts, host, min(val) RANGE (INTERVAL '1' day) FROM host ALIGN (INTERVAL '1' day)
```

### What does the feature do?

Influxdb has supported the default timezone setting, see [blog](https://www.influxdata.com/blog/time-zones-in-flux/),  does GreptimeDB consider to support the timezone setting of MySQL client?

**Comment by killme2008** [comment]
Tracked in https://github.com/GreptimeTeam/greptimedb/issues/2907
