### ISSUE TITLE
Rename the `Calendar` keyword to `UTC0`

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#2894]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Frontend

### Minimal reproduce step

I use MySQL Client to run range queries, and want to aggregate data by +8:00 timezone, then I do the the following steps:

Set timezone:

```sql
SET time_zone = '+08:00';
```

Run the range query:

```sql
SELECT ts, host, min(val) RANGE (INTERVAL '1' day) FROM host ALIGN (INTERVAL '1' day) TO CALENDAR;
```

### What did you expect to see?

Due to the presence of the 'TO' option 'CALENDAR', the result should be aligned to clock 0 for the '+8:00' time zone, but it is aligned to UTC 0. 

### What did you see instead?

The result should be aligned to clock 0 for the '+8:00' time zone.

### What operating system did you use?

Mac OS X

**Comment by tisonkun** [comment]
.. or `UNIX_EPOCH`. I agree that `CALENDAR` is confusing while we document it well - https://docs.greptime.com/reference/sql/range#to-option

**Comment by waynexia** [comment]
I realized that `TO CALENDAR` is the default behavior. Maybe there is no need to define an explicit keyword for it? Like PromQL default aligns to `NOW()` and doesn't provide a way to specify this, which is unnecessary.

**Comment by waynexia** [comment]
Close via #2940, thanks for discussing this @nicecui @tisonkun ❤️
