### ISSUE TITLE
flush_table function to flush a table's memtable

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2899]
### What problem does the new feature solve?

I think the GreptimeDB can provide an SQL function such as:

```sql
flush_table('monitor');
```

to flush a table's memtable as an SST file. It's helpful for DB administrators.

### What does the feature do?

Flush a table's memtable as an SST file.

**Comment by NiwakaDev** [comment]
@killme2008 

I'd like to work on this issue.

>  It's helpful for DB administrators.

When do administrators flush a table? I'd like to know more details for the use case.

**Comment by killme2008** [comment]
> @killme2008
> 
> I'd like to work on this issue.
> 

That's cool. I already did some research on how to implement it. Appreciated if you want to do it.

> > It's helpful for DB administrators.
> 
> When do administrators flush a table? I'd like to know more details for the use case.

For example, when the memory consumption is too much or just want to migrate some regions, the DBA may want to flush some tables manually.
