### ISSUE TITLE
build() function to return the database build info

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2909]
### What problem does the new feature solve?

It's better to have an SQL function `build` that returns the database build info, for example:

```sql
mysql> select build()\G;

branch: develop
commit: fe2fc723bc19f37060b15625d363473f1f5bca10
version: 0.4.4
```

The result may be the same as `greptime --version` outputs.

https://github.com/GreptimeTeam/greptimedb/blob/47e51545dd58a1744d8c33f2eb60a11a893f2e51/src/common/version/src/lib.rs#L18

### What does the feature do?

An SQL function to return the database build info.

### Implementation challenges

Learn how to write a function:

https://github.com/GreptimeTeam/greptimedb/blob/develop/src/common/function/src/scalars/math/rate.rs

**Comment by Dysprosium0626** [comment]
The idea maybe implement Function for something like BuildFunction and get info from build_data and register it in the FunctionRegistry. Then add something in the planner. Maybe I can have a try?

**Comment by killme2008** [comment]
> The idea maybe implement Function for something like BuildFunction and get info from build_data and register it in the FunctionRegistry. Then add something in the planner. Maybe I can have a try?

Yes.

I think we can add a new mod `system` for these administrator functions.

Register functions refer to:

https://github.com/GreptimeTeam/greptimedb/blob/47e51545dd58a1744d8c33f2eb60a11a893f2e51/src/common/function/src/scalars/math.rs#L37

https://github.com/GreptimeTeam/greptimedb/blob/47e51545dd58a1744d8c33f2eb60a11a893f2e51/src/common/function/src/scalars/function_registry.rs#L76
