### ISSUE TITLE
Add a test for parameter type mismatch

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2920]
LGTM. But can we add a test to https://github.com/GreptimeTeam/greptimedb/blob/develop/tests-integration/tests/sql.rs

_Originally posted by @killme2008 in https://github.com/GreptimeTeam/greptimedb/pull/2918#pullrequestreview-1777362581_

**Comment by xxxuuu** [comment]
hi @killme2008, I would like to get involved in GreptimeDB starting from this issue. Could you assign it to me?

**Comment by WenyXu** [comment]
> hi @killme2008, I would like to get involved in GreptimeDB starting from this issue. Could you assign it to me?

Have fun
