### ISSUE TITLE
Unify the case style of configration

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2936]
### What type of enhancement is this?

User experience

### What does the enhancement do?

We currently have two code case styles in our configuration file. We need to standardize to a single code case style without sacrificing backward compatibility.

https://github.com/GreptimeTeam/greptimedb/blob/518bac35bc32834517f8ad356c05406522eb61be/config/metasrv.example.toml#L13

https://github.com/GreptimeTeam/greptimedb/blob/518bac35bc32834517f8ad356c05406522eb61be/config/standalone.example.toml#L2

**Comment by fengjiachun** [comment]
#2962
