### ISSUE TITLE
The `update_table_info` method should update `DatanodeTableValue` if need.

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2957]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

If a table alters its `region_options`, the redundant value `DatanodeTableValue` should be updated too.

Related #2051 #1084

**Comment by WenyXu** [comment]
But we don't support altering table options(stored in `region_options `) for now. cc @evenyag

**Comment by killme2008** [comment]
> But we don't support altering table options(stored in `region_options `) for now. cc @evenyag

Does the new mito engine support altering the region options currently? @evenyag

**Comment by evenyag** [comment]
> > But we don't support altering table options(stored in `region_options `) for now. cc @evenyag
> 
> Does the new mito engine support altering the region options currently? @evenyag

No, but region options are persisted in meta server so the region will use the new options after restart which re-open all regions.
