### ISSUE TITLE
Add built-in greptime_private schema by default

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#2964]
### What problem does the new feature solve?

This built-in schema is designed to store tables that created by our own applications and do not visible to user by default. It also prevents us from creating tables in `public` schema that has a potential risk to conflict with user's table.

### What does the feature do?

Create an empty `greptime_private` schema by default.

**Comment by evenyag** [comment]
Is it the same as the `system` schema in some DBMS?

**Comment by sunng87** [comment]
I think it's a little different from `system` that:

- this schema is designed to store tables created by greptime applications, while `system` schema is for storing tables of database itself
- `system` schema is for database administrators, while in most case user won't need to care about tables in this schema
- this schema is to be created for each catalog in multi-tenant environment, which `system` is created for default catalog only

Example cases for `greptime_private`:

- Our dashboard will ship a Saved Query feature allows user to save a SQL/PromQL script for future use
- Out cloud will write additional alerting logs into tables under this schema
