### ISSUE TITLE
Improve doc label experience

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#2997]
### What type of enhancement is this?

Other

### What does the enhancement do?

In Pulsar, we use https://github.com/apache/pulsar-test-infra/tree/master/docbot to auto label PRs with doc needed or no needed.

Currently, we have [a workflow](https://github.com/GreptimeTeam/greptimedb/blob/48cd22d4590087adc76aec3f57ff555f67c21e06/.github/workflows/user-doc-label-checker.yml) for doing this but it will always fail before any triager properly label it.

### Implementation challenges

Perhaps we depend on https://github.com/apache/pulsar-test-infra/tree/master/docbot; or we create a new repo to host greptime intra-repos actions.

**Comment by tisonkun** [comment]
cc @nicecui @sunng87 @waynexia

**Comment by waynexia** [comment]
Thanks for your information, do you know if Pulsar has any plan to provide it on GitHub Action Market? If I read it correctly, we have to depend on those go code directly to make it work

**Comment by waynexia** [comment]
I find a similar extension https://github.com/marketplace/actions/regex-issue-labeler, let me have a try

**Comment by tisonkun** [comment]
> if Pulsar has any plan to provide it on GitHub Action Market

I don't think so. We use pulsar-test-infra for inter-repos usage. But perhaps I can make one personally.

**Comment by waynexia** [comment]
Submits https://github.com/GreptimeTeam/greptimedb/pull/2998
