### ISSUE TITLE
Mysql client not support lower case `set` command

### ISSUE THREAD

**Issue by Taylor-lagrange** [GreptimeTeam/greptimedb#3006]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode, Frontend

### Minimal reproduce step

![image](https://github.com/GreptimeTeam/greptimedb/assets/46434815/ca41c9d9-c4f7-4e51-af06-28e8faead8fa)

Mysql client not support lower case `set` command

### What did you expect to see?

`set time_zone='UTC'` should work even in lower case

### What did you see instead?

`set time_zone='UTC'` report unsupport error

### What operating system did you use?

Mac OS X 10.5 ARM

**Comment by Taylor-lagrange** [comment]
We used regular expressions to parse some mysql commands, but these regular expressions did not adapt to lowercase letters.

https://github.com/GreptimeTeam/greptimedb/blob/99565a367688f4a81a1954385a1a4170a8cff102/src/servers/src/mysql/federated.rs#L59-L60

But our parser not support parse of `set` command, so cause unsupported  error

https://github.com/GreptimeTeam/greptimedb/blob/99565a367688f4a81a1954385a1a4170a8cff102/src/sql/src/parser.rs#L126-L127

**Comment by Taylor-lagrange** [comment]
After a little research, the real error is regex `(?i)^SET TIME_ZONE\s*=\s*'(\S+)'` only support single quote, not double quote, but the error still confuse user.

**Comment by sunng87** [comment]
Our current solution is a temporary one. This time we can implement `SET` expression with our sqlpaser and statement handlers.

**Comment by tisonkun** [comment]
Ref - https://github.com/GreptimeTeam/greptimedb/issues/1712#issuecomment-1848442765

The regex workaround suffers for case, whitespace, and so on. As @sunng87 mentioned above, we may fully parse the text and do interception in the MySQL layer.

**Comment by Taylor-lagrange** [comment]
I think the main reason why such SQL are not put into the parser is that the way of such SQL (e.g.  `SET time_zone='UTC'`) is very different between each database, but our parser layer is unified, and handling these differences will complex code logic.

But I think it is more reasonable to implement some logic in parser，enable to unify some behaviors between pg or mysql query. 

I think this problem can be solved together with this https://github.com/GreptimeTeam/greptimedb/issues/2907

**Comment by sunng87** [comment]
I think we don't really need to retain sql level compatibility for postgres because it requires too much effort. And don't let it stop us from adding features for other protocols. For postgres we only guarantee wire protocol compatibility.

**Comment by killme2008** [comment]
Looks like it's fixed:

```sql
mysql> set time_zone='UTC';
Query OK, 0 rows affected (0.00 sec)
```
