### ISSUE TITLE
Renaming default branch from develop to main

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3025]
### What type of enhancement is this?

Other

### What does the enhancement do?

As mentioned in https://github.com/GreptimeTeam/greptimedb/issues/2717, we plan to switch the default branch to `main` to avoid confusion.

Progress:
- [x] Prepare the new `main`
- [x] Change all existing PR
- [x] Set default branch to `main`
- [x] Push a deprecate notification to the old `develop`
- [x] Lock `develop`
- [x] Fix CI https://github.com/GreptimeTeam/greptimedb/pull/3026
- [x] Updates contribution guide https://github.com/GreptimeTeam/greptimedb/pull/3026
- [x] Update docs https://github.com/GreptimeTeam/docs/pull/739
- [x] Check other outdated references
- [x] Send Twitter/Slack notification
- [ ] Delete `develop` branch after [TBD]

#### Updates Local Environment

We need to update our local environment manually.
```bash
git branch -m develop main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

If the `main` branch already exists, you could remove it first
```bash
git branch -D main
```

For a forked repo, you could rename your default branch to main
<img width="481" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/7058520/591e23bb-ea32-4c01-af9a-9ce6a75219d8">

**Comment by evenyag** [comment]
We should still use the `develop.yml` for the CI badge. It is not a branch name.
<img width="817" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/7058520/417ff947-3711-4345-b292-0c0eb1441f22">
