### ISSUE TITLE
mito: Checks the entry id returned while opening the region

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#3042]
### What type of enhancement is this?

Other

### What does the enhancement do?

We should check the entry id while replaying the region

https://github.com/GreptimeTeam/greptimedb/blob/b526d159c3dd3bb9309720eadc96464ddb2e9b56/src/mito2/src/region/opener.rs#L386-L388

If the actual entry id in the WAL is less than the flushed entry id, raft-engine might panic while writing into the memtable.

Maybe related to https://github.com/GreptimeTeam/greptimedb/issues/3041

### Implementation challenges

We might provide different recovery mode
- For strict mode we might return error
- For truncate mode we can ignore entry id less than flushed entry id and truncate the WAL

**Comment by v0y4g3r** [comment]
Maybe I should also address this issue in #3073
