### ISSUE TITLE
Upgrade `regex-automata` to latest version

### ISSUE THREAD

**Issue by zhongzc** [GreptimeTeam/greptimedb#3043]
### What type of enhancement is this?

Performance

### What does the enhancement do?

In our inverted index implementation, we have utilized an FST (Finite State Transducer) as a key indexing structure, aiming to achieve excellent search capabilities.

The ability to perform regular expression matches is a particularly standout feature of the FST's search functionalities, and it's something we wish to incorporate into our system to provide more effective filtering for user queries. This capability primarily relies on the [`regex-automata`](https://github.com/BurntSushi/regex-automata) library to compile regular expressions into DFAs (Deterministic Finite Automata), which are utilized for searching within the FST.

The current issue is that `regex-automata` only offers the functionality to compile to DFA in its early versions (`0.1` and `0.2`), and there are a number of limitations within these versions (as detailed in the repository's README). We are looking to upgrade `regex-automata` being used, while maintaining the search capability within the FST.

According to the description at https://github.com/rust-lang/regex/issues/1087:
> Note that you can always write the trait impls yourself for a wrapper type, so you can unblock yourself if necessary.

It appears that we might be able to achieve our goal by following this suggestion.

**Comment by evenyag** [comment]
@tisonkun @zhongzc Can we close this issue now?

**Comment by zhongzc** [comment]
> @tisonkun @zhongzc Can we close this issue now?

yep
