### ISSUE TITLE
Add more tests for `MetaPeerClientRef`

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3044]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

The `MetaPeerClientRef` lacks tests and test utils. It's hard to add new features to `MetaPeerClientRef` and to verify any new features added to `MetaPeerClientRef`.

**Comment by KushnerykPavel** [comment]
Hey @WenyXu  may i pick this one?

**Comment by WenyXu** [comment]
> Hey @WenyXu may i pick this one?

Have fun
