### ISSUE TITLE
Implement the KvBackend trait for MetaPeerClient

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3046]
Nonblocking: I think it seems necessary to implement the KvBackend trait for MetaPeerClient, perhaps in the next PR.

_Originally posted by @fengjiachun in https://github.com/GreptimeTeam/greptimedb/pull/3032#discussion_r1438051340_

**Comment by lyang24** [comment]
Hi I am interested in this issue may i work on this one?

**Comment by WenyXu** [comment]
@lyang24 Thanks, fave fun!🤩

**Comment by lyang24** [comment]
Hi @WenyXu , I have a draft on this issue and i have a few questions.
1. seems like `MetaPeerClient` only offer read-only methods should we leave all the write method unimplemented?
2. The original get method on `MetaPeerClient` is very similar to the default get method on KvBackend trait except the debug assert on length of the kv returned. should we just use the default impl provided by the trait?
3. The draft got tagged 'need doc update' can you please help me understand what needs to be updated? (is there a change log or something)?

Thank you in advance and no rush on these questions :)

**Comment by WenyXu** [comment]
> Hi @WenyXu , I have a draft on this issue and i have a few questions.
> 
> 1. seems like `MetaPeerClient` only offer read-only methods should we leave all the write method unimplemented?
> 2. The original get method on `MetaPeerClient` is very similar to the default get method on KvBackend trait except the debug assert on length of the kv returned. should we just use the default impl provided by the trait?
> 3. The draft got tagged 'need doc update' can you please help me understand what needs to be updated? (is there a change log or something)?
> 
> Thank you in advance and no rush on these questions :)

Hi, @lyang24. Thank you for your concern.  

For questions 1 and 2. Actually, a follower `MetaPeerClient ` will forward all requests to the leader peer. https://github.com/GreptimeTeam/greptimedb/blob/bd1a5dc265bca7d52c62694bb672edcf8be2c072/src/meta-srv/src/cluster.rs#L94-L140

For question 3, I added a mark in your PR's checkbox(the `This PR does not require documentation updates.`); the bot will remove the `need doc update` label.

Feel free to let me know if you have any other questions😉

**Comment by lyang24** [comment]
Thank you, I have addressed the issues and made pr ready for review. Seem like the method of MetaPeerClient is not easy to test since it involves grpc calls, let me know is there any test i can add here.

**Comment by tisonkun** [comment]
Hi @WenyXu @lyang24! Shall we close this issue as done as https://github.com/GreptimeTeam/greptimedb/pull/3076 merged, or it's open for adding some tests around the patch?

**Comment by WenyXu** [comment]
> Hi @WenyXu @lyang24! Shall we close this issue as done as #3076 merged, or it's open for adding some tests around the patch?

Let’s close it
