### ISSUE TITLE
[remote_wal] Rename Topic to stop abuse of alias on Topic

### ISSUE THREAD

**Issue by niebayes** [GreptimeTeam/greptimedb#3055]
### What type of enhancement is this?

Other

### What does the enhancement do?

Our own `Topic` struct is used everywhere. However, the crate exposes it as `KafkaWalTopic` and the users use it through an alias `KafkaWalTopic as Topic`. We need to design a new name for `Topic` and remove those alias.

**Comment by evenyag** [comment]
`TopicName` is fine.

**Comment by niebayes** [comment]
I think we can remove the alias `type Topic = String` and use String directly.
