### ISSUE TITLE
Upgrade rustpython

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3063]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Our rustpython version looks too old, maybe we need to upgrade it.

**Comment by tisonkun** [comment]
@killme2008 @discord9 I remember that in an offline discussion, it's thrown that we might finally use PyO3 only.

Is there any concrete reason and plan? IIRC we initially add RustPython to decouple the dependency to system python interpreter. But now we think it's a fair requirement?

**Comment by killme2008** [comment]
> @killme2008 @discord9 I remember that in an offline discussion, it's thrown that we might finally use PyO3 only.
> 
> Is there any concrete reason and plan? IIRC we initially add RustPython to decouple the dependency to system python interpreter. But now we think it's a fair requirement?

The main reason is that RustPython is far from production currently, and Python and PyO3 are developing rapidly.
Using PyO3 and native Python, the user can use all the community resources such as opensource projects and documents, etc.

**Comment by tisonkun** [comment]
@killme2008 can we first dropping the code related to RustPython and recommend to use the PyO3 backend version?

For PyO3 backend version, the major challenge is supported range of Python version. @messense do you have some inputs in this topic? We're a binary rather than a lib, so we may not release multiple artifacts to cover the py versions like [OpenDAL](https://pypi.org/project/opendal/#files). Instead, we're trying to use abi3 to expand the supported versions range. But we still lack knowledge in how to move forward in this direction.

**Comment by messense** [comment]
Embedding python interpreter is an underexplored area in pyo3, `pyo3-ffi` does not support dynamic loading yet: https://github.com/PyO3/pyo3/issues/2668.

> An alternative could be to build your own `.so` which implements the Python plugin engine (and uses PyO3's existing link model), and then your binary could dynamically load that `.so` if a Python plugin is requested.

Will this work for greptimedb?

**Comment by tisonkun** [comment]
@messense Thanks for your information. Let me think of it ...

Cross-ref: https://pyo3.rs/v0.21.0/building-and-distribution

**Comment by tisonkun** [comment]
> @killme2008 can we first dropping the code related to RustPython and recommend to use the PyO3 backend version?

Found that we currently depend on RustPython's AST parsing function to extra metadata from decorators:

```python
@coprocessor(args=[], returns=["value"], backend="pyo3")
def test_numpy() -> vector[i64]:
    try:
        import numpy as np
        import pyarrow as pa
    except ImportError as e:
        # Python didn't have numpy or pyarrow
        print("Warning: no pyarrow or numpy found in current python", e)
        return vector([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])
    from greptime import vector
    v = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,])
    v = pa.array(v)
    v = vector.from_pyarrow(v)
    v = vector.from_numpy(v.numpy())
    v = v.to_pyarrow()
    v = v.to_numpy()
    v = vector.from_numpy(v)
    return v
```

**Comment by tisonkun** [comment]
@discord9 

No. `ruff` seems to write their own crate.

The API of RustPython has changed a lot, ref - https://github.com/RustPython/Parser/issues/119.

I generally doubt if such source edit approach the way to go. Maybe a Python UDF like PL/Python or a Python worker that can connect to the SQL server a good alternative.

**Comment by tisonkun** [comment]
Supersedes by https://github.com/GreptimeTeam/greptimedb/issues/3777.
