### ISSUE TITLE
The `region_distribution` should returns `RegionDistribution` instead of `Result<RegionDistribution>`

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3079]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

https://github.com/GreptimeTeam/greptimedb/blob/b9302e4f0d431be5c50a1e8c53b5aaf8bfe84db4/src/common/meta/src/rpc/router.rs#L33-L46

Here is no reason to return  `Result<RegionDistribution>`, Let's refactor it.

**Comment by ClSlaid** [comment]
I'd like to take a look.

**Comment by WenyXu** [comment]
> I'd like to take a look.

Have fun!
