### ISSUE TITLE
feat: date_format(datetime, format) to format a timestamp/date/datetime value

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3139]
### What problem does the new feature solve?

We need a function `date_format` to format a timestamp, date or datetime value into a string value.

For example:

```sql
select date_format(now(), ,'%Y-%m-%d %T.%000');
```

### What does the feature do?

Format a format a timestamp/date/datetime value into string.

**Comment by waynexia** [comment]
related to https://github.com/apache/arrow-datafusion/issues/5398
