### ISSUE TITLE
Retrieves cluster metadata via GreptimeDB Cli 

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3141]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Now, the meta-srv has several HTTP APIs that easily retrieve cluster metadata via HTTP:

e.g.,
```
curl localhost:3002/admin/leader
curl localhost:3002/admin/route?table_id=1024
```

The corresponding HTTP handlers can be found at:
https://github.com/GreptimeTeam/greptimedb/blob/312e8e824ec24448f6cdf449919d0bfbe49d37ea/src/meta-srv/src/service/admin.rs#L37

Let's add the ability to retrieve and print the cluster metadata to CLI.

**Comment by killme2008** [comment]
I think it's better to implement this feature via SQL functions or virtual tables in `information_schema`.

**Comment by waynexia** [comment]
I'm hesitant about whether we should expose those information...

**Comment by fengjiachun** [comment]
> I'm hesitant about whether we should expose those information...

+1

**Comment by killme2008** [comment]
They are useful for DBA. For example, I want to know the current table region distribution or I want to migrate a hotspot region.

**Comment by waynexia** [comment]
How about wrapping a web UI for those HTTP APIs in dashboard or someplace else? I remember we are going to implement a cluster insight page here. And IMO CLI is not too much better than curl...

**Comment by killme2008** [comment]
I think we should implement all these features via SQL functions or `information_schema` virtual tables. I don't like too many HTTP APIs.
