### ISSUE TITLE
COPY FROM not support windows path in 0.6.0

### ISSUE THREAD

**Issue by amythos** [GreptimeTeam/greptimedb#3195]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Frontend

### Minimal reproduce step

execute query: COPY tbl_aaa FROM 'D:\\data\\tmp\\aaa.parquet' WITH (FORMAT = 'parquet');

### What did you expect to see?

copy aaa.parquet into tbl_aaa

### What did you see instead?

fail to execute the query

### What operating system did you use?

Windows 11

### What version of GreptimeDB did you use?

0.6.0

### Relevant log output and stack trace

```bash
2024-01-18T14:17:40.729123Z ERROR frontend::instance: Failed to execute query: COPY tbl_aaa FROM 'D:\\data\\tmp\\aaa.parquet' WITH (FORMAT = 'parquet'); err=0: Table operation error, at src\frontend\src\instance.rs:267:14
1: Failed to build data source backend, at C:\a\greptimedb\greptimedb\src\operator\src\statement\copy_table_from.rs:62:59
2: Unsupported backend protocol: d, url: D:\\data\\tmp\\aaa.parquet, at src\common\datasource\src\object_store.rs:73:10
```

**Comment by v0y4g3r** [comment]
Please use `/` as path separator instead of backslash on Windows. `COPY tbl_aaa FROM 'D:/data/tmp/aaa.parquet' WITH (FORMAT = 'parquet');` would do the trick.
