### ISSUE TITLE
Unexpected trim behavior of `join_path`

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#3212]
`join_path` function will trim leading `/` in path. So when joining `/a/b` with `c`, the resulting path will be `a/b/c` instead of `/a/b/c`

---
              > Use join_path?

`join_path` does not apply here since it removes leading `/` in path:
https://github.com/GreptimeTeam/greptimedb/blob/75975adcb6a03dc68fa81e2cfe36f30a0a202538/src/object-store/src/util.rs#L81

_Originally posted by @v0y4g3r in https://github.com/GreptimeTeam/greptimedb/pull/3164#discussion_r1461390626_

**Comment by erichengber** [comment]
Hi I am an undergraduate at the University of Florida looking for my first contribution and this seems like something I can do. Mind if I give it a try?

**Comment by evenyag** [comment]
Sure, you could implement a new `normalize_path()` function based on OpenDAL's [normalize_path()](https://docs.rs/opendal/latest/opendal/raw/fn.normalize_path.html) and modify its default behavior.

**Comment by dalprahcd** [comment]
Hello @erichengber, are you still working on this issue?

**Comment by tisonkun** [comment]
Hi @dalprahcd!

As @erichengber doesn't share more progress for about a week and has no patch yet, you can start to work on it and submit a patch. Feel free to ping me as a reviewer and I'll switch the assignee when a patch is ready.
