### ISSUE TITLE
Add a benchmark for the concurrent write

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3215]
> Good job! Could we provide some benchmark results for this feature? And I wonder if the default value of 8 is the best practice for most common usage.

I will create a benchmark with throughput and latency in the different write concurrency settings. BTW, Based on some sample experiments I did before, a 10Gpbs bandwidth EC2 instance, setting the write concurrency to 25, the program could reach throughput: 500MiB/s with p50 ~250ms.

_Originally posted by @WenyXu in https://github.com/GreptimeTeam/greptimedb/issues/3214#issuecomment-1904195768_

**Comment by niebayes** [comment]
Is it safe to close issue? See https://github.com/GreptimeTeam/greptimedb/pull/3214

**Comment by WenyXu** [comment]
> Is it safe to close this issue? See #3214

Nope, I’m going to add the benchmark later

**Comment by killme2008** [comment]
Can we close the issue right now?
