### ISSUE TITLE
Cannot show-table with Duration Type

### ISSUE THREAD

**Issue by fengjiachun** [GreptimeTeam/greptimedb#3230]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

1. Use the SDK to write data of type Duration, which will trigger automatic table creation in the database.
2. Execute `SHOW CREATE TABLE`, then get a panic.

In fact, the reason is that there is a lack of mapping from the Duration type to the SQL type [here](https://github.com/GreptimeTeam/greptimedb/blob/main/src/sql/src/statements.rs#L504).

### What did you expect to see?

//

### What did you see instead?

//

### What operating system did you use?

Mac OS X 10.5 ARM

### What version of GreptimeDB did you use?

0.6.0

**Comment by QuenKar** [comment]
> In fact, the reason is that there is a lack of mapping from the Duration type to the SQL type

I remember when I realized here, there is no suitable `SqlDataType` for our `Duration` type, https://docs.rs/sqlparser/latest/sqlparser/ast/enum.DataType.html ,how about using `SqlTypeNotSupportedSnafu` here ?
