### ISSUE TITLE
Needs a way to find all peers info in cluster

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3294]
### What type of enhancement is this?

API improvement, Configuration, User experience

### What does the enhancement do?

We need a way to find all peers' info in a cluster, including:

* peer id
* peer address
* peer role, such as `metasrv`, `datanode` and `frontend` etc.
* peer status, such as `alive` or `downgraded` etc.

This info can be provided to the dashboard and users for management.

**Comment by killme2008** [comment]
The `cluster_info` in `information_schema` needs it. @fengjiachun

**Comment by fengjiachun** [comment]
> The `cluster_info` in `information_schema` needs it. @fengjiachun

 I'll get this done as soon as possible.
