### ISSUE TITLE
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "$TARGET_BIN": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by igkg** [GreptimeTeam/greptimedb#3298]
### What type of bug is this?

Crash, Unexpected error

### What subsystems are affected?

Other

### Minimal reproduce step

Windows 11 with wsl2 ubuntu Docker Desktop

```
docker run --security-opt seccomp=unconfined -p 4000-4003:4000-4003 \
-p 4242:4242 -v "$(pwd)/greptimedb:/tmp/greptimedb" \
--name greptime --rm \
greptime/greptimedb standalone start \
--http-addr 0.0.0.0:4000 \
--rpc-addr 0.0.0.0:4001 \
--mysql-addr 0.0.0.0:4002 \
--postgres-addr 0.0.0.0:4003 \
--opentsdb-addr 0.0.0.0:4242

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "$TARGET_BIN": executable file not found in $PATH: unknown.
```

### What did you expect to see?

Container started without error.

### What did you see instead?

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "$TARGET_BIN": executable file not found in $PATH: unknown.`

### What operating system did you use?

Windows 11 wsl2 ubuntu

### What version of GreptimeDB did you use?

0.6

**Comment by zyy17** [comment]
Thank you for your report 🤝 We're working on #3297.
