### ISSUE TITLE
[smartstring 1.0.1] error[E0433]: failed to resolve: use of undeclared crate or module `alloc`

### ISSUE THREAD

**Issue by yurivict** [GreptimeTeam/greptimedb#3304]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

regular build.

### What did you expect to see?

n/a

### What did you see instead?

Build fails on some systems.

I am able to build fine on my local workstation.
But it fails in the following way in the virtual machine w/out internet access:

```
[protobuf-src 1.1.0+21.5] checking for python... :
[protobuf-src 1.1.0+21.5] checking for the pthreads library -lpthreads... no
[smartstring 1.0.1] error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
[smartstring 1.0.1]  --> <anon>:1:18
[smartstring 1.0.1]   |
[smartstring 1.0.1] 1 | pub trait Probe: alloc::alloc::Allocator + Sized {}
[smartstring 1.0.1]   |                  ^^^^^ use of undeclared crate or module `alloc`
[smartstring 1.0.1]   |
[smartstring 1.0.1]   = help: add `extern crate alloc` to use the `alloc` crate 
[smartstring 1.0.1] help: consider importing this module
[smartstring 1.0.1]   |
[smartstring 1.0.1] 1 + use std::alloc;
[smartstring 1.0.1]   |
[smartstring 1.0.1] help: if you import `alloc`, refer to it directly
[smartstring 1.0.1]   |
[smartstring 1.0.1] 1 - pub trait Probe: alloc::alloc::Allocator + Sized {}
```

Do you know what might be causing this failure?

### What operating system did you use?

FreeBSD 14.0

### What version of GreptimeDB did you use?

0.6.0

### Relevant log output and stack trace

```bash
n/a
```

**Comment by tisonkun** [comment]
What version of rustc do you use? `extern crate alloc;` is declared in `src/lib.rs` within smartstring - https://github.com/bodil/smartstring/blob/e407ca23c747257a812d2d2e70bf336412718c3a/src/lib.rs#L106

This doesn't seem a GreptimeDB issue.

**Comment by tisonkun** [comment]
> regular build.

There is no "regular build". The command and the toolchain/env version is important for debugging such issues.

**Comment by yurivict** [comment]
The command is the same as [in this build](https://people.freebsd.org/~yuri/greptimedb-0.6.0-failure.log).

rust-nightly-1.76.0.20231125 is used.
Exactly same rust version builds it fine on the local system, but fails in the VM.

**Comment by tisonkun** [comment]
@yurivict do you try to build smartstring alone? Said -

```
git clone https://github.com/bodil/smartstring.git
cd smartstring
cargo build
```

... on your VM.

**Comment by tisonkun** [comment]
Anyway, this dep doesn't seem useful, I'm trying to opt-out it.
