### ISSUE TITLE
The error message says "Permission denied" but it doesn't say what the file name is

### ISSUE THREAD

**Issue by yurivict** [GreptimeTeam/greptimedb#3322]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

start greptime

### What did you expect to see?

n/a

### What did you see instead?

```
Error: 0: Failed to start frontend, at /usr/ports/databases/greptimedb/work/greptimedb-0.7.0-nightly-20240115-102-g29f11d7b7e/src/cmd/src/standalone.rs:400:10
1: Failed to open raft engine backend, at /usr/ports/databases/greptimedb/work/greptimedb-0.7.0-nightly-20240115-102-g29f11d7b7e/src/frontend/src/instance.rs:176:14
2: Failed to perform raft-engine operation, at src/log-store/src/raft_engine/backend.rs:46:43
3: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

### What operating system did you use?

FreeBSD 14.0

### What version of GreptimeDB did you use?

rev. 29f11d7b7e

**Comment by waynexia** [comment]
BTW, the `Permission denied` error is from third-party dep `raft-engine`. Maybe we should check permission before passing it to `raft-engine`.

**Comment by yurivict** [comment]
It should never print a message with the error code without the relevant detail like the file name.

**Comment by tisonkun** [comment]
> Maybe we should check permission before

Or enrich the error with path configured when getting such IO  error.

**Comment by waynexia** [comment]
There should be a log right before the error that contains the directory, like here is what I get from my env:

```
2024-02-20T02:53:31.195714Z  INFO log: Create raft log directory: ../no_permission/metadata    
Error: 0: Failed to start frontend, at /home/wayne/repo/greptimedb-dev/src/cmd/src/standalone.rs:400:10
1: Failed to open raft engine backend, at /home/wayne/repo/greptimedb-dev/src/frontend/src/instance.rs:176:14
2: Failed to perform raft-engine operation, at src/log-store/src/raft_engine/backend.rs:46:43
3: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

@yurivict do you have a similar thing?

**Comment by yurivict** [comment]
Maybe there was a line "INFO log: Create raft log directory:", but it is several lines above and doesn't make it clear whether it was successful or not.

"Permission denied" should be in the same line with the file name for which permission was denied.

**Comment by tisonkun** [comment]
> "Permission denied" should be in the same line with the file name for which permission was denied.

This is impossible or even more cumbersome due to Rust's std io lib design - it wraps what errno returns without context aware.

We can instead enrich the context as in #3327 so that result is like:

```
Error: 0: Failed to start frontend, at /Users/tison/Brittani/greptimedb/src/cmd/src/standalone.rs:400:10
1: Failed to open raft engine backend, at /Users/tison/Brittani/greptimedb/src/frontend/src/instance.rs:176:14
2: Failed to perform IO on path: /var/root/metadata, at src/log-store/src/raft_engine/backend.rs:50:10
3: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```

Not the same line, but the same stack.
