### ISSUE TITLE
greptime still prints terminal sequences when the log is redirected to a file

### ISSUE THREAD

**Issue by yurivict** [GreptimeTeam/greptimedb#3323]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

start the server, redirect the log to a file

### What did you expect to see?

n/a

### What did you see instead?

The log file contains:
```
^[[2m2024-02-19T08:03:49.205531Z^[[0m ^[[32m INFO^[[0m ^[[2mcommon_procedure::local^[[0m^[[2m:^[[0m LocalManager start to recover
^[[2m2024-02-19T08:03:49.205638Z^[[0m ^[[32m INFO^[[0m ^[[2mcommon_procedure::local^[[0m^[[2m:^[[0m LocalManager finish recovery, cost: 0ms
^[[2m2024-02-19T08:03:49.205738Z^[[0m ^[[32m INFO^[[0m ^[[2mfrontend::instance^[[0m^[[2m:^[[0m Starting service: POSTGRES_SERVER
^[[2m2024-02-19T08:03:49.205829Z^[[0m ^[[32m INFO^[[0m ^[[2mservers::server^[[0m^[[2m:^[[0m Starting POSTGRES_SERVER at 127.0.0.1:4003
^[[2m2024-02-19T08:03:49.205965Z^[[0m ^[[32m INFO^[[0m ^[[2mservers::server^[[0m^[[2m:^[[0m Postgres server started at 127.0.0.1:4003
^[[2m2024-02-19T08:03:49.206119Z^[[0m ^[[32m INFO^[[0m ^[[2mfrontend::instance^[[0m^[[2m:^[[0m Starting service: OPENTSDB_SERVER
```

### What operating system did you use?

FreeBSD 14.0

### What version of GreptimeDB did you use?

rev. 29f11d7b7e

**Comment by MichaelScofield** [comment]
@yurivict there's a logging option called "append_stdout" (see [here](https://docs.greptime.com/user-guide/operations/configuration#logging-options)), set it to "false" then greptimedb won't print logs to stdout (terminal).

**Comment by yurivict** [comment]
@MichaelScofield 

But this isn't what I am asking.

The ```--log-dir=/var/log/greptimedb``` option causes logs written into ```/var/log/greptimedb``` to contain terminal sequences.

**Comment by tisonkun** [comment]
@yurivict "What did you expect to see?"?

If you redirect stdout to a file, then the file contains what is to be printed to stdout.

Please try to fill the issue template clear so that we can avoid ask the same questions in the template once again.

**Comment by MichaelScofield** [comment]
@tisonkun I think what @yurivict means are the "[terminal sequences](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)" like "`^[[2m`" shouldn't have been printed in log files.

**Comment by yurivict** [comment]
exactly.

**Comment by MichaelScofield** [comment]
@yurivict please wait for the linked PR to be merged then the log files will no longer contain the terminal sequences.
