### ISSUE TITLE
Support automatic DNS lookup for kafka bootstrap servers

### ISSUE THREAD

**Issue by niebayes** [GreptimeTeam/greptimedb#3328]
### What type of enhancement is this?

User experience

### What does the enhancement do?

[Amazon MSK](https://aws.amazon.com/msk/pricing/) users can only obtain bootstrap server addresses in the form of `b-1.niebayesmskcluste.vekjkv.c2.kafka.ap-southeast-1.amazonaws.com:9094`. However, greptimedb requires addresses in the form of `127.0.0.1:9094`. Therefore, we need to support automatic DNS lookup to obtain available bootstrap server addresses.

**Comment by niebayes** [comment]
Currently, users are required to provide their own `broker_endpoints` for Kafka wal, or the default endpoint `127.0.0.1:9092` would be used. See the provisioned example configuration files, for e.g. https://github.com/GreptimeTeam/greptimedb/blob/6628c41c3663bb22b41fee3dd10f0edd0769802d/config/metasrv.example.toml#L57-L58

However, users may not able to obtain broker endpoints in the form of `127.0.0.1:9092`, but in the form of `b-1.niebayesmskcluste.vekjkv.c2.kafka.ap-southeast-1.amazonaws.com:9094` which requires DNS lookup. 

We want to eliminate the need for users to manually perform DNS lookup and instead perform automatic DNS lookup within greptimedb.

There might have two methods to accomplish this task (Any other solutions are welcome): 
- Check broker endpoints whenever we use them. If they're not in the form of `127.0.0.1:9092`, perform a DNS lookup. 
- Modify the deserialization logic for `broker_endpoints` to perform an automatic DNS lookup when necessary. You may find the `serde` crate useful. 

The definitions of wal configs reside in this [file](https://github.com/GreptimeTeam/greptimedb/blob/bf5e1905cd7f4987a504d650a00ca6501cd5203c/src/common/wal/src/config.rs).

**Comment by J0HN50N133** [comment]
I would like to offer some help. I've found a simple crate [dns-lookup](https://github.com/keeperofdakeys/dns-lookup) and would like to implement it in the second way.

**Comment by tisonkun** [comment]
@J0HN50N133 Cool. Go ahead and welcome to ping @niebayes or me as a reviewer when you prepare a patch :D
