### ISSUE TITLE
Configure lint options in Cargo.toml

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3344]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

https://github.com/GreptimeTeam/greptimedb/blob/cf08a3de6b13695a2445fa2edca467d12125bd71/.cargo/config.toml#L8-L15

Now https://github.com/rust-lang/cargo/issues/5034 is resolved. You can see

**Comment by SteveLauC** [comment]
let's me try this
