### ISSUE TITLE
Adds SQL function isnull(column)

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3355]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

There is a function `isnull` in MySQL to test if a column is null:

```sql
SELECT ISNULL(NULL);
```

https://www.w3schools.com/sql/func_mysql_isnull.asp

We need it for Navicat compatibility.

### Implementation challenges

If someone is interested in how to implement an SQL function, please refer to https://github.com/GreptimeTeam/greptimedb/pull/3147

**Comment by KKould** [comment]
let me try this
