### ISSUE TITLE
Rename client repos to ingesters

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3411]
### What type of enhancement is this?

Other

### What does the enhancement do?

We make a decision to prefer an ingester-only lib rather than a read-write-supported client.

So far, we archived client-go and client-java, and superseded them with ingester-go and ingester-java. We also rename client-rust to ingester-rust.

I'd suggest we do the same thing for the following repos so that we give a consistent view to visitors:

* https://github.com/GreptimeTeam/greptime-client-js -> greptimedb-ingester-js (or -node if it requires a nodejs env?)
* https://github.com/GreptimeTeam/greptimedb-client-erl -> greptimedb-ingester-erl
* https://github.com/GreptimeTeam/greptimedb-c-client-ffi -> greptimedb-ingester-c
* https://github.com/GreptimeTeam/greptimedb-client-cpp -> greptimedb-ingester-cpp
* https://github.com/GreptimeTeam/greptimedb-client-py -> greptimedb-ingester-py

**Comment by tisonkun** [comment]
What do you think @sunng87 @fengjiachun? I can execute these actions if we reach a consensus.

**Comment by killme2008** [comment]
The `greptimedb-client-erl` is used in emqx currently

https://github.com/emqx/emqx/blob/e9a5670cce9915e5b736cda982e6b69040f5577a/apps/emqx_bridge_greptimedb/rebar.config#L9

I am uncertain whether renaming would cause any dependency issues.

**Comment by tisonkun** [comment]
@killme2008 Generally GitHub would set redirections for renames, as long as we don't create a new repo with the old name, having total different content, that should be fine.

Anyway, we can involve EMQX people to join and test the erlang client rename. But you'd agree that change for all other renames?

FYI we ever call the JS client "greptime-js-sdk" and ever hold it at @alili's personal scope. But when you visit https://github.com/alili/greptime-js-sdk you will be redirected to the new location.

**Comment by tisonkun** [comment]
@SergeTupchiy since you touch the related lines, do you know if rebar can handle this rename things? IIRC GitHub will set up redirections for repo rename. And we can always update the git dep for new versions. So it's for the legacy releases.

@killme2008 or we can postpone the changes on erl and when we finish an ingestor impl, create a new repo for it, and archive the current.

**Comment by fengjiachun** [comment]
My thoughts are the same as Tison's. We should do the same thing for SDKs of all languages to provide the same view. What do you think? @killme2008 @sunng87

**Comment by killme2008** [comment]
@tisonkun I think it's fine to rename the erlang sdk, looks like github will process the redirection.

**Comment by tisonkun** [comment]
OK. Let me apply the changes in days.

**Comment by tisonkun** [comment]
Rename done.

**Comment by tisonkun** [comment]
@fengjiachun @MichaelScofield @waynexia Let's update the README file for these repos.

Also, I'd suggest we provide a roadmap (can be brief) for these ingesters so that the community can have a proper exception and know how to engage. We'd post this roadmap at https://github.com/orgs/GreptimeTeam/discussions.

If you agree on this, we can schedule a meeting for so, or I'd appreciate it if you can just drop a draft.

**Comment by SergeTupchiy** [comment]
Hi guys, 
Sorry for the late response. 
Renaming the repo doesn't cause any troubles for rebar projects as long as GitHub keeps redirecting the old URLs, which is the case.

**Comment by tisonkun** [comment]
@SergeTupchiy Thanks for confirming this! I guess we can anyway update the URL for new EMQX versions :D
