### ISSUE TITLE
Query very large dataset by grpc server streaming

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3429]
### What problem does the new feature solve?

Though unusual (and not recommended), sometimes user just want to query very large dataset. However, now the "big" queries are often resulted in timeout. The problems maybe reside in that huge volume of data are waiting to be gathered inside GreptimeDB, or the large amount of network/hard disk IO costs.

Similar issue: https://github.com/GreptimeTeam/greptimedb/issues/2223

### What does the feature do?

Make querying very large dataset do-able, by featuring GRPC server streaming. Inside GreptimeDB, the results of queries are all streams. So we may create a GRPC interface to poll(adapt) that stream.

**Comment by YCCDSZXH** [comment]
Need some help.
## The origin *.proto may need to be modify
```proto
service GreptimeDatabase {
  rpc Handle(GreptimeRequest) returns (GreptimeResponse);
  rpc HandleRequests(stream GreptimeRequest) returns (GreptimeResponse);
}
...
message GreptimeResponse {
  ResponseHeader header = 1;
  oneof response { AffectedRows affected_rows = 2; }
}
```
to support stream, we may modify it like this?
```proto
service GreptimeDatabase {
  rpc Handle(GreptimeRequest) returns (stream GreptimeResponse);
  rpc HandleRequests(stream GreptimeRequest) returns (stream GreptimeResponse);
}
...
message GreptimeResponse {
  ResponseHeader header = 1;
  oneof response {
    AffectedRows affected_rows = 2;
    ARowInQueryResults row = 3;
  }
}
```
Insert and delete still work, and query result will be return as a stream.
But if we do so, the query response header will be sent multiple times.

**Comment by evenyag** [comment]
@MichaelScofield Could you provide more information such as codes that need to be modified for this issue?

I remember that we are using Arrow Flight service for handling requests from clients, which is already streaming.
https://github.com/GreptimeTeam/greptimedb/blob/bba3108e0d1e8fc8d042dfd821c7c78dd33d0ac3/src/client/src/database.rs#L287-L294

**Comment by waynexia** [comment]
The query is not defined in the *.proto file you mentioned above @YCCDSZXH. We are using Arrow Fligth to define query services, more specifically, the `doGet` method:

https://github.com/apache/arrow-rs/blob/11450ae8ddf902b57cb42491a3d824d9550a05ea/format/Flight.proto#L108

Which returns a `stream` as proposed

**Comment by MichaelScofield** [comment]
@YCCDSZXH Sorry this issue is a little outdated, we decide not to let `GreptimeDatabase` handle query requests. The `QueryRequest`s are used in Arrow Flight service, and it's already streamed. I'm gonna close this issue, you are welcomed to take these two related issues instead: https://github.com/GreptimeTeam/greptimedb/issues/3799 and https://github.com/GreptimeTeam/greptimedb/issues/3798
