### ISSUE TITLE
Support printing postgresql's `bytea` data type in its "hex" and "escape" format

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3438]
### What problem does the new feature solve?

The `bytea` data type is the binary data type in pg. When we "select" it in GreptimeDB, the output is the raw byte string:

```text
public=> CREATE TABLE test(b BLOB, ts TIMESTAMP TIME INDEX);
OK 0
public=> INSERT INTO test VALUES(X'616263', 1687867163);
OK 1
public=> select * from test;
   b    |             ts             
--------+----------------------------
 616263 | 1970-01-20 12:51:07.163000
(1 row)
```

The inserted value is a hex string "616263", which is "abc" in ascii. 

In pg, however, that binary value can be outputted as different formats:

```text
luofucong=# CREATE TABLE test(b bytea, ts bigint);
CREATE TABLE
luofucong=# INSERT INTO test VALUES('\x616263', 1);
INSERT 0 1
luofucong=# set bytea_output = 'hex';
SET
luofucong=# select * from test;
    b     | ts 
----------+----
 \x616263 |  1
(1 row)

luofucong=# set bytea_output = 'escape';
SET
luofucong=# select * from test;
  b  | ts 
-----+----
 abc |  1
(1 row)
```

### What does the feature do?

The pg has a [`SET bytea_output`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-BYTEA-OUTPUT) client configuration to set the output format of the binary value. We could support that as well to offer better usage experience for pg users. The details can be found [here](https://www.postgresql.org/docs/current/datatype-binary.html).

### Implementation challenges

- This client configuration is pg only. So the impl is best to be confined to pg related mods in crate `servers`. That means the actual "set" impl shouldn't be placed in our general stmt executor. However, currently there're none places in the pg related mods that can handle "set"s. This is the first problem to solve.
- Also since this feature is pg only, we should find a way to save the configuration in the client (or session) context that belongs to pg only. Currently there're none either.

**Comment by MichaelScofield** [comment]
@J0HN50N133 Thanks, feel free to take them and ask any questions!

**Comment by MichaelScofield** [comment]
@J0HN50N133 Since it's pg only, I think a more suitable place for it is `pgwire::api::ClientInfo`. It has a "metadata" hashmap we can use to store and retrieve the `bytea_output` set by the pg client. @sunng87 can we use the "metadata" like this?

**Comment by J0HN50N133** [comment]
I guest `extension` is to add some client' specific infomation, and prom_store already have code like:

```
new_query_ctx​.​set_extension​(​PHYSICAL_TABLE_PARAM​,​ physical_table​)​;
```
`PHYSICAL_TABLE_PARAM` should be a prom only parameter.

**Comment by MichaelScofield** [comment]
Yes, the `extension` has been used that way, but it's better for pg-only things stay in pg-only codes.

**Comment by J0HN50N133** [comment]
After reading more codes, I think it's more reasonable to just use `query_context` to pass the `bytea` value and update it's value in current session like this way [set timezone](https://github.com/GreptimeTeam/greptimedb/blob/main/src/servers/src/postgres/handler.rs#L58-L59) do. But I'm not sure whether it's a good idea to add a field call `bytea_format` which is very specific, or add a container to hold more session variables like `bytea_format`, `datestyle` and etc.

**Comment by MichaelScofield** [comment]
`bytea_format` is pg only, better not set in general query context. On the other hand, "timezone" is more general, ok to be put in the general query context.

**Comment by J0HN50N133** [comment]
`query_context` only pass variable value(It's not a good idea to 
access pgserverhandler directly in query_engine for such an easy feature). And value will finally be set in pg related session.

**Comment by J0HN50N133** [comment]
```rust
// src/session/src/context.rs
pub struct ParameterConfiguration {
    // The name of the parameter should be constant
    param_name: &'static str,
    value: Value,
}

pub struct QueryContext {
    ...
    // The configuration parameters are used to store the parameters that are set by the user
    #[builder(default)]
    configuration_parameters: Option<ParameterConfiguration>,
}

// context.rs
impl QueryContext {
    pub fn update_session(&self, session: Session) {
        ...
    }
}

// src/operator/src/statement.rs
fn set_configuration_parameters(exprs: Vec<Expr>, ctx: QueryContextRef) -> Result<()>{
    ... // just set the configuration_parameters field in ctx here
}

// src/session/src/lib.rs
pub struct Session{
    ...
    configuration_parameters: DashMap<&'static str, Value> // parameter name -> parameter value
}

impl Session {
    fn set_configuration_parameters(param: ParameterConfiguration){
        match self.conn_info.channel {
            Postgres => { invoke update function writen in postgres.rs }
            Mysql => todo!()
        }
    }
}
```

Here's what I'm going to do to support both `bytea_format` and `datestyle`, I think by this design most pg related code will only appears in postgres server.

**Comment by MichaelScofield** [comment]
Looking forward to your PR!

**Comment by sunng87** [comment]
> @sunng87 can we use the "metadata" like this?

Sorry, just saw this. Sure we can use metadata to store postgres specific session variables.
