### ISSUE TITLE
Support outputting various date styles for postgresql

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3442]
### What problem does the new feature solve?

Very similar to https://github.com/GreptimeTeam/greptimedb/issues/3438, currently the GreptimeDB lacks the support for outputting various date styles in pg.

### What does the feature do?

Impl the "[`SET datestyle`](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-OUTPUT)" for pg client, to print the desired formatted date string for pg users.

### Implementation challenges

Same as https://github.com/GreptimeTeam/greptimedb/issues/3438

**Comment by MichaelScofield** [comment]
@J0HN50N133 assigned this to you too!

**Comment by v0y4g3r** [comment]
@J0HN50N133 Please comment on this issue so that I can assign it to you.

**Comment by J0HN50N133** [comment]
> @J0HN50N133 Please comment on this issue so that I can assign it to you.

👌
