### ISSUE TITLE
tql eval supports SQL functions for start, end and step.

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3452]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

Current `tql eval` parser only accepts timestamp literal as `start` and`end` parameter, for example:

```sql
TQL eval (1677057993, 1677058993, '1m') rate(prometheus_http_requests_total{job="prometheus"}[5m]);
```

Refer to https://docs.greptime.com/reference/sql/tql#eval

I think it's better to accept SQL functions such as `now()` for these parameters:

```sql
TQL eval ((now() - '5 minute'::interval)/1000, now()/1000, '1m') rate(prometheus_http_requests_total{job="prometheus"}[5m]);
```

Additionally, it would be beneficial if we could simplify the syntax by adding some syntactic sugar:

```sql
TQL eval(now - '5m', now, '1m') rate(prometheus_http_requests_total{job="prometheus"}
```

**Comment by etolbakov** [comment]
@killme2008 happy to give it a go
