### ISSUE TITLE
Tracking issue of painless integrating with Grafana via Prometheus plugin

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3492]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Follows https://github.com/GreptimeTeam/greptimedb/issues/1016, where some necessary APIs are implemented.

This issue is to track unexpected behavior or unimplemented features when connecting GreptimeDB with Grafana via its official Prometheus plugin.

- [x] #3496
- [x] #3497

**Comment by tisonkun** [comment]
Once we're sure about the issue, perhaps open a subtask issue and link here. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists.

**Comment by yuanbohan** [comment]
I have tested Prometheus datasource in Grafana 10.0, and the following is the metadata Grafana needs:

| Path                                                                    | Form values                      | Query strings                                               |
|-------------------------------------------------------------------------|----------------------------------|-------------------------------------------------------------|
| POST <host>/api/v1/query                                                | query=1+1, time=4                | empty                                                       |
| GET <host>/api/v1/label/__name__/values?start=1710289581&end=1710311181 | empty                            | start=1710289581,end=1710311181                             |
| POST <host>/api/v1/labels                                               | start=1710289583,end=1710311183, | empty                                                       |
| GET <host>/api/v1/metadata                                              | empty                            | empty                                                       |
| POST <host>/api/v1/series                                               | empty                            | start=1710289589,end=1710311189,match=["{__name__=\"up\"}"] |

**Comment by waynexia** [comment]
This should be done
