### ISSUE TITLE
Inconsistent and incorrect behaviour when writing zero-value metrics with Prometheus remote write

### ISSUE THREAD

**Issue by dekelpilli** [GreptimeTeam/greptimedb#3495]
### What type of bug is this?

Data corruption, Incorrect result

### What subsystems are affected?

Write Protocols

### Minimal reproduce step

1. Start greptime via docker with default config (standalone or cluster works the same)
```sh
docker run -p 4000-4003:4000-4003 \
-p 4242:4242 -v "$(pwd)/greptimedb:/tmp/greptimedb" \
--name greptime --rm \
greptime/greptimedb standalone start \
--http-addr 0.0.0.0:4000 \
--rpc-addr 0.0.0.0:4001 \
--mysql-addr 0.0.0.0:4002 \
--postgres-addr 0.0.0.0:4003 \
--opentsdb-addr 0.0.0.0:4242
```
2. Send metrics via the remote write endpoint (`http://localhost:4000/v1/prometheus/write?db=public`). Send both 0 and non-0 values, and in different orders.
3. Query results (`curl --location 'http://localhost:4000/v1/sql?db=public' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'sql=select * from <MY_METRIC_NAME_HERE>;'` 

### What did you expect to see?

Metrics are written correctly regardless of their value.

### What did you see instead?

One of the following happens when writing metrics with value=0:
1.  Metric don't get written at all
2. Metric is written, maybe with a different value (sometimes the same value as the last one received, or some other number - it's hard to find a pattern for this, or 0 if it was the first time a metric was written in that cluster). I believe that giving a random value happens in clustered deployments, and using the latest value happens in standalone deployments, but I can't say that for sure.
3. The last written metric is deleted
4. The last written metric is overridden

I wasn't able to determine a pattern for which one of these happens, but I think option 2 is the most common.

### What operating system did you use?

Docker (on both Debian x86_64 and Mac OS 14.3.1 arm64). Reproducing this locally without docker was less consistent, but was still reproduced sometimes.

### What version of GreptimeDB did you use?

0.7.0

**Comment by waynexia** [comment]
Hi @dekelpilli, thanks for reporting this issue.

Could you please check at greptimedb's log? Under `/tmp/greptime/logs`? And please paste the error log if there is any.

>The last written metric is deleted

BTW, what's the sample data you wrote? And what do you mean by "is deleted" or "overridden", was some data seen and then gone?

**Comment by dekelpilli** [comment]
There were times where the last data written disappeared, and times where its value simply changed, but both of these are less common from my tests.

I wrote my data using [Vector](https://vector.dev/docs/reference/configuration/sinks/prometheus_remote_write/) for convenience, but this was also reproduced by others on the team using other software. An example of data I just sent is:
```json
{"name":"a","timestamp":"2024-03-13T06:33:36.338976Z","kind":"absolute","gauge":{"value":10.0}}
{"name":"a","timestamp":"2024-03-13T06:33:38.009689Z","kind":"absolute","gauge":{"value":20.0}}
{"name":"a","timestamp":"2024-03-13T06:33:39.398560Z","kind":"absolute","gauge":{"value":30.0}}
{"name":"a","timestamp":"2024-03-13T06:33:40.187230Z","kind":"absolute","gauge":{"value":0.0}}
{"name":"a","timestamp":"2024-03-13T06:38:39.996856Z","kind":"absolute","gauge":{"value":0.0}}
{"name":"a","timestamp":"2024-03-13T06:38:40.519822Z","kind":"absolute","gauge":{"value":0.0}}
{"name":"a","timestamp":"2024-03-13T06:39:28.207640Z","kind":"absolute","gauge":{"value":15.0}}
{"name":"a","timestamp":"2024-03-13T06:39:31.133972Z","kind":"absolute","gauge":{"value":0.0}}
{"name":"a","timestamp":"2024-03-13T06:39:33.764091Z","kind":"absolute","gauge":{"value":1.0}}
{"name":"a","timestamp":"2024-03-13T06:39:35.902828Z","kind":"absolute","gauge":{"value":0.0}}
```

With the relevant resulting data being:
```json
...
                    [
                        1710311616338,
                        10.0
                    ],
                    [
                        1710311618009,
                        20.0
                    ],
                    [
                        1710311619398,
                        30.0
                    ],
                    [
                        1710311620187,
                        20.0
                    ],
                    [
                        1710311919996,
                        30.0
                    ],
                    [
                        1710311920519,
                        20.0
                    ],
                    [
                        1710311968207,
                        15.0
                    ],
                    [
                        1710311971133,
                        15.0
                    ],
                    [
                        1710311973764,
                        1.0
                    ],
                    [
                        1710311975902,
                        1.0
                    ]
...
```

As you can see from the data at `1710311620187`-`1710311920519`, it doesn't always just take the last value when receiving a 0, but it often does (as it did on `1710311971133` and `1710311975902`).
[These are the logs from the test in this comment, which was a fresh standalone deployment via docker. ](https://github.com/GreptimeTeam/greptimedb/files/14583407/log.txt)

**Comment by waynexia** [comment]
>It's also worth noting that writing metrics to tables using the metrics engine hasn't caused this issue when writing with Influx Line Protocol or SQL inserts, only when writing with Prometheus Remote Write.

This information is valuable. Still using vector but with Influx Line Protocol doesn't cause this issue, right?

I'm trying to reproduce this in my environment, please wait for a while. How did you get those JSON values, Is it from vector or something else?

>These are the logs from the test in this comment, which was a fresh standalone deployment via docker. 

Sadly I cannot open that log. Maybe it's not finished uploading before you post reply?
<img width="319" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/15380403/05f282ea-9dae-4850-ba46-3ac15ae43510">

**Comment by dekelpilli** [comment]
The JSON values are output by Vector and represent the data it self via PRW. 

The Influx Line Protocol tests were done using our own application, not Vector.

I think github is having issues with file uploads, I've reuploaded both here, but these are both temporary links - 

[These are the logs from the test in this comment, which was a fresh standalone deployment via docker.](https://file.io/nko4J0tHpxNx)

[These are logs from a non-docker standalone deployment that had these issues.](https://file.io/MCRTHc4ZMRVT)

**Comment by waynexia** [comment]
Thanks, I've got those files 👍

**Comment by waynexia** [comment]
Hi @dekelpilli, sorry for the inconvenience 😖 I've submitted a PR https://github.com/GreptimeTeam/greptimedb/pull/3505 that fixes this issue in my environment. Could you please give it a try? A CI is building the artifacts https://github.com/GreptimeTeam/greptimedb/actions/runs/8268482091

**Comment by dekelpilli** [comment]
Hi, I've tested against a binary from that CI and the problem seems to be fixed. Thanks!

**Comment by dekelpilli** [comment]
Just adding that v0.7.1 fixed this issue, both docker and non-docker, and both clustered and standalone, thanks again!

**Comment by waynexia** [comment]
> Just adding that v0.7.1 fixed this issue, both docker and non-docker, and both clustered and standalone, thanks again!

Thank you for helping improve GreptimeDB :heart:
