### ISSUE TITLE
Error when saving GreptimeDB as Prometheus data source

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3496]
> readNumberAsString: invalid number, error found in #10 byte of ...|"result":[{"metric":|..., bigger context ...|"success","data":{"resultType":"scalar","result":[{"metric":{"__name__":""},"values":[],"value":[4.0|... - There was an error returned querying the Prometheus API.

**Comment by Finnmccarthy** [comment]
Also having the same issue while attempting to add greptimedb as a Prometheus data source in Grafana. Are there any work arounds for this issue?

> readNumberAsString: invalid number, error found in #10 byte of ...|"result":[{"metric":|..., bigger context ...|"success","data":{"resultType":"scalar","result":[{"metric":{"__name__":""},"values":[],"value":[4.0|... - There was an error returned querying the Prometheus API.

**Comment by waynexia** [comment]
> Also having the same issue while attempting to add greptimedb as a Prometheus data source in Grafana. Are there any work arounds for this issue?
> 
> > readNumberAsString: invalid number, error found in #10 byte of ...|"result":[{"metric":|..., bigger context ...|"success","data":{"resultType":"scalar","result":[{"metric":{"**name**":""},"values":[],"value":[4.0|... - There was an error returned querying the Prometheus API.

Just ignore this error should be fine. The data source is configured successfully.

**Comment by tisonkun** [comment]
@waynexia Thanks for your information. But why do we get this error message? Could we get rid of it?

**Comment by waynexia** [comment]
Working on it... PR this afternoon
