### ISSUE TITLE
The link of roadmap in official is outdated

### ISSUE THREAD

**Issue by okJiang** [GreptimeTeam/greptimedb#3504]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Other

### Minimal reproduce step

![image](https://github.com/GreptimeTeam/greptimedb/assets/23556834/aa4305d4-3682-47bc-acc3-598e034920fd)

### What did you expect to see?

Show the roadmap

### What did you see instead?

![image](https://github.com/GreptimeTeam/greptimedb/assets/23556834/99c7a9e0-5dba-4944-9510-5bbddca6c4d6)

### What operating system did you use?

mac

### What version of GreptimeDB did you use?

none

**Comment by okJiang** [comment]
Sorry I didn't find the official repo, so I file it here

**Comment by tisonkun** [comment]
Thanks for your reporting. I'll handle it tomorrow.

And yes, the official website is held outside a public repo.

**Comment by waynexia** [comment]
Maybe we should add a broken link checker in CI?

**Comment by tisonkun** [comment]
> Maybe we should add a broken link checker in CI?

Make sense. Would you create an issue there? The challenging part is that some internal links are not full resolved. But we may at least check broken links for the prod website regularly.
