### ISSUE TITLE
Maintains physical table's schema

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3513]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Maintain the physical table's schema to make it queryable.

- [x] Extend the region server's interface. Make it possible to return an extra customized map https://github.com/GreptimeTeam/greptime-proto/pull/138
- [x] Return physical schema's change in metric engine https://github.com/GreptimeTeam/greptimedb/pull/3533
- [ ] Receive and process physical schema's change in meta server

**Comment by killme2008** [comment]
@WenyXu @waynexia Is it done?

**Comment by fengjiachun** [comment]
This is done; I'll close it.
