### ISSUE TITLE
Support altering column's data type

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3517]
### What problem does the new feature solve?

Sometimes user just want to modify the column's data type.

### What does the feature do?

Make column's data type changeable via "alter column" stmt. For example, in mysql:
```sql
ALTER TABLE t1 MODIFY b INT
```
(see https://dev.mysql.com/doc/refman/8.0/en/alter-table.html). Or in postgresql:
```sql
ALTER TABLE t1 ALTER COLUMN b TYPE varchar(80)
```
(see https://www.postgresql.org/docs/current/sql-altertable.html).

We might want to go with mysql's "alter column" syntax for the conciseness.

One critical consideration is how to deal with un-convertable data. For example, when you modify the column from string to int, how to deal with the un-convertable data of "a"? In mysql, this results in an error:
```text
mysql> select * from foo;
+------+
| s    |
+------+
| a    |
| 1    |
+------+
2 rows in set (0.01 sec)

mysql> alter table foo modify s int;
ERROR 1366 (HY000): Incorrect integer value: 'a' for column 's' at row 1
mysql> show create table foo;
+-------+----------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                       |
+-------+----------------------------------------------------------------------------------------------------+
| foo   | CREATE TABLE `foo` (
  `s` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
In postgresql, it's error, too:
```text
postgres=# select * from foo;
 s
---
 a
 1
(2 rows)

postgres=# ALTER TABLE foo ALTER COLUMN s TYPE int;
ERROR:  column "s" cannot be cast automatically to type integer
HINT:  You might need to specify "USING s::integer".
postgres=# ALTER TABLE foo ALTER COLUMN s TYPE int using s::integer;
ERROR:  invalid input syntax for type integer: "a"
postgres=# \d foo
               Table "public.foo"
 Column | Type | Collation | Nullable | Default
--------+------+-----------+----------+---------
 s      | text |           |          |
```
(Interestingly, postgresql has a "hint" to let user specify the data convention method. We might want to do the same.)

So it's clear that we'd better follow their steps and return some errors complaining some data are just not convertable to the target type.

### Implementation challenges

The performance is clearly the most challenging part. If we actually change the data's type in the underlying storage, we might need to rewrite all the affected ssts, which can be a lot of work. If we change the reader (so that the data is converted on the fly), it brings extra query cost. Neither is good.

**Comment by KKould** [comment]
> we might need to rewrite all the affected ssts

it is unacceptable to simply overwrite old data, which will lead to a large number of IO operations and high maintenance costs. the reasonable way is to convert the data immediately after executing `ModifyColumn` in a short time, and fix the type when the sstable is compacted.

I think `ModifyColumn` can be decomposed into `AddColumn` and `DropColumn` working at the same time

I recently checked the processing logic related to Alter, and I found that `AddColumn` and `DropColumn` only modify the Schema information during processing, and there are two reading ways when reading data: `ParquetReader` and `CompatReader`. Among them, I think `CompatReader` is responsible for processing Alert schema differences. In `CompatReader`, we can set the `index_or_defaults` of the new Column's `CompatFields` to the old Column's Index and convert the type (so we need to generate a new type in `IndexOrDefault` to perform type conversion based on the index of the old data?)

But this way will cause the Column id to change, is this acceptable?

**Comment by KKould** [comment]
Step for modify column
- Parser supports `Modify Column`: https://github.com/sqlparser-rs/sqlparser-rs/pull/1216
- add `ModifyColumn` on `AlterTableOperation` and `alter_expr::Kind`(greptime-proto)
- mapping `alter_expr::Kind::ModifyColumn` to process the logic of modify column
  - [src/table/src/metadata.rs](https://github.com/GreptimeTeam/greptimedb/pull/3701/files#diff-1dcf594e08caeaea086f669d4d1a612ebd26a80be7dfd98fec11a7ceeefa2357): build new `TableMetaBuilder`
  - [src/store-api/src/region_request.rs](https://github.com/GreptimeTeam/greptimedb/pull/3701/files#diff-839e23ed322c90eacc42fdddeb1f7108335e6434eba0a7a1c6dbc42052a8b9e9): mapping and validate `ModifyColumns`
  - [src/store-api/src/metadata.rs](https://github.com/GreptimeTeam/greptimedb/pull/3701/files#diff-cf4d268d2f2a7ed314bd2930b764cc815f392b3f9be34bc5aa8578a2d1d984bf): use `ModifyColumn` to change `RegionMetadata`
  - [src/common/meta/src/ddl/alter_table/region_request.rs](https://github.com/GreptimeTeam/greptimedb/pull/3701/files#diff-5a410878ae31b9744ee32e84651fe7279cc6068f21e8819608c352459f5730f4): mapping `ModifyColumns`
- `CompatReader` supports Column Cast
  - Tips: the data needs to be type converted before the next compaction, so there is a column type conversion performance problem when reading.

How it works?: https://github.com/GreptimeTeam/greptimedb/pull/3701#issuecomment-2056265559

## There is still one issue that has not yet been resolved:

When modify column, it need to read all the data in this column of the table and check whether each piece of data can be converted e.g. `String` is type-convertible to `Integer`, but `hello` cannot be converted to `Integer`. 

How do I implement it in `src/store-api/src/region_request.rs` `ModifyColumn::validate`(I think it's best handled here)?

**Comment by KKould** [comment]
> Maybe we can specify which value to fill in the `ALTER` statement.

I love this idea and will implement it when PR: https://github.com/sqlparser-rs/sqlparser-rs/pull/1216 is merged if you think my steps are feasible

**Comment by evenyag** [comment]
We can build this feature in a bottom-up pattern. Let's modify the `CompatReader` first. Then we can implement altering column type in the `mito2` engine and other engines. The parser support should be the last step. This ensure that we don't leak an unimplemented feature to users.

**Comment by KKould** [comment]
Got it, then I will implement it in the reverse order of steps

**Comment by WenyXu** [comment]
Hi @KKould, We support flushing and compacting a table via SQL. Would you like to add a fuzz test for column type alteration after #3796?

**Comment by evenyag** [comment]
> Hi @KKould, We support flushing and compacting a table via SQL. Would you like to add a fuzz test for column type alteration after #3796?

We might also add some tests in this file. For example: insert data, change column type, insert data, scan

https://github.com/GreptimeTeam/greptimedb/blob/main/src/mito2/src/engine/alter_test.rs

**Comment by KKould** [comment]
> Hi @KKould, We support flushing and compacting a table via SQL. Would you like to add a fuzz test for column type alteration after #3796?

yep, after https://github.com/GreptimeTeam/greptimedb/pull/3796 merged
