### ISSUE TITLE
Support partition by time interval, automatically

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3523]
### What problem does the new feature solve?

For some use case, it's good to have data partitioned by some time interval. For example, the dominant queries are finding the data in a day, or joining the data across some days. The filters (in "where" clause) all carry the same pattern: "`where ts >= '2024-01-01 00:00:00' and ts < '2024-01-02 00:00:00'`". We can of course handle these queries under current implementation that all data stored in a table (region), but it brings some limitations for performance improvement. If the data can be automatically partitioned by some time interval, we can do more parallel work on these kinds of queries. Besides, separating the data might just result in separating the storage location. Which is good for resource usage like io, or good for backup and restore.

### What does the feature do?

Partitioning the data by some user specified time interval when creating the table. It could be implemented by automatically creating a new region for each time interval. For example, a new region for a new day. The main work are:
- [ ] Design a new partition syntax for this
- [ ] Implement the auto creating region feature; properly modify the region route is the difficult part
- [ ] Might need to change some read/write mechanics accordingly.

**Comment by evenyag** [comment]
https://github.com/GreptimeTeam/greptimedb/pull/3501 already supports partitioning memtables by time
