### ISSUE TITLE
Metric engine ingestion performance degradation

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#3555]
### What type of bug is this?

Performance issue

### What subsystems are affected?

Storage Engine

### Minimal reproduce step

Run prometheus benchmark against latest commit.

### What did you expect to see?

The same ingestion performance as v0.7

### What did you see instead?

With v0.7 we can get ingestion rate at 600k points per second, while witglatest commit it's only roughly 400k.

<img width="1158" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/6406592/fe88676c-9429-4002-b47f-d2682459273d">

### What operating system did you use?

NA

### What version of GreptimeDB did you use?

latest

**Comment by v0y4g3r** [comment]
That's possibly introduced by some configuration change in recent commits.

**Comment by waynexia** [comment]
The peak throughputs are similar, would some flush-related job cause it?

**Comment by v0y4g3r** [comment]
> The peak throughputs are similar, would some flush-related job cause it?

It's caused by `fork_dictionary_bytes`. I'll draft a pr to fix this.
