### ISSUE TITLE
Supporting InfluxDB's "InfluxQL" as a query language

### ISSUE THREAD

**Issue by austin-barrington** [GreptimeTeam/greptimedb#3557]
## Overview:
Integrating support for InfluxQL within GreptimeDB will streamline the migration process for users currently leveraging InfluxDB v1. By aligning GreptimeDB's query language with InfluxQL, users can seamlessly transition to GreptimeDB without the need for extensive modifications to their existing systems.

## Benefits:
**Seamless Migration:** Users of InfluxDB v1 can effortlessly transition to GreptimeDB, leveraging their existing knowledge and infrastructure without the burden of relearning a new query language. This ensures a smooth transition process and minimizes disruptions to workflows.

**Drop-in Replacement:** With GreptimeDB already supporting InfluxDB v1 writing, adding support for InfluxQL further solidifies its position as a preferred choice for users seeking a drop-in replacement solution. This enhances GreptimeDB's versatility and appeal to a broader user base.

## Why Prioritize This Feature?

Given GreptimeDB's existing compatibility with InfluxDB v1 writing, prioritizing support for InfluxQL is a logical step forward. By accommodating InfluxQL, GreptimeDB not only expands its compatibility with existing systems but also strengthens its market position as a flexible and user-friendly solution.

_Please let me know if this is a duplicate issue somewhere_

### What does the feature do?

Adds support for the InfluxQL language to be used to query GreptimeDB.

https://docs.influxdata.com/influxdb/v1/query_language/

**Comment by waynexia** [comment]
Thanks for your advice!

>Please let me know if this is a duplicate issue somewhere

Actually, there was one https://github.com/GreptimeTeam/greptimedb/issues/2598. 

We did consider adding support of InfluxQL, but finally decided not to do so, for some reasons:
- As for time-series scenario, we have already supported PromQL for querying data
- Given that InfluxQL is quite similar (in syntax) to SQL but has many differences in logic, supporting both of them may cause unnecessary confusing
- For a full-featured analytic scenario, we believe SQL is a better choice from flexibility to acceptance. Thus most of our work in query functionality is focused on this.
- Third-party DSL without a vast ecosystem might be short-lived. [Flux](https://www.influxdata.com/blog/the-plan-for-influxdb-3-0-open-source/#heading4) itself is an example

>Seamless Migration: Users of InfluxDB v1 can effortlessly transition to GreptimeDB, leveraging their existing knowledge and infrastructure without the burden of relearning a new query language. This ensures a smooth transition process and minimizes disruptions to workflows.
>
>Drop-in Replacement: With GreptimeDB already supporting InfluxDB v1 writing, adding support for InfluxQL further solidifies its position as a preferred choice for users seeking a drop-in replacement solution. This enhances GreptimeDB's versatility and appeal to a broader user base.

As you mentioned above, we have supported Influx Line Protocol in the write path, so GreptimeDB is now fully applicable as a drop-in replacement to InfluxDB as a sink. And we are composing a migration guidance on how to transform your existing InfluxQL queries into SQL, to help a more smooth transition process and a better future evolution.

**Comment by sunng87** [comment]
hi @austin-barrington , @GreptimeTeam develoer here. In additional the explanation from @waynexia , I would like to know if you are using or plan to use GreptimeDB as an influxdb alternative? If so, we would like to learn about your use-case and to see if we can help you with the switch. You can send email to sunning@greptime.cloud for further discussion.

**Comment by austin-barrington** [comment]
Hey @waynexia, thank you for your detailed response. Your points are a really good reason to not support it.

@sunng87 I'll drop you an email to chat some more.

Feel free to close this one out for now.

**Comment by sunng87** [comment]
Thank you @austin-barrington . I will close this for now and discuss with you via email
