### ISSUE TITLE
Compatible with Postgres system catalog

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3560]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Since we want to support users to access GreptimeDB with psql, we'd better be more compatible when possible.

Currently, when you run `psql -l` against GreptimeDB, it would fail with:

```
psql: ERROR:  Failed to plan SQL: Error during planning: Table not found: greptime.pg_catalog.pg_database
```

### Implementation challenges

This should be similar to MySQL's information

**Comment by tisonkun** [comment]
Not quite easy. Seems related to some internal functions also:

```
Failed to execute query: SELECT d.datname as "Name",
       pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
       pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
       pg_catalog.array_to_string(d.datacl, '\n') AS "Access privileges"
FROM pg_catalog.pg_database d
ORDER BY 1; err=0: Table operation error, at src/frontend/src/instance.rs:272:14
1: Failed to plan statement, at /Users/tison/GreptimeWorkspace/greptimedb/src/operator/src/statement.rs:253:14
2: Failed to plan SQL, at src/query/src/planner.rs:90:14
...
```

**Comment by tisonkun** [comment]
And this is the query for "show tables" (`\dt`):

```
Failed to execute query: SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' WHEN 't' THEN 'TOAST table' WHEN 'f' THEN 'foreign table' WHEN 'p' THEN 'partitioned table' WHEN 'I' THEN 'partitioned index' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','p','')
      AND n.nspname <> 'pg_catalog'
      AND n.nspname !~ '^pg_toast'
      AND n.nspname <> 'information_schema'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 1,2; err=0: Table operation error, at src/frontend/src/instance.rs:272:14
1: Failed to plan statement, at /Users/tison/GreptimeWorkspace/greptimedb/src/operator/src/statement.rs:253:14
2: Failed to plan SQL, at src/query/src/planner.rs:90:14
```

**Comment by yihong0618** [comment]
I did some research about this before, it needs a lot work, and most of them had been done by risingwave, maybe you can use some code from them, and make less effort for this.

FYI: you can refer this issue. 
some of them can easily add in greptime others maybe need to add in pgwire

https://github.com/risingwavelabs/risingwave/issues/2954

**Comment by killme2008** [comment]
Yes, we are doing a lot of work to be compatible with MySQL, pg is our next goal.

**Comment by yihong0618** [comment]
> Yes, we are doing a lot of work to be compatible with MySQL, pg is our next goal.

One thing came to my mind that databend, risgingwave and greptime all using rust and all maybe have the need to implement protocols risingwave mainly for pg, and databend mainly for mysql, maybe you can extract something common and help each other, maybe its triple-win things.

**Comment by sundy-li** [comment]
Let's add pgwrite into databend!

**Comment by J0HN50N133** [comment]
I would like to get involved in this work.😊

**Comment by tisonkun** [comment]
@J0HN50N133 Welcome! You can take a look at how we implement the "information_schema" tables as a reference.

But I'm also still unaware of how to add the necessary functions or work it around.

**Comment by J0HN50N133** [comment]
To support `pg_catalog` related features. The main challenge is to support the [System Information Functions and Operators](https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO).
I will try to add a new schema called `pg_catalog` and related table for trivial cases like `\d` under `src/catalog/pg_catalog` and decide how to implement the system function according to what happen in `DFLogicalPlanner`.

**Comment by J0HN50N133** [comment]
While supporting `\dt`, i.e. the following sql statement, I met some problems:
```sql
SELECT n.nspname as "Schema",
  c.relname as "Name",
  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 't' THEN 'TOAST table' WHEN 'f' THEN 'foreign table' WHEN 'p' THEN 'partitioned table' WHEN 'I' THEN 'partitioned index' END as "Type",
  pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','p','')
      AND n.nspname <> 'pg_catalog'
      AND n.nspname !~ '^pg_toast'
      AND n.nspname <> 'information_schema'
  AND pg_catalog.pg_table_is_visible(c.oid)
ORDER BY 1,2;
```

1. **`n.oid = c.relnamespace`**, this predicate need a `namespace.oid: u32` to check equality,  which can be seen as `schema`'s `id` in greptime. However, there is no such thing like `schema_id` in current `SchemaManager`. https://github.com/J0HN50N133/greptimedb/blob/906abd61de5e6da4e2ae5bba3f13fea567509166/src/common/meta/src/key/schema_name.rs#L54
Should we add this field in `SchemaManager`? This may break backward compatibility.

2. `pg_get_userbyid`: it seems that user authentication is not supported in the open source codebase. Should I just return empty string?

**Comment by tisonkun** [comment]
@J0HN50N133 Thanks for pushing forward this ticket!

> pg_get_userbyid: it seems that user authentication is not supported in the open source codebase. Should I just return empty string?

Yeah. This is reasonable as a first implementation. cc @shuiyisong @zyy17 later we may consider how to integrate it with the plugin system to allow populate user info in this case.

> n.oid = c.relnamespace

Adding ID for schema can be a breaking change and introduce overload burden to overcome in this issue.

cc @killme2008 @waynexia  please take a look at this information schema related logics. A workaround can be using the schema name as "oid" in this place.

**Comment by J0HN50N133** [comment]
> @tisonkun 
> A workaround can be using the schema name as "oid" in this place.

The shortcomings is the potential incompatibility with existing pg eco.

**Comment by tisonkun** [comment]
> The shortcomings is the potential incompatibility with existing pg eco.

Yeah. Some how the type is different, but comparing should work.

cc @killme2008 @waynexia what's the affect if we try to add id to each schema?

**Comment by J0HN50N133** [comment]
Next I will try to support dbeaver connection to greptime, via pg protocol.
```sql
SELECT t.oid,t.*,c.relkind,NULL as base_type_name, d.description
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_class c ON c.oid=t.typrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON t.oid=d.objoid
WHERE t.typname IS NOT NULL
AND (c.relkind IS NULL OR c.relkind = 'c')
```

**Comment by sunng87** [comment]
@J0HN50N133 I just found that tables like `pg_class`, `pg_namespace` are hidden tables that available under all schemas, which means some client can run sql like:

```
SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relkind in ('r', 'p')
```

without calling `pg_catalog.pg_class`.

One idea is to resolve those table like `pg_class`, `pg_namespace` and etc. under any schema to `pg_catalog.*`

**Comment by tisonkun** [comment]
Closed as done.

Further issues and developments can open new tickets.
