### ISSUE TITLE
Migrate "orc-rs" to "datafusion-orc"

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3597]
### What type of enhancement is this?

Other

### What does the enhancement do?

Crate "orc-rs" has been public archived, we should migrate it to the superceded "datafusion-orc".

**Comment by MichaelScofield** [comment]
wait for https://github.com/GreptimeTeam/greptimedb/pull/3554

**Comment by WenyXu** [comment]
The `datafusion-orc` will release a stable version recently. 
See also: https://github.com/datafusion-contrib/datafusion-orc/issues/79

**Comment by WenyXu** [comment]
wait for https://github.com/datafusion-contrib/datafusion-orc/pull/83
