### ISSUE TITLE
Prometheus data write error.

### ISSUE THREAD

**Issue by FengZh61** [GreptimeTeam/greptimedb#3632]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Write Protocols

### Minimal reproduce step

When I access very little Prometheus data, it runs fine, when I access a lot of data, there are failures to write.
[1.txt](https://github.com/GreptimeTeam/greptimedb/files/14848658/1.txt)
[report-ed85ec80-5801-4ac1-96c5-c538ed669861.txt](https://github.com/GreptimeTeam/greptimedb/files/14848686/report-ed85ec80-5801-4ac1-96c5-c538ed669861.txt)
This is the first situation I've encountered where Prometheus has errors and greptimedb has errors on this side when I look at the data.
[2.txt](https://github.com/GreptimeTeam/greptimedb/files/14848706/2.txt)
[gp.log](https://github.com/GreptimeTeam/greptimedb/files/14848719/gp.log)
This is the second scenario I encountered where I created a new bucket to store the data. Also accessing Prometheus, which has a large amount of data, there is a problem with data writes, as well as problems with table structure creation and updates.

### What did you expect to see?

Large amount of data can be written successfully

### What did you see instead?

Large amounts of data writes can fail to be written, and it appears that before this write is processed, the next write task starts again, and these two are in direct conflict.

### What operating system did you use?

Centos 7.6

### What version of GreptimeDB did you use?

0.7.0

**Comment by waynexia** [comment]
This looks like a bug that was fixed in https://github.com/GreptimeTeam/greptimedb/pull/3576. It should be fixed in our newest version.

**Comment by waynexia** [comment]
Close as finished. Feel free to reopen if there is any update
