### ISSUE TITLE
Storing `impl IntoIterator<Item = Source>` instead of `Vec<Source>` in `MergeReaderBuilder`

### ISSUE THREAD

**Issue by cjwcommuny** [GreptimeTeam/greptimedb#3640]
### What type of enhancement is this?

Performance

### What does the enhancement do?

I woule like to open a pull request that replacing `Vec<Source>` with `impl IntoIterator<Item = Source>` in the `MergeReaderBuilder` to avoid unnecessary allocation.

https://github.com/cjwcommuny/greptimedb/blob/922b1a9b66a8f09ed25111e42e876917acc4cffb/src/mito2/src/read/merge.rs#L350-L357

**Comment by evenyag** [comment]
The builder also provides two methods to push a `Source` so we store the `Vec<Source>` in it.
https://github.com/GreptimeTeam/greptimedb/blob/86d377d028d592764109e4622ebd17bfc7710be4/src/mito2/src/read/merge.rs#L370-L380

The allocation of `Vec<Source>` isn't a bottleneck.
