### ISSUE TITLE
Release v0.7.2

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3645]
### What type of enhancement is this?

Other

### What does the enhancement do?

Prepare to release v0.7.2. Fixes
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3614
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3635

Other blockers:
- [x] ~~https://github.com/GreptimeTeam/greptimedb/pull/3626~~
- [x] https://github.com/GreptimeTeam/greptimedb/pull/3658
- [ ] ~~Fix SQL connection regression~~

**Comment by waynexia** [comment]
Release here https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.7.2

**Comment by waynexia** [comment]
`v0.7.2` is released here https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.7.2

**Comment by tisonkun** [comment]
@waynexia do we have a template for this release checklist? I'd like to add an item for sharing the news (announcement) on social media.

**Comment by waynexia** [comment]
I started to use this back to https://github.com/GreptimeTeam/greptimedb/issues/2994 to track ongoing PRs, but there is no formal template and the content changes slightly from time to time. 

Maybe we can list another post-release task tracker somewhere, and link to this one as one step in-release.

**Comment by waynexia** [comment]
BTW, I'm going to close this issue as the code release is done. Feel free to continue this conversation here.
