### ISSUE TITLE
impl Display for Statement

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3646]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

sqlparser's Statement implements Display, we need to implement Display for our Statement, named `sql::statement::Statement` also.

See 

```rust
match self.query_statement(stmt, query_ctx.clone()).await {
    Ok(output) => {
        let output_result =
            query_interceptor.post_execute(output, query_ctx.clone());
        results.push(output_result);
    }
    Err(e) => {
        let redacted = sql::util::redact_sql_secrets(query.as_ref());
        error!(e; "Failed to execute query: {redacted}");

        results.push(Err(e));
        break;
    }
}
```

We currently print all the query if any of the statement failed to execute. We should write instead:

```rust
match self.query_statement(stmt, query_ctx.clone()).await {
    Ok(output) => {
        let output_result =
            query_interceptor.post_execute(output, query_ctx.clone());
        results.push(output_result);
    }
    Err(e) => {
        error!(e; "Failed to execute query: {stmt}");

        results.push(Err(e));
        break;
    }
}
```

with `stmt` probably redacted. And formatting structural `stmt` would be more reliable to redact fields, instead of depending on brittle regexps.

**Comment by irenjj** [comment]
I'd like to give it a try.

**Comment by tisonkun** [comment]
@irenjj a reminder to confirm that you still work on this issue - do you find any trouble here?

**Comment by tisonkun** [comment]
@irenjj Thanks for your update! That's great.
