### ISSUE TITLE
Readonly table error message should not be Internal Error

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3653]
### What type of enhancement is this?

User experience

### What does the enhancement do?

```
mysql> SELECT * FROM build_info;
+---------------------+------------------------------------------+------------------+-----------+-------------+
| git_branch          | git_commit                               | git_commit_short | git_dirty | pkg_version |
+---------------------+------------------------------------------+------------------+-----------+-------------+
| checkpoint_checksum | 7e13a8edc970e5c3d383709dcbefda5f88c7fa77 | 7e13a8e          | false     | 0.7.1       |
+---------------------+------------------------------------------+------------------+-----------+-------------+
1 row in set (0.01 sec)

mysql> INSERT INTO build_info VALUES();
ERROR 1815 (HY000): Invalid SQL, error: column count mismatch, columns: 5, values: 0
mysql> INSERT INTO build_info VALUES('', '', '', '', '');
ERROR 1815 (HY000): Internal error: 1003
```

```
2024-04-07T14:27:24.166624Z ERROR on_query{protocol="mysql"}:mysql::do_query:do_query: frontend::instance: Failed to execute query: INSERT INTO build_info VALUES('', '', '', '', '') err=0: Table operation error, at src/frontend/src/instance.rs:272:14
1: Missing time index column, at src/operator/src/req_convert/insert.rs:39:10
2: Missing time index column in table: build_info, at src/operator/src/req_convert/insert.rs:36:10
```

We'd better to check readonly tables and return more friendly message.

**Comment by tisonkun** [comment]
@waynexia @killme2008 what do you think about the comment above?

IIRC read-only table is a different concept and we shouldn't depend on the coincidence it can be related to the existence of time-index column.

Also cc @MichaelScofield this can be related to the access control design. That is, no users should have write permission on these system tables.

**Comment by killme2008** [comment]
In this case, i think we can just treat all the tables in `information_schema` to be read-only. @killme2008 @CookiePieWw

**Comment by CookiePieWw** [comment]
@killme2008 Thanks! I'll try to add some error messages for it.

I've noticed that it's allowed to create a table inside `information_schema` currently, maybe we need to restrict that as well? Otherwise it would be strange that we could create a table but can't insert into it.

**Comment by killme2008** [comment]
> @killme2008 Thanks! I'll try to add some error messages for it.
> 
> I've noticed that it's allowed to create a table inside `information_schema` currently, maybe we need to restrict that as well? Otherwise it would be strange that we could create a table but can't insert into it.

Agree.
