### ISSUE TITLE
Change create database api's protobuf definition

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#3662]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

https://github.com/GreptimeTeam/greptimedb/pull/3626#issuecomment-2041364264

Change the `database_name` in `CreateDatabaseExpr` to `schema_name` for consistency across the API in [`greptime-proto`](https://github.com/GreptimeTeam/greptime-proto/pull/141/files#diff-0ed821e94d43a185b3d614664c9cb002098e18c785b4566c8387e8682d9c639aR74). Then update database's code accordingly.

**Comment by CookiePieWw** [comment]
Hi, I've made the change in https://github.com/GreptimeTeam/greptime-proto/pull/143, please take a look. I'll create a pr for database once merged to avoid multiple changes to the commit hash.

**Comment by tisonkun** [comment]
Cool! Thank you @CookiePieWw !
