### ISSUE TITLE
Rewrite the UDAF implementation under the new DataFusion

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3666]
### What type of enhancement is this?

Other

### What does the enhancement do?

The new DataFusion deprecates how its UDAF can be written before, specifically the `AggregateUDF::new`:

```rust
impl AggregateUDF {
    /// Create a new AggregateUDF
    ///
    /// See  [`AggregateUDFImpl`] for a more convenient way to create a
    /// `AggregateUDF` using trait objects
    #[deprecated(since = "34.0.0", note = "please implement AggregateUDFImpl instead")]
    pub fn new(
        name: &str,
        signature: &Signature,
        return_type: &ReturnTypeFunction,
        accumulator: &AccumulatorFactoryFunction,
        state_type: &StateTypeFunction,
    ) -> Self {
```

We should use the new implementation once https://github.com/GreptimeTeam/greptimedb/pull/3661 is merged.

**Comment by tisonkun** [comment]
Seems resolved along with https://github.com/GreptimeTeam/greptimedb/commit/314f2704d49d407e87152931b0050d677c8edc7a#diff-f1cdffa91eea1c701e5f2bde8a65fb8a02acb9788c051bbfee7fc0410f4b14aa.
