### ISSUE TITLE
Support TEXT type in MySQL codepath or core SQL path

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3703]
### What problem does the new feature solve?

This DDL failed:

```sql
CREATE TABLE t(ts TIMESTAMP TIME INDEX, payload MEDIUMTEXT);
```

```
ERROR on_query{protocol="mysql"}:mysql::do_query:do_query: frontend::instance: Failed to execute query: CREATE TABLE t(ts TIMESTAMP TIME INDEX, payload MEDIUMTEXT) err=0: Table operation error, at src/frontend/src/instance.rs:274:14
1: Failed to parse SQL, at src/operator/src/expr_factory.rs:318:18
2: SQL data type not supported yet: Custom(ObjectName([Ident { value: "MEDIUMTEXT", quote_style: None }]), [])
```

### What does the feature do?

Support more SQL data type to extend our scenarios. `MEDIUMTEXT` is necessary to use SkyWalking's MySQLTableInstaller and then integrates with SkyWalking as its data storage.

### Implementation challenges

I wonder if this can be a good first issue if it's no more than mapping TEXT to VARCHAR, or follow the impl path of VARCHAR and mapping it into String.

**Comment by CookiePieWw** [comment]
Hi, I'd like to try to implement this :). For me the former impl method seems reasonable since `MEDIUMTEXT` is similar to `TEXT` and `VARCHAR` with different maxium length according to [docs](https://mariadb.com/kb/en/mediumtext/) of mariadb. I wonder if there's some difference of the `TEXT` data type in greptimedb.

**Comment by tisonkun** [comment]
We actually store `Char` `Varchar` `Text` `String` all as String underneath. I support we can treat all the text as `DataType::Text`. Check the follow related code:

https://github.com/GreptimeTeam/greptimedb/blob/d2e081c1f9da11584e6a5d7dbb8532092dfe8ae2/src/sql/src/statements/transform/type_alias.rs#L134-L163
