### ISSUE TITLE
Limiting the size of query results to Dashboard

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3716]
### What type of enhancement is this?

User experience

### What does the enhancement do?

When the query results is huge, Dashboard could be easily crashed. For example, when user accidently `select * from` a table with millions of rows. Dashboard is mainly for humans, returning too many rows is of no use. We can limit the returned rows to 1000, iff the query comes from Dashboard.

**Comment by realtaobo** [comment]
I'd like to go ahead and fix this, it looks like I can start by adding a new `source enum` to the `QueryContext` to identify if it's a request from DashBorad or not, and then handle the flow inside the `post_parsing` (src/servers/src/interceptor.rs:95) function?
https://github.com/GreptimeTeam/greptimedb/blob/a68072cb21fb41c78a6a1ba9c3e4737b19fc06dc/src/frontend/src/instance.rs#L321-L323
@MichaelScofield How do you think this should be implemented, can you provide some suggestions?

**Comment by MichaelScofield** [comment]
@realtaobo I'd recommend doing it in `http::sql` handler, in file servers/src/http/handlers.rs. You can add the "source" in `struct SqlQuery`, and when it's "Dashboard", limits the output rows in `HttpResponse`.

**Comment by zyy17** [comment]
@MichaelScofield Some thoughts: Perhaps we should consider restricting SQL queries in the dashboard. For example, could we automatically append a `LIMIT 1000` statement when a `SELECT *` behavior is detected? It seems it's not common to handle such a specific scenario in greptimedb.

**Comment by MichaelScofield** [comment]
> @MichaelScofield Some thoughts: Perhaps we should consider restricting SQL queries in the dashboard. For example, could we automatically append a `LIMIT 1000` statement when a `SELECT *` behavior is detected? It seems it's not common to handle such a specific scenario in greptimedb. @ZonaHex What do you think?

I think it's better to do it in the db side. Adding the `limit` to the SQL might change how its logical plan is generated and optimized, making the final execution time shown in the Dashboard not real.

**Comment by zyy17** [comment]
@MichaelScofield makes sense. Another thought: Can we provide the parameters in http to control the returned result instead of changing the query? It seems more flexible(cc @realtaobo).

**Comment by MichaelScofield** [comment]
> @MichaelScofield makes sense. Another thought: Can we provide the parameters in http to control the returned size of the query result instead of changing the query? It seems more flexible(cc @realtaobo).

That's a doable alternative. However, currently only Dashboard needs this limit, let's make the parameters less and simple.

**Comment by zyy17** [comment]
> > @MichaelScofield makes sense. Another thought: Can we provide the parameters in http to control the returned size of the query result instead of changing the query? It seems more flexible(cc @realtaobo).
> 
> That's a doable alternative. However, currently only Dashboard needs this limit, let's make the parameters less and simple.

IMO, it's better to add a restriction for end users, and it's very easy to change the configs according to the users in different scenarios.

The current solution is very limited for the following scenarios:

- the dashboard users need to return more than 1000 results in pagination(the dashboard can process the results in pagination format);
- Some users need to change the limit;

**Comment by MichaelScofield** [comment]
> > > @MichaelScofield makes sense. Another thought: Can we provide the parameters in http to control the returned size of the query result instead of changing the query? It seems more flexible(cc @realtaobo).
> > 
> > 
> > That's a doable alternative. However, currently only Dashboard needs this limit, let's make the parameters less and simple.
> 
> IMO, it's better to add a restriction for end users, and it's very easy to change the configs according to the users in different scenarios.
> 
> The current solution is very limited for the following scenarios:
> 
> * the dashboard users need to return more than 1000 results in pagination(the dashboard can process the results in pagination format);
> * Some users need to change the limit;

The Dashboard is for manually peeking some data, rows more than 1000 is of little use, I think.

**Comment by ZonaHex** [comment]
For user experience, it's better to provide the parameter for end users to manually change the size restriction. 1000 as default perhaps.

**Comment by killme2008** [comment]
> For user experience, it's better to provide the parameter for end users to manually change the size restriction. 1000 as default perhaps.

Agree.

Furthermore,  it would be better if we can provide a function that downloads data for huge results.

**Comment by tisonkun** [comment]
@MichaelScofield @ZonaHex @killme2008 

> Furthermore, it would be better if we can provide a function that downloads data for huge results.

Yeah. I found this limiting can introduce a downside that if users would fetch the result set in a paginate manner, because we drop the result, it's impossible now.

BigQuery returns a [JobReference](https://cloud.google.com/bigquery/docs/reference/rest/v2/JobReference) on query and you can [fetch the rest result](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) paginate with it. However, this may require the server to stage the query result for a while.
