### ISSUE TITLE
Implement VIEW

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3729]
### What problem does the new feature solve?

The VIEW statement in SQL allows users to store complex queries in the database as virtual tables. This provides several benefits:

1. Simplifies complex queries: Views can encapsulate complex logic and querying requirements into a single easily accessible object. This can simplify the querying process for users by abstracting away the complexity of the underlying data model.
2. Data security: Views allow users to restrict access to certain rows or columns of a table, providing an additional layer of security. Users can only query the data that is exposed through the view, limiting their access to sensitive information.
3. Reusability: Views can be reused across multiple queries, reports, and applications. This promotes code reusability, reduces redundancy, and makes it easier to maintain and update the underlying database schema.
4. Performance optimization: Views can improve planning performance by caching the input plan.
5. Data abstraction: Views can hide the underlying data model complexity from users, providing a simplified and consistent interface to the database. This can be particularly useful in situations where users need to interact with a complex database schema.

### What does the feature do?

Implement `VIEW` like https://www.postgresql.org/docs/current/sql-createview.html

**Comment by waynexia** [comment]
Going to try it within one week

**Comment by waynexia** [comment]
> Point 4 is not for VIEW, at least the one linked. It's for MATERIALIZE VIEW. They're different concept and quite different in implementation.

Updated

**Comment by killme2008** [comment]
Tracking issues:

* [x] create view #3807 
* [x] query view #3952 
* [ ] view columns
* [ ] drop view
* [ ] show create view
* [ ] show views and `information_schema.views`
