### ISSUE TITLE
No error thrown when data overflows the `precision` param value in InfluxDB API

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#3739]
### What type of bug is this?

User Experience

### What subsystems are affected?

Frontend

### Minimal reproduce step

```shell
curl -v 'http://localhost:4000/v1/influxdb/api/v2/write?db=public&precision=s' \
    -d 'census,location=klamath,scientist=anderson bees=23 1566086400000000000
census,location=portland,scientist=mullen ants=30 1566086400000000000
census,location=klamath,scientist=anderson bees=28 1566086760000000000
census,location=portland,scientist=mullen ants=32 1566086760000000000'
```

### What did you expect to see?

An error should be thrown to indicate the data overflow problem.

### What did you see instead?

```shell
> POST /v1/influxdb/api/v2/write?db=public&precision=s HTTP/1.1
> Host: localhost:4000
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Length: 281
> Content-Type: application/x-www-form-urlencoded
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

### What operating system did you use?

Mac

### What version of GreptimeDB did you use?

0.7.2

**Comment by etolbakov** [comment]
I was curious how influxdb responds, this is the output 

```
curl -v -XPOST "localhost:8086/api/v2/write?bucket=public&org=MyOrgName&precision=s" \
  -d 'census,location=klamath,scientist=anderson bees=23 1566086400000000000'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Connected to localhost (127.0.0.1) port 8086 (#0)
> POST /api/v2/write?bucket=public&org=MyOrgName&precision=s HTTP/1.1
> Host: localhost:8086
> User-Agent: curl/8.0.1
> Accept: */*
> Content-Length: 70
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< X-Influxdb-Build: OSS
< X-Influxdb-Version: v2.7.5
< X-Platform-Error-Code: invalid
< Date: Thu, 18 Apr 2024 22:12:46 GMT
< Content-Length: 182
<
* Connection #0 to host localhost left intact
{"code":"invalid","message":"unable to parse 'census,location=klamath,scientist=anderson bees=23 1566086400000000000': time outside range -9223372036854775806 - 9223372036854775806"}%
```
if we would like to achieve parity in the behaviour, I can give it a go
please let me know @tisonkun

**Comment by tisonkun** [comment]
@etolbakov This issue can be related to https://github.com/GreptimeTeam/greptimedb/issues/3738.

After an offline discuss with @killme2008, we tend to store data written from ILP (InfluxDB Line Protocol) in nanoseconds always. This can change some of the related code path and actually a breaking change on API and schema.

You may refer to InfluxDB v3 implementation for more about how InfluxDB did it:

https://github.com/influxdata/influxdb/blob/main/influxdb3_write/src/write_buffer/mod.rs

```rust
fn validate_and_convert_parsed_line<'a>( ... ) -> Result<()> {
    // set the time value
    let time_value_nanos = line
        .timestamp
        .map(|ts| {
            let multiplier = match precision {
                Precision::Auto => match crate::guess_precision(ts) {
                    Precision::Second => 1_000_000_000,
                    Precision::Millisecond => 1_000_000,
                    Precision::Microsecond => 1_000,
                    Precision::Nanosecond => 1,

                    Precision::Auto => unreachable!(),
                },
                Precision::Second => 1_000_000_000,
                Precision::Millisecond => 1_000_000,
                Precision::Microsecond => 1_000,
                Precision::Nanosecond => 1,
            };

            ts * multiplier
        })
        .unwrap_or(ingest_time.timestamp_nanos());
}
```

I don't think we MUST follow it, but if there is no certain objection, we CAN follow it.

**Comment by tisonkun** [comment]
BTW, InfluxDB v3 implementation has also the overflow panic "bug". We can use sth like [`checked_mul`](https://doc.rust-lang.org/std/primitive.u64.html#method.checked_mul) to improve our case.

**Comment by etolbakov** [comment]
Thanks for response @tisonkun actually that's what I believed to be happening.  Personally, I don't see it as a big issue, so maybe it can be closed

**Comment by killme2008** [comment]
I understand that @fengjiachun is currently working on this.

**Comment by etolbakov** [comment]
ok, I'll drop my draft then, thanks again!

**Comment by etolbakov** [comment]
One thing that I've noticed that currently `precision` [is calculated](https://github.com/GreptimeTeam/greptimedb/blob/d077892e1c4246ea6fee49bc84352e63286815fe/src/servers/src/influxdb.rs#L90) on every iteration of the `for line in &lines {`.
Potentially it could be moved out of the for loop.

**Comment by killme2008** [comment]
> One thing that I've noticed that currently `precision` [is calculated](https://github.com/GreptimeTeam/greptimedb/blob/d077892e1c4246ea6fee49bc84352e63286815fe/src/servers/src/influxdb.rs#L90) on every iteration of the `for line in &lines {`. Potentially it could be moved out of the for loop.

Great insight! cc @fengjiachun
