### ISSUE TITLE
Benchmark suits 

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#378]
A proper benchmark suit (or suits) are useful to monitor and guide performance optimization. I find three suits as candidates:

- [x] ~~Prometheus `write` https://github.com/VictoriaMetrics/prometheus-benchmark~~
        - that suit requires a helm env to run, which is too complicated to be a nightly benchmark I think.
- [x] ~~TPC-H `read` https://github.com/apache/arrow-datafusion/blob/master/benchmarks/README.md~~
        - tpc-h schema doesn't have timestamp column
- [ ] @MichaelScofield  TSBS `write`/`read` https://github.com/timescale/tsbs  
        - not easy to integrate in. Consider making a more generic suit for us
- [x] NYC Taxi dataset #384 
- [ ] @waynexia Timeseries Data Generator

**Comment by killme2008** [comment]
We already fork a branch of tsbs https://github.com/GreptimeTeam/tsbs/

I closed this issue. The performance benchmark will be taken care of in 0.4
