### ISSUE TITLE
Move internal grpc client to test crate

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3798]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

For historic reason, there's an internal grpc client in crate "client" called "`Database`", for talking to Frontend's grpc service. Now it's mainly used in two places: one is in the cli data export tool, and the other is in tests. We can move the grpc client to test crate to make our codes more clear. And in the mean time, use other client (like mysql client, or simply http API) in our cli data export tool, to replace it.

**Comment by tisonkun** [comment]
This is the related struct:

https://github.com/GreptimeTeam/greptimedb/blob/e4101925607726481962000486b32c926d09a0f1/src/client/src/database.rs#L42-L58
