### ISSUE TITLE
Support table level comment

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#3836]
### What problem does the new feature solve?

Currently we only have column level comment. Adding table level comment can attach some information about the table, e.g: `the table is auto-created by schemaless write from influxdb line protocol`.

### What does the feature do?

1. add option for comment on `create table`
2. display the comment in `show create table`

an example table option on creation could be
```sql
CREATE TABLE if not exists monitor (
  host STRING,
  ts TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP() TIME INDEX,
  cpu FLOAT64 DEFAULT 0,
  memory FLOAT64,
  PRIMARY KEY(host)) ENGINE=mito WITH(COMMENT='create by human');
```

### Implementation challenges

tips:
1.  see [here](https://github.com/GreptimeTeam/greptimedb/blob/c387687262b77b752aadeee1821a00bc54327622/src/table/src/requests.rs#L42) for table option validation

**Comment by waynexia** [comment]
Reference: table comment parser in MySQLhttps://dev.mysql.com/doc/refman/8.0/en/create-table.html

**Comment by imp2002** [comment]
I'm interested in this task, can you assign it to me?

**Comment by tisonkun** [comment]
If we use `COMMENT="..."` we can reuse the `with: OptionMap` code. I don't know if sqlparser-rs supports `COMMENT "..."` syntax now.

**Comment by tisonkun** [comment]
It seems MySQL support `COMMENT="..."` also. We can thus reuse the options parse code and focus on conveying the comment.

**Comment by waynexia** [comment]
Just recall that there is a relative field in `TableInfo` for storing table comments:

https://github.com/GreptimeTeam/greptimedb/blob/777bc3b89da75313e2059af3f4fd3008f1726f5d/src/table/src/metadata.rs#L655-L657

We can consider extracting the comment from table option and storing it here.
