### ISSUE TITLE
Sort out repository labels

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3849]
### What type of enhancement is this?

Other

### What does the enhancement do?

We gradually define a lot of labels in this repository. To give developers an intuitive impression and avoid some common mistakes, I suppose we sort out the labels with a few best practices.

1. Retain automation labels. For example, dependabot uses `Dependency` label, and we just leave it as is. The [contribute](https://github.com/greptimeteam/greptimedb/contribute) page depends on `good first issue` label, and we should leave it as is.
2. Avoid whitespace. For other labels, avoid whitespace, so that we can parse it more reliably.
3. Drop `Difficulty` labels since it's often hard to say. We have `good first issue` to identify relative easy issue already; others are by default need some investigation.
4. Drop `Priority` labels since we don't use them.

So, following the pattern from [how CockroachDB defines labels](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/122060807/GitHub+Issue+Labels), I suppose we have the following labels:

* good first issue
* help wanted
* breaking-change
* release-blocker
* tracking-issue

Follow-ups: see https://github.com/GreptimeTeam/greptimedb/issues/3855.

Origins:

* O-fuzz (found by fuzz)
* O-end-to-end (found by end-to-end tests)
* O-chaos (found by chaos tests)

Area:

* A-metasrv
* A-storage
* A-observability
* A-compaction
* A-distributed-write
* A-distributed-query
* A-write
* A-query
* A-flow
* A-index
* A-metric-engine
* A-wal
* A-region-autopilot
* A-frontend

Category:

* C-bug
* C-user-experience
* C-enhancement
* C-feature
* C-performance

**Comment by tisonkun** [comment]
What do you think? cc @GreptimeTeam/db-approver

I'd correspondingly update the label, the automation, and issue templates.

**Comment by evenyag** [comment]
Looks good.

**Comment by tisonkun** [comment]
@evenyag Thanks for your review. For follow-ups label, I create #3855 for further discussion. The current solution is mixed, brittle and actually already has some edge cases.

**Comment by tisonkun** [comment]
Thanks for your feedback. I'll apply the changes before tomorrow.
