### ISSUE TITLE
Add cache for mirror insertion

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3863]
Seems we can cache all metadata of flow, like what we have done with table metadata. cc @WenyXu

_Originally posted by @fengjiachun in https://github.com/GreptimeTeam/greptimedb/pull/3858#discussion_r1590750564_

**Comment by Kelvinyu1117** [comment]
I'm interested in helping this issue.

**Comment by Kelvinyu1117** [comment]
No problem, I'm looking around and trying to find some outstanding tickets.
