### ISSUE TITLE
Implement `SHOW CREATE FLOW`

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3939]
### What problem does the new feature solve?

https://github.com/GreptimeTeam/greptimedb/pull/3806 implements the `CREATE FLOW` clause. This ticket requests a feature for displaying the statement used to create one flow. It's like the `SHOW CREATE TABLE` to `CREATE TABLE`

### What does the feature do?

Implement `SHOW CREATE FLOW` clause. The existing implementation of `SHOW CREATE TABLE` can be a reference.

https://github.com/GreptimeTeam/greptimedb/blob/a260ba3ee799856488e8b4c5d4be2029ef01b656/src/sql/src/statements/show.rs#L123-L126

**Comment by irenjj** [comment]
i'd like to take it, could you please assign it to me?
