### ISSUE TITLE
`show create table` doesn't work for `numbers`

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#3980]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Table Engine

### Minimal reproduce step

just run sql `show create table numbers`

### What did you expect to see?

sql statement for creating this table

### What did you see instead?

"Failed to find table route: 2"

### What operating system did you use?

any

### What version of GreptimeDB did you use?

HEAD

**Comment by tisonkun** [comment]
This is somehow not a bug. Because the `numbers` table is an internal immutable table and there is no way to create from user space.

However, we'd think of #1827 again.

**Comment by sunng87** [comment]
Actually using sql `show create table` is not for creating table but to see its definition and metadata. I think any table, or table-like object, that shows up in `show tables` and `information_schema.tables` should provide this ability.

Imagine that when you show table it says there is a table, but when you run `show create table` it says "failed to find table route", which sounds like an equivalent to "table not found".

**Comment by killme2008** [comment]
We can check the table type, it must be the `Base` type to show the table definition.

https://github.com/GreptimeTeam/greptimedb/blob/85a231850d85bd66c44295212198ce66027a33c7/src/table/src/metadata.rs#L76

Checking the table type in `show_create_table` and return an error if it's not `Base` type.

https://github.com/GreptimeTeam/greptimedb/blob/85a231850d85bd66c44295212198ce66027a33c7/src/operator/src/statement/show.rs#L83

It's a good first issue. Let me label it.

**Comment by sunng87** [comment]
I think we still need a solution to return `show create table` content for non-`Base` type.

Because the table type is never exposed to user. The user won't have chance to know if a table is capable for `show create table`

**Comment by killme2008** [comment]
We'll have other statements to support other table types, such as `show create view` or `show create flow`.

We already have #3939

**Comment by killme2008** [comment]
If you want to know the table metadata, you can use `desc table [table]`. 
The `show create table` is mainly used to get the sql definition of the table and can be used to execute it directly by users.
