### ISSUE TITLE
Implements Display for PartitionExpr

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#3985]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The `PartitionExpr` doesn't implement `Display` trait currently, so the `partition_expression` in `partitions` table is not user-friendly:

```
(a) VALUES LESS THAN (PartitionExpr { lhs: Column("a"), op: Lt, rhs: Value(Int32(10)) })
```

It must be ` a < 10` instead.

Related code:

https://github.com/GreptimeTeam/greptimedb/blob/c71298d3d52eacde037665e07771242e6506d987/src/partition/src/expr.rs#L25

https://github.com/GreptimeTeam/greptimedb/blob/c71298d3d52eacde037665e07771242e6506d987/src/partition/src/partition.rs#L71

**Comment by Kelvinyu1117** [comment]
Can I work on it?

**Comment by killme2008** [comment]
> Can I work on it?

Of course.Thank you.

**Comment by killme2008** [comment]
@Kelvinyu1117  Just a friendly reminder, are you still working on this issue? If you require any assistance, please inform us. Thank you.

**Comment by Kelvinyu1117** [comment]
Yes, I'm working on it, just having some personal stuffs so didnt get chance to dive into the issue.

**Comment by Kelvinyu1117** [comment]
How can I test this feature locally?

**Comment by killme2008** [comment]
> How can I test this feature locally? Do we have any unit tests that involves printing the expressions?

Just run `cargo sqlness -t partition`, and you will see the different results of the test.

And of course, you must always add a unit test for the `PartitionExpr` and `ParitionExpr`, construct an instance and invoke its `to_string()` function to retrieve the display result, making sure it's expected.

**Comment by Kelvinyu1117** [comment]
I have run `cargo sqlness -t partition`, it seems no difference, but my unit test is passed. Am I missing something?
I have opened the PR, perhaps you can have a look and give some suggestions.

**Comment by killme2008** [comment]
> I have run `cargo sqlness -t partition`, it seems no difference, but my unit test is passed. Am I missing something? I have opened the PR, perhaps you can have a look and give some suggestions.

I found the cause. Because we use the `debug` format of `PartitionExpr ` here

https://github.com/GreptimeTeam/greptimedb/blob/88cdefa41e32749f864ebe4819e480680fce9481/src/partition/src/partition.rs#L66

Can you fix it too?

**Comment by killme2008** [comment]
Looks like we must change the `Display` impl for `ParitionDef` too:

https://github.com/GreptimeTeam/greptimedb/blob/88cdefa41e32749f864ebe4819e480680fce9481/src/partition/src/partition.rs#L72

Just display the `partition_bounds`, the columns is unnecessary currently.

You can run `cargo sqlness -t partition` to see the differences.

**Comment by Kelvinyu1117** [comment]
> > I have run `cargo sqlness -t partition`, it seems no difference, but my unit test is passed. Am I missing something? I have opened the PR, perhaps you can have a look and give some suggestions.
> 
> I found the cause. Because we use the `debug` format of `PartitionExpr ` here
> 
> https://github.com/GreptimeTeam/greptimedb/blob/88cdefa41e32749f864ebe4819e480680fce9481/src/partition/src/partition.rs#L66
> 
> Can you fix it too?

Sure, let me do that.

**Comment by evenyag** [comment]
Can we close this issue now?
