### ISSUE TITLE
Configure CI to run fuzz tests in distributed mode with MinIO

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#3997]
### What type of enhancement is this?

Other

### What does the enhancement do?

The PR #3967 enables the fuzz tests to run in distributed mode (with local disk). However, we also need the fuzz tests to run in distributed mode with shared storage(using MinIO).

See also:
- https://min.io/docs/minio/kubernetes/upstream/operations/install-deploy-manage/deploy-minio-tenant-helm.html#deploy-tenant-helm
- https://github.com/GreptimeTeam/helm-charts/tree/main/charts/greptimedb-cluster

BTW, If you encounter issues with pods failing to start in k8s, please reduce the requested resources(e.g., etcd CPU, memory).

**Comment by irenjj** [comment]
can i take it?

**Comment by WenyXu** [comment]
> can i take it?

Have fun🤩
