### ISSUE TITLE
improve observability for procedure

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3999]
### What problem does the new feature solve?

Currently we are not able to check the state of each procedure, how long it takes, which resources it keeps, or which state it at. It's hard to debug or verify things related to one specific procedure.

This ticket proposes to improve the observability of procedures, by exposing the above things somewhere. Like an HTTP API or a table in information_schema.

Useful links
- procedure state
   https://github.com/GreptimeTeam/greptimedb/blob/1b5862223c0a8561ef1ce3045128d4c5a27c7d5e/src/common/procedure/src/procedure.rs#L301-L315

- acquiring locks
   https://github.com/GreptimeTeam/greptimedb/blob/530353785cd632faa6ec71552d25ed9da137cb0b/src/common/procedure/src/local/runner.rs#L115-L125

- implement cluster_info table in information_schema https://github.com/GreptimeTeam/greptimedb/pull/3832 

### What does the feature do?

- [ ] Improve `ProcedureState::Running` to contain a `String`. This string shows a procedure's current stage.
- [ ] Count the procedure's execution time and store it.
- [ ] Expose those information to information_schema

**Comment by Kelvinyu1117** [comment]
I would like to work on it.
How can I verify my change locally for this improvement?

**Comment by evenyag** [comment]
> Improve ProcedureState::Running to contain a String. This string shows a procedure's current stage.

For this feature, one approach is adding a debug or trace log in the runner to print the current state of the procedure.
https://github.com/GreptimeTeam/greptimedb/blob/1b5862223c0a8561ef1ce3045128d4c5a27c7d5e/src/common/procedure/src/local/runner.rs#L195-L197

@WenyXu Do you have any suggestions?

**Comment by Kelvinyu1117** [comment]
For the execution time, it should be measuring how long does `execute_procedure_in_loop()` take right?
What precision (milliseconds, microseconds, nanoseconds?) do you want for the `execution_time`?

**Comment by evenyag** [comment]
Milliseconds should be enough.
