### ISSUE TITLE
Make auto-create/alter table through gRPC put request optional

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#4013]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

*This ticket affects the public gRPC interface and thus is also related to ingester repos.*

At present, all gRPC put requests will try to create or alter table if necessary. This brings lots of avoidable overhead on the write path. This ticket requests an improvement on the path between ingester clients and frontend server.

On some (or many) cases, the client or even the ingester SDK itself knows that one request won't trigger schema change or table creation. Especially when the client is running in a loop to put data continuously. It would be very beneficial if we could make use of this pre-condition, to alleviate the overhead of checking schema on the server side.

To achieve this, we need to add one flag in the gRPC interface. For example, in `InsertRequests` or `Header`. It's a hint to the server that if it can skip checking schema for one request. And make corresponding API changes in ingester SDKs to reflect this change.

### Implementation challenges

Open for discussion:
- Where to put this flag? Interface, common header or insert request
-

**Comment by fengjiachun** [comment]
@waynexia Can we close this issue now that we have a hint? #4700

**Comment by killme2008** [comment]
@fengjiachun I think we must document the hints

Let's close this issue.
