### ISSUE TITLE
Support "show status"

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#4017]
### What problem does the new feature solve?

For the compatibility of some mysql clients(like navicat), we'd better implement the "show status". Otherwise the client may report some annoying error messages, which makes people confused. (In the older version of navicat, it seems the error of "show status" can't be omitted.)

### What does the feature do?

Implement the "show status" in mysql as its document [here](https://dev.mysql.com/doc/refman/8.3/en/show-status.html). But we don't need to fully implement it all, just:

- the plain "show status" is enough; no others like "like" or "where"
- pick some meaningful server status variables [here](https://dev.mysql.com/doc/refman/8.3/en/server-status-variables.html), as best as we can

**Comment by LYZJU2019** [comment]
Can I have a try?

**Comment by LYZJU2019** [comment]
I am confused about where to get the value of [server status variables](https://dev.mysql.com/doc/refman/8.3/en/server-status-variables.html). It seems that Greptime does not have a `performance_schema` table, which is used to inspect the internal execution of the server at runtime. The `information_schema` table provides metadata about the database but does not reflect the current state of the server.

**Comment by WenyXu** [comment]
> ... but does not reflect the current state of the server

Yes, we may need a place(a global status registry or something else) to track all related info. cc @killme2008 @MichaelScofield

**Comment by MichaelScofield** [comment]
> I am confused about where to get the value of [server status variables](https://dev.mysql.com/doc/refman/8.3/en/server-status-variables.html). It seems that Greptime does not have a `performance_schema` table, which is used to inspect the internal execution of the server at runtime. The `information_schema` table provides metadata about the database but does not reflect the current state of the server.

Fow now, it doesn't matter what variables should be returned by "show status". All we want is to make Navicat not complained. So I think we can simply add a regex rule in `federated.rs` for "show status" first, returning empty contents, and see how Navicat satisfy about it. If Navicat then still complains some variables are missing, we can "fake" them (at last we are not really mysql, don't need to fully comply to it).

**Comment by MichaelScofield** [comment]
Just tried the "show status", it prints empty set. However, I think we'd better print the table header as well even there's indeed no value. Like this:
```text
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
+--------------------+----------+
```
So this issue is still opened.

**Comment by LindaSummer** [comment]
Hi @MichaelScofield ,

I'm a newbie of GreptimeDB and want to make some contribution.
Can this task be assigned to me?

Best Regards,
Edward

**Comment by killme2008** [comment]
> Hi @MichaelScofield ,
> 
> I'm a newbie of GreptimeDB and want to make some contribution. Can this task be assigned to me?
> 
> Best Regards, Edward

Of course, thank you.

**Comment by LindaSummer** [comment]
Hi @killme2008 ,

Sorry for delay reply.
After searching the mysql cli source code and trying mysql cli myself, I find it seems hard to just display headers without data.
Maybe we should add a simple status or an empty row as a placeholder to display the header.

Here is the mysql cli output.
```
MySQL [(none)]> select VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.4.1     |
+-----------+
1 row in set (0.001 sec)

MySQL [(none)]> show status where Variable_name='non-existed';
Empty set (0.002 sec)
```

Here is mysql cli code in display data.

https://github.com/mysql/mysql-server/blob/527c12ed611f3fe072c3043734319edb2c733099/client/mysql.cc#L3702-L3714
```cpp
      if (!mysql_num_rows(result) && !quick && !column_types_flag) {
        my_stpcpy(buff, "Empty set");
        if (opt_xml) {
          /*
            We must print XML header and footer
            to produce a well-formed XML even if
            the result set is empty (Bug#27608).
          */
          init_pager();
          print_table_data_xml(result);
          end_pager();
        }
  }
```

It will directly print fixed string "Empty set" as response.
The `column_types_flag` is a mysql-cli flag.
After enabling it with `mysql --column-type-info -h **** -P **** -u **** -p`, I got below output.
```
MySQL [(none)]> show status where Variable_name='non-existed';
Field   1:  `Variable_name`
Org_field:  `Variable_name`
Catalog:    `def`
Database:   `performance_schema`
Table:      `session_status`
Org_table:  `session_status`
Type:       VAR_STRING
Collation:  utf8mb3_general_ci (33)
Length:     192
Max_length: 0
Decimals:   0
Flags:      NOT_NULL NO_DEFAULT_VALUE

Field   2:  `Value`
Org_field:  `Value`
Catalog:    `def`
Database:   `performance_schema`
Table:      `session_status`
Org_table:  `session_status`
Type:       VAR_STRING
Collation:  utf8mb3_general_ci (33)
Length:     3072
Max_length: 0
Decimals:   0
Flags:


0 rows in set (0.008 sec)
```
The column info should have been contained in response data and just doesn't be displayed in mysql cli.

Could we have a simple status for `Variable_name` and make the response not empty to display column headers?

Best Regards,
Edward

**Comment by killme2008** [comment]
> Hi @killme2008 ,
> 
> Sorry for delay reply. After searching the mysql cli source code and trying mysql cli myself, I find it seems hard to just display headers without data. Maybe we should add a simple status or an empty row as a placeholder to display the header.
> 
> Here is the mysql cli output.
> 
> ```
> MySQL [(none)]> select VERSION();
> +-----------+
> | VERSION() |
> +-----------+
> | 8.4.1     |
> +-----------+
> 1 row in set (0.001 sec)
> 
> MySQL [(none)]> show status where Variable_name='non-existed';
> Empty set (0.002 sec)
> ```
> 
> Here is mysql cli code in display data.
> 
> https://github.com/mysql/mysql-server/blob/527c12ed611f3fe072c3043734319edb2c733099/client/mysql.cc#L3702-L3714
> 
> ```c++
>       if (!mysql_num_rows(result) && !quick && !column_types_flag) {
>         my_stpcpy(buff, "Empty set");
>         if (opt_xml) {
>           /*
>             We must print XML header and footer
>             to produce a well-formed XML even if
>             the result set is empty (Bug#27608).
>           */
>           init_pager();
>           print_table_data_xml(result);
>           end_pager();
>         }
>   }
> ```
> 
> It will directly print fixed string "Empty set" as response. The `column_types_flag` is a mysql-cli flag. After enabling it with `mysql --column-type-info -h **** -P **** -u **** -p`, I got below output.
> 
> ```
> MySQL [(none)]> show status where Variable_name='non-existed';
> Field   1:  `Variable_name`
> Org_field:  `Variable_name`
> Catalog:    `def`
> Database:   `performance_schema`
> Table:      `session_status`
> Org_table:  `session_status`
> Type:       VAR_STRING
> Collation:  utf8mb3_general_ci (33)
> Length:     192
> Max_length: 0
> Decimals:   0
> Flags:      NOT_NULL NO_DEFAULT_VALUE
> 
> Field   2:  `Value`
> Org_field:  `Value`
> Catalog:    `def`
> Database:   `performance_schema`
> Table:      `session_status`
> Org_table:  `session_status`
> Type:       VAR_STRING
> Collation:  utf8mb3_general_ci (33)
> Length:     3072
> Max_length: 0
> Decimals:   0
> Flags:
> 
> 
> 0 rows in set (0.008 sec)
> ```
> 
> The column info should have been contained in response data and just doesn't be displayed in mysql cli.
> 
> Could we have a simple status for `Variable_name` and make the response not empty to display column headers?
> 
> Best Regards, Edward

Thank you for your investigation. Looks like the MySQL CLI doesn't display the header when the records are empty.

It already set the correct schema at

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/query/src/sql.rs#L653-L656

So i think this issue can be closed.

**Comment by killme2008** [comment]
> Just tried the "show status", it prints empty set. However, I think we'd better print the table header as well even there's indeed no value. Like this:
> 
> ```
> +--------------------+----------+
> | Variable_name      | Value    |
> +--------------------+----------+
> +--------------------+----------+
> ```
> 
> So this issue is still opened.

This is a blank record with the name and value are both empty strings. It's unnecessary.
