### ISSUE TITLE
Support to drop multiple tables

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4020]
### What problem does the new feature solve?

Drop multiple tables in the single statement

### What does the feature do?

To implement the `DROP [TEMPORARY] TABLE [IF EXISTS] tbl_name [, tbl_name]`

**Comment by sarailQAQ** [comment]
Can I try it?

**Comment by sarailQAQ** [comment]
I have a question: When an error occurs while dropping multiple tables, what action should I take?
- Attempt to drop the remaining tables and then, finally, return an error message. Or,
- Immediately abort the process of dropping tables and return an error?

**Comment by WenyXu** [comment]
> I have a question: When an error occurs while dropping multiple tables, what action should I take?
> 
> * Attempt to drop the remaining tables and then, finally, return an error message. Or,
> * Immediately abort the process of dropping tables and return an error?

I prefer the first one.

**Comment by sarailQAQ** [comment]
> > I have a question: When an error occurs while dropping multiple tables, what action should I take?
> > 
> > * Attempt to drop the remaining tables and then, finally, return an error message. Or,
> > * Immediately abort the process of dropping tables and return an error?
> 
> I prefer the first one.

There is another question: in more extreme cases, if multiple errors occur, how do I deal with these errors?

**Comment by WenyXu** [comment]
> There is another question: in more extreme cases, if multiple errors occur, how do I deal with these errors?
How about referencing the behavior of the MySQL.
