### ISSUE TITLE
Checking if database is used currently when dropping database

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4029]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The GreptimeDB doesn't checking if current session is using the database which will be dropped:

```sql
mysql> create database test;
Query OK, 1 row affected (0.05 sec)

mysql> use test;
Database changed

mysql> drop database test;
Query OK, 0 rows affected (0.02 sec)
```

It's better to prevent dropping the database if the user is using it in MySQL or Postgres Session.

### Implementation challenges

Looks like it can be checked at 

https://github.com/GreptimeTeam/greptimedb/blob/466f7c644885853876a16f6f5faf045eaae9c29a/src/operator/src/statement/ddl.rs#L657
Retrieving the current database using QueryContext#current_schema and checking if it's the database to be dropped.

**Comment by etolbakov** [comment]
I might give it a shot if that’s ok
