### ISSUE TITLE
Implement the Buf to avoid extra memory allocation

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4065]
We need something like this: https://github.com/apache/opendal/blob/dd70b3c706f1689c2fe9455405cbd1e773c483ab/core/src/types/buffer.rs#L114-L122

_Originally posted by @WenyXu in https://github.com/GreptimeTeam/greptimedb/pull/4038#discussion_r1618113196_

**Comment by LYZJU2019** [comment]
Can I give it a try?

**Comment by WenyXu** [comment]
> Can I give it a try?

Have fun

**Comment by ozewr** [comment]
Can I give it a try?

**Comment by WenyXu** [comment]
> Can I give it a try?

Have fun🚀

**Comment by ozewr** [comment]
Sorry,this question unrelated to this issue logically.What is the minimum memory required to compile this project? I encountered an out-of-memory (OOM) issue when running `cargo nextest run`. I was running it inside a Docker container with the configuration: `--cpus=8 --memory 16g --memory-swap=32g`. I also tried running it directly on my personal PC, but it caused the system to crash. My PC has 24GB of RAM.I can't run it 😢.@WenyXu
> [12662.902005] Memory cgroup out of memory: Killed process 211599 (ld) total-vm:2666868kB, anon-rss:2659840kB, file-rss:3780kB, shmem-rss:0kB, UID:0 pgtables:5276kB oom_score_adj:0

**Comment by WenyXu** [comment]
> Sorry,this question unrelated to this issue logically.What is the minimum memory required to compile this project? I encountered an out-of-memory (OOM) issue when running `cargo nextest run`. I was running it inside a Docker container with the configuration: `--cpus=8 --memory 16g --memory-swap=32g`. I also tried running it directly on my personal PC, but it caused the system to crash. My PC has 24GB of RAM.I can't run it 😢.@WenyXu
> 
> > [12662.902005] Memory cgroup out of memory: Killed process 211599 (ld) total-vm:2666868kB, anon-rss:2659840kB, file-rss:3780kB, shmem-rss:0kB, UID:0 pgtables:5276kB oom_score_adj:0

Hi, you can try this https://github.com/rui314/mold
