### ISSUE TITLE
Consider adding the stats of region data size

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4071]
Yep, it only contains the manifest size, can it include the data size too?

_Originally posted by @killme2008 in https://github.com/GreptimeTeam/greptimedb/pull/4070#discussion_r1619737231_

**Comment by evenyag** [comment]
We can collect the file sizes from the SstVersion
https://github.com/GreptimeTeam/greptimedb/blob/05751084e7bbfc5e646df7f51bb7c3e5cbf16d58/src/mito2/src/sst/version.rs#L87-L102
