### ISSUE TITLE
Adaptive parquet row group size based on memory size

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#412]
`RowGroup` is an organization level in parquet format, on top of `Page`. It has its own statistics and metadata for filtering on reading. Currently the parquet file generated by flushing memtable in GTDB has a fixed row group size 256 (default to the constant `READ_BATCH_SIZE` 🥹) https://github.com/GreptimeTeam/greptimedb/blob/6e99bb8490fd7641998239fa769ebd1cc3eaa789/src/store-api/src/storage/consts.rs#L80

Naming aside for now, I propose to make the row group size dynamic, based on the content size. In other word, fix on how many spaces will a row group occupied rather than how many rows will a row group contains. E.g., we let each row group's uncompressed size fixed to 128KB. This can be done by counting the entries' size when itering memtable.

I've run some test around this parameter. For a ~10 columns, most are short string or number table. The test dataset contains ~2,000,000 rows, in a 46MB parquet file. Our row group size set to 256 and 4096's results:
- row group size 256
  - avg ~430 row groups per file
  - avg ~7.6 kB per row group
  - total 129MB data generated
  - write takes ~4mins
- row group size 4096
  - avg ~25 row groups per file
  - avg ~83 kB per row group
  - total 66MB data generated
  - write takes ~40s

Both time and space complexities are reduced. And the table scan performance improved ~`1.5min` to ~`2sec`)

As we are (going to) using parquet's row group for filtering to accelerate query, one would ask will this change reduce the filtering effect? There may have some affects if row group's size increases. But parquet also has [page level index](https://github.com/apache/parquet-format/blob/master/PageIndex.md) for pruning. I think the after all performance is acceptable or even better.

**Comment by CookiePieWw** [comment]
Is this still active? I'd like to have a try :)

**Comment by fengjiachun** [comment]
Can we close it if it's no longer needed? @v0y4g3r @waynexia @evenyag

**Comment by evenyag** [comment]
The current row group size is already large enough and is a size balancing pruning and scan performance.
https://github.com/GreptimeTeam/greptimedb/blob/ff4c153d4bba17a17e9f422eeb392f5a44f6d0d0/src/mito2/src/sst/parquet.rs#L41-L43

Also the index pruning may use the constant row group size to compute the row selectors.

We can close this issue.
