### ISSUE TITLE
[Tracking Issue] Make region failover great again 

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4161]
### What type of enhancement is this?

Refactor, Tech debt reduction

### What does the enhancement do?

Currently, the region failover procedure has follow issues:
1. The region failover doesn't support migrating a region without data loss.
2. The failover detector relies on the receiving heartbeats from the datanode; if the datanode doesn't send any heartbeats, we can't detect the failed region.
3. We can't track the in-flight failover procedures, which means we can't trigger the failover procedure again if a failover procedure fails.

**Comment by killme2008** [comment]
I think we can close the issue @WenyXu
