### ISSUE TITLE
Supports input interval type in the format of ISO 8601

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4215]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

Unfortunately, GreptimeDB doesn't support writing the interval in the format of [ISO 8601 time intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) such as `P3Y3M700DT133H17M36.789S` etc. But it's output supports it.

But I think we can support it by the transform rules too just like #4182 

This lib looks helpful: https://docs.rs/iso8601/latest/iso8601/

Using the `Duration::from_str(s)` to parse the interval.

https://docs.rs/iso8601/latest/iso8601/enum.Duration.html

**Comment by leaf-potato** [comment]
I am interested in this issue and would like to try to implement it.

**Comment by etolbakov** [comment]
Frankly speaking I already did a draft, but happy to step away @leaf-potato! 
Fill free to ping me in case of questions as very likely you are going to extend the `expand_interval.rs`.

@killme2008 a quick question do you expect an output something like 
```sql
SELECT INTERVAL 'P3Y3M700DT133H17M36.789S';

+-------------------------------------------------------------+
| IntervalMonthDayNano("163343856789000000")                  |
+-------------------------------------------------------------+
| 0 years 0 mons 0 days 45373 hours 17 mins 36.789000000 secs |
+-------------------------------------------------------------+
```

or it should be the exact match of years/months/days etc?

**Comment by killme2008** [comment]
> @killme2008 a quick question do you expect an output something like

Yes, it's exactly what we need.

**Comment by etolbakov** [comment]
Hey @leaf-potato 
Just curious if you had time to take a look at this ticket?
