### ISSUE TITLE
Run tests in workspace failed

### ISSUE THREAD

**Issue by leaf-potato** [GreptimeTeam/greptimedb#4324]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Other

### Minimal reproduce step

```
cargo test --workspace
```

### What did you expect to see?

All tests run successfully.

### What did you see instead?

Some tests in common-time crate run failed:
```
failures:

---- time::tests::test_serialize_to_json_value stdout ----
thread 'time::tests::test_serialize_to_json_value' panicked at src/common/time/src/time.rs:338:9:
assertion `left == right` failed
  left: "10:00:01+1000"
 right: "08:00:01+0800"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- time::tests::test_to_timezone_aware_string stdout ----
thread 'time::tests::test_to_timezone_aware_string' panicked at src/common/time/src/time.rs:375:9:
assertion `left == right` failed
  left: "10:00:00.001"
 right: "08:00:00.001"

---- time::tests::test_to_iso8601_string stdout ----
thread 'time::tests::test_to_iso8601_string' panicked at src/common/time/src/time.rs:316:9:
assertion `left == right` failed
  left: "10:16:40.001+1000"
 right: "08:16:40.001+0800"

---- timestamp::tests::test_as_formatted_string stdout ----
thread 'timestamp::tests::test_as_formatted_string' panicked at src/common/time/src/timestamp.rs:1240:9:
assertion `left == right` failed
  left: "1970-01-01 00:00:00"
 right: "1970-01-01 08:00:00"

---- timezone::tests::test_from_tz_string stdout ----
thread 'timezone::tests::test_from_tz_string' panicked at src/common/time/src/timezone.rs:176:9:
assertion `left == right` failed
  left: Named(UTC)
 right: Named(Asia/Shanghai)


failures:
    time::tests::test_serialize_to_json_value
    time::tests::test_to_iso8601_string
    time::tests::test_to_timezone_aware_string
    timestamp::tests::test_as_formatted_string
    timezone::tests::test_from_tz_string

test result: FAILED. 90 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

error: test failed, to rerun pass `-p common-time --lib`
```

### What operating system did you use?

Max OS Ventura 13.4 ARM

### What version of GreptimeDB did you use?

0.8.2

**Comment by leaf-potato** [comment]
Even if function `set_default_timezone` in `src/common/time/src/timezone.rs` is called multiple times, variable `DEFAULT_TIMEZONE` will only be initialized once.

Therefore, calling function `set_default_timezone` in different tests to set different default values and the final accessed value does not match the expected value.

**Comment by waynexia** [comment]
Please use `make test` or `cargo nextest run` instead. The vanilla test harness is no longer supported.

**Comment by waynexia** [comment]
Unlike the vanilla harness, nextest will run each case in a separate environment, thus avoiding the shared global variable problem.

**Comment by leaf-potato** [comment]
@waynexia Update the docs on the official website simultaneously?
<img width="1488" alt="image" src="https://github.com/GreptimeTeam/greptimedb/assets/49188857/7aa20e46-3c1e-4963-80dc-e866689acb8a">

**Comment by waynexia** [comment]
Thank you for reminding me! It's updated at https://github.com/GreptimeTeam/docs/pull/1048
