### ISSUE TITLE
Adds information_schema.views

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4339]
### What type of enhancement is this?

API improvement, Configuration, User experience

### What does the enhancement do?

Part of #2931 #3729 

Implements `information_schema.views` to provide information about views in databases.

Refer to https://dev.mysql.com/doc/refman/8.4/en/information-schema-views-table.html

### Implementation challenges

The implement detail notes:

1. Refer to `information_schema.tables` for example to implement the `views`:
    - https://github.com/GreptimeTeam/greptimedb/blob/main/src/catalog/src/information_schema/tables.rs
2. Register it to `information_schema`:
    - https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/catalog/src/information_schema.rs#L211
3. Adds unit tests and sqlness tests https://github.com/GreptimeTeam/greptimedb/tree/main/tests/cases/standalone/common/information_schema

**Comment by lyang24** [comment]
Hi, I would like to work on this. I assume the view info could be retrieved by `ViewInfoManager`, is there a collection of viewIDs that i can iterate to get view info?

**Comment by killme2008** [comment]
@lyang24 Great, thanks a lot.

There is a field `definition` which is the view definition:

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/common/meta/src/key/view_info.rs#L94

Retrieving the `view_info` by `ViewInfoCache`:

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/common/meta/src/cache/table/view_info.rs#L30

`ViewInfoCache` can be retrieved by:

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/catalog/src/kvbackend/manager.rs#L103

**Comment by killme2008** [comment]
One way to obtain the `ViewInfoCache` is by incorporating a function similar to the following:

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/catalog/src/information_schema/utils.rs#L57

During runtime, the `catalog_manager` is consistently `KvBackendCatalogManager`.

**Comment by killme2008** [comment]
Another example to retrieve view info in `catalog` crate:

https://github.com/GreptimeTeam/greptimedb/blob/da0c8402619134d455242bd5c16e16a3b3955994/src/catalog/src/table_source.rs#L135-L143
