### ISSUE TITLE
Please generate the configuration options by GreptimeDB version

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#4344]
### What problem does the new feature solve?

There are two documents for the configuration file options, one on [the documentation website](https://docs.greptime.com/user-guide/operations/configuration), the other [on Github](https://github.com/GreptimeTeam/greptimedb/blob/main/config/config.md). When an option is updated, we need to manually copy the description of the option from Github to the website, which is unnessessary.

### What does the feature do?

Can we generate the configuration options on Github by GreptimeDB version? For example, change the config location from `/config/config.md` to `/config/v0.x/config.md`?

Then we can just add a link in the website to guide users to read the options on Github, which saves the effort of manually copying and checking.

**Comment by killme2008** [comment]
@zyy17 I think so.

Could we change the release CI to generate the specific configuration for the release version? And keeps all these versions in repo `config` folder.

**Comment by sunng87** [comment]
We don't need to store all those version under /config. We can just use github tags for them, like https://github.com/GreptimeTeam/greptimedb/blob/v0.8.2/config/config.md

**Comment by nicecui** [comment]
Thanks @sunng87 for the great answer! And we no longer need to develop this feature.
