### ISSUE TITLE
Fail to parse number 32768

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4351]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step

1. create table
```sql
CREATE TABLE et(
`iUStO` TIMESTAMP(6) TIME INDEX,
`auT` BIGINT,
`veLIt` DOUBLE,
facilis BIGINT NOT NULL,
`CoNsequatUr` DOUBLE,
`quAe` FLOAT,
`dOlOres` BOOLEAN,
repudiandae BIGINT NOT NULL,
fugit FLOAT NOT NULL,
`LAborum` BOOLEAN DEFAULT true,
`IPSAm` SMALLINT DEFAULT 20108,
`RaTioNE` BIGINT,
`nIHIL` FLOAT NOT NULL,
`iNVENTorE` INT DEFAULT 1356103243,
`necessitatibUs` FLOAT DEFAULT 0.95625234,
`POSSIMuS` DOUBLE,
`SaepE` INT,
libero DOUBLE NULL,
`nObis` BOOLEAN DEFAULT false,
`Et` SMALLINT DEFAULT -32768,
rerum BOOLEAN,
nisi BIGINT NULL,
`MoLesTiae` DOUBLE,
qui BOOLEAN NOT NULL,
PRIMARY KEY(`RaTioNE`, `quAe`, `veLIt`, `CoNsequatUr`, `SaepE`)
)
ENGINE=mito;
```

### What did you expect to see?
table created

### What did you see instead?
1: Database(MySqlDatabaseError { code: Some("HY000"), number: 1815, message: "Failed to parse value: Fail to parse number 32768, ParseIntError { kind: PosOverflow }" })

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace

https://github.com/GreptimeTeam/greptimedb/actions/runs/9890751716/job/27320252984?pr=4345

**Comment by killme2008** [comment]
Looks like it's expected. The SmallInt type range is –32,767~32767.

**Comment by WenyXu** [comment]
> Looks like it's expected. The SmallInt type range is –32,767~32767.

Should be -32,768~32767.

**Comment by killme2008** [comment]
It's the issue introduced by #4301
