### ISSUE TITLE
Maybe can't read tables containing uppercase letters sent from prometheus

### ISSUE THREAD

**Issue by NiwakaDev** [GreptimeTeam/greptimedb#4383]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode (Maybe both mode)

### Minimal reproduce step

1. Run prometheus.
2. Run node exporter.
3. Run greptimedb. (I tried only standalone, but I think the issue also happens in distributed mode)

### What did you expect to see?

When reading all tables sent from the prometheus, every query should work, like this:

```sql
select * from node_netstat_Tcp_InSegs;
```

### What did you see instead?

error: `ERROR 1146 (42S02): (TableNotFound): Failed to plan SQL: Table not found: greptime.public.node_netstat_tcp_insegs`

It seems like tables sent from Prometheus aren't created as lowercase, while we can read those created from others, like MySQL client.

This is because those from others are created in lowercase, I guess.

### What operating system did you use?

Maybe Any OS

### What version of GreptimeDB did you use?

latest commit(e39f49fe567be8e7cb41c8541bcdfbf206af5c8f)

**Comment by NiwakaDev** [comment]
By the way, we can read a lowercase table like so:
```sql 
select * from node_time_seconds;
```

Am I missing something? If not, I'd like to work on this issue.

**Comment by killme2008** [comment]
The MySQL client or Postgres?

You need to quote the identifier if it's case-sensitive:

```sql
select * from "node_netstat_Tcp_InSegs";
```

or

```sql
select * from `node_netstat_Tcp_InSegs`
```

https://docs.greptime.com/reference/sql/compatibility#ansi-compatibility

**Comment by NiwakaDev** [comment]
@killme2008  @tisonkun 
Thanks!
