### ISSUE TITLE
Alter column option

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4395]
### What problem does the new feature solve?

since v0.9, GreptimeDB supports full-text index for string columns with the extra `fulltext` option:

```sql
CREATE TABLE `logs` (
  `message` STRING FULLTEXT,
  `time` TIMESTAMP TIME INDEX,
) WITH (
  append_mode = 'true'
);
```

But if you can't enable an existing string column `fulltext` option by alter.

### What does the feature do?

It already has the `modify` statement to change the column type:

```sql
ALTER TABLE monitor MODIFY COLUMN load_15 STRING;
```

Supports alter column options just like:

```sql
ALTER TABLE monitor SET COLUMN load_15 fulltext WITH(analyzer = 'Chinese', case_sensitive = 'false');
```

**Comment by irenjj** [comment]
maybe we should first add a new enum member for `Kind` in greptime-proto for `expr_factory` to use.

**Comment by killme2008** [comment]
> maybe we should first add a new enum member for `Kind` in greptime-proto for `expr_factory` to use.

Yes. A first step.

**Comment by WenyXu** [comment]
I think `ALTER COLUMN`(or `MODIFY COLUMN`) should be better, considering we might have `unset` operation. @irenjj @killme2008 

```sql
ALTER TABLE monitor ALTER COLUMN load_15 SET fulltext WITH (analyzer = 'Chinese', case_sensitive = 'false');
```

```sql
ALTER TABLE monitor ALTER COLUMN load_15 UNSET fulltext;
```

Instead of 

```sql
ALTER TABLE monitor UNSET COLUMN load_15 fulltext;
```

**Comment by irenjj** [comment]
> I think `ALTER COLUMN`(or `MODIFY COLUMN`) should be better, considering we might have `unset` operation. @irenjj @killme2008
> 
> ```sql
> ALTER TABLE monitor ALTER COLUMN load_15 SET fulltext WITH (analyzer = 'Chinese', case_sensitive = 'false');
> ```
> 
> ```sql
> ALTER TABLE monitor ALTER COLUMN load_15 UNSET fulltext;
> ```
> 
> Instead of
> 
> ```sql
> ALTER TABLE monitor UNSET COLUMN load_15 fulltext;
> ```

I agree.

**Comment by killme2008** [comment]
Don't add new syntax, keep using `modify column [set | unset]`.
