### ISSUE TITLE
Introduce sqlancer to find logic bugs

### ISSUE THREAD

**Issue by J0HN50N133** [GreptimeTeam/greptimedb#4402]
### What type of enhancement is this?

Other

### What does the enhancement do?

[SQLancer](https://github.com/sqlancer/sqlancer) (Synthesized Query Lancer) is a tool to automatically test Database Management Systems (DBMS) in order to find logic bugs in their implementation which maybe be hard to find with fuzzing test. Some tsdbs , `CnosDB`/`TDEngine`, are using it.

**Comment by J0HN50N133** [comment]
If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get 
$3,5,6$ and $9$. The sum of these multiples is $23$.

Find the sum of all the multiples of $3$ or $5$ below $10$.

**Comment by killme2008** [comment]
We are using sqlness currently

https://github.com/CeresDB/sqlness
