### ISSUE TITLE
Dry-run API for event ingestion 

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#4415]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

The idea is to provide a dry-run API for user to test their pipeline and input data. 

Features we need from this API:

- Accepts saved pipeline name or raw pipeline definition (without saving)
- Accepts all formats that supported by ingest API
- Output data just like `select * from <table>`
- Provide error information of pipeline or data

This API will be the key for our pipeline manager/editor

**Comment by paomian** [comment]
relate https://github.com/GreptimeTeam/greptimedb/pull/4667
