### ISSUE TITLE
error: failed to run custom build command for `greptime-proto v0.1.0 '

### ISSUE THREAD

**Issue by sunheyi6** [GreptimeTeam/greptimedb#4420]
### What type of bug is this?

Configuration

### What subsystems are affected?

Other

### Minimal reproduce step

cargo build

### What did you expect to see?

no error

### What did you see instead?

no 

### What operating system did you use?

Windows 11 x64

### What version of GreptimeDB did you use?

main

### Relevant log output and stack trace
error: failed to run custom build command for `greptime-proto v0.1.0 (https://github.com/GreptimeTeam/greptime-proto.git?rev=5c801650435d464891114502539b701c77a1b914#5c801650)`

**Comment by tisonkun** [comment]
Can you provide full build log?

**Comment by tisonkun** [comment]
Answered at https://github.com/GreptimeTeam/greptimedb/issues/4419#issuecomment-2247022523
