### ISSUE TITLE
Access link in CONTRIBUTING.md file failed

### ISSUE THREAD

**Issue by leaf-potato** [GreptimeTeam/greptimedb#4467]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Other

### Minimal reproduce step

Click `Code of Conduct` of CONTRIBUTING.md file.
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/71b38743-868c-461c-b421-5a1d1045d2c8">

### What did you expect to see?

The code of conduct page.

### What did you see instead?

Jump to a page that does not exist.
<img width="2026" alt="image" src="https://github.com/user-attachments/assets/6740dfec-ac50-4169-b63c-de21d37bb5cc">

### What operating system did you use?

Max OS Ventura 13.4 ARM

### What version of GreptimeDB did you use?

0.8.2

**Comment by killme2008** [comment]
Good catch! It should link to https://github.com/GreptimeTeam/.github/blob/main/.github/CODE_OF_CONDUCT.md

Could you help to create a pull request to fix it?

**Comment by leaf-potato** [comment]
> Could you help to create a pull request to fix it?
Of course.
