### ISSUE TITLE
Incorrect `version` in `greptime_app_version`

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb#4533]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

Access the `/metrics` endpoint when the DB is ready:

```
bash-5.1# curl -q  http://10.244.1.27:4000/metrics | grep greptime_app
greptime_app_version app version
# TYPE greptime_app_version gauge
greptime_app_version{short_version="0.9.1",version="-fe1cfbf2"} 1
```

The `version` should be `fe1cfbf2`, not `-fe1cfbf2`.

### What did you expect to see?

We should get the correct version without the prefix `-`.

### What did you see instead?

Get the `version` with prefix `-`.

### What operating system did you use?

Linux

### What version of GreptimeDB did you use?

v0.9.1

**Comment by leaf-potato** [comment]
Maybe I can give it a try.

**Comment by zyy17** [comment]
@leaf-potato it's yours. Have fun. Feel free to ask if anything needs to be clarified.

**Comment by leaf-potato** [comment]
The version uses the `branch-commit` format. When git checkout to a commit, there is no branch. 
https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/common/version/src/lib.rs#L127-L129

Therefore, fix it by using commit id directly when the branch is empty.

**Comment by zyy17** [comment]
> The version uses the `branch-commit` format. When git checkout to a commit, there is no branch.
> 
> https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/common/version/src/lib.rs#L127-L129
> 
> Therefore, fix it by using commit id directly when the branch is empty.

I'm confused with `short_version` and `version`. In fact, `version` is some kind of "short" version.

Can we just return `branch` and `commit_short`? For example:

```rust
pub const fn branch_and_short_commit() -> (&'static str, &'static str) {
    (BUILD_INFO.branch, BUILD_INFO.commit_short)
} 
```

IMO, `version` should be semantic, for example, `v0.9.1`. We can make `greptime_app_version` looks like:

```
greptime_app_version{version="0.9.1",short_commit="fe1cfbf2",branch="main"}
```

**Comment by leaf-potato** [comment]
> I'm confused with `short_version`(`CARGO_PKG_VERSION`) and `version`(`${commit_short}-${branch}`). In fact, `version` is some kind of "short" version.

Mabey it's a bug. When calling the `log_version` function, pass the return value of the `short_version()` function to the `app_version` parameter: 

https://github.com/GreptimeTeam/greptimedb/blob/2c3fccb516addcfb082a7c12302b3fffafcbbab8/src/cmd/src/flownode.rs#L218-L220

However, inside the function `log_version`, the value of `app_version` is assigned to `version` instead of `short_version`:
https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/cmd/src/lib.rs#L31-L34

https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/cmd/src/lib.rs#L79-L86

**Comment by MichaelScofield** [comment]
@leaf-potato It's unusual that "branch" is empty. I was digging into the "shadow-rs"(that find the git info) one time, and suspect the incorrectness was origin from its usage of "git2". Maybe you can disable the "git2" feature and give it a try?

**Comment by zyy17** [comment]
> > I'm confused with `short_version`(`CARGO_PKG_VERSION`) and `version`(`${commit_short}-${branch}`). In fact, `version` is some kind of "short" version.
> 
> Mabey it's a bug. When calling the `log_version` function, pass the return value of the `short_version()` function to the `app_version` parameter:
> 
> https://github.com/GreptimeTeam/greptimedb/blob/2c3fccb516addcfb082a7c12302b3fffafcbbab8/src/cmd/src/flownode.rs#L218-L220
> 
> However, inside the function `log_version`, the value of `app_version` is assigned to `version` instead of `short_version`:
> 
> https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/cmd/src/lib.rs#L31-L34
> 
> https://github.com/GreptimeTeam/greptimedb/blob/93be81c0410a32f8955769599090de0f4f11e73f/src/cmd/src/lib.rs#L79-L86
> 
> The simple solution is to swap the current assignment operation.

Two version labels still confuse the user. The user has to understand(or we assume the user knows) the format of `app_version`, which is constructed with `branch` and `commit`. It will be clearer if we use the raw git info as the metric label, for example, `branch` and `commit`.

**Comment by evenyag** [comment]
> Two version labels still confuse the user. The user has to understand(or we assume the user knows) the format of `app_version`, which is constructed with `branch` and `commit`. It will be clearer if we use the raw git info as the metric label, for example, `branch` and `commit`.

+1

**Comment by leaf-potato** [comment]
> and suspect the incorrectness was origin from its usage of "git2"

@MichaelScofield  Maybe not. Disabling git2 in shadow-rs also has the same problem:
```toml
#before:
shadow-rs = "0.31"

#after:
shadow-rs = { version = "0.31", default-features = false}
```



> It's unusual that "branch" is empty.

You can reproduce the problem by following the steps below:
```sh
git checkout HEAD^
git branch --show-current
```

**Comment by leaf-potato** [comment]
> It will be clearer if we use the raw git info as the metric label, for example, `branch` and `commit`

Got it!

**Comment by MichaelScofield** [comment]
@leaf-potato If you do git checkout like that, it's in the "detached" mode, there's no branch. A walkaround might be `git branch --remote --contains | sed "s|[[:space:]]*origin/||"`

**Comment by leaf-potato** [comment]
> git branch --remote --contains | sed "s|[[:space:]]*origin/||"

You also need to filter out HEAD: `git branch --remote --contains | sed "s|[[:space:]]*origin/||"|grep -v "HEAD"`. Should this be supported by shadow-rs?

**Comment by MichaelScofield** [comment]
@leaf-potato Wait...On second thought, do we really need the "branch" info? "commit id" is sufficient to uniquely locate the codes revision. The way to find branch in detached mode is kind of magic, you can try to fire an issue in shardow-rs.

**Comment by baoyachi** [comment]
When building GitLab or GitHub, it will check out from a certain branch, causing the command to retrieve the current branch with empty content.

The delivered product (binary) version should be concrete, and in fact, it is more recommended to use the git tag mechanism for tagging, because branches are often deleted, and git tags are usually treated as archives.

When building shadow-rs, it is recommended to use git tag recording in this way. For details, [please refer to](https://github.com/baoyachi/shadow-rs/blob/deff1f4bf56a9db4a32c487c877c0025401dabde/example_shadow/src/main.rs#L12-L14).

If you want to choose between branch or tag, you need to make a judgment. The pseudocode is roughly as follows:
```diff
{
 "version":shadow::PKG_VERSION,
+ "branch/tag":if ! shadow::BRANCH.is_empty(){ shadow::BRANCH} else{shadow::LAST_TAG},
"commit_hash":shadow::SHORT_COMMIT,
"build_time":shadow::BUILD_TIME,
}

**Comment by raju130404** [comment]
Hi, if this is not completed yet, can I give it a try?

**Comment by zyy17** [comment]
@raju130404 It's already resolved in https://github.com/GreptimeTeam/greptimedb/pull/4572.
