### ISSUE TITLE
GreptimeDB commandline utilities

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#454]
Like MySQL's `mysqldump`/`mysqlcheck`, we need to provide a set of executable utlities for functionalities like:
- WAL dump & repair @v0y4g3r 
- Read manifest file of tables
- Backup database
- Import data in bulk load manner
- ...

**Comment by tisonkun** [comment]
Move to Ideas until we have more concrete proposals.
