### ISSUE TITLE
Make pg_catalog schema visible only when client connect from Postgres protocol

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#4543]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

This was a comment from the initial PR of pg_catalog feature #4332 . This `pg_catalog` is designed to work with postgresql client tools like psql to get meta information of the database. It should only be visible when client connects from postgresql protocol. We should not see it from our mysql clients, and http dashbaord.

### Implementation challenges

Check the `QueryContext` to see current whether current client is from postgresql port or not.

**Comment by J0HN50N133** [comment]
assign this to me.
