### ISSUE TITLE
Upgrade rustls family to 0.23

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#4557]
### What type of enhancement is this?

Other

### What does the enhancement do?

Upgrade the entire protocol tier to rustls 0.23.

- tokio-rustls 0.26
- opensrv-mysql: requires upstream update https://github.com/datafuselabs/opensrv/pull/65
- pgwire 0.21
- tonic 0.12 (including [greptime-proto](https://github.com/GreptimeTeam/greptime-proto) )

**Comment by leaf-potato** [comment]
Maybe I can give it a try.

**Comment by leaf-potato** [comment]
Curious about what issues rustls 0.23 solves and why greptime needs to be upgraded.

**Comment by sunng87** [comment]
It's not an urgent issue. We just want to keep our dependencies up-to-date.

**Comment by leaf-potato** [comment]
> It's not an urgent issue. We just want to keep our dependencies up-to-date.

Ok, besides that, the latest version of tonic 0.12（[CHANGELOG](https://github.com/hyperium/tonic/blob/master/CHANGELOG.md)） doesn't seem to have been upgraded to rustls 0.23.
<img width="900" alt="image" src="https://github.com/user-attachments/assets/7194572c-4dc0-40be-ad84-0ea610b2a833">

**Comment by leaf-potato** [comment]
@sunng87 Please review greptime-proto code https://github.com/GreptimeTeam/greptime-proto/pull/186.

**Comment by sunng87** [comment]
@leaf-potato Thank you! It may take some time to get the proto merged and you don't have to be blocked by this. Just use your git branch for now to upgrade in greptimedb.
