### ISSUE TITLE
Supports health checking in gRPC SDKs

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4674]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

It would be ideal for the gRPC SDK to have a status indicator to show whether it is currently healthy, just like to probe the database and connections. Users can use this status to perform fault tolerance and disaster recovery actions

**Comment by killme2008** [comment]
Already implemented in erlang ingester `is_alive`

https://github.com/GreptimeTeam/greptimedb-ingester-erl/blob/73f5d11977abf5dc2bce4b5eddc5334277d3b7ae/src/greptimedb.erl#L114

**Comment by killme2008** [comment]
@fengjiachun Do we have the same function in java ingester? If not,i think we should implement it.

https://github.com/GreptimeTeam/greptime-proto/blob/973f49cde88a582fb65755cc572ebcf6fb93ccf7/proto/greptime/v1/health.proto#L26

**Comment by fengjiachun** [comment]
> @fengjiachun Do we have the same function in java ingester? If not,i think we should implement it.
> 
> https://github.com/GreptimeTeam/greptime-proto/blob/973f49cde88a582fb65755cc572ebcf6fb93ccf7/proto/greptime/v1/health.proto#L26

I will implement this later.

**Comment by fengjiachun** [comment]
@killme2008 PTAL https://github.com/GreptimeTeam/greptimedb-ingester-java/pull/50

**Comment by fengjiachun** [comment]
Currently, the Java, Erlang, and Golang SDKs all support health checking; we can close it.
