### ISSUE TITLE
Customize channel information for sqlness tests

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#4679]
### What type of enhancement is this?

Other

### What does the enhancement do?

Our sqlness tests are using http api for sql test. Now with changes like #4580 different protocol/channel may behaviour different. It would be helpful to be able to test different channel via sqlness tests.

**Comment by J0HN50N133** [comment]
May I try?

**Comment by sunng87** [comment]
@J0HN50N133 Yes this is for you. I just can't assign it to you without you participating this thread. :laughing:
