### ISSUE TITLE
Prepared statement support in MySQL and PostgreSQL

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#470]
In order to support prepared statement, we need to implement a parse-bind-execute process in frontend caches parsed statement at connection-session scope.

**Comment by SSebo** [comment]
some references: 
https://www.postgresql.org/docs/current/sql-prepare.html
https://en.wikipedia.org/wiki/Prepared_statement
https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html

**Comment by MichaelScofield** [comment]
@SSebo I think "prepared" stmt should be handled here:

https://github.com/GreptimeTeam/greptimedb/blob/57979c9d3dba13beef5d63b4dc73fa1b3281e7e6/src/servers/src/mysql/handler.rs#L111

ane then "execute" here:

https://github.com/GreptimeTeam/greptimedb/blob/57979c9d3dba13beef5d63b4dc73fa1b3281e7e6/src/servers/src/mysql/handler.rs#L123

**Comment by SSebo** [comment]
@MichaelScofield Does this issue dependent on https://github.com/GreptimeTeam/greptimedb/issues/600 ?

**Comment by MichaelScofield** [comment]
@SSebo yes, part of it. The session crate was introduced in [this PR](https://github.com/GreptimeTeam/greptimedb/pull/672) already, I think prepared stmt can be stored in the `QueryContext` now.

**Comment by SSebo** [comment]
> @SSebo yes, part of it. The session crate was introduced in [this PR](https://github.com/GreptimeTeam/greptimedb/pull/672) already, I think prepared stmt can be stored in the `QueryContext` now.

Good job! you can assign this to me.

**Comment by SSebo** [comment]
@MichaelScofield I found `prepare` statement is not work for `msql-srv` crate. `fn on_prepare(&mut self, _query: &str, info: StatementMetaWriter<W>) -> io::Result<()>` is not called back when execute `PREPARE stmt1 FROM 'SELECT SQRT(POW(?,2) + POW(?,2)) AS hypotenuse';`

**Comment by MichaelScofield** [comment]
@SSebo It seems you have to use `[COM_STMT_PREPARE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html)` to trigger the callback of `on_prepare`. It is not text protocol.

**Comment by SSebo** [comment]
> @SSebo It seems you have to use [COM_STMT_PREPARE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html) to trigger the callback of `on_prepare`. It is not text protocol.

I debug the `msql-srv`, found the type is not  `[COM_STMT_PREPARE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html)` https://github.com/jonhoo/msql-srv/blob/26a5c35ed648f31cd2bb3943806e11b61b9dfd90/src/commands.rs#L106-L126
when execute that statement through mysql client to `msql-srv`
but It is ok when I execute real mysql server.

**Comment by MichaelScofield** [comment]
@SSebo prepare stmt in mysql could be executed in mysql-cli like [this](https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html), and this feature request is tracked in #769 . I think in this issue, we can focus on the "COM_STMT_PREPARE" type of prepare stmt. At last, it's the most often used type of prepare stmt. (Applications use some mysql drivers tend to use binary protocol to submit prepare stmt.)

As for pg, there're ["simple" and "extended" query protocols](https://www.postgresql.org/docs/current/protocol-overview.html), and prepare stmt uses the latter one. pgwire has the corresponding "simple" and "extended" handler for us to implement prepare stmt.

**Comment by SSebo** [comment]
> @SSebo prepare stmt in mysql could be executed in mysql-cli like [this](https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html) 

the prepare statement I used to execute is from [this](https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html) to mysql-cli, it can not trigger `on_prepare`.

**Comment by MichaelScofield** [comment]
@SSebo Yes, it's not COM_STMT_PREPARE. It's not using binary protocol, in the mysql command cli. It's the other form of prepare stmt.

**Comment by MichaelScofield** [comment]
ping @SSebo , any updates?

**Comment by SSebo** [comment]
Since MySQL and PG support prepared statement in different ways,
I would like to split the work into multiple small parts:

MySQL

```sql
mysql> PREPARE stmt1 FROM 'SELECT SQRT(POW(?,2) + POW(?,2)) AS hypotenuse';
mysql> SET @a = 3;
mysql> SET @b = 4;
mysql> EXECUTE stmt1 USING @a, @b;
+------------+
| hypotenuse |
+------------+
|          5 |
+------------+
mysql> DEALLOCATE PREPARE stmt1;

```


- [ ] support subset of [SET statement](https://dev.mysql.com/doc/refman/5.7/en/set-variable.html) (not include GLOBAL\SYSTEM system_var).
- [ ] support [PREPARE statment](https://dev.mysql.com/doc/refman/8.0/en/prepare.html)
- [ ] support [EXECUTE statement](https://dev.mysql.com/doc/refman/8.0/en/execute.html)
- [ ] support [DEALLOCATE statement](https://dev.mysql.com/doc/refman/8.0/en/deallocate-prepare.html)

Postgres

```sql
PREPARE fooplan (int, text, bool, numeric) AS
    INSERT INTO foo VALUES($1, $2, $3, $4);
EXECUTE fooplan(1, 'Hunter Valley', 't', 200.00);
DEALLOCATE PREPARE fooplan;
```

- [ ] support [PREPARE statment](https://www.postgresql.org/docs/current/sql-prepare.html)
- [ ] support [EXECUTE statement](https://www.postgresql.org/docs/current/sql-execute.html)
- [ ] support [DEALLOCATE statement](https://www.postgresql.org/docs/current/sql-deallocate.html)

**Comment by sunng87** [comment]
hi @SSebo , at least in modern postgresql clients, prepare keyword is no longer used. I have implemented prepared statement for postgresql in #925. Now it should work for most clients except rust-postgres, which uses parameter type inference that requires an upgrade of datafusion to support.

I suggest you to check mysql clients if `prepare` keyword are actually used. Mysql has a binary protocol for prepared statement: https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_command_phase_ps.html

**Comment by SSebo** [comment]
@sunng87 Got it. I'll do the MySQL binary protocol [prepared statements](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_command_phase_ps.html)

- [ ] [COM_STMT_PREPARE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_prepare.html)  MysqlShim::on_prepare
- [ ] [COM_STMT_EXECUTE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_execute.html) MysqlShim::on_execute
- [ ] [COM_STMT_CLOSE](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_close.html) MysqlShim::on_close

**Comment by SSebo** [comment]
It takes me lots of times to figure out how to infer the placeholder types in prepared sql which used in ' COM_STMT_PREPARE_OK'. 

Infer prepared statement parameter types supported by datafusion by this PR https://github.com/apache/arrow-datafusion/pull/4701

I patched the latest datafusion to greptime used revision for prepared statement logic to infer type https://github.com/apache/arrow-datafusion/compare/main...SSebo:arrow-datafusion:prepare.

When I checked the  rust, golang, and c mysql connector source code, I found the type information just ignored. 
Only the number of params is used.  so in my PR, just generate some dummy column in prepare phase.

**Comment by sunng87** [comment]
The situation is quite similar in postgresql, pg has parameter type inference as well, but some clients like jdbc are not using this feature at all. However, other clients like rust-postgres fully rely on this and has strict check for returned types.

**Comment by SSebo** [comment]
@sunng87 @MichaelScofield I'm working on the type infer version of prepare. Should statement be saved or  plain query string? Since `do_statement_query` is removed. there is not way to execute statement. 
Could you give me some advice?

**Comment by MichaelScofield** [comment]
@SSebo `do_statement_query` is removed because we are planning to not support executing SQLs directly in datanode instance, all protocol related tasks are handled in frontend. As tracked in #1010. That said, in the mean time, there's a `StatementHandler` implemented for datanode instance that can be used to execute stmt.

**Comment by sunng87** [comment]
I would suggest to cache `LogicalPlan` as prepared statement eventually because it's the most structured form of a query. Datafusion's `LogicalPlan` is capable with parameter type inference and replacement.

At the moment we only use `LogicalPlan` for selects but @MichaelScofield is going to change this in #1010. 

I think after the refactoring, protocol servers(mysql/pg) are responsible for 1. parsing sql query string to statement in protocol server's dialect; 2. transforming statement into neutral `LogicalPlan`. SqlHandlers will execute `LogicalPlan`s directly. 

If we have a plan for this, I think @SSebo can hold on the work on prepared statement and join the refactoring above. @MichaelScofield WDTY

**Comment by MichaelScofield** [comment]
@SSebo you are welcome to join #1010 , I think we can start from implementing `LogicalPlan::Prepare` in query engine.

**Comment by SSebo** [comment]
@sunng87 https://docs.pingcap.com/tidb/v5.4/sql-prepared-plan-cache this feature is very similar to your idea.

**Comment by killme2008** [comment]
The final PR was merged https://github.com/GreptimeTeam/greptimedb/pull/1813

We can close this issue right now, thanks to all of you.
