### ISSUE TITLE
Failed to use table name which is valid in MySQL

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#4749]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Table Engine

### Minimal reproduce step

```
CREATE TABLE IF NOT EXISTS `p_perftest001@cc3kvQ_D1D9H9GOZGMIY97TWH20R1LRC8U0SFBA` (
    ts TIMESTAMP TIME INDEX,
    a INT
);
```

### What did you expect to see?

```
Query OK, 0 rows affected (0.02 sec)
```

### What did you see instead?

```
ERROR 1210 (HY000): (InvalidArguments): Invalid table name: p_perftest001@cc3kvQ_D1D9H9GOZGMIY97TWH20R1LRC8U0SFBA
```

### What operating system did you use?

macOS

### What version of GreptimeDB did you use?

0.9.3

**Comment by shuiyisong** [comment]
Addition
- we might want to ensure the behavior is consistent under all insert protocols(MySQL, PG, gRPC, influxdb, etc.)

**Comment by v0y4g3r** [comment]
Looks loke `@` is not considered a valid character:

- https://github.com/GreptimeTeam/greptimedb/blob/dcae21208bf9b0511ca21174464bffdd52f0cfe5/src/common/meta/src/key.rs#L147

**Comment by killme2008** [comment]
> Looks loke `@` is not considered a valid character in table name:
> 
> * https://github.com/GreptimeTeam/greptimedb/blob/dcae21208bf9b0511ca21174464bffdd52f0cfe5/src/common/meta/src/key.rs#L147

We can add it to the valid character sets. Change the regular expression.

**Comment by v0y4g3r** [comment]
> > Looks loke `@` is not considered a valid character in table name:
> > 
> > * https://github.com/GreptimeTeam/greptimedb/blob/dcae21208bf9b0511ca21174464bffdd52f0cfe5/src/common/meta/src/key.rs#L147
> 
> We can add it to the valid character sets. Change the regular expression.

Sounds good #4766
