### ISSUE TITLE
Timeout support for MySQL and Postgres channel

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#4760]
### What problem does the new feature solve?

Add variables to MySQL and Postgres for controlling statement execution timeout.

This is also a compatibility requirement from Sigma.

### What does the feature do?

For MySQL protocol, we need to support `SET MAX_EXECUTION_TIME = 5000`: https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_max_execution_time

For Postgres protocol, we need to support `SET statement_timeout TO 5000`: https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT

**Comment by lyang24** [comment]
This looks interesting. I wonder are timeout settings per session? I am trying to measure the scope of the work, do we have similar session variable implementation examples on the codebase?

**Comment by sunng87** [comment]
@lyang24 good to hear. Yes this variable is session-scoped like our time zone setting. You can check `src/session/src/lib.rs` as the start for timezone impl, including how we set and how we use it.

**Comment by lyang24** [comment]
Thanks for the code pointers. may i take this issue?

**Comment by sunng87** [comment]
Sure
