### ISSUE TITLE
use `information_schema` returns Unknown database 'information_schema'

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4773]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step

1. Start a standalone instance
2. Connect via MySQL client or pg client
3. run `use information_schema`

### What did you expect to see?

Database changed

### What did you see instead?

ERROR 1102 (42000): Unknown database 'information_schema'

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

**Comment by WenyXu** [comment]
The bug related to https://github.com/GreptimeTeam/greptimedb/blob/627a3262735eaa490cee8dadf413b61a04948d16/src/frontend/src/instance.rs#L357-L364 @J0HN50N133  Would you like to take a look 👀

**Comment by J0HN50N133** [comment]
I've addressed the bug. Could I fix it later this weekend? The `is_reserved_schema_name` check should only be done when creating new database/schema.

**Comment by sunng87** [comment]
duplicate #4762
