### ISSUE TITLE
Support flexible data exporting demand in `copy to`

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#4776]
### What problem does the new feature solve?

`copy to` can only export data within a time range, which is not sufficient for various data exporting demand sometimes.

### What does the feature do?

To meet the various data exporting demand, I think it's best for user to write queries in the `copy to` statement. Like this:

```sql
COPY tbl TO '/xxx/xxx/output.parquet' WITH (FORMAT = 'parquet', Q = 'select a, b from tbl where c = 1');
```

Only the data populated by the "Q" is exported. In this way, user could express his data exporting demand in the query, which is very flexible.

**Comment by Kev1n8** [comment]
I'm interested in this. And I have a wonder regarding the implementation, looking forward to any suggestions:

Assume making time range option compatible with `Q` option. How should it behave when the cmd is: `COPY tbl TO 'xxx.parquet' WITH (FORMAT = 'parquet', START_TIME = some_st, END_TIME = some_et, Q = 'SELECT * from tbl where ts <some_st')`? One way is to perform `AND` on both time range filters inside and outside of the `Q`.

**Comment by MichaelScofield** [comment]
@Kev1n8 Thank you for being interested. I'm thinking we can use the "csv" of the [alternative format](https://docs.greptime.cn/en/user-guide/protocols/http#alternative-formats) in the http api instead. So I'm gonna close this issue. Thanks again!
