### ISSUE TITLE
PromQL  __field__  column has  Upper

### ISSUE THREAD

**Issue by Fordisk123** [GreptimeTeam/greptimedb#4786]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Query Engine

### Minimal reproduce step

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/9546537e-fa8a-43b6-bb17-15f87dcb701e">
I get an error when I query this field

### What did you expect to see?

<img width="1637" alt="image" src="https://github.com/user-attachments/assets/9281f892-2b42-4c09-9178-bb28a6f40c04">
this query will

### What did you see instead?

Is it a bug or does it need additional escaping?

### What operating system did you use?

Centos7

### What version of GreptimeDB did you use?

0.9.3

### Relevant log output and stack trace

```bash
Internal error during building DataFusion plan: No field named ess_meter_negativeacticet. Valid fields are "snStorageEssMeterYcTopic"."ess_meter_negativeacticeT", "snStorageEssMeterYcTopic"."ess_meter_positiveacticeT", "snStorageEssMeterYcTopic".ess_meter_cos, "snStorageEssMeterYcTopic".ess_meter_f, "snStorageEssMeterYcTopic".ess_meter_ia, "snStorageEssMeterYcTopic".ess_meter_ib, "snStorageEssMeterYcTopic".ess_meter_ic, "snStorageEssMeterYcTopic".ess_meter_negativeacticef, "snStorageEssMeterYcTopic".ess_meter_negativeacticeg, "snStorageEssMeterYcTopic".ess_meter_negativeacticej, "snStorageEssMeterYcTopic".ess_meter_negativeacticep, "snStorageEssMeterYcTopic".ess_meter_p, "snStorageEssMeterYcTopic".ess_meter_positiveacticef, "snStorageEssMeterYcTopic".ess_meter_positiveacticeg, "snStorageEssMeterYcTopic".ess_meter_positiveacticej, "snStorageEssMeterYcTopic".ess_meter_positiveacticep, "snStorageEssMeterYcTopic".ess_meter_q, "snStorageEssMeterYcTopic".ess_meter_ua, "snStorageEssMeterYcTopic".ess_meter_ub, "snStorageEssMeterYcTopic".ess_meter_uc, "snStorageEssMeterYcTopic"."jiancedianID", "snStorageEssMeterYcTopic".ts.
```

**Comment by evenyag** [comment]
Looks like a bug. Could you also provide the SQL that creates this table?

**Comment by killme2008** [comment]
Could you try use the single quote? `'ess_meger_xxx'`.

**Comment by Fordisk123** [comment]
> Looks like a bug. Could you also provide the SQL that creates this table?

CREATE TABLE IF NOT EXISTS "snStorageEssMeterYcTopic" (
  "jiancedianID" STRING NULL,
  "ess_meter_negativeacticeT" DOUBLE NULL,
  "ess_meter_positiveacticeT" DOUBLE NULL,
  "ts" TIMESTAMP(9) NOT NULL,
  "ess_meter_cos" DOUBLE NULL,
  "ess_meter_f" DOUBLE NULL,
  "ess_meter_ia" DOUBLE NULL,
  "ess_meter_ib" DOUBLE NULL,
  "ess_meter_ic" DOUBLE NULL,
  "ess_meter_negativeacticef" DOUBLE NULL,
  "ess_meter_negativeacticeg" DOUBLE NULL,
  "ess_meter_negativeacticej" DOUBLE NULL,
  "ess_meter_negativeacticep" DOUBLE NULL,
  "ess_meter_p" DOUBLE NULL,
  "ess_meter_positiveacticef" DOUBLE NULL,
  "ess_meter_positiveacticeg" DOUBLE NULL,
  "ess_meter_positiveacticej" DOUBLE NULL,
  "ess_meter_positiveacticep" DOUBLE NULL,
  "ess_meter_q" DOUBLE NULL,
  "ess_meter_ua" DOUBLE NULL,
  "ess_meter_ub" DOUBLE NULL,
  "ess_meter_uc" DOUBLE NULL,
  TIME INDEX ("ts"),
  PRIMARY KEY ("jiancedianID")
)

ENGINE=mito
WITH(
  merge_mode = 'last_non_null'
)

**Comment by Fordisk123** [comment]
> Could you try use the single quote? `'ess_meger_xxx'`.

<img width="1248" alt="image" src="https://github.com/user-attachments/assets/f6ad63fc-19c9-4f97-bccb-f9628374a6ea">

**Comment by Fordisk123** [comment]
> > Could you try use the single quote? `'ess_meger_xxx'`.
> 
> <img alt="image" width="1248" src="https://private-user-images.githubusercontent.com/24662495/375413653-f6ad63fc-19c9-4f97-bccb-f9628374a6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Njk3MTIsIm5iZiI6MTcyODU2OTQxMiwicGF0aCI6Ii8yNDY2MjQ5NS8zNzU0MTM2NTMtZjZhZDYzZmMtMTljOS00Zjk3LWJjY2ItZjk2MjgzNzRhNmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDE0MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYmQ1ZGRlYTliNGJmZTEzN2UwY2E2ZjFiZGQzZTFhZDQwZmFlMGFhNGQ4OThmMTEyZWVlNjMzMTNhZTYxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FKIvXXIZiKpA8DdvazMis8ZRUEB-lopJcUMNj7xoUjA">

{
    "code": 3000,
    "error": "Internal error during building DataFusion plan: No field named __filed__. Valid fields are \"snStorageEssMeterYcTopic\".\"ess_meter_negativeacticeT\", \"snStorageEssMeterYcTopic\".\"ess_meter_positiveacticeT\", \"snStorageEssMeterYcTopic\".ess_meter_cos, \"snStorageEssMeterYcTopic\".ess_meter_f, \"snStorageEssMeterYcTopic\".ess_meter_ia, \"snStorageEssMeterYcTopic\".ess_meter_ib, \"snStorageEssMeterYcTopic\".ess_meter_ic, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticef, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticeg, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticej, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticep, \"snStorageEssMeterYcTopic\".ess_meter_p, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticef, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticeg, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticej, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticep, \"snStorageEssMeterYcTopic\".ess_meter_q, \"snStorageEssMeterYcTopic\".ess_meter_ua, \"snStorageEssMeterYcTopic\".ess_meter_ub, \"snStorageEssMeterYcTopic\".ess_meter_uc, \"snStorageEssMeterYcTopic\".\"jiancedianID\", \"snStorageEssMeterYcTopic\".ts, \"snStorageEssMeterYcTopic\".\"jiancedianID\", \"snStorageEssMeterYcTopic\".\"ess_meter_negativeacticeT\", \"snStorageEssMeterYcTopic\".\"ess_meter_positiveacticeT\", \"snStorageEssMeterYcTopic\".ts, \"snStorageEssMeterYcTopic\".ess_meter_cos, \"snStorageEssMeterYcTopic\".ess_meter_f, \"snStorageEssMeterYcTopic\".ess_meter_ia, \"snStorageEssMeterYcTopic\".ess_meter_ib, \"snStorageEssMeterYcTopic\".ess_meter_ic, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticef, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticeg, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticej, \"snStorageEssMeterYcTopic\".ess_meter_negativeacticep, \"snStorageEssMeterYcTopic\".ess_meter_p, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticef, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticeg, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticej, \"snStorageEssMeterYcTopic\".ess_meter_positiveacticep, \"snStorageEssMeterYcTopic\".ess_meter_q, \"snStorageEssMeterYcTopic\".ess_meter_ua, \"snStorageEssMeterYcTopic\".ess_meter_ub, \"snStorageEssMeterYcTopic\".ess_meter_uc.",
    "execution_time_ms": 2
}
