### ISSUE TITLE
Support index on JSON keys and values

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#4849]
### What problem does the new feature solve?

The JSON datatype is now supported by the database. However, we don't have mechanisms to speedup the query if we want to filter certain keys or values within the JSON.

### What does the feature do?

Support creating an index using JSON keys or values. Here is an example of a map index in Clickhouse.

```
INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
```

**Comment by evenyag** [comment]
Duplicated with #5080
