### ISSUE TITLE
flow result incorrect 

### ISSUE THREAD

**Issue by slitobo** [GreptimeTeam/greptimedb#4863]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode

### Minimal reproduce step

I referenced this document to verify the usage of flow, but it reported an error in version v0.9
https://docs.greptime.cn/user-guide/continuous-aggregation/usecase-example

### What did you expect to see?

flow is working ok , table ngx_country is ok . 

### What did you see instead?

//  select * from ngx_access_log limit 1;

1640966400000 | client1 | US
-- | -- | --

// show flows;
calc_ngx_country

// select * from ngx_country;
nothing 

log: 

2024-10-22T11:54:40.381756Z ERROR flow::adapter: Flow 1029 has following errors: 0: Internal error: Accum and output should have the non-zero and same length, found accum.len() = 0, output.len() = 0, at src/flow/src/compute/render/reduce.rs:859:9

### What operating system did you use?

centos7

### What version of GreptimeDB did you use?

0.9.3

### Relevant log output and stack trace

```bash
2024-10-22T11:54:40.381756Z ERROR flow::adapter: Flow 1029 has following errors: 0: Internal error: Accum and output should have the non-zero and same length, found accum.len() = 0, output.len() = 0, at src/flow/src/compute/render/reduce.rs:859:9
```

**Comment by discord9** [comment]
This bug is fixed in v0.9.5 release in #4599(specifically in [here](https://github.com/GreptimeTeam/greptimedb/pull/4599/commits/dd5716c5413bd7d8bb5c7142d7709c3864850029)), so if it isn't too much trouble updating database to latest version  should make this bug go away.

**Comment by slitobo** [comment]
i chage to v0.9.5, try this: https://docs.greptime.cn/user-guide/continuous-aggregation/overview
but get a error:

2024-10-22T12:19:44.061559Z ERROR flow::adapter: Send writeback request errors err=0: External error, at src/flow/src/adapter.rs:316:30
1: External error, at src/flow/src/server.rs:497:14
2: Failed to insert data, at /greptimedb/src/operator/src/insert.rs:333:26
3: External error, at src/frontend/src/instance/standalone.rs:87:14
4: Operation to region server failed, at src/frontend/src/instance/standalone.rs:69:14
5: Execute gRPC request error, at src/datanode/src/region_server.rs:381:18
6: Failed to handle request for region 4745938862080(1105, 0), at src/datanode/src/region_server.rs:770:14
7: Invalid request to region 4745938862080(1105, 0), reason: value has type Int64, but column high_size_count has type Ok(Float64)(10), at src/mito2/src/request.rs:372:9

**Comment by slitobo** [comment]
After updating to 0.9.5, it works normally
