### ISSUE TITLE
The gRPC protocol needs to support the JSON type

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#4872]
### What type of enhancement is this?

Tech debt reduction, User experience

### What does the enhancement do?

The GreptimeDB already supports JSON type via SQL statements.
But gRPC protocol doesn't support it.
There are two things need to be done:
1. Support JSON type in the `proto` file.
2. Support JSON type in the [Go SDK](https://github.com/GreptimeTeam/greptimedb-ingester-go) and [Java SDK](https://github.com/GreptimeTeam/greptimedb-ingester-java).

**Comment by fengjiachun** [comment]
Java SDK done: https://github.com/GreptimeTeam/greptimedb-ingester-java/pull/52

**Comment by fengjiachun** [comment]
@daviderli614 Let's add JSON Type support to the Go SDK.

**Comment by daviderli614** [comment]
Wait until I finish this PR：https://github.com/GreptimeTeam/greptimedb-ingester-go/pull/51

**Comment by daviderli614** [comment]
> @daviderli614 Let's add JSON Type support to the Go SDK.

Wait until I finish this PR：https://github.com/GreptimeTeam/greptimedb-ingester-go/pull/51

**Comment by daviderli614** [comment]
Go SDK example: https://github.com/GreptimeTeam/greptimedb-ingester-go/blob/main/examples/jsondata/README.md

**Comment by nicecui** [comment]
done
