### ISSUE TITLE
Support altering table's compaction options

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#4905]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Like altering table's TTL option, compaction options are best able to be modified after table is created.

**Comment by lyang24** [comment]
I think alter compaction option can be implemented in the front end starting with adding a new variant to [ChangeOption](https://github.com/GreptimeTeam/greptimedb/blob/be72d3bedba9202cc3c938fdfde41f591f5c7355/src/store-api/src/region_request.rs#L661C1-L664C2). However, [TWCS](https://github.com/GreptimeTeam/greptimedb/blob/be72d3bedba9202cc3c938fdfde41f591f5c7355/src/mito2/src/region/options.rs#L151C1-L159C2) is the only compaction strategy available. Do we plan to offer some compaction option in the near future?

**Comment by MichaelScofield** [comment]
@lyang24 Right now changing the configs of TWCS is sufficient.

**Comment by lyang24** [comment]
sounds good can i work on this issue?

**Comment by MichaelScofield** [comment]
@lyang24 Sure, assigned to you.

**Comment by killme2008** [comment]
Closed via #4965 
Thank you @lyang24
