### ISSUE TITLE
Unify the datanode options in frontend and metasrv

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#4932]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Currently there are two `DatanodeOptions`: one in `frontend::service_config::datanode` and the other in `meta_srv::metasrv`. They both have the same purpose: set the grpc client options to datanode. It's better to unify them.

**Comment by linyihai** [comment]
I would like to take a look.
