### ISSUE TITLE
refactor: Avoid wrapping `Option` for `CacheManagerRef`

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#4968]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

In the mito2 crate, we use `Option<CacheManagerRef>` to make writing tests easier. (We can pass `None` directly).
https://github.com/GreptimeTeam/greptimedb/blob/0e0c4faf0d784f25fed8f26e7000f1f869c88587/src/mito2/src/read/scan_region.rs#L162-L170

https://github.com/GreptimeTeam/greptimedb/blob/0e0c4faf0d784f25fed8f26e7000f1f869c88587/src/mito2/src/region/opener.rs#L67-L69

However, the manager actually won't be None in other cases. This introduces a lot of lengthy option checks.

### Implementation challenges

We can replace all usage of `Option<CacheManagerRef>` with `CacheMangerRef`.

**Comment by linyihai** [comment]
the changes were more than I thought, but according to the compiler prompts, it can run the test, but I still need to review if there is any problem, and then submit a PR later

**Comment by evenyag** [comment]
Thanks, @linyihai. I have merged #4996
