### ISSUE TITLE
Add support for all comparable types for `greatest` function

### ISSUE THREAD

**Issue by 0neSe7en** [GreptimeTeam/greptimedb#4991]
### What problem does the new feature solve?

The `greatest` function only supports `date`. It would be great if it could support all comparable types. For now I have to use  `CASE WHEN` to get the greatest value.

### What does the feature do?

support `select greatest(v1, 100)` etc.

**Comment by waynexia** [comment]
reference to upstream: https://github.com/apache/datafusion/issues/6531
