### ISSUE TITLE
sqlness vector test results difference in local env

### ISSUE THREAD

**Issue by lyang24** [GreptimeTeam/greptimedb#5004]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

cargo sqlness on lastest main branch

### What did you expect to see?

no diff on test result files

### What did you see instead?

looks like some precision diff?

--- a/tests/cases/standalone/common/types/vector/vector.result
+++ b/tests/cases/standalone/common/types/vector/vector.result
@@ -56,9 +56,9 @@ SELECT round(cos_distance('[7.0, 8.0, 9.0]', v), 4) FROM t;
 +-----------------------------------------------------------+
 | round(cos_distance(Utf8("[7.0, 8.0, 9.0]"),t.v),Int64(4)) |
 +-----------------------------------------------------------+
-| 0.0406                                                    |
-| 0.0018                                                    |
-| 0.0                                                       |
+| 0.0432                                                    |
+| 0.0037                                                    |
+| 0.0005                                                    |
 +-----------------------------------------------------------+
 
 SELECT *, round(cos_distance('[7.0, 8.0, 9.0]', v), 4) as d FROM t ORDER BY d;
@@ -66,9 +66,9 @@ SELECT *, round(cos_distance('[7.0, 8.0, 9.0]', v), 4) as d FROM t ORDER BY d;
 +-------------------------+--------------------------+--------+
 | ts                      | v                        | d      |
 +-------------------------+--------------------------+--------+
-| 1970-01-01T00:00:00.003 | 0000e0400000004100001041 | 0.0    |
-| 1970-01-01T00:00:00.002 | 000080400000a0400000c040 | 0.0018 |
-| 1970-01-01T00:00:00.001 | 0000803f0000004000004040 | 0.0406 |
+| 1970-01-01T00:00:00.003 | 0000e0400000004100001041 | 0.0005 |
+| 1970-01-01T00:00:00.002 | 000080400000a0400000c040 | 0.0037 |
+| 1970-01-01T00:00:00.001 | 0000803f0000004000004040 | 0.0432 |

### What operating system did you use?

mac

### What version of GreptimeDB did you use?

lastest main

**Comment by killme2008** [comment]
@zhongzc Please take a look

**Comment by zhongzc** [comment]
Under investigation
