### ISSUE TITLE
Cannot alter table to set TTL

### ISSUE THREAD

**Issue by dekelpilli** [GreptimeTeam/greptimedb#5026]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step

1. Create a table

```sql
CREATE TABLE IF NOT EXISTS "test" (
  "ts" TIMESTAMP(9) NOT NULL,
  "s" STRING,
  TIME INDEX ("ts"),
  PRIMARY KEY ("s")
);
```

2. Attempt to set TTL on table as per docs (https://docs.greptime.com/reference/sql/alter/#alter-table-options)

```sql
ALTER TABLE test SET 'ttl'='1d';
```

### What did you expect to see?

Successful execution, causing table to gain TTL

### What did you see instead?

```json
{
    "code": 2000,
    "error": "sql parser error: expect keyword ADD or DROP or MODIFY or RENAME after ALTER TABLE, found SET",
    "execution_time_ms": 0
}
```

### What operating system did you use?

Mac OS 15.1

### What version of GreptimeDB did you use?

0.9.5

**Comment by lyang24** [comment]
Hi, I did not find ttl support on 0.9.5's [release notes](https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.9.5). However, alter ttl feature is already [merged](https://github.com/GreptimeTeam/greptimedb/pull/4848) in master and will likely be included on the future releases.

**Comment by dekelpilli** [comment]
I see, so it's just that the docs website shouldn't be showing that option under `0.9` (yet?). Thanks for the quick response.

**Comment by evenyag** [comment]
We'll release v0.10 soon. The latest nightly release should support this feature: https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.10.0-nightly-20241111

**Comment by evenyag** [comment]
> I see, so it's just that the docs website shouldn't be showing that option under `0.9` (yet?).

Oh, that's unexpected. We should correct the document. Thanks for your report!
