### ISSUE TITLE
Fix invalidation for schema caches.

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#5064]
@WenyXu  Looks like schema cache is missing in `build_fundamental_cache_registry` so the cache invalidation does not take effect https://github.com/GreptimeTeam/greptimedb/blob/24612f62dd7c0f131c2edb926487e96c72ed2c6b/src/cache/src/lib.rs#L43

_Originally posted by @v0y4g3r in https://github.com/GreptimeTeam/greptimedb/issues/5063#issuecomment-2505118645_

**Comment by evenyag** [comment]
Can we close this issue? @v0y4g3r
