### ISSUE TITLE
Keep PipelineChecker in the end of all PhysicalOptimizer rules

### ISSUE THREAD

**Issue by Fischer0522** [GreptimeTeam/greptimedb#5076]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Currently, datafusion places `PipelineChecker` at the end of the PhysicalOptimizer rules and uses it as a final gatekeeping rule. Therefore, all custom requests should be added before it to ensure that the plans after custom optimization (like `WindowedSort` or `RemoveDuplicate`) can still meet the checks of PipelineChecker.

In datafusion, `PipelineChecker` is described as follow:
```Rust
            // The PipelineChecker rule will reject non-runnable query plans that use
            // pipeline-breaking operators on infinite input(s). The rule generates a
            // diagnostic error message when this happens. It makes no changes to the
            // given query plan; i.e. it only acts as a final gatekeeping rule.
            Arc::new(PipelineChecker::new()),
```

**Comment by killme2008** [comment]
@Fischer0522 Thanks for your suggestion.

@waynexia What do you think?

**Comment by waynexia** [comment]
Thanks for pointing this out @Fischer0522 ❤️ The patch is in #5092
