### ISSUE TITLE
Add the backup and restore API for metasrv

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb#5085]
### What type of enhancement is this?

Refactor

## Background

The metadata that metasrv manages is vital for the whole cluster management. Like other data, we also need to add the backup and restore API for metasrv:

1. **Add the abstraction for metadata backup and restore**: Although we can backup and restore metadata for backend storage of metasrv, it's not the best operation practice. It should be better to handle in the metasrv;
2. **For disaster recovery**: If we back up the metadata period, it's easy to recover from a disaster. Actually, we always back up the etcd data scheduled;
3. **Easy to troubleshoot**: It will be easy to dump the raw metadata to debug the problem;

## Implementation

We can add `backup` and `restore` API in [metasrv admin API](https://docs.greptime.com/contributor-guide/metasrv/admin-api#maintenance-http-endpoint).

**Comment by ozewr** [comment]
Hello, I want to give this a try. Could you tell me which part of the code I should read, or provide some other relevant information?

**Comment by zyy17** [comment]
> Hello, I want to give this a try. Could you tell me which part of the code I should read, or provide some other relevant information?

👍 Maybe @fengjiachun and @WenyXu can give you some tips.

**Comment by WenyXu** [comment]
Hi @ozewr, thank you for your interest in this good first issue! To get started, you can take a look at [this file](https://github.com/GreptimeTeam/greptimedb/blob/main/src/common/meta/src/key.rs), which provides some context on how metadata is structured in our system.

The first task involves dumping and restoring the metadata. Additionally, we aim to design a format to store the exported metadata, ensuring its compatibility and flexibility for future use.

Let us know if you have any questions or need further guidance. We're here to help!

**Comment by ozewr** [comment]
Hi,I have already read the relevant code.I think can use [query](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L50) to dump all metadate.And use [put](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L52) to restore it. Can't we use `json` or `toml` to store the metadata?

**Comment by ozewr** [comment]
Hi,I have already read the relevant code.I think can use [query](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L50) to dump all metadate.And use [put](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L52) to restore it. Can't we use `json` or `toml` to store the metadata?@WenyXu @zyy17

**Comment by WenyXu** [comment]
> Hi,I have already read the relevant code.I think can use [query](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L50) to dump all metadate.And use [put](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/common/meta/src/kv_backend.rs#L52) to restore it. Can't we use `json` or `toml` to store the metadata?@WenyXu @zyy17

I believe storing metadata in a JSON file is not ideal. Instead, we should handle metadata as binary data rather than JSON.

**Comment by ozewr** [comment]
> I believe storing metadata in a JSON file is not ideal. Instead, we should handle metadata as binary data rather than JSON.

I want to use the [bincode](https://docs.rs/bincode/latest/bincode/index.html) crate so that I can easily serialize metadata into binary data. However, I couldn't find it in the Cargo.toml.

**Comment by ozewr** [comment]
> I believe storing metadata in a JSON file is not ideal. Instead, we should handle metadata as binary data rather than JSON.

I want to use the [bincode](https://docs.rs/bincode/latest/bincode/index.html) crate so that I can easily serialize metadata into binary data. However, I couldn't find it in the Cargo.toml. Can I import it ?

**Comment by ozewr** [comment]
> ## Implementation
> 
> We can add `backup` and `restore` API in [metasrv admin API](https://docs.greptime.com/contributor-guide/metasrv/admin-api#maintenance-http-endpoint).


I'm trying to accomplish this, but I noticed that the [Admin](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69) HTTP implementation seems quite simple. It doesn't appear to support receiving a binary stream, which makes me unsure how to extract data from a backup binary file during the restore process. Does this require an extension? @WenyXu @zyy17 
[src/meta-srv/src/service/admin.rs:69](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69)
```rust
#[async_trait::async_trait]
pub trait HttpHandler: Send + Sync {
    async fn handle(
        &self,
        path: &str,
        method: http::Method,
        params: &HashMap<String, String>,
    ) -> crate::Result<http::Response<String>>;
}
```

**Comment by WenyXu** [comment]
> > ## Implementation
> > We can add `backup` and `restore` API in [metasrv admin API](https://docs.greptime.com/contributor-guide/metasrv/admin-api#maintenance-http-endpoint).
> 
> I'm trying to accomplish this, but I noticed that the [Admin](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69) HTTP implementation seems quite simple. It doesn't appear to support receiving a binary stream, which makes me unsure how to extract data from a backup binary file during the restore process. Does this require an extension? @WenyXu @zyy17 [src/meta-srv/src/service/admin.rs:69](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69)
> 
> ```rust
> #[async_trait::async_trait]
> pub trait HttpHandler: Send + Sync {
>     async fn handle(
>         &self,
>         path: &str,
>         method: http::Method,
>         params: &HashMap<String, String>,
>     ) -> crate::Result<http::Response<String>>;
> }
> ```

We can use the CLI to create a `kvbackend` for direct connection to the store backend.

**Comment by ozewr** [comment]
> > > ## Implementation
> > > We can add `backup` and `restore` API in [metasrv admin API](https://docs.greptime.com/contributor-guide/metasrv/admin-api#maintenance-http-endpoint).
> > 
> > 
> > I'm trying to accomplish this, but I noticed that the [Admin](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69) HTTP implementation seems quite simple. It doesn't appear to support receiving a binary stream, which makes me unsure how to extract data from a backup binary file during the restore process. Does this require an extension? @WenyXu @zyy17 [src/meta-srv/src/service/admin.rs:69](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69)
> > ```rust
> > #[async_trait::async_trait]
> > pub trait HttpHandler: Send + Sync {
> >     async fn handle(
> >         &self,
> >         path: &str,
> >         method: http::Method,
> >         params: &HashMap<String, String>,
> >     ) -> crate::Result<http::Response<String>>;
> > }
> > ```
> 
> We can use the CLI to create a `kvbackend` for direct connection to the store backend.

You mean not using APIs during backup and restore, directly connecting via CLI instead?

**Comment by WenyXu** [comment]
> > > > ## Implementation
> > > > We can add `backup` and `restore` API in [metasrv admin API](https://docs.greptime.com/contributor-guide/metasrv/admin-api#maintenance-http-endpoint).
> > > 
> > > 
> > > I'm trying to accomplish this, but I noticed that the [Admin](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69) HTTP implementation seems quite simple. It doesn't appear to support receiving a binary stream, which makes me unsure how to extract data from a backup binary file during the restore process. Does this require an extension? @WenyXu @zyy17 [src/meta-srv/src/service/admin.rs:69](https://github.com/GreptimeTeam/greptimedb/blob/5ffda7e97130c449455ee83f2afc80ee76d4b168/src/meta-srv/src/service/admin.rs#L69)
> > > ```rust
> > > #[async_trait::async_trait]
> > > pub trait HttpHandler: Send + Sync {
> > >     async fn handle(
> > >         &self,
> > >         path: &str,
> > >         method: http::Method,
> > >         params: &HashMap<String, String>,
> > >     ) -> crate::Result<http::Response<String>>;
> > > }
> > > ```
> > 
> > 
> > We can use the CLI to create a `kvbackend` for direct connection to the store backend.
> 
> You mean not using APIs during backup and restore, directly connecting via CLI instead?

Yes. But adding `backup` and `restore` APIs to the admin endpoint would also bring some benefits. It would allow PaaS-level services to invoke these APIs directly. cc @zyy17, any thoughts

**Comment by ozewr** [comment]
> Yes. But adding `backup` and `restore` APIs to the admin endpoint would also bring some benefits. It would allow PaaS-level services to invoke these APIs directly. cc @zyy17, any thoughts

If we are going to use APIs, I think we should extend the current HTTP implementation of the Admin. If we are using the CLI, would it require creating a new project?
