### ISSUE TITLE
Consider adjusting the default purge size and interval of the WAL

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#5106]
### What type of enhancement is this?

User experience

### What does the enhancement do?

The default purge config for the WAL may be too large
https://github.com/GreptimeTeam/greptimedb/blob/c732016fa0f6ebee536e00fd945a728ae79ce283/src/common/wal/src/config/raft_engine.rs#L53-L54

The WAL can easily consume more than 4GB of disk space. We may consider adjusting the default config.

### Implementation challenges

We may find a proper default value. Users can adjust the value if the default config becomes the bottleneck.

**Comment by killme2008** [comment]
Let's fix it in v0.11
