### ISSUE TITLE
discussion for set fulltext options method

### ISSUE THREAD

**Issue by lyang24** [GreptimeTeam/greptimedb#5116]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

https://github.com/GreptimeTeam/greptimedb/blob/19373d806d7bedbb8f701d169706d23a3d1c2d8f/src/datatypes/src/schema/column_schema.rs#L286C1-L300C6

seems like duplicate to me, can we replace set_fulltext_options with  with_fulltext_options ?

**Comment by CookiePieWw** [comment]
They are different in parameters and return type actually. It seems interchangeable as you said but replacement requires lots of manual work as I tried, so I'd like to keep them all, one for initialization and one as setter.
