### ISSUE TITLE
TLS support for database protocols

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#515]
Both mysql and postgresql shares same port of plain-text connection and secure one. Unlike http or grpc transports, database protocols have their own tls handshake process. So we might not be able to utilize haproxy or cloud load balancer for tls termination. Tls support has to be implemented in database side. Task including:

- provide option to configure certs/key for mysql/postgresql
- load configured certs/key from file system
- start mysql/postgresql port with tls acceptor
- add session information about whether a connection is secure or not

We can provide options to restrict insecure connection access in future

**Comment by sunng87** [comment]
Yes, at least we need some configuration to enable TLS. 

For postgres, using [pgwire](https://github.com/sunng87/pgwire), TLS is already supported via [this option](https://github.com/GreptimeTeam/greptimedb/blob/e823cde6ff7b1cbed33093306204e894c0523d01/src/servers/src/postgres/server.rs#L73), which is set to `None` to disable.  There is [an example](https://github.com/sunng87/pgwire/blob/master/examples/secure_server.rs) in pgwire to demo its usage.

For MySQL, I haven't got time investigate its library support for TLS, we probably need to work with [upstream](https://github.com/datafuselabs/opensrv) and [upstream of upstream](https://github.com/blackbeam/rust_mysql_common) for the support.

When all protocol level supported finished, we need to add last-mile configuration to manage and load cert/key files.

**Comment by SSebo** [comment]
For MySQL, looks like there is one [issue](https://github.com/datafuselabs/opensrv/issues/6 ) about this.

**Comment by SSebo** [comment]
I made a PR to opensrv-mysql to support MySQL TLS https://github.com/datafuselabs/opensrv/pull/34
