### ISSUE TITLE
When will the authentication system be done?

### ISSUE THREAD

**Issue by DiamondMofeng** [GreptimeTeam/greptimedb#526]
I have a small programme using InfluxDB,and I am glad to try Greptime.

While in the doc/User Guide/Concepts/Components ,which says "Frontend accepts incoming request, authenticates it,......", I have not found a way to authenticate requests. 

As there is no way to authenticate requests, I am afraid that data will leak or be tampered with.

**Comment by MichaelScofield** [comment]
Thanks, the auth feature is under rapid development, we will release it in the near future!
