### ISSUE TITLE
Explain query not work in MySQL client

### ISSUE THREAD

**Issue by francis-du** [GreptimeTeam/greptimedb#531]
### What type of bug is this?

Crash

### What subsystems are affected?

Standalone mode

### What happened?

![image](https://user-images.githubusercontent.com/25944814/202078728-6a9453fe-5211-4e73-8a05-4dffcfe53e0b.png)

### What operating system did you use?

MBP Intel CPU

### How can we reproduce the bug?

Run query in MySQL client:

```bash
explain select * from numbers;
```

**Comment by v0y4g3r** [comment]
MySQL protocol now only supports reading and writing data, more functionalities is under active developing. `EXPLAIN` will soon be supported.

**Comment by francis-du** [comment]
How to support `Explain` syntax for this? can i try it?

**Comment by v0y4g3r** [comment]
> How to support `Explain` syntax for this? can i try it?

We'd appreciate any contribution, please reach us if you need any help! 

As to implementing `EXPLAIN` statement in MySQL protocol, you need to first implement SQL parser for `EXPLAIN` keyword, and convert the query following `EXPLAIN` to plans in datafusion, and serialize the plan to string and then return to client.

**Comment by v0y4g3r** [comment]
Anyway if MySQL protocol handler receives any statement that is currently not supported, it should return an `UnsupportedError` instead of just panicking. We will fix this.

**Comment by francis-du** [comment]
> > How to support `Explain` syntax for this? can i try it?
> 
> We'd appreciate any contribution, please reach us if you need any help!
> 
> As to implementing `EXPLAIN` statement in MySQL protocol, you need to first implement [SQL parser for `EXPLAIN` keyword](https://github.com/GrepTimeTeam/greptimedb/blob/29ad16d048d83c8451982cf67a48e73bdce446ce/src/sql/src/parser.rs#L220-L222), and convert the query following `EXPLAIN` to plans in datafusion, and serialize the plan to string and then return to client.

Thanks you, let me try. Can you assign this issue to me?

**Comment by v0y4g3r** [comment]
> > > How to support `Explain` syntax for this? can i try it?
> > 
> > 
> > We'd appreciate any contribution, please reach us if you need any help!
> > As to implementing `EXPLAIN` statement in MySQL protocol, you need to first implement [SQL parser for `EXPLAIN` keyword](https://github.com/GrepTimeTeam/greptimedb/blob/29ad16d048d83c8451982cf67a48e73bdce446ce/src/sql/src/parser.rs#L220-L222), and convert the query following `EXPLAIN` to plans in datafusion, and serialize the plan to string and then return to client.
> 
> Thanks you, let me try. Can you assign this issue to me?

If you need any help, please reach us thru our [slack channel(https://join.slack.com/t/greptimedbcommunity/shared_invite/zt-1jop1xdl3-KGqEPhEv8QjuQNybO2p6ng)

**Comment by francis-du** [comment]
Thanks for your information @v0y4g3r
