### ISSUE TITLE
Implement DESCRIBE TABLE clause

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#534]
### What problem does the new feature solve?

Describe the structure of a table, as well as the default values.

### What does the feature do?

Support syntax like 

```sql
DESC[RIBE] TABLE <name>;
```

It returns a table like this:
```text
Name               Null             Type                Default        Semantic Type

ID                    Not Null        INT                    0           PRIMARY KEY
Timestamp                            TIMESTAMP                          TIME INDEX
```

### Implementation challenges

- Add these syntaxes to parser
- Retrieve `TableInfo` from corresponding table
- Extract infos from `TableInfo` and output them.

**Comment by morigs** [comment]
Hi, I was experimenting while exploring the source code and now I have almost complete implementation.
This missing piece of puzzle is how to get semantic type from `ColumnSchema`. If I'm not mistaken, it should be `TIMESTAMP` when `is_time_index` is true. But what about `TAG`? Should I treat fields from `TableMeta.primary_key_indices` as `TAG`s and the rest as `FIELD`s?

**Comment by waynexia** [comment]
>Should I treat fields from TableMeta.primary_key_indices as TAGs and the rest as FIELDs?

That's right! Sorry that the document isn't clear. Primary key and tag are the same thing here.

And since the `CREATE TABLE` clause uses `PRIMARY KEY`, I think I'd better to change the PR description to use this word as well. So the three possible value of "semantic type" here are `TIME INDEX`(not timestamp), `PRIMARY KEY` and `VALUE` (not field).

**Comment by morigs** [comment]
👍🏼 Thx, I'll try to implement this soon. Could you pls assign this to me?
