### ISSUE TITLE
Support SHOW CREATE TABLE

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#535]
### What problem does the new feature solve?

Support the `SHOW CREATE TABLE tbl_name` statement, so we could inspect the `CREATE TABLE` statement for a table via the MySQL client.

### What does the feature do?

e.g.
```sql
CREATE TABLE monitor (
  host STRING,
  ts TIMESTAMP,
  cpu DOUBLE DEFAULT 0,
  memory DOUBLE,
  TIME INDEX (ts),
  PRIMARY KEY(host)) ENGINE=mito WITH(regions=1);

SHOW CREATE TABLE monitor;

+-------+-----------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                      |
+-------+-----------------------------------------------------------------------------------------------------------------------------------+
| monitor   | CREATE TABLE monitor (
  host STRING,
  ts TIMESTAMP,
  cpu DOUBLE DEFAULT 0,
  memory DOUBLE,
  TIME INDEX (ts),
  PRIMARY KEY(host)) ENGINE=mito WITH(regions=1) |
+-------+-----------------------------------------------------------------------------------------------------------------------------------+
```

The parser part of `SHOW CREATE TABLE` is implemented, but we still need to execute the statement in the SQL handler
https://github.com/GreptimeTeam/greptimedb/blob/57979c9d3dba13beef5d63b4dc73fa1b3281e7e6/src/datanode/src/instance/sql.rs#L118-L120

Reference:
- [SHOW CREATE TABLE Statement](https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html)

### Implementation challenges

Now the `DistTable` doesn't implement the `table_info()` method, we may need to wait for the `DistTable` ready, see #536.

**Comment by azhsmesos** [comment]
please assigned it to me.

**Comment by azhsmesos** [comment]
Sorry，I accidentally turned this pr off, I will send a new pr request.

**Comment by MichaelScofield** [comment]
ping @azhsmesos , any updates?

**Comment by azhsmesos** [comment]
> ping @azhsmesos , any updates?

Sorry, this pr did not push successfully, I have given up before the year.
