### ISSUE TITLE
Move common dependencies to workspace dep

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#538]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

For some common dependencies, we should specify it for every sub-crate. And need to change all the occurrences when trying to bump version.

Rust/Cargo now support workspace dependencies, with it we only need to write the version number once.

**Comment by waynexia** [comment]
The current toolchain hasn't stablize this feature:
```
Caused by:
  feature `workspace-inheritance` is required

  The package requires the Cargo feature called `workspace-inheritance`, but that feature is not stabilized in this version of Cargo (1.64.0-nightly (b1dd22e66 2022-07-09)).
  Consider adding `cargo-features = ["workspace-inheritance"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance for more information about the status of this feature.
```

I'm afraid we should wait for https://github.com/GreptimeTeam/greptimedb/discussions/388

**Comment by killme2008** [comment]
@waynexia Looks like we have already done this refactor?

**Comment by waynexia** [comment]
Yes, it's done in #782.
