### ISSUE TITLE
Change the datanode MySQL default port

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#548]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

Right now the datanode listens on `127.0.0.1:3306` for MySQL connections, it may conflict with the user's MySQL server, so we should change this default address.

**Comment by azhsmesos** [comment]
Please assigned it to me

**Comment by waynexia** [comment]
Closed by https://github.com/GreptimeTeam/greptimedb/pull/568
