### ISSUE TITLE
Adds --version command line option

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#550]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Displaying the binary version by passing `--version` to the `greptime` command, which is more convenient than matching the checksum to find out the release version.
```
./greptime --version
```

**Comment by waynexia** [comment]
The build branch and commit are also helpful

**Comment by lizhemingi** [comment]
![image](https://user-images.githubusercontent.com/9639449/203537407-4e47d6fc-90cd-495a-834e-ff1655dc32f8.png)

Does this output meet the requirement?

**Comment by MichaelScofield** [comment]
LGTM, please submit a PR, thx!
