### ISSUE TITLE
Github uses the old PR title as commit message

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#567]
### What problem does the new feature solve?

We only have a PR title checker, but it doesn't check the commit messages. At least these PRs introduced invalid commit messages, but I'm not sure why GitHub doesn't use the final PR title as its commit message.
- #552
- #517

A commit message checker in CI may help discover this.

### What does the feature do?

Adds a commit message checker, there are some existing actions in marketplace
- [GsActions/commit-message-checker](https://github.com/marketplace/actions/gs-commit-message-checker)
- [Conventional Commit Checker](https://github.com/marketplace/actions/conventional-commit-checker)
- [webiny/action-conventional-commits](https://github.com/webiny/action-conventional-commits)

**Comment by evenyag** [comment]
We may still need to do a final check when merging a PR.

**Comment by evenyag** [comment]
This option in the `Pull Requests` setting may solve the problem

<img width="757" alt="image" src="https://user-images.githubusercontent.com/7058520/202610140-2246ec7b-785a-4658-b14a-3fecfc904106.png">

**Comment by zyy17** [comment]
@evenyag it looks can solve the problem  👍

**Comment by waynexia** [comment]
I've tried in https://github.com/GreptimeTeam/greptimedb/pull/565 , it looks good.

The original title is `ci: add nightly build`, it's the same with the only commit. Then I change it to `ci: add nightly build job` and click merge. The default merge message pops up is `ci: add nightly build job` not the commit message. 👍
