### ISSUE TITLE
CSV output format for http sql api

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#577]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Add CSV, and framework to support other formats, to our http `/sql` api. This allows user to export data from our dashboard.

### Implementation challenges

For initial implementation, we just serialize `Output` into csv format. But for future performance consideration, streaming is required for this interface, as well as existed Json format. There has been such kind of attempt on axum framework: https://github.com/abdolence/axum-streams-rs/

**Comment by zeroslope** [comment]
I want to try. Please assign it to me.

**Comment by zeroslope** [comment]
I have some initial thoughts.
1. distinguish the returned format by the request header being `Accept: application/json` or `Accept: application/csv`.
2. only HttpRecordsOutput (SELECT statement) supports CSV format, other statements will have no effect when `Accept: application/csv` is set.
3. when any error is encountered, the returned result will be in JSON format.

If `chunked=true` is set in the request, then streaming will be used

**Comment by MichaelScofield** [comment]
@zeroslope I'm ok with most of your thoughts. ping @sunng87 if with any further consideration

**Comment by sunng87** [comment]
Thank you!  Sounds mostly good to me. Just my two cents:

- Can we make streaming default? Because it's the database who wants to utilize streaming for better performance. Most users won't set that option until issue encountered. 
- Besides using `Accept` header for content negotiation, I would recommend a dedicated query param for format. For cases like clickable `/sql` link, there is no chance to specify a http header. Using query param is more universal imo. We can support both strategies by defining a priority of them.  [More on multi-strategy content negotiation](https://www.baeldung.com/spring-mvc-content-negotiation-json-xml)

**Comment by zeroslope** [comment]
@sunng87 Thank you for your reply. Having combined your suggestions, the resulting solution is as follows.

For the format of the return value.
1. first use query param "format=", optional values are json, csv
2. second use Accept Header, optional values are Accept: application/json or Accept: application/csv
If neither is available, the default value (csv) is used.

For stream, if  query param "chunked=false" is passed, then streaming is not applicable, otherwise streaming is enabled by default.

**Comment by sunng87** [comment]
Awesome. Let's get started with this approach.

**Comment by zeroslope** [comment]
@sunng87 After attempts, I don't think this issue is suitable as the first issue. Serializing the result to csv is not difficult in itself. But the original design is all based on json, and my changes would result in very many changes. 
I am very sorry that I may not be able to solve this issue.

**Comment by sunng87** [comment]
Never mind. Thank you again for this. Please keep your branch and we could move on from that.

**Comment by tisonkun** [comment]
For the end-user manner, currently, greptimedb does:

```
$ curl localhost:4000/v1/sql -d "sql=SELECT 1"                                             
{"code":0,"output":[{"records":{"schema":{"column_schemas":[{"name":"Int64(1)","data_type":"Int64"}]},"rows":[[1]]}}],"execution_time_ms":1}
```

whose output is more than the result but also metadata.

Compared with ClickHouse:

```
$ curl -i "https://play.clickhouse.com/?user=explorer" --data-binary "SELECT 'Play ClickHouse', 42 FORMAT CSV"


HTTP/1.1 200 OK
Date: Fri, 10 Nov 2023 08:15:05 GMT
Connection: Keep-Alive
Content-Type: text/csv; charset=UTF-8; header=absent
X-ClickHouse-Server-Display-Name: play-us
Transfer-Encoding: chunked
X-ClickHouse-Query-Id: f5e8c84a-e694-4584-8559-da0bcb993760
X-ClickHouse-Format: CSV
X-ClickHouse-Timezone: Etc/UTC
Keep-Alive: timeout=3
X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"1","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"683481"}

"Play ClickHouse",42

$ curl -i "https://play.clickhouse.com/?user=explorer" --data-binary "SELECT 'Play ClickHouse', 42"


HTTP/1.1 200 OK
Date: Fri, 10 Nov 2023 08:15:22 GMT
Connection: Keep-Alive
Content-Type: text/tab-separated-values; charset=UTF-8
X-ClickHouse-Server-Display-Name: play-us
Transfer-Encoding: chunked
X-ClickHouse-Query-Id: f03803f3-5ec0-4934-a0e4-2a0bd65ebb1b
X-ClickHouse-Format: TabSeparated
X-ClickHouse-Timezone: Etc/UTC
Keep-Alive: timeout=3
X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"1","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"459860"}

Play ClickHouse	42
```

Metadata are included in headers, and the payload is barely result.


Thus, we have two directions to choose:

1. Keep the outer JSON structure, but return the CSV formatted result in "output" JSON field.
2. Follow what ClickHouse does.

@sunng87 @MichaelScofield @zeroslope which one should be the one GreptimeDB chose?

**Comment by MichaelScofield** [comment]
@tisonkun I think it's better to put metadata in http headers. However, making this the default behavior will introduce breaking change. On the other hand, we don't support `select ... format csv" grammar. So I suggest make "format=csv" an http parameter for the sql api. If format is csv, put data in http body, metadata in http header. If format is none, goes the old way. @sunng87 WDYT?
