### ISSUE TITLE
Consider remove build script and generate files using unit tests. It is unnecessary for users to have ` protoc`

### ISSUE THREAD

**Issue by CherishCai** [GreptimeTeam/greptimedb#585]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

- [api] remove build script and generate files using unit tests. reference https://github.com/open-telemetry/opentelemetry-rust/pull/881

### Implementation challenges

No major difficulties

**Comment by evenyag** [comment]
Looks like we need to put the generated files in the repo if we remove the build script?

**Comment by CherishCai** [comment]
> Looks like we need to put the generated files in the repo if we remove the build script?

Yeah. Then the user does not need to have a `protoc` environment.

**Comment by evenyag** [comment]
> Yeah. Then the user does not need to have a `protoc` environment.

Our proto is still unstable and may change rapidly at this period. Putting generated files in the repo may result in a large diff in PR. It might be better to consider this when we stabilize our protocol.
