### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jonyangx** [GreptimeTeam/greptimedb#594]
### What type of bug is this?

Configuration

### What subsystems are affected?

Standalone mode

### What happened?

greptimedb git:(develop) sudo cargo build
   Compiling arrow2 v0.10.1
   Compiling rustpython-vm v0.1.2 (https://github.com/RustPython/RustPython?rev=02a1d1d#02a1d1d7)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "simd", feature(portable_simd))]
  |                                       ^^^^^^^^^^^^^

error[E0599]: no method named `lanes_eq` found for struct `std::simd::Simd` in the current scope
  --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/types/simd/packed.rs:77:21
   |
77 |     (idx & vecmask).lanes_eq(idx)
   |                     ^^^^^^^^ help: there is an associated function with a similar name: `lanes`

error[E0599]: no method named `lanes_eq` found for struct `std::simd::Simd` in the current scope
  --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/types/simd/packed.rs:87:21
   |
87 |     (idx & vecmask).lanes_eq(idx)
   |                     ^^^^^^^^ help: there is an associated function with a similar name: `lanes`

error[E0599]: no method named `lanes_eq` found for struct `std::simd::Simd` in the current scope
   --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/types/simd/packed.rs:112:29
    |
112 |     (idx & left & vecmask1).lanes_eq(idx) | (idx & right & vecmask2).lanes_eq(idx)
    |                             ^^^^^^^^ help: there is an associated function with a similar name: `lanes`

error[E0599]: no method named `lanes_eq` found for struct `std::simd::Simd` in the current scope
   --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/types/simd/packed.rs:112:70
    |
112 |     (idx & left & vecmask1).lanes_eq(idx) | (idx & right & vecmask2).lanes_eq(idx)
    |                                                                      ^^^^^^^^ help: there is an associated function with a similar name: `lanes`

error[E0599]: no method named `lanes_eq` found for struct `std::simd::Simd` in the current scope
   --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/types/simd/packed.rs:169:50
    |
169 |         result |= (idxs[i] & u8x64::splat(a[i])).lanes_eq(idx)
    |                                                  ^^^^^^^^ help: there is an associated function with a similar name: `lanes`

^C  Building [======================>  ] 661/694: arrow2, rustpython-vm

### What operating system did you use?

Mac OS X 10.5

### How can we reproduce the bug?

```bash
cargo build
```

**Comment by jonyangx** [comment]
➜  greptimedb git:(develop) sudo rustup override add nightly-2022-07-14
info: using existing install for 'nightly-2022-07-14-x86_64-apple-darwin'
info: override toolchain for '/Users/apple/opensource/greptimedb' set to 'nightly-2022-07-14-x86_64-apple-darwin'

  nightly-2022-07-14-x86_64-apple-darwin unchanged - rustc 1.64.0-nightly (87588a2af 2022-07-13)

➜  greptimedb git:(develop) sudo cargo build
   Compiling arrow2 v0.10.1
   Compiling rustpython-vm v0.1.2 (https://github.com/RustPython/RustPython?rev=02a1d1d#02a1d1d7)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/apple/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arrow2-0.10.1/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "simd", feature(portable_simd))]
  |                                       ^^^^^^^^^^^^^

^C  Building [======================>  ] 661/694: arrow2, rustpython-vm
➜  greptimedb git:(develop)
➜  greptimedb git:(develop)

**Comment by waynexia** [comment]
#554 turns out that homebrew might not be the reason.... Not sure what's the cause

**Comment by jonyangx** [comment]
I try command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
workaroud it.
