### ISSUE TITLE
Tracking Issue for Substrait support

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#597]
### What problem does the new feature solve?

Support conversion between DataFusion's logical plan and Substrait's representation. This is a necessary feature for distributed execution.

### What does the feature do?

- [x] Primitive datatypes (part of `ConcreteDataType`) #351
- [x] Schema #351
- Basic Expression
  - [x] Scalar Functions #678
  - [ ] Scalar UDF
  - [x] Selection #678
  - [ ] Literal
  - [ ] Window Functions
  - [ ] Window UDF
  - [ ] Aggregate UDF
  - [ ] Cast
  - [ ] Subquery
  - [ ] ...
- [ ] Basic Logical Plan
- [ ] *extensions*

**Comment by killme2008** [comment]
What's the status of this tracking issue right now? Can we close it or keep it? @waynexia

**Comment by waynexia** [comment]
This could be tracked in upstream implementation. Closing it
