### ISSUE TITLE
Add server-side authentication mechanism

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#603]
### What problem does the new feature solve?

GreptimeDB is now accepting all connections / requests without basic authentication ability. This feature adds basic capability to check incoming request and authenticate. 

### What does the feature do?

This feature adds server-side authentication mechanism for the incoming connection from client in various protocol handlers like MySQL, Postgres, etc. It checks whether the connection from client is authenticated and is able to move forward.

note: the implementation of this feature may need to work with #600

**Comment by killme2008** [comment]
Note:  we also have to impl system tables such as `users` and `roles` etc. to store authentication information.

**Comment by sunng87** [comment]
@killme2008 we need to decouple authentication and privilege system, in authentication we need

- authentication on mysql/pg username/password
- compile-time configurable/plug-able authentication source support
- system tables as one of these sources

see https://docs.snowflake.com/en/user-guide/authentication.html

**Comment by killme2008** [comment]
@sunng87 Yep, of course. There must be an abstract layer for these different sources.

**Comment by killme2008** [comment]
We need to add some docs to describe this feature @shuiyisong
