### ISSUE TITLE
supports write in MQTT protocol

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#605]
### What problem does the new feature solve?

MQTT protocol is very important in IOT industry, we should support it.

ref:
- https://mqtt.org/

### What does the feature do?

Insert metrics into our db in MQTT protocol.

### Implementation challenges

- One implementation option:

Use EMQX's "Data Bridges" feature to write data into GreptimeDB. 

In general, we can simply create a webhook of it (see its ["Quick Start"](https://www.emqx.io/docs/en/v5.0/data-integration/data-bridges.html#quick-start-with-data-bridge) ), then EMQX will call the specified http endpoint. The http endpoint is exposed by GreptimeDB, and through which we ingest the data feed by EMQX.

EMQX uses ["Rules"](https://www.emqx.io/docs/en/v5.0/data-integration/rules.html#composition-of-rules) to extract fields from input data and assemble output data, we might need to design a request protocol, specify the required params. 

Also, aside from a table for storing mqtt data, GreptimeDB might need a mqtt "status" table, to store the various ["events"](https://www.emqx.io/docs/en/v5.0/data-integration/rule-sql-events-and-fields.html#mqtt-events) emitted by EMQX.

- Another implementation option:

TBD

**Comment by killme2008** [comment]
I don't think we can impl the whole MQTT protocol in GreptimeDB, it's really complicated.

I think we can impl an EMQX plugin to write data from EMQ into greptimedb.

https://www.emqx.io/docs/en/v1.0/plugins.html

**Comment by sunng87** [comment]
Typically we don't expose MQTT directly to IoT devices because that layer has its own authentication, data validation and device management business logic. 

In most case we need to bridge our customer's internal kafka/pulsa/pravega queues to our db. These bridges can be implemented in our solution products.

**Comment by waynexia** [comment]
Is this supported? @killme2008

**Comment by killme2008** [comment]
I am developing a data bridge for EMQX https://github.com/killme2008/emqx/pull/3 and i'll create a PR this week.

This issue can be closed, we don't support the MQTT protocol directly in GreptimeDB, but provide this data bridge.

**Comment by codering** [comment]
only used in enterprise version？
