### ISSUE TITLE
Rust SDK

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#606]
### What problem does the new feature solve?

Our db's grpc service lacks of a Rust SDK.

### What does the feature do?

A Rust SDK for our grpc service.

**Comment by SSebo** [comment]
Is it ok to follow the go client API interface design?

**Comment by MichaelScofield** [comment]
It's ok. However, we already have the rust client in GreptimeDB's codes, I'd prefer extract it to a standalone repo, and build upon it thereafter. GreptimeDB should be the first user of it.

**Comment by killme2008** [comment]
We have an independent project to track this feature

https://github.com/GreptimeTeam/greptimedb-client-rust
