### ISSUE TITLE
Speed up the building process

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/greptimedb#611]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Since the rust code is growing fastly, the building process will get slower. We can use the following methods to speed up:

- Use EC2(for example, use [ec2-github-runner](https://github.com/machulav/ec2-github-runner)) to resource scale-up;
- Refine the rust cache mechanism;

**Comment by morigs** [comment]
Check out [fleet](https://fleet.rs/) too
