### ISSUE TITLE
File object store should write to a temp file and rename it later

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#613]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

File object store should write to a temp file and rename it later, ensuring the file object is complete.

### Implementation challenges
We need to implement a new Backend or an adapter for [`fs::Backend`](https://github.com/datafuselabs/opendal/blob/fc675bedb8a2608438c1585c22d494a96c4e5649/src/services/fs/backend.rs#L265)

**Comment by killme2008** [comment]
Already implemented in https://github.com/datafuselabs/opendal/pull/991

Waiting for opendal to release a new version.
