### ISSUE TITLE
Failed to execute insert: table not found

### ISSUE THREAD

**Issue by francis-du** [GreptimeTeam/greptimedb#615]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

![image](https://user-images.githubusercontent.com/25944814/203073851-5a54493c-b624-4651-a833-94696a2f8d08.png)

### What operating system did you use?

Mac M2

#### DataNode log

```log
2022-11-21T13:58:49.654854Z ERROR datanode::instance::grpc: Failed to handle insert, catalog name: greptime, schema name: public, table name: dist_table err.msg=Table not found: dist_table err.code=TableNotFound
```

### How can we reproduce the bug?

Start a cluster according to the [doc](https://docs.greptime.com/getting-started/distributed)

It works in Standalone

**Comment by killme2008** [comment]
I guess that you have restarted a node or reconstructed the cluster. 
There is an issue in the [doc](https://docs.greptime.com/getting-started/distributed): it doesn't use different data/wal paths for different nodes, so if you restart one of them, the data is corrupted. 

@MichaelScofield already provide `--wal-dir` and ` --data-dir` in #576 , the doc  is updated too in https://github.com/GreptimeTeam/docs/pull/80, but not approved yet.

**Comment by MichaelScofield** [comment]
ping @francis-du , the "distributed" doc is updated, as well as the codes. Can you try it again?
