### ISSUE TITLE
Imporve GreptimeDB startup performance

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#628]
### What type of enhancement is this?

Performance

### What does the enhancement do?

When hundreds of tables are created in GreptimeDB, it may take a long time to open these tables during database instance startup. 

One major reason is that Table engine must replay the whole WAL to load the `SystemCatalogTable` which holds all table names. While opening each table, table engine also replays the whole WAL to construct the state of it, including table DDLs, memtable data, etc. That addes up to replaying whole WAL for 1+N times.

To speed up startup performance, We can improve this number to 2 by replaying WAL to load `SystemCatalogTable`, after that we should replay the WAL once and dispatch these WAL entries to each tables. That would be enough.

**Comment by killme2008** [comment]
Related to https://github.com/GreptimeTeam/greptimedb/issues/353

**Comment by v0y4g3r** [comment]
As we've already introduced raft-engine based wal, we may have a significant improvement in startup speed, because replaying entries in some namespace no longer needs to read the whole WAL. 

I did a simple validation by creating 1000 tables:
```bash
while [  $COUNTER -lt 1000 ]; do
    mysql -h 127.0.0.1 -P 4002 -e "CREATE TABLE monitor${COUNTER} (host STRING,ts TIMESTAMP,cpu DOUBLE DEFAULT 0,memory DOUBLE,TIME INDEX (ts),PRIMARY KEY(host)) ENGINE=mito WITH(regions=1);"
    let COUNTER=COUNTER+1
done
```

And then restart datanode:
```
2023-01-06T06:26:34.657599Z  INFO cmd::standalone: Standalone frontend options: FrontendOptions ....
....
2023-01-06T06:26:35.892063Z  INFO catalog::local::manager: All system catalog entries processed, max table id: 2023
```

It takes about 1235ms to recovering all 1000 tables. The performance looks fairly acceptable.
