### ISSUE TITLE
Use released axum 0.6

### ISSUE THREAD

**Issue by dongxuwang** [GreptimeTeam/greptimedb#642]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Use axum 0.6 instead of rc since it release recently.

https://tokio.rs/blog/2022-11-25-announcing-axum-0-6-0

### Implementation challenges

There is a recommended type safe way to cope with state

**Comment by dongxuwang** [comment]
https://github.com/GreptimeTeam/greptimedb/blob/develop/src/servers/src/http.rs#L351-L357

**Comment by sunng87** [comment]
We need [aide](https://github.com/tamasfe/aide) to update to axum 0.6 as well.

**Comment by sunng87** [comment]
aide 0.8.1 is already there.
