### ISSUE TITLE
Support promethus exporter?

### ISSUE THREAD

**Issue by qqeasonchen** [GreptimeTeam/greptimedb#644]
### What problem does the new feature solve?

Store metrics data collected by Promethus exporter

### What does the feature do?

Store metrics data collected by Promethus exporter

**Comment by killme2008** [comment]
GreptimeDB already supports Prometheus remote read and write, please refer to https://docs.greptime.com/user-guide/supported-protocols/prometheus. We also have the plan to enable PromQL natively #596 .

But we don't plan to support metrics collector in greptimedb directly right now.

**Comment by qqeasonchen** [comment]
I see, thank you dennis.
