### ISSUE TITLE
Remove version field from the `Schema` struct

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#666]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

Discussed in https://github.com/GreptimeTeam/greptimedb/discussions/349

<div type='discussions-op-text'>

<sup>Originally posted by **evenyag** October 25, 2022</sup>
Now we have RegionSchema and TableInfo that could hold the version field, so we might be able to remove the version field from the Schema struct. Since some schemas might not have version info.</div>

### Implementation challenges

We need to refactor all tests that call the `SchemaBuilder::version` API.

**Comment by etolbakov** [comment]
Hi @evenyag @killme2008 
Is this issue still relevant and worth taking a look?

**Comment by evenyag** [comment]
@etolbakov I'm afraid that this is too complicated as some tests rely on that field. I have removed the `good first issue` label.

**Comment by etolbakov** [comment]
That makes sense, thanks for the clarifications!

**Comment by killme2008** [comment]
It looks  unnecessary.
