### ISSUE TITLE
Simplify the grammar defines TIME INDEX column

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#667]
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

Give an example `CREATE TABLE` SQL from the [document](https://docs.greptime.com/getting-started/create-a-time-series-table)
```sql
CREATE TABLE system_metrics (
    host STRING,
    idc STRING,
    ts TIMESTAMP NOT NULL,
    PRIMARY KEY(host, idc),
    TIME INDEX(ts)
);
```
There are two special column specifications `PRIMARY KEY` and `TIME INDEX`. The first one is used to define primary keys (or tags in some systems), and the second is to define which column is the special timestamp column.

For TIMESTAMP column, a simplification is to change the grammar to
```sql
    ts TIMESTAMP TIME INDEX,
```
By doing so, it
- need not to write `NOT NULL`, this is implied by `TIME INDEX` keywords
- need not to specify `TIME INDEX` in another line

**Comment by killme2008** [comment]
I think we can support both of this two grammar.

**Comment by SSebo** [comment]
@waynexia  Could you give me some advice to start? I'm interested in this issue.

**Comment by waynexia** [comment]
Of course! As this is mainly focused on grammar improvement, the parser (`ParserContext`) is a good point to get involved in. You can check `ParserContext::parse_columns` to see how a column is processed in the `CREATE TABLE` clause. Hope this can help, and please let us know if anything is unclear to you :heart:

**Comment by SSebo** [comment]
@waynexia Thanks a lot！you can assign this issue to me.
