### ISSUE TITLE
Be able to invoke Python UDF directly in SQL query

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#675]
### What problem does the new feature solve?

GreptimeDB supports users to write post-process logic in Python ([official document](https://docs.greptime.com/getting-started/process-data-with-python)) like 
```python
@coprocessor(args=["host", "idc", "cpu_util", "memory_util", "disk_util"],
             returns = ["host", "idc", "status"],
             sql = "SELECT * FROM system_metrics")
def calc_status(hosts, idcs, cpus, memories, disks):
    statuses = []
    for host, cpu, memory, disk in zip(hosts, cpus, memories, disks):
        if cpu > 80 or memory > 80 or disk > 80:
            statuses.append("red")
            continue
        status = cpu * 0.4 + memory * 0.4 + disk * 0.2

    return hosts, idcs, statuses
```

In this example script it runs on the result of SQL `SELECT * FROM system_metrics`.

And we can make it more amazing if the customized process logic can be integrated directly into the SQL itself, like 
```sql
SELECT
  host,
  idc,
  calc_status(cpu_util, memory_util, disk_util)
FROM
  system_metrics;
```

### What does the feature do?

Give the ability to embed pre-defined UDF scripts into SQL query

**Comment by sunng87** [comment]
We can make udf and script different objects in database. 

Stored procedure in snowflake: https://docs.snowflake.com/en/sql-reference/stored-procedures.html
UDFs in snowflake: https://docs.snowflake.com/en/sql-reference/user-defined-functions.html
