### ISSUE TITLE
Support built-in account management

### ISSUE THREAD

**Issue by shuiyisong** [GreptimeTeam/greptimedb#679]
### What problem does the new feature solve?

Currently GreptimeDB doesn't support native account management like `CREATE USER` statement and built-in `user` table, thus lack of a way to manage user infos that are allowed to connect to the database. 

### What does the feature do?

- [ ] support user-related sql `CREATE USER / ALTER USER / DROP USER / RENAME USER`
- [ ] create built-in `user` table to store the information with distribution support

**Comment by tisonkun** [comment]
@shuiyisong shall we still want to do it now?

IIRC we have a new ABAC/RBAC design.

**Comment by shuiyisong** [comment]
@tisonkun We can close it for now. Our RBAC proposal is still in very early stage. I'll reopen it if we have a solid plan to work on.
