### ISSUE TITLE
SQL support: create table if not exists

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/greptimedb#711]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Allow `IF NOT EXISTS` clause in table creation.

**Comment by killme2008** [comment]
`CreateTableRequest` already has a field `create_if_not_exists: boolean` for it. Support this option in the parser have to be done.

**Comment by e1ijah1** [comment]
It looks like this feature has already been implemented.

https://github.com/GreptimeTeam/greptimedb/blob/90c832b33ddfda7a2fafaa80bdb33d9a3dcb4687/src/mito/src/engine.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L290-L299

**Comment by waynexia** [comment]
> It looks like this feature has already been implemented.
> 
> https://github.com/GreptimeTeam/greptimedb/blob/90c832b33ddfda7a2fafaa80bdb33d9a3dcb4687/src/mito/src/engine.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L290-L299

It's implemented in the protocol and data level, and looks like the parser also handles `IF NOT EXIST` keywords. But I get this when I run the query against develop branch:
```
ERROR 1815 (HY000): Failed to execute query: CREATE TABLE if not exist system_metrics (
    host STRING,
    idc STRING,
    ts TIMESTAMP NOT NULL,
    PRIMARY KEY(host, idc),
    TIME INDEX(ts)
), source: Failed to parse SQL, source: SQL statement is not supported: CREATE TABLE if not exist system_metrics (
    host STRING,
    idc STRING,
    ts TIMESTAMP NOT NULL,
    PRIMARY KEY(host, idc),
    TIME INDEX(ts)
), keyword: not
```

I'd like to treat this as "bug" rather than "enhancement" -- the parser cannot handle `IF NOT EXIST` correctly.

**Comment by e1ijah1** [comment]
In MySQL syntax, the correct keyword is `IF NOT EXISTS` so the parser is also correct.(https://dev.mysql.com/doc/refman/8.0/en/create-table.html)

https://github.com/GreptimeTeam/greptimedb/blob/833216d3173073d3b90199a1decaadfdde320aa5/src/sql/src/parsers/create_parser.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L73-L77

I ran this query and got the correct result.

```
mysql> show tables;                                                                                                                                                                             
+----------------+
| Tables         |
+----------------+
| numbers        |
| system_metrics |
| scripts        |
| test           |
+----------------+
4 rows in set (2 min 3.77 sec)

mysql> create table if not exists test_table (
    ->     host STRING,
    ->     idc STRING,
    ->     cpu_util DOUBLE,
    ->     memory_util DOUBLE,
    ->     disk_util DOUBLE,
    ->     ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ->     PRIMARY KEY(host, idc),
    ->     TIME INDEX(ts)
    -> );
Query OK, 1 row affected (30.50 sec)

```

**Comment by waynexia** [comment]
My bad...🫣 Thanks for pointing it out.

So we do have the support for this feature. I am closing this issue
