### ISSUE TITLE
Duplicated definition of Values

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#731]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### What happened?

Seems there're two identical definitions for `Values`

https://github.com/GreptimeTeam/greptimedb/blob/74ea529d1a409551394ad457ce6d571e238c774a/src/storage/proto/write_batch.proto#L67-L85

https://github.com/GreptimeTeam/greptimedb/blob/c1b8981f61873a4b4466184e59901566177ce7e9/src/api/greptime/v1/column.proto#L15-L36

Not sure if it's intentional, but better refactor these into one proto.

### What operating system did you use?

NA

### Relevant log output and stack trace

```bash
NA
```

### How can we reproduce the bug?

```bash
NA
```

**Comment by killme2008** [comment]
Already resolved. Only keeps `column.proto`.
