### ISSUE TITLE
Supports INSERT INTO SELECT statement

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#760]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Using it to copy data from one table and inserts it into another table, such as:

```
INSERT INTO table2 SELECT * FROM table1 WHERE condition;
```

**Comment by francis-du** [comment]
Hi,Has anyone claimed this issue? If not, can you assign it to me? I want to try it.

**Comment by waynexia** [comment]
Glad you're interested. This is a relatively complex feature. Feel free to reach out to us and share your question if any 😄

**Comment by francis-du** [comment]
> Glad you're interested. This is a relatively complex feature. Feel free to reach out to us and share your question if any 😄

Hi, Ruihang. About SQL Parser I think I don't need any help. I would like to ask about `Insert data` how do I start?

**Comment by waynexia** [comment]
My general thought is to make `INSERT` able to invoke the query engine if there is no plain data, but another query like `SELECT` in this issue. And insert data from the evaluated query like normal `INSERT`. I think `Instance` is a good place to make this deal, as it keeps both `QueryEngine` and `Table` (via `CatalogManager`).

**Comment by francis-du** [comment]
> My general thought is to make `INSERT` able to invoke the query engine if there is no plain data, but another query like `SELECT` in this issue. And insert data from the evaluated query like normal `INSERT`. I think `Instance` is a good place to make this deal, as it keeps both `QueryEngine` and `Table` (via `CatalogManager`).

Thank you, Ruihang.

**Comment by killme2008** [comment]
@francis-du Hi, are u still working on this feature?  The #405 may depend on it.

**Comment by francis-du** [comment]
> @francis-du Hi, are u still working on this feature? The #405 may depend on it.

Yeah. I just finished my vacation, next I will speed up on this.

**Comment by evenyag** [comment]
Is it possible to divide this into some small tasks (or steps) and track them in a tracking issue? So more people could get involved in. @francis-du @killme2008

**Comment by killme2008** [comment]
> Is it possible to divide this into some small tasks (or steps) and track them in a tracking issue? So more people could get involved in. @francis-du @killme2008

Agree. We want to release this feature in 0.1-beta(maybe on 15th Feb), I think we can create an issue to track the tasks. @francis-du

**Comment by fengjiachun** [comment]
Hi, @francis-du , due to the length of time and we want to release this feature in 0.1-beta(maybe on 15th Feb), we have automatically unsign, so please continue to pick up [other tasks](https://github.com/GreptimeTeam/greptimedb/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) if needed.

**Comment by killme2008** [comment]
We have to implement it in distributed mode too. It's related to #1010 .
