### ISSUE TITLE
Physical planner does not support subquery expression

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#791]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

Looks like a datafusion feature missing: https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/planner.rs#L446

Create a table and insert some data:

```sql
CREATE TABLE integers(i INTEGER, j BIGINT TIME INDEX);
INSERT INTO integers VALUES (1, 1), (2, 2), (3, 3), (NULL, 4);
```

Run queries:

```sql
SELECT * FROM integers WHERE i IN ((SELECT i FROM integers)) ORDER BY I;

SELECT * FROM integers WHERE i NOT IN ((SELECT i FROM integers WHERE i=1)) ORDER BY I;

SELECT * FROM integers WHERE i IN ((SELECT i FROM integers)) AND i<3 ORDER BY I;

SELECT i1.i,i2.i FROM integers i1, integers i2 WHERE i IN ((SELECT i FROM integers)) AND i1.i=i2.i ORDER BY 1;
```
All these queries fail with the error:

```text
Failed to execute, error: Datanode { code: 3001, msg: "Failed to execute SQL, 
source: Fail to create physical plan: 
This feature is not implemented: Physical plan does not support logical expression (<subquery>)" }

```

### What operating system did you use?

Mac Osx

### How can we reproduce the bug?

```bash
Described above.
```

**Comment by waynexia** [comment]
It looks like you have duplicated brackets around subqueries. It should be `(<subquery>)` rather than `((<subquery>))`, isn't it?

I can get results with the following queries after removing a pair of brackets for each:
```sql
SELECT * FROM integers WHERE column1 IN (SELECT column1 FROM integers);

SELECT * FROM integers WHERE column1 NOT IN (SELECT column1 FROM integers WHERE column1=1);

SELECT * FROM integers WHERE column1 IN (SELECT column1 FROM integers) AND column1<3 ;

SELECT i1.column1,i2.column1 FROM integers i1, integers i2 WHERE column1 IN (SELECT column1 FROM integers) AND i1.column1=i2.column1 ;
```

**Comment by MichaelScofield** [comment]
wait for https://github.com/apache/arrow-datafusion/issues/5529

**Comment by evenyag** [comment]
Does PostgreSQL support this?

**Comment by MichaelScofield** [comment]
I've tested all 4 sqls in mysql, pg and duckdb. The last sql all failed with some error like "...ambiguous column i...". However, the other 3 are good.
