### ISSUE TITLE
duplicate error logs into a separate file

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#805]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Currently, the runtime log will be output to stdout and file: https://github.com/GreptimeTeam/greptimedb/blob/d0ef3aa9eb4fb5e77a8060dc7f6ca2b55f28a730/src/common/telemetry/src/logging.rs#L97-L101

Both consumers are holding all the logs with valid levels. E.g., if the level is set to `INFO`, then all the `ERROR`, `WARN` and `INFO` logs will present in stdout and log file. 

It would be useful if we could duplicate some important logs separately. Like only placing `ERROR` level in `error.log`, and `ERROR`, `WARN` and `INFO` in the normal log file like we have present. `tracing` provides such functionality [`with_filter`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/trait.Layer.html#method.with_filter) which allows setting per-layer filter. I tried it and successfully separated the `ERROR` log in the stdout (left), while still keeping the full content in the log file (right).

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/15380403/209936132-4f237d41-42cc-4550-8e0c-b59860813315.png">

**Comment by azhsmesos** [comment]
Today on slack, I received a New Year's gift from GreptimeDB community, which is very happy. Rust Hong persuaded me to withdraw an issue before, but I am still learning and do not give up. I want to try to complete this issue, I may encounter many problems, but I will not give up, please assign it to me, thanks!

**Comment by waynexia** [comment]
Hi @azhsmesos, just a friendly ping, do you have any progress or problems to share?

**Comment by azhsmesos** [comment]
> Hi @azhsmesos, just a friendly ping, do you have any progress or problems to share?

Sorry, I am still in the Spring Festival holiday, not yet developed

**Comment by waynexia** [comment]
Wish you a wonderful holiday 🎆  As it has been over a month since assign, we'd release this task and make it up for grabs. Feel free to retake it when you get back to work

**Comment by lizhemingi** [comment]
Let me take it.
