### ISSUE TITLE
Adjust `QueryEngine` trait to adapt upcoming multiple query languages

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#830]
### What type of enhancement is this?

API improvement

### What does the enhancement do?

Currently, the `QueryEngine` trait is defined as

```rust
pub trait QueryEngine: Send + Sync {
    fn sql_to_statement(&self, sql: &str) -> Result<Statement>;

    fn statement_to_plan(&self, stmt: Statement, query_ctx: QueryContextRef)
        -> Result<LogicalPlan>;

    fn sql_to_plan(&self, sql: &str, query_ctx: QueryContextRef) -> Result<LogicalPlan>;

    // omitted
}
``` 

It exposes the intermediate struct `Statement`, some of which are wrapped over `sqlparser`. That makes it becomes an `SQL`-specific query engine. To make it support other query languages (which may have different AST, like PromQL), I propose to do some adjustments to `QueryEngine`. The key point is to hide the step between query language (`String`) and plan (`LogicalPlan`). Like the following (just remove `sql_to_statement` and `statement_to_plan`, and rename `sql` to `query`):

```rust
pub trait QueryEngine: Send + Sync {
    fn sql_to_plan(&self, query: &str, query_ctx: QueryContextRef) -> Result<LogicalPlan>;

    // omitted as above
}
``` 

And to make it clear, we may also introduce an enum `QueryLanguage`:
```rust
enum QueryLanguage {
    SQL(String),
    PromQL(String),
    // others in the future
}
```

I've gone through all the references of `sql_to_statement`, and found some most of them are using `QueryEngine` like a parser. For example: https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/datanode/src/sql.rs#L257-L262 

I think this is the most troublesome part of this ticket. Since we're encapsulating all kinds of statements in `Statement`,  not only query. But only `Query` can be handled by `QueryEngine`. Looks like we need to dispatch on the statement kind before it reaches `QueryEngine`?

**Comment by killme2008** [comment]
> I've gone through all the references of sql_to_statement, and found some most of them are using QueryEngine like a parser.

Looks like only for testing, we can replace them with sqlparser.
