### ISSUE TITLE
WAL disk usage based flush strategy

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#842]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

If WAL takes up too much disk space, the recovery process may take a long time to finish. 

We can implement a `FlushStrategy` by checking the disk usage of WAL files, and flush the data in memtable to SST so that WAL files can be compacted.

**Comment by ShenJunkun** [comment]
I'm interested in this issue. Can you assign this task to me?

**Comment by v0y4g3r** [comment]
> I'm interested in this issue. Can you assign this task to me?

Some info that maybe useful for this:
- [Engine::get_used_size](https://docs.rs/raft-engine/0.3.0/raft_engine/struct.Engine.html#method.get_used_size) returns the disk usage of log files.
- [FlushStrategy](https://github.com/GreptimeTeam/greptimedb/blob/4015dd80752e1e6aaa3d7cacc3203cb67ed9be6d/src/storage/src/flush.rs#L36) determines whether to flush memtables to SST.
- And the check happens [everytime a new batch is written to memtable](https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/storage/src/region/writer.rs#L483).

Please let me know if you need any help :grinning:

**Comment by ShenJunkun** [comment]
Thx!

**Comment by evenyag** [comment]
> We can implement a `FlushStrategy` by checking the disk usage of WAL files, and flush the data in memtable to SST

We might need to find out the regions with largest disk consumption or referring the oldest WAL file and flush those regions. But we lack some mechanism to get a global view of the regions now.

**Comment by evenyag** [comment]
As mentioned in #1462, I'd like to close this issue. We could reopen #1462 if we need to implement a flush strategy based on disk usage.
