### ISSUE TITLE
A new table engine for metrics

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#844]
### What problem does the new feature solve?

Now our default table engine mito stores each table in a separate directory. This may not be suitable for monitoring as users might create 1k+ or even 100k+ of metrics which results in lots of files.

Managing so many tables is a big challenge:
- Each table has its own manifest files and SST files
- How to flush or compact so many tables
- How to improve the compression ratio? Since many metrics might share the same tags
- Speed up opening tables
- Minimize memory consumption of metadata

Some TSDBs like Prometheus and OpenTSDB store metrics under the same storage space or table. Prometheus uses a special `__name__` label to store the metric name, so we can consider all metrics to be stored in the same "table". It also supports filtering and aggregating series from multiple metrics: [PromQL Queries for Exploring Your Metrics](https://promlabs.com/blog/2020/12/17/promql-queries-for-exploring-your-metrics)

To better support metrics, we might need to develop a new table engine.

### What does the feature do?

A new engine for metrics, which supports 100k+ metrics
- It might allow metrics (logical table) to share the same underlying physical table
- It would be easier to support querying series across multiple metrics

### Implementation challenges

We might need to provide comparable performance for a single metric (table) to the mito engine. It is also necessary to see
- How many tables that users actually create?
- The row number/storage space of the metrics.
- Is mito enough to support storing metrics?
- Metrics might have different sample intervals and retention policies

**Comment by fengjiachun** [comment]
Can we close this issue now? @evenyag @waynexia

**Comment by evenyag** [comment]
Yes, we have a tracking issue https://github.com/GreptimeTeam/greptimedb/issues/2070 for it. We can use that issue.
