### ISSUE TITLE
Remove backtrace from sql::error::Error

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#855]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Most backtraces in `sql::error::Error` are unnecessary and might hurt performance since the parser would always return them while parsing an invalid SQL
https://github.com/GreptimeTeam/greptimedb/blob/72f05a3137bdedf0e7502a246a2533ded8d104cc/src/sql/src/error.rs#L54-L58

https://github.com/GreptimeTeam/greptimedb/blob/72f05a3137bdedf0e7502a246a2533ded8d104cc/src/sql/src/error.rs#L71-L83

https://github.com/GreptimeTeam/greptimedb/blob/72f05a3137bdedf0e7502a246a2533ded8d104cc/src/sql/src/error.rs#L98-L111Most

### Implementation challenges

We could remove the backtrace field from the variants listed above.

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by waynexia** [comment]
Sure! Glad you are interested ❤️

**Comment by fengjiachun** [comment]
Hi, @Rishav1707 , due to the length of time, we have automatically unsign, so please continue to pick up [other tasks](https://github.com/GreptimeTeam/greptimedb/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) if needed.

**Comment by etolbakov** [comment]
@evenyag Thanks for merging my PR!
My understanding is that this issue has been resolved.
I would try looking for another "good first issue" but if you can think of any issue I can take a look in the meantime, please let me know. Thanks!

**Comment by evenyag** [comment]
Fixed by #966

@etolbakov Thanks! I also create a new issue #971 that should be friendly to Rust beginners.

**Comment by etolbakov** [comment]
Hi @evenyag @fengjiachun 
I was looking at the code and found `Backtrace` usage here as well.
https://github.com/GreptimeTeam/greptimedb/blob/c06e04afbbeecbc54fe42c075a3d4ae563efdf06/src/storage/src/error.rs#L42-L51
What's your opinion - should it be removed from `storage` module as well? If yes - I'm happy to do it as a part of this ticket.

**Comment by evenyag** [comment]
> should it be removed from `storage` module as well

`storage` crate doesn't due with user input directly. Backtraces should be helpful in locating where the error occurs. So let's keep them.

But I find out that the `FlushIo` variant is unused. We could simply remove this variant.
