### ISSUE TITLE
Long running regression test suite

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#858]
### What type of enhancement is this?

Other

### What does the enhancement do?

As GreptimeDB is releasing weekly builds, we may need some regression test suite that runs continuously 24x7 to check if any recent change breaks the major functionalities.

We shall first start with data integrity tests that insert random rows of data into GreptimeDB and checks whether:
- row num counted matches rows inserted;
- simple SQL queries return correct results, like min/max/point queries/group by queries;
- deleting table rows reclaims disk space;
- any degradation in performance happens;
- ...

The regression test suite may evolve to a chao test suite in the future.

**Comment by sunng87** [comment]
Longevity testing: https://github.com/scylladb/scylla-longevity-tests
