### ISSUE TITLE
Use rust-toolchain.toml to replace rust-toolchain.

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#877]
### What type of enhancement is this?

Configuration

### What does the enhancement do?

The [rust-toolchain](https://github.com/GreptimeTeam/greptimedb/blob/develop/rust-toolchain) is a legacy format, i think we can migrate it to `rust-toolchain.toml` file format.

https://rust-lang.github.io/rustup/overrides.html

**Comment by waynexia** [comment]
Maybe this is why `rust-toolchain` always goes wrong I suspect? It's good to have a try and see if it works.
