### ISSUE TITLE
cannot create table with a name which is occupied before

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#892]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode

### What happened?

For the following queries

```sql
CREATE TABLE t(i INTEGER, j BIGINT TIME INDEX);

ALTER TABLE t RENAME new_table;

SELECT * FROM t;

CREATE TABLE t(i INTEGER, j BIGINT TIME INDEX);
```

the third `SELECT` clause will report the table doesn't exist, but the fourth `CREATE` clause will fill due to table already exist

### What operating system did you use?

M1 Mac

### How can we reproduce the bug?

```bash
By running the provided queries
```

**Comment by waynexia** [comment]
cc @e1ijah1 who has made a great contribution to `RENAME TABLE` feature

**Comment by e1ijah1** [comment]
> cc @e1ijah1 who has made a great contribution to `RENAME TABLE` feature

I have already submitted my PR and PTAL
