### ISSUE TITLE
Respect saved catalog in query context

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#909]
### What type of enhancement is this?

User experience

### What does the enhancement do?

Greptime cloud may save catalog in query context (see #798 ), db should respect that in processing read/write. Currently only default catalog is used.

**Comment by MichaelScofield** [comment]
Upon discussion with @sunng87 , we found that there's another issue related to the catalog used in Greptime cloud, that how to auth the full table name in SQL stmt. Full table name as in "catalog.schema.table" after the `FROM` token. For example, if a user only has access to his catalog "catalog_a", we need to deny executing his possible submitted SQL "select * from catalog_b.schema_a.table_a". Because SQL parsing and catalog authentication are two separate phases in current db impl, when and how to resolve the above issue remain uncertain. A possible way is through the SQL interceptor. cc @shuiyisong

**Comment by shuiyisong** [comment]
Since there might be cases to use such statement(`catalog.schema.table`, e.g: mysql switching databases, system level metics collecting), this grammar will remain valid, and SQL level authorization will be implemented in SQL interceptor as mentioned later. cc @sunng87

**Comment by sunng87** [comment]
Sounds good. Then we will need to check the scope of current session to see if the table operation is allowed.

**Comment by sunng87** [comment]
Let's verify if this is already fixed.
