### ISSUE TITLE
"DESC TABLE" in http sql api does not support `db` param

### ISSUE THREAD

**Issue by DiamondMofeng** [GreptimeTeam/greptimedb#912]
### What type of bug is this?

Incorrect result

### What subsystems are affected?

Standalone mode, Frontend

### What happened?

I am not sure if this problem has been fixed, but it exists in the newest release. 

I have a greptimedb, whose databases and tables looks like below
```
  public: {
    number,
    scripts,
    system_metrics
  },
  test: {
    system_metrics2
  }
```

From the screenshots below, you can clearly learn that `db` param is ignored.

BTW, I have not tested other statements yet and do not have much motivation to do that.

![图片](https://user-images.githubusercontent.com/52260316/215317359-80d75725-c1bc-4f40-a0f7-ebc1ce655431.png)

![图片](https://user-images.githubusercontent.com/52260316/215317384-a4d90fda-0e19-4de6-8e96-f6bd74c7824c.png)

![图片](https://user-images.githubusercontent.com/52260316/215317407-5807c7b9-bd0a-44fa-8b04-5943519dc0b5.png)

![图片](https://user-images.githubusercontent.com/52260316/215317441-12b7bafc-0452-4c08-aa53-3a174a42cf1b.png)

### What operating system did you use?

Ubuntu 20.04.4 LTS x64

### How can we reproduce the bug?

Assume that the following operations are all performed using http sql api

```
?sql=CREATE DATABASE test2
```
```
?sql=CREATE TABLE system_metrics3 ( host STRING, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    PRIMARY KEY(host),  TIME INDEX(ts))&db=test2
```
```
?sql=DESC TABLE system_metrics3&db=test2
```

The last request will return an error `Table not found: system_metrics3`

**Comment by DiamondMofeng** [comment]
Okay, I did more test and found that `db` param is not ignored. It seems more like that the `db_name` in `DESC TABLE {db_name}`  was hard coded as `public`

**Comment by DiamondMofeng** [comment]
I have figured it out. 
1. Before parsing the sql, [http sql api handler will check if the given `db` is existed](https://github.com/GreptimeTeam/greptimedb/blob/539ead54606436aa3d0adbdb722e88032e07b10c/src/servers/src/http/handler.rs#L51) 
2. Then the sql is parsed by [this parser](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/sql/src/parser.rs#L270). As users has passed `db` param, they would simply use `DESC TABLE {table_name}` instead of `DESC TABLE {db_name.table_name}`. So eventually the `schema` is parsed as `DEFAULT_SCHEMA_NAME`, the `public`
3. [Finally, the parsed statement is processed here](https://github.com/GreptimeTeam/greptimedb/blob/9428e70971b24d684b697904172bcd310e379a9d/src/query/src/sql.rs#L173). But it uses the `schema` from step2, instead of the `db` param from `query_ctx`.

To fix this bug, we just need to pass `query_ctx` to [describe_table](https://github.com/GreptimeTeam/greptimedb/blob/9428e70971b24d684b697904172bcd310e379a9d/src/query/src/sql.rs#L173) function, and extract `db` as `schema` from there.

BTW, the step1 explains why the `db` param seems to be ignored.

**Comment by DiamondMofeng** [comment]
I have no idea about the priority between `db` param and the schema provided in the sql statement. 
I am glad to fix this bug if you could clarify the priority.

**Comment by MichaelScofield** [comment]
@DiamondMofeng I think the schema provided in SQL is preference to the `db` param in query context, just like how `use` is treated in MySQL. You are very welcome to submit a PR to fix this!

**Comment by sunng87** [comment]
This is related to #867 and @MichaelScofield is working on an overhaul of table name resolution. But perhaps we can have a quick fix to let it work for standalone mode. @MichaelScofield WDYT

**Comment by MichaelScofield** [comment]
@sunng87 A quick fix for standalone is good to me.

**Comment by DiamondMofeng** [comment]
@MichaelScofield This involves much more things than I have expected. For example, type of `catalog_name` and `schema_name` in [describe struct](https://github.com/GreptimeTeam/greptimedb/blob/develop/src/sql/src/statements/describe.rs#L17) should be changed into `Option<String>`, thus the return type of [`table_idents_to_full_name function`](https://github.com/GreptimeTeam/greptimedb/blob/18e6740ac95f74c5865373f4493f4bd25830940a/src/sql/src/statements.rs#L51) should also be changed to `Result<(Option<String>, Option<String>, String)>`, involving much more changes.

**Comment by MichaelScofield** [comment]
@DiamondMofeng That's fine, I'll look into it. Assigned to myself. Thx for your efforts!

**Comment by DiamondMofeng** [comment]
I have see #922 and it seems solving this issue. I will try it in the next weekly release. Thank you!

**Comment by DiamondMofeng** [comment]
It works well in the latest relase. Thank you!
