### ISSUE TITLE
Enable caching in opendal when using s3/oss storage. 

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#918]
### What type of enhancement is this?

Performance

### What does the enhancement do?

The OpenDAL has a [CacheLayer](https://github.com/datafuselabs/opendal/blob/764e72184e42f5949dd4c8f29770a2e397e89204/src/layers/cache/layer.rs) for caching data content. 

We may enable this layer by default when using s3/OSS storage in the GreptimeDB.

But in future, we can implement more accurate and flexible caching for object storage, especially under distributed and serverless modes.

**Comment by e1ijah1** [comment]
I'd like to work on this issue :)

**Comment by killme2008** [comment]
@e1ijah1  Cool, it's yours.
