### ISSUE TITLE
Pass region filters through substrait plans

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#926]
### What type of enhancement is this?

Performance

### What does the enhancement do?

Frontend invokes datanodes' flight API to scan rows.
https://github.com/GreptimeTeam/greptimedb/blob/cb0421304d452d39a272c7ce20d97f012028e262/src/datanode/src/instance/grpc.rs#L99-L116

Normally the request is just a logical plan encoded by substrait, then the plan immediately get executed by query engine on datanode. If frontend wants to specify the regions to scan (or any other filters that can help to reduce rows retrieved), we must find a way to carry those filters in requests.

I came up with two methods to solve this problem:
- Add a `metadata` argument to the flight service definition to carry the filters
https://github.com/GreptimeTeam/greptimedb/blob/64243e3a7d8007c3b281847d378c770abb069aae/src/api/greptime/v1/database.proto#L8-L14
But as I just stated, the logical plan immediately gets executed by query engine, the filters cannot be get passed to `TableScan` physical plan
https://github.com/GreptimeTeam/greptimedb/blob/cb0421304d452d39a272c7ce20d97f012028e262/src/datanode/src/instance/grpc.rs#L59
- Mannually adds the filters to the logical plan when building logical plan
https://github.com/GreptimeTeam/greptimedb/blob/72f05a3137bdedf0e7502a246a2533ded8d104cc/src/frontend/src/table/scan.rs#L70
We can convert `regions=[1,2,3]` to a `InList` expr with `regions` as scalar variable like:
```rust
    if !table_scan.regions.is_empty() {
        let region_list = table_scan
            .regions
            .iter()
            .map(|r| DfExpr::Literal(ScalarValue::UInt32(Some(*r))))
            .collect::<Vec<_>>();

        let expr = DfExpr::ScalarVariable(DataType::UInt32, vec!["__regions".to_string()]);
        let region_filter = DfExpr::InList {
            negated: false,
            expr: Box::new(expr),
            list: region_list,
        };
        builder = builder
            .filter(region_filter)
            .context(error::BuildDfLogicalPlanSnafu)?;
    }
```
But currently substrait does not support `InList` expr.
https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/common/substrait/src/df_expr.rs#L562-L582

**Comment by MichaelScofield** [comment]
I think the second method is better. An extra condition denotes which regions are this query needed like this, is very "natural" to me. Further we can extend this method to SQL as well, for example, `select * from my_table where __regions in [1,3,5]`.
