### ISSUE TITLE
Supports "SAMPLE BY"  statement

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#933]
### What problem does the new feature solve?

`SAMPLE BY` in [questdb](https://questdb.io/docs/reference/sql/sample-by/#examples) is a really useful statement for summarising large datasets into aggregates of homogeneous time chunks.

```sql
SELECT time, avg(price) FROM trades SAMPLE BY 30m
```

We already implement PromQL plans such as `SeriesNormalize`, `InstantManipulate` etc. in our pure rust PromQL implementation. I think it's easy to support this statement by adding those plans into SQL planners to enhance the SQL too.

### What does the feature do?

Described above.

**Comment by DiamondMofeng** [comment]
Will this also introduce the support of time literal outside of `SAMPLE BY` statement? For example, Influxdb's influxql supports syntax like `WHERE time >= now - 12h`

**Comment by killme2008** [comment]
> Will this also introduce the support of time literal outside `SAMPLE BY` statement? For example, Influxdb's influxql supports syntax like `WHERE time >= now() - 12h`

The syntax sugar for timestamp such as `12h` or `5m`etc.  is an important part of TSDB, and we want to support them too. 
I think we can create an independent issue to track it.

**Comment by waynexia** [comment]
> > Will this also introduce the support of time literal outside `SAMPLE BY` statement? For example, Influxdb's influxql supports syntax like `WHERE time >= now() - 12h`
> 
> The syntax sugar for timestamp such as `12h` or `5m`etc. is an important part of TSDB query language, and we want to support them too. I think we can create an independent issue to track it.

We can derive this duration parsing functionality from `promql-parser` [here](https://github.com/GreptimeTeam/promql-parser/blob/main/src/util/duration.rs#L68), which is in PromQL's format like `5m`, `4d3h`.

**Comment by killme2008** [comment]
Duplicated with #1662
