### ISSUE TITLE
sql: failed to parse plus operator `+` 

### ISSUE THREAD

**Issue by DiamondMofeng** [GreptimeTeam/greptimedb#941]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Other

### What happened?

While `*` and `-` works..

![图片](https://user-images.githubusercontent.com/52260316/216683740-358766a9-ad56-4f56-ae4f-37cabf803979.png)

![图片](https://user-images.githubusercontent.com/52260316/216683876-788cae9d-04ee-420c-92bd-944760945f28.png)

![图片](https://user-images.githubusercontent.com/52260316/216683937-766956ca-64f5-4ab2-bf78-94863f11e923.png)

### What operating system did you use?

Ubuntu 20.04.4 LTS x64

### How can we reproduce the bug?

```bash
select 1 + 1
```

**Comment by DiamondMofeng** [comment]
This bug is not caused by sqlparser 0.28.0
![图片](https://user-images.githubusercontent.com/52260316/216686766-fd897d99-82e6-4ab8-a731-56ccdb12f4d6.png)

**Comment by killme2008** [comment]
Looks like the dashboard's bug, the query param is not properly encoded. We already have such [test cases](https://github.com/GreptimeTeam/greptimedb/blob/develop/tests/cases/standalone/select/dummy.sql#L3).

I created an issue https://github.com/GreptimeTeam/dashboard/issues/104 to track it.

**Comment by DiamondMofeng** [comment]
Thank you, I just ignored that `+` will be decoded into space.
