### ISSUE TITLE
Move tests in `query/tests` to `query/src`

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#971]
Now the `query` crate put its tests under directory `src/query/tests`, which makes it inconvenient to reuse codes across tests. We have to suppress some warnings manually because each file under `query/tests` is a separate binary crate.

https://github.com/GreptimeTeam/greptimedb/blob/7d6f4cd88b2623f7d9729cbfc915d6a753761f92/src/query/tests/query_engine_test.rs#L16-L20

https://github.com/GreptimeTeam/greptimedb/blob/e77a7f253c1473b19ad2bda48305299daa7524f2/src/query/tests/function.rs#L15-L16

We could refactor this by moving the `src/query/tests` mod to `src/query/src/tests` like other crates.

https://github.com/GreptimeTeam/greptimedb/blob/e77a7f253c1473b19ad2bda48305299daa7524f2/src/datanode/src/lib.rs#L26-L27

Then files under `tests` will become normal mods and can share codes easily.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by etolbakov** [comment]
Sorry @tarunsamanta2k20 I've already started working on this as it came as part of https://github.com/GreptimeTeam/greptimedb/pull/966.
Forgot to update, my bad, sorry 🙏
@evenyag please assign it to me to avoid any further confusions

**Comment by waynexia** [comment]
Really sorry for the delay @tarunsamanta2k20, we are very honored to have your interest. You could check our other [good first issue](https://github.com/GreptimeTeam/greptimedb/labels/good%20first%20issue) if you are still willing to take participant 🥰
