### ISSUE TITLE
Merge `store_api::storage::chunk::Chunk` with `storage::read::Batch`

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#974]
### What type of enhancement is this?

Tech debt reduction

### What does the enhancement do?

Looks we have two identical structs that represent a batch of columns

https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/store-api/src/storage/chunk.rs#L23-L26

https://github.com/GreptimeTeam/greptimedb/blob/4e07795dfcf34df62b59363936e7467bf216a502/src/storage/src/read.rs#L36-L42

Maybe we should merge `Chunk` and `Batch` and only use the one defined in`store-api`  crate.

Also `storage::read::BatchReader` and  `store_api::storage::chunk::ChunkReader`:

https://github.com/GreptimeTeam/greptimedb/blob/8ffc078f88f5e265eb0821820593a1c4bd309c17/src/store-api/src/storage/chunk.rs#L36-L44
https://github.com/GreptimeTeam/greptimedb/blob/4e07795dfcf34df62b59363936e7467bf216a502/src/storage/src/read.rs#L246-L257

**Comment by v0y4g3r** [comment]
Looks like there's a slight difference: `Batch` contains internal columns while `Chunk` does not, thus `ProjectedSchema` has a `batch_to_chunk` method to strip those internal columns. That's a bit confusing.

**Comment by evenyag** [comment]
We have the assumption that `Batch` returned by the `BatchReader` has the following format:
```
[key columns][value columns][internal columns]
```

This is implementation details and I don't want to expose it to users.

But the `ChunkReader` always return what users expect to read: the position of the column is determined by its position in the `projection` field (Vec<usize>). So I'd like to keep `BatchReader` unchanged. But you could refactor the `ChunkReaderBuilder` to something like `MergeReaderBulder` or `ReaderBuilder` if we'd like to access batch with internal columns.
