### ISSUE TITLE
Refactor `push_value_ref()` method in MutableVector trait

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#978]
Now using `MutableVector::push_value_ref` is verbose as callers always need to handle the returned `Result`.
https://github.com/GreptimeTeam/greptimedb/blob/be897efd0109ee8ac4a35fae52039546fd0b67e3/src/datatypes/src/vectors.rs#L178

Most times, callers ensure that the pushed value ref has a valid data type. But they still need to add a safety note in the comment and unwrap the result manually.
https://github.com/GreptimeTeam/greptimedb/blob/be897efd0109ee8ac4a35fae52039546fd0b67e3/src/datatypes/src/schema/column_schema.rs#L148-L149

Consider refactoring the `MutableVector` and changing the `push_value_ref()` to panic by default (with `panic` section in doc comments). We could rename the old `push_value_ref()` method to `try_push_value_ref()`.
```rust
trait MutableVector {
    fn try_push_value_ref(&mut self, value: ValueRef) -> Result<()>; 

    fn push_value_ref(&mut self, value: ValueRef) -> Result<()> {
        self.try_push_value_ref(value).unwrap()
    }

    fn push_null(&mut self);
}
```

We could also add a `push_null` method to make pushing null more convenient
https://github.com/GreptimeTeam/greptimedb/blob/be897efd0109ee8ac4a35fae52039546fd0b67e3/src/common/grpc-expr/src/insert.rs#L99-L101

**Comment by etolbakov** [comment]
@evenyag I would like to give it a try if you don't mind.
