### ISSUE TITLE
An error occurred when requesting the http doc api

### ISSUE THREAD

**Issue by Fengys123** [GreptimeTeam/greptimedb#983]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

When I request the following http api, an error is reported:
1. http://localhost:4000/v1/private/api.json
2. http://localhost:4000/v1/private/docs
<img width="687" alt="image" src="https://user-images.githubusercontent.com/40801205/218438667-e40bf93b-3d9c-4bd5-a9e9-70039e497d32.png">
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/40801205/218438740-167da936-df03-4743-8e1d-c6f7e59dccef.png">

### What operating system did you use?

Mac

### How can we reproduce the bug?

```bash
1. cargo run -- standalone start
2. request http api
```

**Comment by killme2008** [comment]
I closed this issue, but i think we should add a API test for this case @Fengys123

**Comment by Fengys123** [comment]
> I closed this issue, but i think we should add a API test for this case @Fengys123

okay, i will add Api test later.
